/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 Accessibility module

 (c) 2010-2019 Highsoft AS
 Author: Oystein Moseng

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/accessibility",["highcharts"],function(q){a(q);a.Highcharts=q;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function q(a,l,n,p){a.hasOwnProperty(l)||(a[l]=p.apply(null,n))}a=a?a._modules:{};q(a,"modules/accessibility/KeyboardNavigationHandler.js",[a["parts/Globals.js"]],function(a){function h(a,e){this.chart=a;this.keyCodeMap=
e.keyCodeMap||[];this.validate=e.validate;this.init=e.init;this.terminate=e.terminate;this.response={success:1,prev:2,next:3,noHandler:4,fail:5}}var n=a.find;h.prototype={run:function(a){var e=a.which||a.keyCode,g=this.response.noHandler,h=n(this.keyCodeMap,function(a){return-1<a[0].indexOf(e)});h?g=h[1].call(this,e,a):9===e?g=this.response[a.shiftKey?"prev":"next"]:27===e&&(this.chart&&this.chart.tooltip&&this.chart.tooltip.hide(0),g=this.response.success);return g}};return h});q(a,"modules/accessibility/utils/htmlUtilities.js",
[a["parts/Globals.js"]],function(a){function h(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")}var n=a.merge,p=a.win.document;return{addClass:function(a,g){a.classList?a.classList.add(g):0>a.className.indexOf(g)&&(a.className+=g)},escapeStringForHTML:h,getElement:function(a){return p.getElementById(a)},removeElement:function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},reverseChildNodes:function(a){for(var g=
a.childNodes.length;g--;)a.appendChild(a.childNodes[g])},setElAttrs:function(a,g){Object.keys(g).forEach(function(e){var k=g[e];null===k?a.removeAttribute(e):(k=h(""+k),a.setAttribute(e,k))})},stripHTMLTagsFromString:function(a){return"string"===typeof a?a.replace(/<\/?[^>]+(>|$)/g,""):a},visuallyHideElement:function(a){n(!0,a.style,{position:"absolute",width:"1px",height:"1px",overflow:"hidden","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",filter:"alpha(opacity=1)",opacity:"0.01"})}}});
q(a,"modules/accessibility/utils/chartUtilities.js",[a["modules/accessibility/utils/htmlUtilities.js"]],function(a){function h(a){return a.points&&a.points.length&&a.points[0].graphic&&a.points[0].graphic.element}function n(a){var g=h(a);return g&&g.parentNode||a.graph&&a.graph.element||a.group&&a.group.element}function p(a,e){e.setAttribute("aria-hidden",!1);e!==a.renderTo&&e.parentNode&&(Array.prototype.forEach.call(e.parentNode.childNodes,function(a){a.hasAttribute("aria-hidden")||a.setAttribute("aria-hidden",
!0)}),p(a,e.parentNode))}var e=a.stripHTMLTagsFromString;return{getChartTitle:function(a){return e(a.options.title.text||a.langFormat("accessibility.defaultChartTitle",{chart:a}))},getAxisDescription:function(a){return e(a&&(a.userOptions&&a.userOptions.accessibility&&a.userOptions.accessibility.description||a.axisTitle&&a.axisTitle.textStr||a.options.id||a.categories&&"categories"||a.isDatetimeAxis&&"Time"||"values"))},getPointFromXY:function(a,e,k){for(var c=a.length,b;c--;)if(b=(a[c].points||[]).find(function(b){return b.x===
e&&b.y===k}))return b},getSeriesFirstPointElement:h,getSeriesFromName:function(a,e){return e?(a.series||[]).filter(function(a){return a.name===e}):a.series},getSeriesA11yElement:n,unhideChartElementFromAT:p,hideSeriesFromAT:function(a){(a=n(a))&&a.setAttribute("aria-hidden",!0)}}});q(a,"modules/accessibility/utils/EventProvider.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,l){l=l.extend;var h=function(){this.eventRemovers=[]};l(h.prototype,{addEvent:function(){var h=a.addEvent.apply(a,
arguments);this.eventRemovers.push(h);return h},removeAddedEvents:function(){this.eventRemovers.forEach(function(a){a()});this.eventRemovers=[]}});return h});q(a,"modules/accessibility/utils/DOMElementProvider.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n){var h=a.win.document;a=l.extend;var e=n.removeElement;n=function(){this.elements=[]};a(n.prototype,{createElement:function(){var a=h.createElement.apply(h,arguments);this.elements.push(a);
return a},destroyCreatedElements:function(){this.elements.forEach(function(a){e(a)});this.elements=[]}});return n});q(a,"modules/accessibility/AccessibilityComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/DOMElementProvider.js"]],function(a,l,n,p,e,g){function h(){}var k=a.win,c=k.document,b=a.merge;a=l.extend;
var d=l.pick,f=n.removeElement,u=p.unhideChartElementFromAT;h.prototype={initBase:function(a){this.chart=a;this.eventProvider=new e;this.domElementProvider=new g;this.keyCodes={left:37,right:39,up:38,down:40,enter:13,space:32,esc:27,tab:9}},addEvent:function(){return this.eventProvider.addEvent.apply(this.eventProvider,arguments)},createElement:function(){return this.domElementProvider.createElement.apply(this.domElementProvider,arguments)},fakeClickEvent:function(a){if(a&&a.onclick&&c.createEvent){var b=
c.createEvent("Event");b.initEvent("click",!0,!1);a.onclick(b)}},addProxyGroup:function(a){this.createOrUpdateProxyContainer();var b=this.createElement("div");Object.keys(a||{}).forEach(function(c){null!==a[c]&&b.setAttribute(c,a[c])});this.chart.a11yProxyContainer.appendChild(b);return b},createOrUpdateProxyContainer:function(){var a=this.chart,b=a.renderer.box;a.a11yProxyContainer=a.a11yProxyContainer||this.createProxyContainerElement();b.nextSibling!==a.a11yProxyContainer&&a.container.insertBefore(a.a11yProxyContainer,
b.nextSibling)},createProxyContainerElement:function(){var a=c.createElement("div");a.className="highcharts-a11y-proxy-container";return a},createProxyButton:function(a,c,d,f,k){var r=a.element,m=this.createElement("button"),v=b({"aria-label":r.getAttribute("aria-label")},d);a=this.getElementPosition(f||a);Object.keys(v).forEach(function(a){null!==v[a]&&m.setAttribute(a,v[a])});m.className="highcharts-a11y-proxy-button";k&&this.addEvent(m,"click",k);this.setProxyButtonStyle(m,a);this.proxyMouseEventsForButton(r,
m);c.appendChild(m);v["aria-hidden"]||u(this.chart,m);return m},getElementPosition:function(a){var b=a.element;return(a=this.chart.renderTo)&&b&&b.getBoundingClientRect?(b=b.getBoundingClientRect(),a=a.getBoundingClientRect(),{x:b.left-a.left,y:b.top-a.top,width:b.right-b.left,height:b.bottom-b.top}):{x:0,y:0,width:1,height:1}},setProxyButtonStyle:function(a,c){b(!0,a.style,{"border-width":0,"background-color":"transparent",cursor:"pointer",outline:"none",opacity:.001,filter:"alpha(opacity=1)","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
zIndex:999,overflow:"hidden",padding:0,margin:0,display:"block",position:"absolute",width:(c.width||1)+"px",height:(c.height||1)+"px",left:d(c.x,c.left)+"px",top:d(c.y,c.top)+"px"})},proxyMouseEventsForButton:function(a,b){var c=this;["click","mouseover","mouseenter","mouseleave","mouseout"].forEach(function(d){c.addEvent(b,d,function(b){var r=c.cloneMouseEvent(b);if(a)if(r)a.fireEvent?a.fireEvent(r):a.dispatchEvent&&a.dispatchEvent(r);else if(a["on"+d])a["on"+d](b);b.stopPropagation();b.preventDefault()})})},
cloneMouseEvent:function(a){if("function"===typeof k.MouseEvent)return new k.MouseEvent(a.type,a);if(c.createEvent){var b=c.createEvent("MouseEvent");if(b.initMouseEvent)return b.initMouseEvent(a.type,a.bubbles,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget),b;b=c.createEvent("Event");if(b.initEvent)return b.initEvent(a.type,!0,!0),b}},destroyBase:function(){f(this.chart.a11yProxyContainer);this.domElementProvider.destroyCreatedElements();
this.eventProvider.removeAddedEvents()}};a(h.prototype,{init:function(){},getKeyboardNavigation:function(){},onChartUpdate:function(){},onChartRender:function(){},destroy:function(){}});return h});q(a,"modules/accessibility/KeyboardNavigation.js",[a["parts/Globals.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/EventProvider.js"]],function(a,l,n,p){function e(a,c,f){this.init(a,c,f)}var h=a.merge,t=a.win,
k=t.document,c=l.getElement;e.prototype={init:function(a,c){var b=this,d=this.eventProvider=new p;this.chart=a;this.components=c;this.modules=[];this.currentModuleIx=0;a.container.hasAttribute("tabIndex")||a.container.setAttribute("tabindex","0");d.addEvent(a.renderTo,"keydown",function(a){b.onKeydown(a)});d.addEvent(k,"mouseup",function(){b.onMouseUp()});this.update();this.modules.length&&this.modules[0].init(1)},update:function(a){var b=this.chart.options.accessibility;b=b&&b.keyboardNavigation;
var c=this.components;b&&b.enabled&&a&&a.length?(this.modules=a.reduce(function(a,b){b=c[b].getKeyboardNavigation();return b.length?a.concat(b):(a.push(b),a)},[new n(this.chart,{})]),this.updateExitAnchor()):(this.modules=[],this.currentModuleIx=0,this.removeExitAnchor())},onMouseUp:function(){if(!(this.keyboardReset||this.chart.pointer&&this.chart.pointer.chartPosition)){var a=this.chart,c=this.modules&&this.modules[this.currentModuleIx||0];c&&c.terminate&&c.terminate();a.focusElement&&a.focusElement.removeFocusBorder();
this.currentModuleIx=0;this.keyboardReset=!0}},onKeydown:function(a){a=a||t.event;var b,c=this.modules&&this.modules.length&&this.modules[this.currentModuleIx];this.keyboardReset=!1;if(c){var k=c.run(a);k===c.response.success?b=!0:k===c.response.prev?b=this.prev():k===c.response.next&&(b=this.next());b&&(a.preventDefault(),a.stopPropagation())}},prev:function(){return this.move(-1)},next:function(){return this.move(1)},move:function(a){var b=this.modules&&this.modules[this.currentModuleIx];b&&b.terminate&&
b.terminate(a);this.chart.focusElement&&this.chart.focusElement.removeFocusBorder();this.currentModuleIx+=a;if(b=this.modules&&this.modules[this.currentModuleIx]){if(b.validate&&!b.validate())return this.move(a);if(b.init)return b.init(a),!0}this.currentModuleIx=0;0<a?(this.exiting=!0,this.exitAnchor.focus()):this.chart.renderTo.focus();return!1},updateExitAnchor:function(){var a=c("highcharts-end-of-chart-marker-"+this.chart.index);this.removeExitAnchor();a?(this.makeElementAnExitAnchor(a),this.exitAnchor=
a):this.createExitAnchor()},makeElementAnExitAnchor:function(a){a.setAttribute("class","highcharts-exit-anchor");a.setAttribute("tabindex","0");a.setAttribute("aria-hidden",!1);this.addExitAnchorEventsToEl(a)},createExitAnchor:function(){var a=this.chart,c=this.exitAnchor=k.createElement("div");h(!0,c.style,{position:"absolute",width:"1px",height:"1px",zIndex:0,overflow:"hidden",outline:"none"});a.renderTo.appendChild(c);this.makeElementAnExitAnchor(c)},removeExitAnchor:function(){this.exitAnchor&&
this.exitAnchor.parentNode&&(this.exitAnchor.parentNode.removeChild(this.exitAnchor),delete this.exitAnchor)},addExitAnchorEventsToEl:function(a){var b=this.chart,c=this;this.eventProvider.addEvent(a,"focus",function(a){a=a||t.event;a.relatedTarget&&b.container.contains(a.relatedTarget)||c.exiting?c.exiting=!1:(b.renderTo.focus(),a.preventDefault(),c.modules&&c.modules.length&&(c.currentModuleIx=c.modules.length-1,(a=c.modules[c.currentModuleIx])&&a.validate&&!a.validate()?c.prev():a&&a.init(-1)))})},
destroy:function(){this.removeExitAnchor();this.eventProvider.removeAddedEvents()}};return e});q(a,"modules/accessibility/components/LegendComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n,p,e){l=l.extend;var h=e.stripHTMLTagsFromString,t=e.removeElement;a.Chart.prototype.highlightLegendItem=function(k){var c=this.legend.allItems,
b=this.highlightedLegendItemIx;if(c[k]){c[b]&&a.fireEvent(c[b].legendGroup.element,"mouseout");b=this.legend;var d=b.allItems[k].pageIx,f=b.currentPage;"undefined"!==typeof d&&d+1!==f&&b.scroll(1+d-f);this.setFocusToElement(c[k].legendItem,c[k].a11yProxyElement);a.fireEvent(c[k].legendGroup.element,"mouseover");return!0}return!1};a.addEvent(a.Legend,"afterColorizeItem",function(a){var c=a.item;this.chart.options.accessibility.enabled&&c&&c.a11yProxyElement&&c.a11yProxyElement.setAttribute("aria-pressed",
a.visible?"false":"true")});e=function(){};e.prototype=new n;l(e.prototype,{init:function(){var k=this;this.addEvent(a.Legend,"afterScroll",function(){this.chart===k.chart&&k.updateProxies()})},updateLegendItemProxyVisibility:function(){var a=this.chart.legend,c=a.currentPage||1;(a.allItems||[]).forEach(function(a){var b=(a.pageIx||0)!==c-1;a.a11yProxyElement&&(a.a11yProxyElement.style.visibility=b?"hidden":"visible")})},onChartRender:function(){this.legendProxyButtonClicked?delete this.legendProxyButtonClicked:
this.updateProxies()},updateProxies:function(){t(this.legendProxyGroup);var a=this.chart,c=a.legend&&a.legend.allItems,b=a.options.legend.accessibility||{};!c||!c.length||a.colorAxis&&a.colorAxis.length||!1===b.enabled||(this.addLegendProxyGroup(),this.proxyLegendItems(),this.updateLegendItemProxyVisibility())},addLegendProxyGroup:function(){var a=this.chart.options.accessibility,c=this.chart.langFormat("accessibility.legend.legendLabel");this.legendProxyGroup=this.addProxyGroup({"aria-label":c,role:"all"===
a.landmarkVerbosity?"region":null})},proxyLegendItems:function(){var a=this;(this.chart.legend&&this.chart.legend.allItems).forEach(function(c){c.legendItem&&c.legendItem.element&&a.proxyLegendItem(c)})},proxyLegendItem:function(a){var c=this,b=this.chart.langFormat("accessibility.legend.legendItem",{chart:this.chart,itemName:h(a.name)});a.a11yProxyElement=this.createProxyButton(a.legendItem,this.legendProxyGroup,{tabindex:-1,"aria-pressed":!a.visible,"aria-label":b},a.legendGroup.div?a.legendItem:
a.legendGroup,function(){c.legendProxyButtonClicked=!0})},getKeyboardNavigation:function(){var a=this.keyCodes,c=this;return new p(this.chart,{keyCodeMap:[[[a.left,a.right,a.up,a.down],function(a){return c.onKbdArrowKey(this,a)}],[[a.enter,a.space],function(){return c.onKbdClick(this)}]],validate:function(){return c.shouldHaveLegendNavigation()},init:function(a){return c.onKbdNavigationInit(a)}})},onKbdArrowKey:function(a,c){var b=this.keyCodes,d=a.response,f=this.chart,e=f.options.accessibility,
h=f.legend.allItems.length;c=c===b.left||c===b.up?-1:1;return f.highlightLegendItem(this.highlightedLegendItemIx+c)?(this.highlightedLegendItemIx+=c,d.success):1<h&&e.keyboardNavigation.wrapAround?(a.init(c),d.success):d[0<c?"next":"prev"]},onKbdClick:function(e){var c=this.chart.legend.allItems[this.highlightedLegendItemIx];c&&c.a11yProxyElement&&a.fireEvent(c.a11yProxyElement,"click");return e.response.success},shouldHaveLegendNavigation:function(){var a=this.chart,c=a.colorAxis&&a.colorAxis.length,
b=(a.options.legend||{}).accessibility||{};return a.legend&&a.legend.allItems&&a.legend.display&&!c&&b.enabled&&b.keyboardNavigation&&b.keyboardNavigation.enabled},onKbdNavigationInit:function(a){var c=this.chart,b=c.legend.allItems.length-1;a=0<a?0:b;c.highlightLegendItem(a);this.highlightedLegendItemIx=a}});return e});q(a,"modules/accessibility/components/MenuComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],
a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n,p,e,g){l=l.extend;var h=e.unhideChartElementFromAT,k=g.removeElement;a.Chart.prototype.showExportMenu=function(){if(this.exportSVGElements&&this.exportSVGElements[0])this.exportSVGElements[0].element.onclick()};a.Chart.prototype.hideExportMenu=function(){var a=this.exportDivElements;a&&this.exportContextMenu&&(a.forEach(function(a){if("highcharts-menu-item"===a.className&&a.onmouseout)a.onmouseout()}),
this.highlightedExportItemIx=0,this.exportContextMenu.hideMenu(),this.container.focus())};a.Chart.prototype.highlightExportItem=function(a){var c=this.exportDivElements&&this.exportDivElements[a],d=this.exportDivElements&&this.exportDivElements[this.highlightedExportItemIx];if(c&&"LI"===c.tagName&&(!c.children||!c.children.length)){var f=!!(this.renderTo.getElementsByTagName("g")[0]||{}).focus;c.focus&&f&&c.focus();if(d&&d.onmouseout)d.onmouseout();if(c.onmouseover)c.onmouseover();this.highlightedExportItemIx=
a;return!0}};a.Chart.prototype.highlightLastExportItem=function(){var a;if(this.exportDivElements)for(a=this.exportDivElements.length;a--;)if(this.highlightExportItem(a))return!0;return!1};a=function(){};a.prototype=new n;l(a.prototype,{init:function(){var a=this.chart,b=this;this.addEvent(a,"exportMenuShown",function(){b.onMenuShown()});this.addEvent(a,"exportMenuHidden",function(){b.onMenuHidden()})},onMenuHidden:function(){var a=this.chart.exportContextMenu;a&&a.setAttribute("aria-hidden","true");
this.setExportButtonExpandedState("false")},onMenuShown:function(){var a=this.chart,b=a.exportContextMenu;b&&(this.addAccessibleContextMenuAttribs(),h(a,b));this.setExportButtonExpandedState("true")},setExportButtonExpandedState:function(a){var c=this.exportButtonProxy;c&&c.setAttribute("aria-expanded",a)},onChartRender:function(){var a=this.chart,b=a.options.accessibility;k(this.exportProxyGroup);var d=a.options.exporting;d&&!1!==d.enabled&&d.accessibility&&d.accessibility.enabled&&a.exportSVGElements&&
a.exportSVGElements[0]&&a.exportSVGElements[0].element&&(this.exportProxyGroup=this.addProxyGroup("all"===b.landmarkVerbosity?{"aria-label":a.langFormat("accessibility.exporting.exportRegionLabel",{chart:a}),role:"region"}:null),this.exportButtonProxy=this.createProxyButton(this.chart.exportSVGElements[0],this.exportProxyGroup,{"aria-label":a.langFormat("accessibility.exporting.menuButtonLabel",{chart:a}),"aria-expanded":"false"}))},addAccessibleContextMenuAttribs:function(){var a=this.chart,b=a.exportDivElements;
b&&b.length&&(b.forEach(function(a){"LI"!==a.tagName||a.children&&a.children.length?a.setAttribute("aria-hidden","true"):a.setAttribute("tabindex",-1)}),b=b[0].parentNode,b.removeAttribute("aria-hidden"),b.setAttribute("aria-label",a.langFormat("accessibility.exporting.chartMenuLabel",{chart:a})))},getKeyboardNavigation:function(){var a=this.keyCodes,b=this.chart,d=this;return new p(b,{keyCodeMap:[[[a.left,a.up],function(){return d.onKbdPrevious(this)}],[[a.right,a.down],function(){return d.onKbdNext(this)}],
[[a.enter,a.space],function(){return d.onKbdClick(this)}],[[a.esc],function(){return this.response.prev}]],validate:function(){return b.exportChart&&!1!==b.options.exporting.enabled&&!1!==b.options.exporting.accessibility.enabled},init:function(a){b.showExportMenu();0>a?b.highlightLastExportItem():b.highlightExportItem(0)},terminate:function(){b.hideExportMenu()}})},onKbdPrevious:function(a){var b=this.chart,c=b.options.accessibility;a=a.response;for(var f=b.highlightedExportItemIx||0;f--;)if(b.highlightExportItem(f))return a.success;
return c.keyboardNavigation.wrapAround?(b.highlightLastExportItem(),a.success):a.prev},onKbdNext:function(a){var b=this.chart,c=b.options.accessibility;a=a.response;for(var f=(b.highlightedExportItemIx||0)+1;f<b.exportDivElements.length;++f)if(b.highlightExportItem(f))return a.success;return c.keyboardNavigation.wrapAround?(b.highlightExportItem(0),a.success):a.next},onKbdClick:function(a){var b=this.chart;this.fakeClickEvent(b.exportDivElements[b.highlightedExportItemIx]);return a.response.success}});
return a});q(a,"modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/chartUtilities.js"]],function(a,l,n,p,e){function g(a){var b=a.index,c=a.series.points,r=c.length;if(c[b]!==a)for(;r--;){if(c[r]===a)return r}else return b}function h(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation,
c=a.options.accessibility||{},r=c.keyboardNavigation;return r&&!1===r.enabled||!1===c.enabled||!1===a.options.enableMouseTracking||!a.visible||b.pointNavigationEnabledThreshold&&b.pointNavigationEnabledThreshold<=a.points.length}function k(a){var b=a.series.chart.options.accessibility;return a.isNull&&b.keyboardNavigation.seriesNavigation.skipNullPoints||!1===a.visible||h(a.series)}function c(a,b,c,f){var m=Infinity,r=b.points.length,d=function(a){return!(u(a.plotX)&&u(a.plotY))};if(!d(a)){for(;r--;){var v=
b.points[r];if(!d(v)&&(v=(a.plotX-v.plotX)*(a.plotX-v.plotX)*(c||1)+(a.plotY-v.plotY)*(a.plotY-v.plotY)*(f||1),v<m)){m=v;var e=r}}return u(e)?b.points[e]:void 0}}function b(a){var b=!1;delete a.highlightedPoint;return b=a.series.reduce(function(a,b){return a||b.highlightFirstValidPoint()},null)}function d(a,b){this.keyCodes=b;this.chart=a}var f=l.extend,u=l.defined,w=e.getPointFromXY,x=e.getSeriesFromName;a.Series.prototype.keyboardMoveVertical=!0;["column","pie"].forEach(function(b){a.seriesTypes[b]&&
(a.seriesTypes[b].prototype.keyboardMoveVertical=!1)});a.Point.prototype.highlight=function(){var a=this.series.chart;if(this.isNull)a.tooltip&&a.tooltip.hide(0);else this.onMouseOver();this.graphic&&a.setFocusToElement(this.graphic);a.highlightedPoint=this;return this};a.Chart.prototype.highlightAdjacentPoint=function(a){var b=this.series,c=this.highlightedPoint,f=c&&g(c)||0,m=c&&c.series.points,d=this.series&&this.series[this.series.length-1];d=d&&d.points&&d.points[d.points.length-1];if(!b[0]||
!b[0].points)return!1;if(c){if(b=b[c.series.index+(a?1:-1)],f=m[f+(a?1:-1)],!f&&b&&(f=b.points[a?0:b.points.length-1]),!f)return!1}else f=a?b[0].points[0]:d;return k(f)?(b=f.series,h(b)?this.highlightedPoint=a?b.points[b.points.length-1]:b.points[0]:this.highlightedPoint=f,this.highlightAdjacentPoint(a)):f.highlight()};a.Series.prototype.highlightFirstValidPoint=function(){var a=this.chart.highlightedPoint,b=(a&&a.series)===this?g(a):0;a=this.points;var c=a.length;if(a&&c){for(var f=b;f<c;++f)if(!k(a[f]))return a[f].highlight();
for(;0<=b;--b)if(!k(a[b]))return a[b].highlight()}return!1};a.Chart.prototype.highlightAdjacentSeries=function(a){var b,f=this.highlightedPoint;var d=(b=this.series&&this.series[this.series.length-1])&&b.points&&b.points[b.points.length-1];if(!this.highlightedPoint)return b=a?this.series&&this.series[0]:b,(d=a?b&&b.points&&b.points[0]:d)?d.highlight():!1;b=this.series[f.series.index+(a?-1:1)];if(!b)return!1;d=c(f,b,4);if(!d)return!1;if(h(b))return d.highlight(),a=this.highlightAdjacentSeries(a),a?
a:(f.highlight(),!1);d.highlight();return d.series.highlightFirstValidPoint()};a.Chart.prototype.highlightAdjacentPointVertical=function(a){var b=this.highlightedPoint,c=Infinity,f;if(!u(b.plotX)||!u(b.plotY))return!1;this.series.forEach(function(m){h(m)||m.points.forEach(function(d){if(u(d.plotY)&&u(d.plotX)&&d!==b){var e=d.plotY-b.plotY,r=Math.abs(d.plotX-b.plotX);r=Math.abs(e)*Math.abs(e)+r*r*4;m.yAxis.reversed&&(e*=-1);!(0>=e&&a||0<=e&&!a||5>r||k(d))&&r<c&&(c=r,f=d)}})});return f?f.highlight():
!1};f(d.prototype,{init:function(){var c=this,f=this.chart,d=this.eventProvider=new p;d.addEvent(a.Series,"destroy",function(){return c.onSeriesDestroy()});d.addEvent(f,"afterDrilldown",function(){b(this);this.focusElement&&this.focusElement.removeFocusBorder()});d.addEvent(f,"drilldown",function(a){a=a.point;var b=a.series;c.lastDrilledDownPoint={x:a.x,y:a.y,seriesName:b?b.name:null}});d.addEvent(f,"drillupall",function(){setTimeout(function(){c.onDrillupAll()},10)})},onDrillupAll:function(){var a=
this.lastDrilledDownPoint,b=this.chart,c=x(b,a.seriesName);a=c&&w(c,a.x,a.y);b.container&&b.container.focus();a&&a.highlight&&a.highlight();b.focusElement&&b.focusElement.removeFocusBorder()},getKeyboardNavigationHandler:function(){var a=this,b=this.keyCodes,c=this.chart,d=c.inverted;return new n(c,{keyCodeMap:[[d?[b.up,b.down]:[b.left,b.right],function(b){return a.onKbdSideways(this,b)}],[d?[b.left,b.right]:[b.up,b.down],function(b){return a.onKbdVertical(this,b)}],[[b.enter,b.space],function(){c.highlightedPoint&&
c.highlightedPoint.firePointEvent("click");return this.response.success}]],init:function(b){return a.onHandlerInit(this,b)},terminate:function(){return a.onHandlerTerminate()}})},onKbdSideways:function(a,b){var c=this.keyCodes;return this.attemptHighlightAdjacentPoint(a,b===c.right||b===c.down)},onKbdVertical:function(a,b){var c=this.chart,d=this.keyCodes;b=b===d.down||b===d.right;d=c.options.accessibility.keyboardNavigation.seriesNavigation;if(d.mode&&"serialize"===d.mode)return this.attemptHighlightAdjacentPoint(a,
b);c[c.highlightedPoint&&c.highlightedPoint.series.keyboardMoveVertical?"highlightAdjacentPointVertical":"highlightAdjacentSeries"](b);return a.response.success},onHandlerInit:function(a,c){var d=this.chart;if(0<c)b(d);else{c=d.series.length;for(var f;c--&&!(d.highlightedPoint=d.series[c].points[d.series[c].points.length-1],f=d.series[c].highlightFirstValidPoint()););}return a.response.success},onHandlerTerminate:function(){var a=this.chart;a.tooltip&&a.tooltip.hide(0);delete a.highlightedPoint},
attemptHighlightAdjacentPoint:function(a,b){var c=this.chart,d=c.options.accessibility.keyboardNavigation.wrapAround;return c.highlightAdjacentPoint(b)?a.response.success:d?a.init(b?1:-1):a.response[b?"next":"prev"]},onSeriesDestroy:function(){var a=this.chart;a.highlightedPoint&&a.highlightedPoint.series===this&&(delete a.highlightedPoint,a.focusElement&&a.focusElement.removeFocusBorder())},destroy:function(){this.eventProvider.removeAddedEvents()}});return d});q(a,"modules/accessibility/components/SeriesComponent/SeriesDescriber.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"]],function(a,l,n,p){function e(a){return a.series&&a.series.data&&C(a.index)?a.series.data.find(function(b){return b&&b.index>a.index&&b.graphic&&b.graphic.element})||null:null}function h(a){var b=a.chart.options.accessibility.series.pointDescriptionEnabledThreshold;return!!(!1!==b&&a.points&&a.points.length>=b)}function t(a){var b=a.options.accessibility||
{};return!h(a)&&!b.exposeAsGroupOnly}function k(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation;return!(!a.points||!(a.points.length<b.pointNavigationEnabledThreshold||!1===b.pointNavigationEnabledThreshold))}function c(a,b){var c=a.series.chart,d=c.numberFormatter,f=c.options.accessibility.point||{};a=a.series.tooltipOptions||{};c=c.options.lang;return B(b)?d(b,f.valueDecimals||a.valueDecimals||-1,c.decimalPoint,c.accessibility.thousandsSep||c.thousandsSep):b}function b(a){var b=
(a.options.accessibility||{}).description;return b&&a.chart.langFormat("accessibility.series.description",{description:b,series:a})}function d(a,b){return a.chart.langFormat("accessibility.series."+b+"Description",{name:q(a[b]),series:a})}function f(b){var c=b.series,d=c.chart,f=d.options.accessibility.point||{};if(c.xAxis&&c.xAxis.isDatetimeAxis)return c=a.Tooltip.prototype.getXDateFormat.call({getDateFormat:a.Tooltip.prototype.getDateFormat,chart:d},b,d.options.tooltip,c.xAxis),f=f.dateFormatter&&
f.dateFormatter(b)||f.dateFormat||c,d.time.dateFormat(f,b.x)}function u(a){var b=f(a),c=(a.series.xAxis||{}).categories&&C(a.category)&&(""+a.category).replace("<br/>"," "),d=a.id&&0>a.id.indexOf("highcharts-"),m="x, "+a.x;return a.name||b||c||(d?a.id:m)}function w(a,b,d){var f=b||"",e=d||"";return a.series.pointArrayMap.reduce(function(b,d){b+=b.length?", ":"";var h=c(a,m(a[d],a.options[d]));return b+(d+": "+f+h+e)},"")}function x(a){var b=a.series,d=b.chart.options.accessibility.point||{},f=b.tooltipOptions||
{},m=d.valuePrefix||f.valuePrefix||"";d=d.valueSuffix||f.valueSuffix||"";f=c(a,a["undefined"!==typeof a.value?"value":"y"]);return a.isNull?b.chart.langFormat("accessibility.series.nullPointValue",{point:a}):b.pointArrayMap?w(a,m,d):m+f+d}function r(a){var b=a.series,c=b.chart,d=a.options&&a.options.accessibility&&a.options.accessibility.description,f=m(b.xAxis&&b.xAxis.options.accessibility&&b.xAxis.options.accessibility.enabled,!c.angular),e=u(a),h=x(a);return(C(a.index)?a.index+1+". ":"")+(f?e+
", ":"")+(h+".")+(d?" "+d:"")+(1<c.series.length&&b.name?" "+b.name+".":"")}function v(a){var b=t(a),c=k(a);(b||c)&&a.points.forEach(function(a){var c=a.isNull,d;if(!(d=a.graphic&&a.graphic.element)){if(c){d=a.series;d=(c=e(a))?c.graphic.parentGroup:d.graph||d.group;var f=c?{x:m(a.plotX,c.plotX,0),y:m(a.plotY,c.plotY,0)}:{x:m(a.plotX,0),y:m(a.plotY,0)};f=a.series.chart.renderer.rect(f.x,f.y,1,1);f.attr({"class":"highcharts-a11y-dummy-point",fill:"none","fill-opacity":0,"stroke-opacity":0,opacity:0});
d&&d.element?(a.graphic=f,f.add(d),d.element.insertBefore(f.element,c?c.graphic.element:null),c=f.element):c=void 0}d=c}if(c=d)c.setAttribute("tabindex","-1"),b?(f=a.series,d=f.chart.options.accessibility.point||{},f=f.options.accessibility||{},a=z(f.pointDescriptionFormatter&&f.pointDescriptionFormatter(a)||d.descriptionFormatter&&d.descriptionFormatter(a)||r(a)),c.setAttribute("role","img"),c.setAttribute("aria-label",a)):c.setAttribute("aria-hidden",!0)})}function y(a){var c=a.chart,f=c.types||
[],m=b(a),e=function(b){return c[b]&&1<c[b].length&&a[b]},h=d(a,"xAxis"),u=d(a,"yAxis"),g={name:a.name||"",ix:a.index+1,numSeries:c.series&&c.series.length,numPoints:a.points&&a.points.length,series:a};f=1<f.length?"Combination":"";return(c.langFormat("accessibility.series.summary."+a.type+f,g)||c.langFormat("accessibility.series.summary.default"+f,g))+(m?" "+m:"")+(e("yAxis")?" "+u:"")+(e("xAxis")?" "+h:"")}var B=l.isNumber,m=l.pick,C=l.defined,z=n.stripHTMLTagsFromString,A=n.reverseChildNodes,q=
p.getAxisDescription,D=p.getSeriesFirstPointElement,F=p.getSeriesA11yElement,G=p.unhideChartElementFromAT;return{describeSeries:function(a){var b=a.chart,c=D(a),d=F(a);if(d){d.lastChild===c&&A(d);v(a);G(b,d);var f=a.chart;b=f.options.chart||{};c=1<f.series.length;f=f.options.accessibility.series.describeSingleSeries;var m=(a.options.accessibility||{}).exposeAsGroupOnly;b.options3d&&b.options3d.enabled&&c||!(c||f||m||h(a))?d.setAttribute("aria-label",""):(b=a.chart.options.accessibility,c=b.landmarkVerbosity,
(a.options.accessibility||{}).exposeAsGroupOnly?d.setAttribute("role","img"):"all"===c&&d.setAttribute("role","region"),d.setAttribute("tabindex","-1"),d.setAttribute("aria-label",z(b.series.descriptionFormatter&&b.series.descriptionFormatter(a)||y(a))))}},defaultPointDescriptionFormatter:r,defaultSeriesDescriptionFormatter:y,getPointA11yTimeDescription:f,getPointXDescription:u,getPointValueDescription:x}});q(a,"modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js",[a["parts/Globals.js"],
a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/DOMElementProvider.js"]],function(a,l,n,p,e,g,t){function h(a){var b=a.series.data.filter(function(b){return a.x===b.x&&a.y===b.y});return 1===b.length?b[0]:a}function c(a,b){var c=(a||[]).concat(b||[]).reduce(function(a,b){a[b.name+
b.index]=b;return a},{});return Object.keys(c).map(function(a){return c[a]})}var b=l.extend,d=l.defined,f=n.visuallyHideElement,u=p.getChartTitle,w=e.defaultPointDescriptionFormatter,x=e.defaultSeriesDescriptionFormatter;l=function(a){this.chart=a};b(l.prototype,{init:function(){this.lastAnnouncementTime=0;this.dirty={allSeries:{}};this.eventProvider=new g;this.domElementProvider=new t;this.announceRegion=this.addAnnounceRegion();this.addEventListeners()},destroy:function(){this.eventProvider.removeAddedEvents();
this.domElementProvider.destroyCreatedElements()},addAnnounceRegion:function(){var a=this.chart,b=this.domElementProvider.createElement("div"),c=a.options.accessibility.announceNewData;b.setAttribute("aria-hidden",!1);b.setAttribute("aria-live",c.interruptUser?"assertive":"polite");f(b);a.renderTo.insertBefore(b,a.renderTo.firstChild);return b},addEventListeners:function(){var b=this,c=this.chart,d=this.eventProvider;d.addEvent(c,"afterDrilldown",function(){b.lastAnnouncementTime=0});d.addEvent(a.Series,
"updatedData",function(){b.onSeriesUpdatedData(this)});d.addEvent(c,"afterAddSeries",function(a){b.onSeriesAdded(a.series)});d.addEvent(a.Series,"addPoint",function(a){b.onPointAdded(a.point)});d.addEvent(c,"redraw",function(){b.announceDirtyData()})},onSeriesUpdatedData:function(a){var b=this.chart;a.chart===b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a)},onSeriesAdded:function(a){this.chart.options.accessibility.announceNewData.enabled&&
(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a,this.dirty.newSeries=d(this.dirty.newSeries)?null:a)},onPointAdded:function(a){var b=a.series.chart;this.chart===b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.newPoint=d(this.dirty.newPoint)?null:a)},announceDirtyData:function(){var a=this;if(this.chart.options.accessibility.announceNewData&&this.dirty.hasDirty){var b=this.dirty.newPoint;b&&(b=h(b));this.queueAnnouncement(Object.keys(this.dirty.allSeries).map(function(b){return a.dirty.allSeries[b]}),
this.dirty.newSeries,b);this.dirty={allSeries:{}}}},queueAnnouncement:function(a,b,d){var f=this.chart.options.accessibility.announceNewData;if(f.enabled){var m=this,e=+new Date;f=Math.max(0,f.minAnnounceInterval-(e-this.lastAnnouncementTime));a=c(this.queuedAnnouncement&&this.queuedAnnouncement.series,a);if(b=this.buildAnnouncementMessage(a,b,d))this.queuedAnnouncement&&clearTimeout(this.queuedAnnouncementTimer),this.queuedAnnouncement={time:e,message:b,series:a},m.queuedAnnouncementTimer=setTimeout(function(){m&&
m.announceRegion&&(m.lastAnnouncementTime=+new Date,m.liveRegionSpeak(m.queuedAnnouncement.message),delete m.queuedAnnouncement,delete m.queuedAnnouncementTimer)},f)}},liveRegionSpeak:function(a){var b=this;this.announceRegion.innerHTML=a;this.clearAnnouncementContainerTimer&&clearTimeout(this.clearAnnouncementContainerTimer);this.clearAnnouncementContainerTimer=setTimeout(function(){b.announceRegion.innerHTML="";delete b.clearAnnouncementContainerTimer},1E3)},buildAnnouncementMessage:function(b,
c,d){var f=this.chart,m=f.options.accessibility.announceNewData;if(m.announcementFormatter&&(b=m.announcementFormatter(b,c,d),!1!==b))return b.length?b:null;b=a.charts&&1<a.charts.length?"Multiple":"Single";b=c?"newSeriesAnnounce"+b:d?"newPointAnnounce"+b:"newDataAnnounce";m=u(f);return f.langFormat("accessibility.announceNewData."+b,{chartTitle:m,seriesDesc:c?x(c):null,pointDesc:d?w(d):null,point:d,series:c})}});return l});q(a,"modules/accessibility/components/SeriesComponent/forcedMarkers.js",[a["parts/Globals.js"]],
function(a){function h(a){n(!0,a,{marker:{enabled:!0,states:{normal:{opacity:0}}}})}var n=a.merge;return function(){a.addEvent(a.Series,"render",function(){var a=this.options,e=this.chart.options.accessibility.enabled,g=!1!==(this.options.accessibility&&this.options.accessibility.enabled);var t=this.chart.options.accessibility;t=this.points.length<t.series.pointDescriptionEnabledThreshold||!1===t.series.pointDescriptionEnabledThreshold;var k=this.chart.options.accessibility.keyboardNavigation.seriesNavigation;
k=this.points.length<k.pointNavigationEnabledThreshold||!1===k.pointNavigationEnabledThreshold;if(e&&g&&(t||k)){if(a.marker&&!1===a.marker.enabled&&(this.a11yMarkersForced=!0,h(this.options)),this._hasPointMarkers&&this.points&&this.points.length)for(a=this.points,e=a.length;e--;)g=a[e].options,g.marker&&(g.marker.enabled?n(!0,g.marker,{states:{normal:{opacity:g.marker.states&&g.marker.states.normal&&g.marker.states.normal.opacity||1}}}):h(g))}else this.a11yMarkersForced&&this.resetMarkerOptions&&
(delete this.a11yMarkersForced,a=this.resetA11yMarkerOptions,n(!0,this.options,{marker:{enabled:a.enabled,states:{normal:{opacity:a.states&&a.states.normal&&a.states.normal.opacity}}}}))});a.addEvent(a.Series,"afterSetOptions",function(a){this.resetA11yMarkerOptions=n(a.options.marker||{},this.userOptions.marker||{})})}});q(a,"modules/accessibility/components/SeriesComponent/SeriesComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js"],
a["modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js"],a["modules/accessibility/components/SeriesComponent/forcedMarkers.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"]],function(a,l,n,p,e,g,t,k){l=l.extend;var c=t.hideSeriesFromAT,b=k.describeSeries;a.SeriesAccessibilityDescriber=k;g();g=function(){};g.prototype=new n;l(g.prototype,{init:function(){this.newDataAnnouncer=new e(this.chart);this.newDataAnnouncer.init();
this.keyboardNavigation=new p(this.chart,this.keyCodes);this.keyboardNavigation.init();this.hideTooltipFromATWhenShown();this.hideSeriesLabelsFromATWhenShown()},hideTooltipFromATWhenShown:function(){var b=this;this.addEvent(a.Tooltip,"refresh",function(){this.chart===b.chart&&this.label&&this.label.element&&this.label.element.setAttribute("aria-hidden",!0)})},hideSeriesLabelsFromATWhenShown:function(){this.addEvent(this.chart,"afterDrawSeriesLabels",function(){this.series.forEach(function(a){a.labelBySeries&&
a.labelBySeries.attr("aria-hidden",!0)})})},onChartRender:function(){this.chart.series.forEach(function(a){!1!==(a.options.accessibility&&a.options.accessibility.enabled)&&a.visible?b(a):c(a)})},getKeyboardNavigation:function(){return this.keyboardNavigation.getKeyboardNavigationHandler()},destroy:function(){this.newDataAnnouncer.destroy();this.keyboardNavigation.destroy()}});return g});q(a,"modules/accessibility/components/ZoomComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],
a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n,p,e,g){var h=l.extend,k=l.pick,c=e.unhideChartElementFromAT,b=g.setElAttrs,d=g.removeElement;a.Axis.prototype.panStep=function(a,b){var c=b||3;b=this.getExtremes();var d=(b.max-b.min)/c*a;c=b.max+d;d=b.min+d;var f=c-d;0>a&&d<b.dataMin?(d=b.dataMin,c=d+f):0<a&&c>b.dataMax&&(c=b.dataMax,d=c-f);this.setExtremes(d,c)};a=function(){};
a.prototype=new n;h(a.prototype,{init:function(){var a=this,b=this.chart;["afterShowResetZoom","afterDrilldown","drillupall"].forEach(function(c){a.addEvent(b,c,function(){a.updateProxyOverlays()})})},onChartUpdate:function(){var a=this.chart,b=this;a.mapNavButtons&&a.mapNavButtons.forEach(function(d,f){c(a,d.element);b.setMapNavButtonAttrs(d.element,"accessibility.zoom.mapZoom"+(f?"Out":"In"))})},setMapNavButtonAttrs:function(a,c){var d=this.chart;c=d.langFormat(c,{chart:d});b(a,{tabindex:-1,role:"button",
"aria-label":c})},onChartRender:function(){this.updateProxyOverlays()},updateProxyOverlays:function(){var a=this.chart;d(this.drillUpProxyGroup);d(this.resetZoomProxyGroup);a.resetZoomButton&&this.recreateProxyButtonAndGroup(a.resetZoomButton,"resetZoomProxyButton","resetZoomProxyGroup",a.langFormat("accessibility.zoom.resetZoomButton",{chart:a}));a.drillUpButton&&this.recreateProxyButtonAndGroup(a.drillUpButton,"drillUpProxyButton","drillUpProxyGroup",a.langFormat("accessibility.drillUpButton",{chart:a,
buttonText:a.getDrilldownBackText()}))},recreateProxyButtonAndGroup:function(a,b,c,e){d(this[c]);this[c]=this.addProxyGroup();this[b]=this.createProxyButton(a,this[c],{"aria-label":e,tabindex:-1})},getMapZoomNavigation:function(){var a=this.keyCodes,b=this.chart,c=this;return new p(b,{keyCodeMap:[[[a.up,a.down,a.left,a.right],function(a){return c.onMapKbdArrow(this,a)}],[[a.tab],function(a,b){return c.onMapKbdTab(this,b)}],[[a.space,a.enter],function(){return c.onMapKbdClick(this)}]],validate:function(){return b.mapZoom&&
b.mapNavButtons&&b.mapNavButtons.length},init:function(a){return c.onMapNavInit(a)}})},onMapKbdArrow:function(a,b){var c=this.keyCodes;this.chart[b===c.up||b===c.down?"yAxis":"xAxis"][0].panStep(b===c.left||b===c.up?-1:1);return a.response.success},onMapKbdTab:function(a,b){var c=this.chart;a=a.response;var d=(b=b.shiftKey)&&!this.focusedMapNavButtonIx||!b&&this.focusedMapNavButtonIx;c.mapNavButtons[this.focusedMapNavButtonIx].setState(0);if(d)return c.mapZoom(),a[b?"prev":"next"];this.focusedMapNavButtonIx+=
b?-1:1;b=c.mapNavButtons[this.focusedMapNavButtonIx];c.setFocusToElement(b.box,b.element);b.setState(2);return a.success},onMapKbdClick:function(a){this.fakeClickEvent(this.chart.mapNavButtons[this.focusedMapNavButtonIx].element);return a.response.success},onMapNavInit:function(a){var b=this.chart,c=b.mapNavButtons[0],d=b.mapNavButtons[1];c=0<a?c:d;b.setFocusToElement(c.box,c.element);c.setState(2);this.focusedMapNavButtonIx=0<a?0:1},simpleButtonNavigation:function(a,b,c){var d=this.keyCodes,f=this,
e=this.chart;return new p(e,{keyCodeMap:[[[d.tab,d.up,d.down,d.left,d.right],function(a,b){return this.response[a===d.tab&&b.shiftKey||a===d.left||a===d.up?"prev":"next"]}],[[d.space,d.enter],function(){var a=c(this,e);return k(a,this.response.success)}]],validate:function(){return e[a]&&e[a].box&&f[b]},init:function(){e.setFocusToElement(e[a].box,f[b])}})},getKeyboardNavigation:function(){return[this.simpleButtonNavigation("resetZoomButton","resetZoomProxyButton",function(a,b){b.zoomOut()}),this.simpleButtonNavigation("drillUpButton",
"drillUpProxyButton",function(a,b){b.drillUp();return a.response.prev}),this.getMapZoomNavigation()]}});return a});q(a,"modules/accessibility/components/RangeSelectorComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n,p,e,g){l=l.extend;var h=e.unhideChartElementFromAT,
k=g.setElAttrs;a.Chart.prototype.highlightRangeSelectorButton=function(a){var b=this.rangeSelector.buttons;b[this.highlightedRangeSelectorItemIx]&&b[this.highlightedRangeSelectorItemIx].setState(this.oldRangeSelectorItemState||0);this.highlightedRangeSelectorItemIx=a;return b[a]?(this.setFocusToElement(b[a].box,b[a].element),this.oldRangeSelectorItemState=b[a].state,b[a].setState(2),!0):!1};a=function(){};a.prototype=new n;l(a.prototype,{onChartUpdate:function(){var a=this.chart,b=this,d=a.rangeSelector;
d&&(d.buttons&&d.buttons.length&&d.buttons.forEach(function(c){h(a,c.element);b.setRangeButtonAttrs(c)}),d.maxInput&&d.minInput&&["minInput","maxInput"].forEach(function(c,e){if(c=d[c])h(a,c),b.setRangeInputAttrs(c,"accessibility.rangeSelector."+(e?"max":"min")+"InputLabel")}))},setRangeButtonAttrs:function(a){var b=this.chart;b=b.langFormat("accessibility.rangeSelector.buttonText",{chart:b,buttonText:a.text&&a.text.textStr});k(a.element,{tabindex:-1,role:"button","aria-label":b})},setRangeInputAttrs:function(a,
b){var c=this.chart;k(a,{tabindex:-1,role:"textbox","aria-label":c.langFormat(b,{chart:c})})},getRangeSelectorButtonNavigation:function(){var a=this.chart,b=this.keyCodes,d=this;return new p(a,{keyCodeMap:[[[b.left,b.right,b.up,b.down],function(a){return d.onButtonNavKbdArrowKey(this,a)}],[[b.enter,b.space],function(){return d.onButtonNavKbdClick(this)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.buttons&&a.rangeSelector.buttons.length},init:function(b){var c=a.rangeSelector.buttons.length-
1;a.highlightRangeSelectorButton(0<b?0:c)}})},onButtonNavKbdArrowKey:function(a,b){var c=a.response,f=this.keyCodes,e=this.chart,g=e.options.accessibility.keyboardNavigation.wrapAround;b=b===f.left||b===f.up?-1:1;return e.highlightRangeSelectorButton(e.highlightedRangeSelectorItemIx+b)?c.success:g?(a.init(b),c.success):c[0<b?"next":"prev"]},onButtonNavKbdClick:function(){var a=this.chart;3!==a.oldRangeSelectorItemState&&this.fakeClickEvent(a.rangeSelector.buttons[a.highlightedRangeSelectorItemIx].element)},
getRangeSelectorInputNavigation:function(){var a=this.chart,b=this.keyCodes,d=this;return new p(a,{keyCodeMap:[[[b.tab,b.up,b.down],function(a,c){return d.onInputKbdMove(this,a===b.tab&&c.shiftKey||a===b.up?-1:1)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.inputGroup&&"hidden"!==a.rangeSelector.inputGroup.element.getAttribute("visibility")&&!1!==a.options.rangeSelector.inputEnabled&&a.rangeSelector.minInput&&a.rangeSelector.maxInput},init:function(a){d.onInputNavInit(a)},terminate:function(){d.onInputNavTerminate()}})},
onInputKbdMove:function(a,b){var c=this.chart;a=a.response;var e=c.highlightedInputRangeIx+=b;if(1<e||0>e)return a[0<b?"next":"prev"];c.rangeSelector[e?"maxInput":"minInput"].focus();return a.success},onInputNavInit:function(a){var b=this.chart;a=0<a?0:1;b.highlightedInputRangeIx=a;b.rangeSelector[a?"maxInput":"minInput"].focus()},onInputNavTerminate:function(){var a=this.chart.rangeSelector||{};a.maxInput&&a.hideInput("max");a.minInput&&a.hideInput("min")},getKeyboardNavigation:function(){return[this.getRangeSelectorButtonNavigation(),
this.getRangeSelectorInputNavigation()]}});return a});q(a,"modules/accessibility/components/InfoRegionsComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,l,n,p,e){function g(a){return a.replace(/&lt;(h[1-7]|p|div)&gt;/g,"<$1>").replace(/&lt;&#x2F;(h[1-7]|p|div|a|button)&gt;/g,"</$1>").replace(/&lt;(div|a|button) id=&quot;([a-zA-Z\-0-9#]*?)&quot;&gt;/g,
'<$1 id="$2">')}var h=a.win.document,k=a.format,c=l.extend,b=l.pick,d=p.unhideChartElementFromAT,f=p.getChartTitle,u=p.getAxisDescription,w=e.addClass,q=e.setElAttrs,r=e.escapeStringForHTML,v=e.stripHTMLTagsFromString,y=e.getElement,B=e.visuallyHideElement;a.Chart.prototype.getTypeDescription=function(a){var b=a[0],c=this.series&&this.series[0]||{};c={numSeries:this.series.length,numPoints:c.points&&c.points.length,chart:this,mapTitle:c.mapTitle};if(!b)return this.langFormat("accessibility.chartTypes.emptyChart",
c);if("map"===b)return c.mapTitle?this.langFormat("accessibility.chartTypes.mapTypeDescription",c):this.langFormat("accessibility.chartTypes.unknownMap",c);if(1<this.types.length)return this.langFormat("accessibility.chartTypes.combinationChart",c);a=a[0];b=this.langFormat("accessibility.seriesTypeDescriptions."+a,c);var d=this.series&&2>this.series.length?"Single":"Multiple";return(this.langFormat("accessibility.chartTypes."+a+d,c)||this.langFormat("accessibility.chartTypes.default"+d,c))+(b?" "+
b:"")};l=function(){};l.prototype=new n;c(l.prototype,{init:function(){var a=this.chart,b=this;this.initRegionsDefinitions();this.addEvent(a,"afterGetTable",function(a){b.onDataTableCreated(a)});this.addEvent(a,"afterViewData",function(a){b.dataTableDiv=a;setTimeout(function(){b.focusDataTable()},300)})},initRegionsDefinitions:function(){var a=this;this.screenReaderSections={before:{element:null,buildContent:function(b){var c=b.options.accessibility.screenReaderSection.beforeChartFormatter;return c?
c(b):a.defaultBeforeChartFormatter(b)},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.renderTo.firstChild)},afterInserted:function(){a.initDataTableButton(a.dataTableButtonId)}},after:{element:null,buildContent:function(b){var c=b.options.accessibility.screenReaderSection.afterChartFormatter;return c?c(b):a.defaultAfterChartFormatter(b)},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.container.nextSibling)},afterInserted:function(){a.endOfChartMarkerId&&(a.chart.endOfChartMarker=
y(a.endOfChartMarkerId))}}}},onChartUpdate:function(){var a=this;this.linkedDescriptionElement=this.getLinkedDescriptionElement();this.setLinkedDescriptionAttrs();Object.keys(this.screenReaderSections).forEach(function(b){a.updateScreenReaderSection(b)})},getLinkedDescriptionElement:function(){var a=this.chart.options.accessibility.linkedDescription;if(a){if(a.innerHTML)return a;a=k(a,this.chart);a=h.querySelectorAll(a);if(1===a.length)return a[0]}},setLinkedDescriptionAttrs:function(){var a=this.linkedDescriptionElement;
a&&(a.setAttribute("aria-hidden","true"),w(a,"highcharts-linked-description"))},updateScreenReaderSection:function(a){var b=this.chart,c=this.screenReaderSections[a],e=c.buildContent(b),f=c.element=c.element||this.createElement("div"),m=f.firstChild||this.createElement("div");this.setScreenReaderSectionAttribs(f,a);m.innerHTML=e;f.appendChild(m);c.insertIntoDOM(f,b);B(m);d(b,m);c.afterInserted&&c.afterInserted()},setScreenReaderSectionAttribs:function(a,b){var c=this.chart,d=c.langFormat("accessibility.screenReaderSection."+
b+"RegionLabel",{chart:c});q(a,{id:"highcharts-screen-reader-region-"+b+"-"+c.index,"aria-label":d});a.style.position="relative";"all"===c.options.accessibility.landmarkVerbosity&&d&&a.setAttribute("role","region")},defaultBeforeChartFormatter:function(){var b=this.chart,c=b.options.accessibility.screenReaderSection.beforeChartFormat,d=this.getAxesDescription(),e="hc-linkto-highcharts-data-table-"+b.index;b={chartTitle:f(b),typeDescription:this.getTypeDescriptionText(),chartSubtitle:this.getSubtitleText(),
chartLongdesc:this.getLongdescText(),xAxisDescription:d.xAxis,yAxisDescription:d.yAxis,viewTableButton:b.getCSV?this.getDataTableButtonText(e):""};c=a.i18nFormat(c,b);this.dataTableButtonId=e;return g(r(c)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},defaultAfterChartFormatter:function(){var b=this.chart.options.accessibility.screenReaderSection.afterChartFormat,c={endOfChartMarker:this.getEndOfChartMarkerText()};b=a.i18nFormat(b,c);return g(r(b)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},getLinkedDescription:function(){var a=
this.linkedDescriptionElement;return v(a&&a.innerHTML||"")},getLongdescText:function(){var a=this.chart.options,b=a.caption;b=b&&b.text;var c=this.getLinkedDescription();return a.accessibility.description||c||b||""},getTypeDescriptionText:function(){var a=this.chart;return a.types?a.options.accessibility.typeDescription||a.getTypeDescription(a.types):""},getDataTableButtonText:function(a){var b=this.chart;b=b.langFormat("accessibility.table.viewAsDataTableButtonText",{chart:b,chartTitle:f(b)});return'<a id="'+
a+'">'+b+"</a>"},getSubtitleText:function(){var a=this.chart.options.subtitle;return v(a&&a.text||"")},getEndOfChartMarkerText:function(){var a=this.chart,b=a.langFormat("accessibility.screenReaderSection.endOfChartMarker",{chart:a});return'<div id="highcharts-end-of-chart-marker-'+a.index+'">'+b+"</div>"},onDataTableCreated:function(a){var b=this.chart;b.options.accessibility.enabled&&(this.viewDataTableButton&&this.viewDataTableButton.setAttribute("aria-expanded","true"),a.html=a.html.replace("<table ",
'<table tabindex="0" summary="'+b.langFormat("accessibility.table.tableSummary",{chart:b})+'"'))},focusDataTable:function(){var a=this.dataTableDiv;(a=a&&a.getElementsByTagName("table")[0])&&a.focus&&a.focus()},initDataTableButton:function(a){var b=this.viewDataTableButton=a&&y(a),c=this.chart;a=a&&a.replace("hc-linkto-","");b&&(q(b,{role:"button",tabindex:"-1","aria-expanded":!!y(a),href:"#"+a}),b.onclick=c.options.accessibility.screenReaderSection.onViewDataTableClick||function(){c.viewData()})},
getAxesDescription:function(){var a=this.chart,c=function(c,d){c=a[c];return 1<c.length||c[0]&&b(c[0].options.accessibility&&c[0].options.accessibility.enabled,d)},d=0>a.types.indexOf("map"),e=a.hasCartesianSeries,f=c("xAxis",!a.angular&&e&&d);c=c("yAxis",e&&d);d={};f&&(d.xAxis=this.getAxisDescriptionText("xAxis"));c&&(d.yAxis=this.getAxisDescriptionText("yAxis"));return d},getAxisDescriptionText:function(a){var b=this,c=this.chart,d=c[a];return c.langFormat("accessibility.axis."+a+"Description"+
(1<d.length?"Plural":"Singular"),{chart:c,names:d.map(function(a){return u(a)}),ranges:d.map(function(a){return b.getAxisRangeDescription(a)}),numAxes:d.length})},getAxisRangeDescription:function(a){var b=a.options||{};return b.accessibility&&"undefined"!==typeof b.accessibility.rangeDescription?b.accessibility.rangeDescription:a.categories?this.getCategoryAxisRangeDesc(a):!a.isDatetimeAxis||0!==a.min&&0!==a.dataMin?this.getAxisFromToDescription(a):this.getAxisTimeLengthDesc(a)},getCategoryAxisRangeDesc:function(a){var b=
this.chart;return b.langFormat("accessibility.axis.rangeCategories",{chart:b,axis:a,numCategories:a.dataMax-a.dataMin+1})},getAxisTimeLengthDesc:function(a){var b=this.chart,c={},d="Seconds";c.Seconds=(a.max-a.min)/1E3;c.Minutes=c.Seconds/60;c.Hours=c.Minutes/60;c.Days=c.Hours/24;["Minutes","Hours","Days"].forEach(function(a){2<c[a]&&(d=a)});c.value=c[d].toFixed("Seconds"!==d&&"Minutes"!==d?1:0);return b.langFormat("accessibility.axis.timeRange"+d,{chart:b,axis:a,range:c.value.replace(".0","")})},
getAxisFromToDescription:function(a){var b=this.chart,c=b.options.accessibility.screenReaderSection.axisRangeDateFormat,d=function(d){return a.isDatetimeAxis?b.time.dateFormat(c,a[d]):a[d]};return b.langFormat("accessibility.axis.rangeFromTo",{chart:b,axis:a,rangeFrom:d("min"),rangeTo:d("max")})}});return l});q(a,"modules/accessibility/components/ContainerComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],
a["modules/accessibility/AccessibilityComponent.js"]],function(a,l,n,p,e){var g=a.win.document;a=l.extend;var h=n.stripHTMLTagsFromString,k=p.unhideChartElementFromAT,c=p.getChartTitle;n=function(){};n.prototype=new e;a(n.prototype,{onChartUpdate:function(){this.handleSVGTitleElement();this.setSVGContainerLabel();this.setGraphicContainerAttrs();this.setRenderToAttrs();this.makeCreditsAccessible()},handleSVGTitleElement:function(){var a=this.chart,d="highcharts-title-"+a.index,e=h(a.langFormat("accessibility.svgContainerTitle",
{chartTitle:c(a)}));if(e.length){var k=this.svgTitleElement=this.svgTitleElement||g.createElementNS("http://www.w3.org/2000/svg","title");k.textContent=e;k.id=d;a.renderTo.insertBefore(k,a.renderTo.firstChild)}},setSVGContainerLabel:function(){var a=this.chart,d=h(a.langFormat("accessibility.svgContainerLabel",{chartTitle:c(a)}));a.renderer.box&&d.length&&a.renderer.box.setAttribute("aria-label",d)},setGraphicContainerAttrs:function(){var a=this.chart,d=a.langFormat("accessibility.graphicContainerLabel",
{chartTitle:c(a)});d.length&&a.container.setAttribute("aria-label",d)},setRenderToAttrs:function(){var a=this.chart;"disabled"!==a.options.accessibility.landmarkVerbosity?a.renderTo.setAttribute("role","region"):a.renderTo.removeAttribute("role");a.renderTo.setAttribute("aria-label",a.langFormat("accessibility.chartContainerLabel",{title:c(a),chart:a}))},makeCreditsAccessible:function(){var a=this.chart,c=a.credits&&a.credits.element;c&&(a.credits.textStr&&c.setAttribute("aria-label",h(a.langFormat("accessibility.credits",
{creditsStr:a.credits.textStr}))),k(a,c))},destroy:function(){this.chart.renderTo.setAttribute("aria-hidden",!0)}});return n});q(a,"modules/accessibility/high-contrast-mode.js",[a["parts/Globals.js"]],function(a){var h=a.isMS,n=a.win,p=n.document;return{isHighContrastModeActive:function(){if(n.matchMedia&&h&&/Edge\/\d./i.test(n.navigator.userAgent))return n.matchMedia("(-ms-high-contrast: active)").matches;if(h&&n.getComputedStyle){var a=p.createElement("div");a.style.backgroundImage="url(#)";p.body.appendChild(a);
var g=(a.currentStyle||n.getComputedStyle(a)).backgroundImage;p.body.removeChild(a);return"none"===g}return!1},setHighContrastTheme:function(a){a.highContrastModeActive=!0;var e=a.options.accessibility.highContrastTheme;a.update(e,!1);a.series.forEach(function(a){var g=e.plotOptions[a.type]||{};a.update({color:g.color||"windowText",colors:[g.color||"windowText"],borderColor:g.borderColor||"window"});a.points.forEach(function(a){a.options&&a.options.color&&a.update({color:g.color||"windowText",borderColor:g.borderColor||
"window"},!1)})});a.redraw()}}});q(a,"modules/accessibility/high-contrast-theme.js",[],function(){return{chart:{backgroundColor:"window"},title:{style:{color:"windowText"}},subtitle:{style:{color:"windowText"}},colorAxis:{minColor:"windowText",maxColor:"windowText",stops:null},colors:["windowText"],xAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},yAxis:{gridLineColor:"windowText",
labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},tooltip:{backgroundColor:"window",borderColor:"windowText",style:{color:"windowText"}},plotOptions:{series:{lineColor:"windowText",fillColor:"window",borderColor:"windowText",edgeColor:"windowText",borderWidth:1,dataLabels:{connectorColor:"windowText",color:"windowText",style:{color:"windowText",textOutline:"none"}},marker:{lineColor:"windowText",fillColor:"windowText"}},
pie:{color:"window",colors:["window"],borderColor:"windowText",borderWidth:1},boxplot:{fillColor:"window"},candlestick:{lineColor:"windowText",fillColor:"window"},errorbar:{fillColor:"window"}},legend:{backgroundColor:"window",itemStyle:{color:"windowText"},itemHoverStyle:{color:"windowText"},itemHiddenStyle:{color:"#555"},title:{style:{color:"windowText"}}},credits:{style:{color:"windowText"}},labels:{style:{color:"windowText"}},drilldown:{activeAxisLabelStyle:{color:"windowText"},activeDataLabelStyle:{color:"windowText"}},
navigation:{buttonOptions:{symbolStroke:"windowText",theme:{fill:"window"}}},rangeSelector:{buttonTheme:{fill:"window",stroke:"windowText",style:{color:"windowText"},states:{hover:{fill:"window",stroke:"windowText",style:{color:"windowText"}},select:{fill:"#444",stroke:"windowText",style:{color:"windowText"}}}},inputBoxBorderColor:"windowText",inputStyle:{backgroundColor:"window",color:"windowText"},labelStyle:{color:"windowText"}},navigator:{handles:{backgroundColor:"window",borderColor:"windowText"},
outlineColor:"windowText",maskFill:"transparent",series:{color:"windowText",lineColor:"windowText"},xAxis:{gridLineColor:"windowText"}},scrollbar:{barBackgroundColor:"#444",barBorderColor:"windowText",buttonArrowColor:"windowText",buttonBackgroundColor:"window",buttonBorderColor:"windowText",rifleColor:"windowText",trackBackgroundColor:"window",trackBorderColor:"windowText"}}});q(a,"modules/accessibility/options/options.js",[],function(){return{accessibility:{enabled:!0,screenReaderSection:{beforeChartFormat:"<h5>{chartTitle}</h5><div>{typeDescription}</div><div>{chartSubtitle}</div><div>{chartLongdesc}</div><div>{xAxisDescription}</div><div>{yAxisDescription}</div><div>{viewTableButton}</div>",
afterChartFormat:"{endOfChartMarker}",axisRangeDateFormat:"%Y-%m-%d %H:%M:%S"},series:{describeSingleSeries:!1,pointDescriptionEnabledThreshold:200},landmarkVerbosity:"all",linkedDescription:'*[data-highcharts-chart="{index}"] + .highcharts-description',keyboardNavigation:{enabled:!0,focusBorder:{enabled:!0,hideBrowserFocusOutline:!0,style:{color:"#335cad",lineWidth:2,borderRadius:3},margin:2},order:["series","zoom","rangeSelector","legend","chartMenu"],wrapAround:!0,seriesNavigation:{skipNullPoints:!0,
pointNavigationEnabledThreshold:!1}},announceNewData:{enabled:!1,minAnnounceInterval:5E3,interruptUser:!1}},legend:{accessibility:{enabled:!0,keyboardNavigation:{enabled:!0}}},exporting:{accessibility:{enabled:!0}}}});q(a,"modules/accessibility/options/langOptions.js",[],function(){return{accessibility:{defaultChartTitle:"Chart",chartContainerLabel:"{title}. Highcharts interactive chart.",svgContainerLabel:"Interactive chart",drillUpButton:"{buttonText}",credits:"Chart credits: {creditsStr}",thousandsSep:",",
svgContainerTitle:"",graphicContainerLabel:"",screenReaderSection:{beforeRegionLabel:"Chart screen reader information.",afterRegionLabel:"",endOfChartMarker:"End of interactive chart."},legend:{legendLabel:"Toggle series visibility",legendItem:"Toggle visibility of {itemName}"},zoom:{mapZoomIn:"Zoom chart",mapZoomOut:"Zoom out chart",resetZoomButton:"Reset zoom"},rangeSelector:{minInputLabel:"Select start date.",maxInputLabel:"Select end date.",buttonText:"Select range {buttonText}"},table:{viewAsDataTableButtonText:"View as data table. {chartTitle}",
tableSummary:"Table representation of chart."},announceNewData:{newDataAnnounce:"Updated data for chart {chartTitle}",newSeriesAnnounceSingle:"New data series: {seriesDesc}",newPointAnnounceSingle:"New data point: {pointDesc}",newSeriesAnnounceMultiple:"New data series in chart {chartTitle}: {seriesDesc}",newPointAnnounceMultiple:"New data point in chart {chartTitle}: {pointDesc}"},seriesTypeDescriptions:{boxplot:"Box plot charts are typically used to display groups of statistical data. Each data point in the chart can have up to 5 values: minimum, lower quartile, median, upper quartile, and maximum.",
arearange:"Arearange charts are line charts displaying a range between a lower and higher value for each point.",areasplinerange:"These charts are line charts displaying a range between a lower and higher value for each point.",bubble:"Bubble charts are scatter charts where each data point also has a size value.",columnrange:"Columnrange charts are column charts displaying a range between a lower and higher value for each point.",errorbar:"Errorbar series are used to display the variability of the data.",
funnel:"Funnel charts are used to display reduction of data in stages.",pyramid:"Pyramid charts consist of a single pyramid with item heights corresponding to each point value.",waterfall:"A waterfall chart is a column chart where each column contributes towards a total end value."},chartTypes:{emptyChart:"Empty chart",mapTypeDescription:"Map of {mapTitle} with {numSeries} data series.",unknownMap:"Map of unspecified region with {numSeries} data series.",combinationChart:"Combination chart with {numSeries} data series.",
defaultSingle:"Chart with {numPoints} data {#plural(numPoints, points, point)}.",defaultMultiple:"Chart with {numSeries} data series.",splineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",splineMultiple:"Line chart with {numSeries} lines.",lineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",lineMultiple:"Line chart with {numSeries} lines.",columnSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",columnMultiple:"Bar chart with {numSeries} data series.",
barSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",barMultiple:"Bar chart with {numSeries} data series.",pieSingle:"Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.",pieMultiple:"Pie chart with {numSeries} pies.",scatterSingle:"Scatter chart with {numPoints} {#plural(numPoints, points, point)}.",scatterMultiple:"Scatter chart with {numSeries} data series.",boxplotSingle:"Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotMultiple:"Boxplot with {numSeries} data series.",
bubbleSingle:"Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleMultiple:"Bubble chart with {numSeries} data series."},axis:{xAxisDescriptionSingular:"The chart has 1 X axis displaying {names[0]}. {ranges[0]}",xAxisDescriptionPlural:"The chart has {numAxes} X axes displaying {#each(names, -1) }and {names[-1]}.",yAxisDescriptionSingular:"The chart has 1 Y axis displaying {names[0]}. {ranges[0]}",yAxisDescriptionPlural:"The chart has {numAxes} Y axes displaying {#each(names, -1) }and {names[-1]}.",
timeRangeDays:"Range: {range} days.",timeRangeHours:"Range: {range} hours.",timeRangeMinutes:"Range: {range} minutes.",timeRangeSeconds:"Range: {range} seconds.",rangeFromTo:"Range: {rangeFrom} to {rangeTo}.",rangeCategories:"Range: {numCategories} categories."},exporting:{chartMenuLabel:"Chart menu",menuButtonLabel:"View chart menu",exportRegionLabel:"Chart menu"},series:{summary:{"default":"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",defaultCombination:"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",
line:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",lineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",spline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",splineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",column:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",
columnCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",bar:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",barCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",pie:"{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.",pieCombination:"{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.",
scatter:"{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.",scatterCombination:"{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.",boxplot:"{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotCombination:"{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",bubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",
bubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.",map:"{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.",mapCombination:"{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.",mapline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",maplineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",
mapbubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",mapbubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}."},description:"{description}",xAxisDescription:"X axis, {name}",yAxisDescription:"Y axis, {name}",nullPointValue:"No value"}}}});q(a,"modules/accessibility/options/deprecatedOptions.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,l){function h(a,c,
e){b("Highcharts: Deprecated option "+c+" used. This will be removed from future versions of Highcharts. Use "+e+" instead.",!1,a)}function p(a,b,e){for(var d,f=0;f<b.length-1;++f)d=b[f],a=a[d]=c(a[d],{});a[b[b.length-1]]=e}function e(a,b,c,e){function d(a,b){return b.reduce(function(a,b){return a[b]},a)}var f=d(a.options,b),g=d(a.options,c);Object.keys(e).forEach(function(d){var k=f[d];"undefined"!==typeof k&&(p(g,e[d],k),h(a,b.join(".")+"."+d,c.join(".")+"."+e[d].join(".")))})}function g(a){var b=
a.options.chart||{},c=a.options.accessibility||{};["description","typeDescription"].forEach(function(d){b[d]&&(c[d]=b[d],h(a,"chart."+d,"accessibility."+d))})}function t(a){a.axes.forEach(function(b){(b=b.options)&&b.description&&(b.accessibility=b.accessibility||{},b.accessibility.description=b.description,h(a,"axis.description","axis.accessibility.description"))})}function k(a){var b={description:["accessibility","description"],exposeElementToA11y:["accessibility","exposeAsGroupOnly"],pointDescriptionFormatter:["accessibility",
"pointDescriptionFormatter"],skipKeyboardNavigation:["accessibility","keyboardNavigation","enabled"]};a.series.forEach(function(c){Object.keys(b).forEach(function(d){var e=c.options[d];"undefined"!==typeof e&&(p(c.options,b[d],"skipKeyboardNavigation"===d?!e:e),h(a,"series."+d,"series."+b[d].join(".")))})})}var c=l.pick,b=a.error;return function(a){g(a);t(a);a.series&&k(a);e(a,["accessibility"],["accessibility"],{pointDateFormat:["point","dateFormat"],pointDateFormatter:["point","dateFormatter"],
pointDescriptionFormatter:["point","descriptionFormatter"],pointDescriptionThreshold:["series","pointDescriptionEnabledThreshold"],pointNavigationThreshold:["keyboardNavigation","seriesNavigation","pointNavigationEnabledThreshold"],pointValueDecimals:["point","valueDecimals"],pointValuePrefix:["point","valuePrefix"],pointValueSuffix:["point","valueSuffix"],screenReaderSectionFormatter:["screenReaderSection","beforeChartFormatter"],describeSingleSeries:["series","describeSingleSeries"],seriesDescriptionFormatter:["series",
"descriptionFormatter"],onTableAnchorClick:["screenReaderSection","onViewDataTableClick"],axisRangeDateFormat:["screenReaderSection","axisRangeDateFormat"]});e(a,["accessibility","keyboardNavigation"],["accessibility","keyboardNavigation","seriesNavigation"],{skipNullPoints:["skipNullPoints"],mode:["mode"]});e(a,["lang","accessibility"],["lang","accessibility"],{legendItem:["legend","legendItem"],legendLabel:["legend","legendLabel"],mapZoomIn:["zoom","mapZoomIn"],mapZoomOut:["zoom","mapZoomOut"],
resetZoomButton:["zoom","resetZoomButton"],screenReaderRegionLabel:["screenReaderSection","beforeRegionLabel"],rangeSelectorButton:["rangeSelector","buttonText"],rangeSelectorMaxInput:["rangeSelector","maxInputLabel"],rangeSelectorMinInput:["rangeSelector","minInputLabel"],svgContainerEnd:["screenReaderSection","endOfChartMarker"],viewAsDataTable:["table","viewAsDataTableButtonText"],tableSummary:["table","tableSummary"]})}});q(a,"modules/accessibility/a11y-i18n.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],
function(a,l){function h(a,g){var e=a.indexOf("#each("),k=a.indexOf("#plural("),c=a.indexOf("["),b=a.indexOf("]");if(-1<e){c=a.slice(e).indexOf(")")+e;var d=a.substring(0,e);k=a.substring(c+1);c=a.substring(e+6,c).split(",");e=Number(c[1]);a="";if(g=g[c[0]])for(e=isNaN(e)?g.length:e,e=0>e?g.length+e:Math.min(e,g.length),c=0;c<e;++c)a+=d+g[c]+k;return a.length?a:""}if(-1<k){d=a.slice(k).indexOf(")")+k;a=a.substring(k+8,d).split(",");switch(Number(g[a[0]])){case 0:a=p(a[4],a[1]);break;case 1:a=p(a[2],
a[1]);break;case 2:a=p(a[3],a[1]);break;default:a=a[1]}a?(g=a,g=g.trim&&g.trim()||g.replace(/^\s+|\s+$/g,"")):g="";return g}return-1<c?(k=a.substring(0,c),a=Number(a.substring(c+1,b)),g=g[k],!isNaN(a)&&g&&(0>a?(d=g[g.length+a],"undefined"===typeof d&&(d=g[0])):(d=g[a],"undefined"===typeof d&&(d=g[g.length-1]))),"undefined"!==typeof d?d:""):"{"+a+"}"}var p=l.pick;a.i18nFormat=function(e,g,l){var k=function(a,b){a=a.slice(b||0);var c=a.indexOf("{"),d=a.indexOf("}");if(-1<c&&d>c)return{statement:a.substring(c+
1,d),begin:b+c+1,end:b+d}},c=[];var b=0;do{var d=k(e,b);b=e.substring(b,d&&d.begin-1);b.length&&c.push({value:b,type:"constant"});d&&c.push({value:d.statement,type:"statement"});b=d&&d.end+1}while(d);c.forEach(function(a){"statement"===a.type&&(a.value=h(a.value,g))});return a.format(c.reduce(function(a,b){return a+b.value},""),g,l)};a.Chart.prototype.langFormat=function(e,g){e=e.split(".");for(var h=this.options.lang,k=0;k<e.length;++k)h=h&&h[e[k]];return"string"===typeof h&&a.i18nFormat(h,g,this)}});
q(a,"modules/accessibility/focusBorder.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,l){var h=a.addEvent,p=l.extend,e=l.pick;p(a.SVGElement.prototype,{addFocusBorder:function(a,h){this.focusBorder&&this.removeFocusBorder();var g=this.getBBox();a=e(a,3);g.x+=this.translateX?this.translateX:0;g.y+=this.translateY?this.translateY:0;this.focusBorder=this.renderer.rect(g.x-a,g.y-a,g.width+2*a,g.height+2*a,h&&h.borderRadius).addClass("highcharts-focus-border").attr({zIndex:99}).add(this.parentGroup);
this.renderer.styledMode||this.focusBorder.attr({stroke:h&&h.stroke,"stroke-width":h&&h.strokeWidth})},removeFocusBorder:function(){this.focusBorder&&(this.focusBorder.destroy(),delete this.focusBorder)}});a.Chart.prototype.setFocusToElement=function(a,e){var g=this.options.accessibility.keyboardNavigation.focusBorder;(e=e||a.element)&&e.focus&&(e.hcEvents&&e.hcEvents.focusin||h(e,"focusin",function(){}),e.focus(),g.hideBrowserFocusOutline&&(e.style.outline="none"));g.enabled&&(this.focusElement&&
this.focusElement.removeFocusBorder(),a.addFocusBorder(g.margin,{stroke:g.style.color,strokeWidth:g.style.lineWidth,borderRadius:g.style.borderRadius}),this.focusElement=a)}});q(a,"modules/accessibility/accessibility.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigation.js"],a["modules/accessibility/components/LegendComponent.js"],a["modules/accessibility/components/MenuComponent.js"],
a["modules/accessibility/components/SeriesComponent/SeriesComponent.js"],a["modules/accessibility/components/ZoomComponent.js"],a["modules/accessibility/components/RangeSelectorComponent.js"],a["modules/accessibility/components/InfoRegionsComponent.js"],a["modules/accessibility/components/ContainerComponent.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/high-contrast-mode.js"],a["modules/accessibility/high-contrast-theme.js"],a["modules/accessibility/options/options.js"],
a["modules/accessibility/options/langOptions.js"],a["modules/accessibility/options/deprecatedOptions.js"]],function(a,l,n,p,e,g,q,k,c,b,d,f,u,w,x,r,v,y){function h(a){this.init(a)}var m=a.addEvent,t=a.win.document,z=a.merge,A=a.fireEvent,E=l.extend;z(!0,a.defaultOptions,r,{accessibility:{highContrastTheme:x},lang:v});a.A11yChartUtilities=u;a.KeyboardNavigationHandler=n;a.AccessibilityComponent=p;h.prototype={init:function(a){this.chart=a;t.addEventListener&&a.renderer.isSVG?(y(a),this.initComponents(),
this.keyboardNavigation=new e(a,this.components),this.update()):a.renderTo.setAttribute("aria-hidden",!0)},initComponents:function(){var a=this.chart,e=a.options.accessibility;this.components={container:new f,infoRegions:new d,legend:new g,chartMenu:new q,rangeSelector:new b,series:new k,zoom:new c};e.customComponents&&E(this.components,e.customComponents);var h=this.components;Object.keys(h).forEach(function(b){h[b].initBase(a);h[b].init()})},update:function(){var a=this.components,b=this.chart,
c=b.options.accessibility;A(b,"beforeA11yUpdate");b.types=this.getChartTypes();Object.keys(a).forEach(function(c){a[c].onChartUpdate();A(b,"afterA11yComponentUpdate",{name:c,component:a[c]})});this.keyboardNavigation.update(c.keyboardNavigation.order);!b.highContrastModeActive&&w.isHighContrastModeActive(b)&&w.setHighContrastTheme(b);A(b,"afterA11yUpdate")},destroy:function(){var a=this.chart||{},b=this.components;Object.keys(b).forEach(function(a){b[a].destroy();b[a].destroyBase()});this.keyboardNavigation&&
this.keyboardNavigation.destroy();a.renderTo&&a.renderTo.setAttribute("aria-hidden",!0);a.focusElement&&a.focusElement.removeFocusBorder()},getChartTypes:function(){var a={};this.chart.series.forEach(function(b){a[b.type]=1});return Object.keys(a)}};a.Chart.prototype.updateA11yEnabled=function(){var a=this.accessibility,b=this.options.accessibility;b&&b.enabled?a?a.update():this.accessibility=new h(this):a?(a.destroy&&a.destroy(),delete this.accessibility):this.renderTo.setAttribute("aria-hidden",
!0)};m(a.Chart,"render",function(a){this.a11yDirty&&this.renderTo&&(delete this.a11yDirty,this.updateA11yEnabled());var b=this.accessibility;b&&Object.keys(b.components).forEach(function(c){b.components[c].onChartRender(a)})});m(a.Chart,"update",function(a){if(a=a.options.accessibility)a.customComponents&&(this.options.accessibility.customComponents=a.customComponents,delete a.customComponents),z(!0,this.options.accessibility,a),this.accessibility&&this.accessibility.destroy&&(this.accessibility.destroy(),
delete this.accessibility);this.a11yDirty=!0});m(a.Point,"update",function(){this.series.chart.accessibility&&(this.series.chart.a11yDirty=!0)});["addSeries","init"].forEach(function(b){m(a.Chart,b,function(){this.a11yDirty=!0})});["update","updatedData","remove"].forEach(function(b){m(a.Series,b,function(){this.chart.accessibility&&(this.chart.a11yDirty=!0)})});["afterDrilldown","drillupall"].forEach(function(b){m(a.Chart,b,function(){this.accessibility&&this.accessibility.update()})});m(a.Chart,
"destroy",function(){this.accessibility&&this.accessibility.destroy()})});q(a,"masters/modules/accessibility.src.js",[],function(){})});
//# sourceMappingURL=accessibility.js.map