/*
 Highstock JS v7.2.1-modified (2019-11-18)

 Drag-panes module

 (c) 2010-2019 Highsoft AS
 Author: Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/drag-panes",["highcharts","highcharts/modules/stock"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,b,y,e){a.hasOwnProperty(b)||(a[b]=e.apply(null,y))}a=a?a._modules:{};e(a,"modules/drag-panes.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,b){var e=b.clamp,
z=b.isNumber,A=b.objectEach,B=a.hasTouch;b=a.merge;var u=a.wrap,g=a.addEvent,v=a.relativeLength,m=a.Axis,w=a.Pointer;b(!0,m.prototype.defaultYAxisOptions,{minLength:"10%",maxLength:"100%",resize:{controlledAxis:{next:[],prev:[]},enabled:!1,cursor:"ns-resize",lineColor:"#cccccc",lineDashStyle:"Solid",lineWidth:4,x:0,y:0}});a.AxisResizer=function(c){this.init(c)};a.AxisResizer.prototype={init:function(c,a){this.axis=c;this.options=c.options.resize;this.render();a||this.addMouseEvents()},render:function(){var c=
this.axis,a=c.chart,d=this.options,x=d.x,b=d.y,k=e(c.top+c.height+b,a.plotTop,a.plotTop+a.plotHeight),l={};a.styledMode||(l={cursor:d.cursor,stroke:d.lineColor,"stroke-width":d.lineWidth,dashstyle:d.lineDashStyle});this.lastPos=k-b;this.controlLine||(this.controlLine=a.renderer.path().addClass("highcharts-axis-resizer"));this.controlLine.add(c.axisGroup);d=a.styledMode?this.controlLine.strokeWidth():d.lineWidth;l.d=a.renderer.crispLine(["M",c.left+x,k,"L",c.left+c.width+x,k],d);this.controlLine.attr(l)},
addMouseEvents:function(){var c=this,a=c.controlLine.element,d=c.axis.chart.container,e=[],b,k,l;c.mouseMoveHandler=b=function(a){c.onMouseMove(a)};c.mouseUpHandler=k=function(a){c.onMouseUp(a)};c.mouseDownHandler=l=function(a){c.onMouseDown(a)};e.push(g(d,"mousemove",b),g(d.ownerDocument,"mouseup",k),g(a,"mousedown",l));B&&e.push(g(d,"touchmove",b),g(d.ownerDocument,"touchend",k),g(a,"touchstart",l));c.eventsToUnbind=e},onMouseMove:function(c){c.touches&&0===c.touches[0].pageX||!this.grabbed||(this.hasDragged=
!0,this.updateAxes(this.axis.chart.pointer.normalize(c).chartY-this.options.y))},onMouseUp:function(c){this.hasDragged&&this.updateAxes(this.axis.chart.pointer.normalize(c).chartY-this.options.y);this.grabbed=this.hasDragged=this.axis.chart.activeResizer=null},onMouseDown:function(c){this.axis.chart.pointer.reset(!1,0);this.grabbed=this.axis.chart.activeResizer=!0},updateAxes:function(c){var a=this,d=a.axis.chart,b=a.options.controlledAxis,g=0===b.next.length?[d.yAxis.indexOf(a.axis)+1]:b.next;b=
[a.axis].concat(b.prev);var k=[],l=!1,q=d.plotTop,n=d.plotHeight,m=q+n;c=e(c,q,m);var r=c-a.lastPos;1>r*r||([b,g].forEach(function(b,g){b.forEach(function(b,h){var f=(b=z(b)?d.yAxis[b]:g||h?d.get(b):b)&&b.options;if(f&&"navigator-y-axis"!==f.id){h=b.top;var t=Math.round(v(f.minLength,n));var p=Math.round(v(f.maxLength,n));g?(r=c-a.lastPos,f=Math.round(e(b.len-r,t,p)),h=b.top+r,h+f>m&&(p=m-f-h,c+=p,h+=p),h<q&&(h=q,h+f>m&&(f=n)),f===t&&(l=!0),k.push({axis:b,options:{top:100*(h-q)/n+"%",height:100*f/
n+"%"}})):(f=Math.round(e(c-h,t,p)),f===p&&(l=!0),c=h+f,k.push({axis:b,options:{height:100*f/n+"%"}}))}})}),l||(k.forEach(function(a){a.axis.update(a.options,!1)}),d.redraw(!1)))},destroy:function(){var a=this;delete a.axis.resizer;this.eventsToUnbind&&this.eventsToUnbind.forEach(function(a){a()});a.controlLine.destroy();A(a,function(c,b){a[b]=null})}};m.prototype.keepProps.push("resizer");g(m,"afterRender",function(){var c=this.resizer,b=this.options.resize;b&&(b=!1!==b.enabled,c?b?c.init(this,!0):
c.destroy():b&&(this.resizer=new a.AxisResizer(this)))});g(m,"destroy",function(a){!a.keepEvents&&this.resizer&&this.resizer.destroy()});u(w.prototype,"runPointActions",function(a){this.chart.activeResizer||a.apply(this,Array.prototype.slice.call(arguments,1))});u(w.prototype,"drag",function(a){this.chart.activeResizer||a.apply(this,Array.prototype.slice.call(arguments,1))})});e(a,"masters/modules/drag-panes.src.js",[],function(){})});
//# sourceMappingURL=drag-panes.js.map