/*
 Highcharts Gantt JS v7.2.1-modified (2019-11-18)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?(q["default"]=q,module.exports=q):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(H){q(H);q.Highcharts=H;return q}):q("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(q){function H(b,d,D,F){b.hasOwnProperty(d)||(b[d]=F.apply(null,D))}q=q?q._modules:{};H(q,"parts-gantt/CurrentDateIndicator.js",[q["parts/Globals.js"]],function(b){var d=b.addEvent,D=b.PlotLineOrBand,F=b.merge,B=b.wrap,
C={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(d,u){return b.dateFormat(u,d)},rotation:0,style:{fontSize:"10px"}}};d(b.Axis,"afterSetOptions",function(){var b=this.options,d=b.currentDateIndicator;d&&(d="object"===typeof d?F(C,d):F(C),d.value=new Date,b.plotLines||(b.plotLines=[]),b.plotLines.push(d))});d(D,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});B(D.prototype,"getLabelText",function(b,
d){var w=this.options;return w.currentDateIndicator&&w.label&&"function"===typeof w.label.formatter?(w.value=new Date,w.label.formatter.call(this,w.value,w.label.format)):b.call(this,d)})});H(q,"parts-gantt/GridAxis.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var D=d.defined,F=d.erase,B=d.isArray,C=d.isNumber,E=d.pick,u=b.addEvent,w=b.dateFormat,A=function(f){return d.isObject(f,!0)},g=b.merge,n=b.wrap,z=b.Chart,t=b.Axis,r=b.Tick,a=function(f){var c=f.options;c.labels||(c.labels=
{});c.labels.align=E(c.labels.align,"center");f.categories||(c.showLastLabel=!1);f.labelRotation=0;c.labels.rotation=0},k={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};t.prototype.isOuterAxis=function(){var f=this,c=f.columnIndex,e=f.linkedParent&&f.linkedParent.columns||f.columns,a=c?f.linkedParent:f,p=-1,k=0;f.chart[f.coll].forEach(function(c,h){c.side!==f.side||c.options.isInternal||(k=h,c===a&&(p=h))});return k===p&&(C(c)?e.length===c:!0)};t.prototype.getMaxLabelDimensions=
function(f,c){var a={width:0,height:0};c.forEach(function(c){c=f[c];if(A(c)){var e=A(c.label)?c.label:{};c=e.getBBox?e.getBBox().height:0;e.textStr&&!C(e.textPxLength)&&(e.textPxLength=e.getBBox().width);e=C(e.textPxLength)?Math.round(e.textPxLength):0;a.height=Math.max(c,a.height);a.width=Math.max(e,a.width)}});return a};b.dateFormats.W=function(a){a=new Date(a);a.setHours(0,0,0,0);a.setDate(a.getDate()-(a.getDay()||7));var c=new Date(a.getFullYear(),0,1);return Math.ceil(((a-c)/864E5+1)/7)};b.dateFormats.E=
function(a){return w("%a",a,!0).charAt(0)};u(r,"afterGetLabelPosition",function(a){var c=this.label,e=this.axis,f=e.reversed,p=e.chart,v=e.options,g=v&&A(v.grid)?v.grid:{};v=e.options.labels;var h=v.align,l=k[e.side],m=a.tickmarkOffset,y=e.tickPositions,G=this.pos-m;y=C(y[a.index+1])?y[a.index+1]-m:e.max+m;var I=e.tickSize("tick",!0);m=B(I)?I[0]:0;I=I&&I[1]/2;if(!0===g.enabled){if("top"===l){g=e.top+e.offset;var L=g-m}else"bottom"===l?(L=p.chartHeight-e.bottom+e.offset,g=L+m):(g=e.top+e.len-e.translate(f?
y:G),L=e.top+e.len-e.translate(f?G:y));"right"===l?(l=p.chartWidth-e.right+e.offset,f=l+m):"left"===l?(f=e.left+e.offset,l=f-m):(l=Math.round(e.left+e.translate(f?y:G))-I,f=Math.round(e.left+e.translate(f?G:y))-I);this.slotWidth=f-l;a.pos.x="left"===h?l:"right"===h?f:l+(f-l)/2;a.pos.y=L+(g-L)/2;p=p.renderer.fontMetrics(v.style.fontSize,c.element);c=c.getBBox().height;v.useHTML?a.pos.y+=p.b+-(c/2):(c=Math.round(c/p.h),a.pos.y+=(p.b-(p.h-p.f))/2+-((c-1)*p.h/2));a.pos.x+=e.horiz&&v.x||0}});u(t,"afterTickSize",
function(a){var c=this.defaultLeftAxisOptions,e=this.horiz,f=this.options.grid;f=void 0===f?{}:f;var p=this.maxLabelDimensions;f.enabled&&(c=2*Math.abs(c.labels.x),e=e?f.cellHeight||c+p.height:c+p.width,B(a.tickSize)?a.tickSize[0]=e:a.tickSize=[e])});u(t,"afterGetTitlePosition",function(a){var c=this.options;if(!0===(c&&A(c.grid)?c.grid:{}).enabled){var e=this.axisTitle,f=e&&e.getBBox().width,p=this.horiz,v=this.left,g=this.top,h=this.width,l=this.height,m=c.title;c=this.opposite;var y=this.offset,
G=this.tickSize()||[0],I=m.x||0,L=m.y||0,J=E(m.margin,p?5:10);e=this.chart.renderer.fontMetrics(m.style&&m.style.fontSize,e).f;G=(p?g+l:v)+G[0]/2*(c?-1:1)*(p?1:-1)+(this.side===k.bottom?e:0);a.titlePosition.x=p?v-f/2-J+I:G+(c?h:0)+y+I;a.titlePosition.y=p?G-(c?l:0)+(c?e:-e)/2+y+L:g-J+L}});n(t.prototype,"unsquish",function(a){var c=this.options;return!0===(c&&A(c.grid)?c.grid:{}).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))});u(t,"afterSetOptions",
function(a){var c=this.options;a=a.userOptions;var e=c&&A(c.grid)?c.grid:{};if(!0===e.enabled){var f=g(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],
["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(D(a.linkedTo)&&!D(a.tickPixelInterval)&&(f.tickPixelInterval=350),D(a.tickPixelInterval)||!D(a.linkedTo)||D(a.tickPositioner)||D(a.tickInterval)||(f.tickPositioner=function(c,a){var e=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(e){var h,l=f.units;for(h=0;h<l.length;h++)if(l[h][0]===e.unitName){var m=h;break}if(l[m+1]){var y=l[m+1][0];var G=(l[m+1][1]||[1])[0]}else"year"===
e.unitName&&(y="year",G=10*e.count);e=b.timeUnits[y];this.tickInterval=e*G;return this.getTimeTicks({unitRange:e,count:G,unitName:y},c,a,this.options.startOfWeek)}}));g(!0,this.options,f);this.horiz&&(c.minPadding=E(a.minPadding,0),c.maxPadding=E(a.maxPadding,0));C(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=e.borderWidth)}});u(t,"afterSetAxisTranslation",function(){var a=this.options,c=a&&A(a.grid)?a.grid:{},e=this.tickPositions&&this.tickPositions.info,x=this.userOptions.labels||{};this.horiz&&
(!0===c.enabled&&this.series.forEach(function(c){c.options.pointRange=0}),e&&(!1===a.dateTimeLabelFormats[e.unitName].range||1<e.count)&&!D(x.align)&&(a.labels.align="left",D(x.x)||(a.labels.x=3)))});u(t,"trimTicks",function(){var a=this.options,c=a&&A(a.grid)?a.grid:{},e=this.categories,x=this.tickPositions,p=x[0],k=x[x.length-1],v=this.linkedParent&&this.linkedParent.min||this.min,h=this.linkedParent&&this.linkedParent.max||this.max,l=this.tickInterval;!0!==c.enabled||e||!this.horiz&&!this.isLinked||
(p<v&&p+l>v&&!a.startOnTick&&(x[0]=v),k>h&&k-l<h&&!a.endOnTick&&(x[x.length-1]=h))});u(t,"afterRender",function(){var a=this.options,c=a&&A(a.grid)?a.grid:{},e=this.chart.renderer;if(!0===c.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var x=a.lineWidth;if(x){var p=this.getLinePath(x);var v=p.indexOf("M")+1;var g=p.indexOf("L")+1;c=p.indexOf("M")+2;var h=p.indexOf("L")+2;var l=
(this.tickSize("tick")[0]-1)*(this.side===k.top||this.side===k.left?-1:1);this.horiz?(p[c]+=l,p[h]+=l):(p[v]+=l,p[g]+=l);this.axisLineExtra?this.axisLineExtra.animate({d:p}):(this.axisLineExtra=e.path(p).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),e.styledMode||this.axisLineExtra.attr({stroke:a.lineColor,"stroke-width":x}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(c){c.render()})}});var v={afterGetOffset:function(){(this.columns||
[]).forEach(function(a){a.getOffset()})},afterInit:function(){var f=this.chart,c=this.userOptions,e=this.options;e=e&&A(e.grid)?e.grid:{};e.enabled&&(a(this),n(this,"labelFormatter",function(c){var a=this.axis,e=a.tickPositions,m=this.value,f=(a.isLinked?a.linkedParent:a).series[0],G=m===e[0];e=m===e[e.length-1];f=f&&b.find(f.options.data,function(c){return c[a.isXAxis?"x":"y"]===m});this.isFirst=G;this.isLast=e;this.point=f;return c.call(this)}));if(e.columns)for(var x=this.columns=[],p=this.columnIndex=
0;++p<e.columns.length;){var k=g(c,e.columns[e.columns.length-p-1],{linkedTo:0,type:"category"});delete k.grid.columns;k=new t(this.chart,k,!0);k.isColumn=!0;k.columnIndex=p;F(f.axes,k);F(f[this.coll],k);x.push(k)}},afterSetOptions:function(a){a=(a=a.userOptions)&&A(a.grid)?a.grid:{};var c=a.columns;a.enabled&&c&&g(!0,this.options,c[c.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(c){c.destroy(a.keepEvents)})},
init:function(a){var c=(a=a.userOptions)&&A(a.grid)?a.grid:{};c.enabled&&D(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor)}};Object.keys(v).forEach(function(a){u(t,a,v[a])});u(z,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})})});H(q,"modules/static-scale.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var D=d.defined,F=d.isNumber,B=d.pick;d=b.Chart;b.addEvent(b.Axis,"afterSetOptions",
function(){var b=this.chart.options&&this.chart.options.chart;!this.horiz&&F(this.options.staticScale)&&(!b.height||b.scrollablePlotArea&&b.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});d.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(b){var d=b.chart,u=!!d.initiatedScale&&d.options.animation,w=b.options.staticScale;if(b.staticScale&&D(b.min)){var A=B(b.unitLength,b.max+b.tickInterval-b.min)*w;A=Math.max(A,w);
w=A-d.plotHeight;1<=Math.abs(w)&&(d.plotHeight=A,d.redrawTrigger="adjustHeight",d.setSize(void 0,d.chartHeight+w,u));b.series.forEach(function(g){(g=g.sharedClipKey&&d[g.sharedClipKey])&&g.attr({height:d.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};b.addEvent(d,"render",d.prototype.adjustHeight)});H(q,"parts-gantt/Tree.js",[q["parts/Utilities.js"]],function(b){var d=b.extend,D=b.isNumber,F=b.pick,B=function(b,d){var w=b.reduce(function(b,g){var d=F(g.parent,"");"undefined"===
typeof b[d]&&(b[d]=[]);b[d].push(g);return b},{});Object.keys(w).forEach(function(b,g){var n=w[b];""!==b&&-1===d.indexOf(b)&&(n.forEach(function(b){g[""].push(b)}),delete g[b])});return w},q=function(b,u,w,A,g,n){var z=0,t=0,r=n&&n.after,a=n&&n.before;u={data:A,depth:w-1,id:b,level:w,parent:u};var k,v;"function"===typeof a&&a(u,n);a=(g[b]||[]).map(function(a){var c=q(a.id,b,w+1,a,g,n),e=a.start;a=!0===a.milestone?e:a.end;k=!D(k)||e<k?e:k;v=!D(v)||a>v?a:v;z=z+1+c.descendants;t=Math.max(c.height+1,
t);return c});A&&(A.start=F(A.start,k),A.end=F(A.end,v));d(u,{children:a,descendants:z,height:t});"function"===typeof r&&r(u,n);return u};return{getListOfParents:B,getNode:q,getTree:function(b,d){var w=b.map(function(b){return b.id});b=B(b,w);return q("",null,1,null,b,d)}}});H(q,"mixins/tree-series.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var D=d.extend,q=d.isArray,B=d.isNumber,C=d.isObject,E=d.pick,u=b.merge;return{getColor:function(d,A){var g=A.index,n=A.mapOptionsToLevel,
z=A.parentColor,t=A.parentColorIndex,r=A.series,a=A.colors,k=A.siblings,v=r.points,f=r.chart.options.chart,c;if(d){v=v[d.i];d=n[d.level]||{};if(n=v&&d.colorByPoint){var e=v.index%(a?a.length:f.colorCount);var x=a&&a[e]}if(!r.chart.styledMode){a=v&&v.options.color;f=d&&d.color;if(c=z)c=(c=d&&d.colorVariation)&&"brightness"===c.key?b.color(z).brighten(g/k*c.to).get():z;c=E(a,f,x,c,r.color)}var p=E(v&&v.options.colorIndex,d&&d.colorIndex,e,t,A.colorIndex)}return{color:c,colorIndex:p}},getLevelOptions:function(b){var d=
null;if(C(b)){d={};var g=B(b.from)?b.from:1;var n=b.levels;var z={};var t=C(b.defaults)?b.defaults:{};q(n)&&(z=n.reduce(function(b,a){if(C(a)&&B(a.level)){var k=u({},a);var v="boolean"===typeof k.levelIsConstant?k.levelIsConstant:t.levelIsConstant;delete k.levelIsConstant;delete k.level;a=a.level+(v?0:g-1);C(b[a])?D(b[a],k):b[a]=k}return b},{}));n=B(b.to)?b.to:1;for(b=0;b<=n;b++)d[b]=u({},t,C(z[b])?z[b]:{})}return d},setTreeValues:function n(b,g){var d=g.before,t=g.idRoot,r=g.mapIdToNode[t],a=g.points[b.i],
k=a&&a.options||{},v=0,f=[];D(b,{levelDynamic:b.level-(("boolean"===typeof g.levelIsConstant?g.levelIsConstant:1)?0:r.level),name:E(a&&a.name,""),visible:t===b.id||("boolean"===typeof g.visible?g.visible:!1)});"function"===typeof d&&(b=d(b,g));b.children.forEach(function(c,a){var e=D({},g);D(e,{index:a,siblings:b.children.length,visible:b.visible});c=n(c,e);f.push(c);c.visible&&(v+=c.val)});b.visible=0<v||b.visible;d=E(k.value,v);D(b,{children:f,childrenTotal:v,isLeaf:b.visible&&!v,val:d});return b},
updateRootId:function(b){if(C(b)){var g=C(b.options)?b.options:{};g=E(b.rootNode,g.rootId,"");C(b.userOptions)&&(b.userOptions.rootId=g);b.rootNode=g}return g}}});H(q,"modules/broken-axis.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var D=d.extend,q=d.isArray,B=d.pick;d=b.addEvent;var C=b.find,E=b.fireEvent,u=b.Axis,w=b.Series,A=function(b,d){return C(d,function(g){return g.from<b&&b<g.to})};D(u.prototype,{isInBreak:function(b,d){var g=b.repeat||Infinity,n=b.from,r=b.to-b.from;
d=d>=n?(d-n)%g:g-(n-d)%g;return b.inclusive?d<=r:d<r&&0!==d},isInAnyBreak:function(b,d){var g=this.options.breaks,n=g&&g.length,r;if(n){for(;n--;)if(this.isInBreak(g[n],b)){var a=!0;r||(r=B(g[n].showPoints,!this.isXAxis))}var k=a&&d?a&&!r:a}return k}});d(u,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});d(u,"afterSetTickPositions",function(){if(this.isBroken){var b=this.tickPositions,d=this.tickPositions.info,z=[],t;for(t=0;t<b.length;t++)this.isInAnyBreak(b[t])||
z.push(b[t]);this.tickPositions=z;this.tickPositions.info=d}});d(u,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});u.prototype.setBreaks=function(b,d){function g(a){var b=a,f;for(f=0;f<r.breakArray.length;f++){var c=r.breakArray[f];if(c.to<=a)b-=c.len;else if(c.from>=a)break;else if(r.isInBreak(c,a)){b-=a-c.from;break}}return b}function n(a){var b;for(b=0;b<r.breakArray.length;b++){var f=r.breakArray[b];if(f.from>=a)break;else f.to<a?a+=f.len:r.isInBreak(f,a)&&(a+=f.len)}return a}
var r=this,a=q(b)&&!!b.length;r.isDirty=r.isBroken!==a;r.isBroken=a;r.options.breaks=r.userOptions.breaks=b;r.forceRedraw=!0;a||r.val2lin!==g||(delete r.val2lin,delete r.lin2val);a&&(r.userOptions.ordinal=!1,r.val2lin=g,r.lin2val=n,r.setExtremes=function(a,b,f,c,e){if(this.isBroken){for(var x,p=this.options.breaks;x=A(a,p);)a=x.to;for(;x=A(b,p);)b=x.from;b<a&&(b=a)}u.prototype.setExtremes.call(this,a,b,f,c,e)},r.setAxisTranslation=function(a){u.prototype.setAxisTranslation.call(this,a);this.unitLength=
null;if(this.isBroken){a=r.options.breaks;var b=[],f=[],c=0,e,x=r.userMin||r.min,p=r.userMax||r.max,k=B(r.pointRangePadding,0),d;a.forEach(function(c){e=c.repeat||Infinity;r.isInBreak(c,x)&&(x+=c.to%e-x%e);r.isInBreak(c,p)&&(p-=p%e-c.from%e)});a.forEach(function(c){l=c.from;for(e=c.repeat||Infinity;l-e>x;)l-=e;for(;l<x;)l+=e;for(d=l;d<p;d+=e)b.push({value:d,move:"in"}),b.push({value:d+(c.to-c.from),move:"out",size:c.breakSize})});b.sort(function(c,a){return c.value===a.value?("in"===c.move?0:1)-("in"===
a.move?0:1):c.value-a.value});var h=0;var l=x;b.forEach(function(a){h+="in"===a.move?1:-1;1===h&&"in"===a.move&&(l=a.value);0===h&&(f.push({from:l,to:a.value,len:a.value-l-(a.size||0)}),c+=a.value-l-(a.size||0))});r.breakArray=f;r.unitLength=p-x-c+k;E(r,"afterBreaks");r.staticScale?r.transA=r.staticScale:r.unitLength&&(r.transA*=(p-r.min+k)/r.unitLength);k&&(r.minPixelPadding=r.transA*r.minPointOffset);r.min=x;r.max=p}});B(d,!0)&&this.chart.redraw()};d(w,"afterGeneratePoints",function(){var b=this.xAxis,
d=this.yAxis,z=this.points,t=z.length,r=this.options.connectNulls;if(b&&d&&(b.options.breaks||d.options.breaks))for(;t--;){var a=z[t];var k=null===a.y&&!1===r;k||!b.isInAnyBreak(a.x,!0)&&!d.isInAnyBreak(a.y,!0)||(z.splice(t,1),this.data[t]&&this.data[t].destroyElements())}});d(w,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,B(this.pointArrayMap,["y"]))});b.Series.prototype.drawBreaks=function(b,d){var g=this,n=g.points,r,a,k,v;b&&d.forEach(function(f){r=b.breakArray||
[];a=b.isXAxis?b.min:B(g.options.threshold,b.min);n.forEach(function(c){v=B(c["stack"+f.toUpperCase()],c[f]);r.forEach(function(e){k=!1;if(a<e.from&&v>e.to||a>e.from&&v<e.from)k="pointBreak";else if(a<e.from&&v>e.from&&v<e.to||a>e.from&&v>e.to&&v<e.from)k="pointInBreak";k&&E(b,k,{point:c,brk:e})})})})};b.Series.prototype.gappedPath=function(){var d=this.currentDataGrouping,n=d&&d.gapSize;d=this.options.gapSize;var z=this.points.slice(),t=z.length-1,r=this.yAxis;if(d&&0<t)for("value"!==this.options.gapUnit&&
(d*=this.basePointRange),n&&n>d&&n>=this.basePointRange&&(d=n);t--;)z[t+1].x-z[t].x>d&&(n=(z[t].x+z[t+1].x)/2,z.splice(t+1,0,{isNull:!0,x:n}),this.options.stacking&&(n=r.stacks[this.stackKey][n]=new b.StackItem(r,r.options.stackLabels,!1,n,this.stack),n.total=0));return this.getGraphPath(z)}});H(q,"parts-gantt/TreeGrid.js",[q["parts/Globals.js"],q["parts/Utilities.js"],q["parts-gantt/Tree.js"],q["mixins/tree-series.js"]],function(b,d,D,q){var B=d.defined,F=d.extend,E=d.isNumber,u=d.isString,w=d.pick,
A=b.addEvent,g=function(c){return Array.prototype.slice.call(c,1)},n=b.find,z=b.fireEvent,t=q.getLevelOptions,r=b.merge,a=function(c){return d.isObject(c,!0)},k=b.wrap;q=b.Axis;var v=b.Tick,f=function(c,a){var e;for(e in a)if(Object.hasOwnProperty.call(a,e)){var h=a[e];k(c,e,h)}},c=function(c,a){var e=c.collapseStart;c=c.collapseEnd;c>=a&&(e-=.5);return{from:e,to:c,showPoints:!1}},e=function(c){return Object.keys(c.mapOfPosToGridNode).reduce(function(a,e){e=+e;c.min<=e&&c.max>=e&&!c.isInAnyBreak(e)&&
a.push(e);return a},[])},x=function(a,e){var h=a.options.breaks||[],l=c(e,a.max);return h.some(function(c){return c.from===l.from&&c.to===l.to})},p=function(a,e){var h=a.options.breaks||[];a=c(e,a.max);h.push(a);return h},K=function(a,e){var h=a.options.breaks||[],l=c(e,a.max);return h.reduce(function(c,a){a.to===l.to&&a.from===l.from||c.push(a);return c},[])},Q=function(c,a){var e=c.labelIcon,h=!e,l=a.renderer,b=a.xy,f=a.options,m=f.width,x=f.height,y=b.x-m/2-f.padding;b=b.y-x/2;var p=a.collapsed?
90:180,k=a.show&&E(b);h&&(c.labelIcon=e=l.path(l.symbols[f.type](f.x,f.y,m,x)).addClass("highcharts-label-icon").add(a.group));k||e.attr({y:-9999});l.styledMode||e.attr({"stroke-width":1,fill:w(a.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});e[h?"attr":"animate"]({translateX:y,translateY:b,rotation:p})},h=function(c,e,h){var l=[],b=[],f={},m={},x=-1,G="boolean"===typeof e?e:!1;c=D.getTree(c,{after:function(c){c=m[c.pos];var a=0,e=0;c.children.forEach(function(c){e+=
c.descendants+1;a=Math.max(c.height+1,a)});c.descendants=e;c.height=a;c.collapsed&&b.push(c)},before:function(c){var e=a(c.data)?c.data:{},h=u(e.name)?e.name:"",b=f[c.parent];b=a(b)?m[b.pos]:null;var p=function(c){return c.name===h},y;G&&a(b)&&(y=n(b.children,p))?(p=y.pos,y.nodes.push(c)):p=x++;m[p]||(m[p]=y={depth:b?b.depth+1:0,name:h,nodes:[c],children:[],pos:p},-1!==p&&l.push(h),a(b)&&b.children.push(y));u(c.id)&&(f[c.id]=c);!0===e.collapsed&&(y.collapsed=!0);c.pos=p}});m=function(c,e){var h=function(c,
l,b){var f=l+(-1===l?0:e-1),m=(f-l)/2,x=l+m;c.nodes.forEach(function(c){var e=c.data;a(e)&&(e.y=l+e.seriesIndex,delete e.seriesIndex);c.pos=x});b[x]=c;c.pos=x;c.tickmarkOffset=m+.5;c.collapseStart=f+.5;c.children.forEach(function(c){h(c,f+1,b);f=c.collapseEnd-.5});c.collapseEnd=f+.5;return b};return h(c["-1"],-1,{})}(m,h);return{categories:l,mapOfIdToNode:f,mapOfPosToGridNode:m,collapsedNodes:b,tree:c}},l=function(c){c.target.axes.filter(function(c){return"treegrid"===c.options.type}).forEach(function(e){var l=
e.options||{},f=l.labels,m,x=l.uniqueNames,y=0;if(!e.mapOfPosToGridNode||e.series.some(function(c){return!c.hasRendered||c.isDirtyData||c.isDirty})){l=e.series.reduce(function(c,e){e.visible&&(e.options.data.forEach(function(e){a(e)&&(e.seriesIndex=y,c.push(e))}),!0===x&&y++);return c},[]);var k=h(l,x,!0===x?y:1);e.categories=k.categories;e.mapOfPosToGridNode=k.mapOfPosToGridNode;e.hasNames=!0;e.tree=k.tree;e.series.forEach(function(c){var e=c.options.data.map(function(c){return a(c)?r(c):c});c.visible&&
c.setData(e,!1)});e.mapOptionsToLevel=t({defaults:f,from:1,levels:f.levels,to:e.tree.height});"beforeRender"===c.type&&(m=b.addEvent(e,"foundExtremes",function(){k.collapsedNodes.forEach(function(c){c=p(e,c);e.setBreaks(c,!1)});m()}))}})};f(q.prototype,{init:function(c,a,e){var h="treegrid"===e.type;h&&(A(a,"beforeRender",l),A(a,"beforeRedraw",l),e=r({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,
padding:5}},uniqueNames:!1},e,{reversed:!0,grid:{columns:void 0}}));c.apply(this,[a,e]);h&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(c){var a=this.options,e=a&&a.labels;a=e&&E(e.indentation)?a.labels.indentation:0;e=c.apply(this,g(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var h=this.mapOfPosToGridNode[-1].height;e.width+=a*(h-1)}return e},generateTick:function(c,e){var h=a(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},l=this.ticks,
b=l[e],f;if("treegrid"===this.options.type){var x=this.mapOfPosToGridNode[e];(h=h[x.depth])&&(f={labels:h});b?(b.parameters.category=x.name,b.options=f,b.addLabel()):l[e]=new v(this,e,null,void 0,{category:x.name,tickmarkOffset:x.tickmarkOffset,options:f})}else c.apply(this,g(arguments))},setTickInterval:function(c){var a=this.options;"treegrid"===a.type?(this.min=w(this.userMin,a.min,this.dataMin),this.max=w(this.userMax,a.max,this.dataMax),z(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=
.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?e(this):[]):c.apply(this,g(arguments))}});f(v.prototype,{getLabelPosition:function(c,e,h,l,b,f,x,p,k){var m=w(this.options&&this.options.labels,f);f=this.pos;var G=this.axis,d="treegrid"===G.options.type;c=c.apply(this,[e,h,l,b,m,x,p,k]);d&&(e=m&&a(m.symbol)?m.symbol:{},m=m&&E(m.indentation)?m.indentation:0,f=(f=(G=G.mapOfPosToGridNode)&&G[f])&&f.depth||1,c.x+=e.width+2*e.padding+(f-1)*m);return c},renderLabel:function(c){var e=this,
h=e.pos,l=e.axis,f=e.label,m=l.mapOfPosToGridNode,p=l.options,k=w(e.options&&e.options.labels,p&&p.labels),d=k&&a(k.symbol)?k.symbol:{},v=(m=m&&m[h])&&m.depth;p="treegrid"===p.type;var K=!(!f||!f.element),n=-1<l.tickPositions.indexOf(h);h=l.chart.styledMode;p&&m&&K&&f.addClass("highcharts-treegrid-node-level-"+v);c.apply(e,g(arguments));p&&m&&K&&0<m.descendants&&(l=x(l,m),Q(e,{color:!h&&f.styles.color,collapsed:l,group:f.parentGroup,options:d,renderer:f.renderer,show:n,xy:f.xy}),d="highcharts-treegrid-node-"+
(l?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(l?"collapsed":"expanded")).removeClass(d),h||f.css({cursor:"pointer"}),[f,e.labelIcon].forEach(function(c){c.attachedTreeGridEvents||(b.addEvent(c.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),b.addEvent(c.element,"mouseout",function(){var c=B(k.style)?k.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:c.textDecoration})}),
b.addEvent(c.element,"click",function(){e.toggleCollapse()}),c.attachedTreeGridEvents=!0)}))}});F(v.prototype,{collapse:function(c){var a=this.axis,e=p(a,a.mapOfPosToGridNode[this.pos]);a.setBreaks(e,w(c,!0))},expand:function(c){var a=this.axis,e=K(a,a.mapOfPosToGridNode[this.pos]);a.setBreaks(e,w(c,!0))},toggleCollapse:function(c){var a=this.axis;var e=a.mapOfPosToGridNode[this.pos];e=x(a,e)?K(a,e):p(a,e);a.setBreaks(e,w(c,!0))}});q.prototype.utils={getNode:D.getNode}});H(q,"parts-gantt/PathfinderAlgorithms.js",
[q["parts/Utilities.js"]],function(b){function d(b,d,z){z=z||0;var g=b.length-1;d-=1e-7;for(var n,a;z<=g;)if(n=g+z>>1,a=d-b[n].xMin,0<a)z=n+1;else if(0>a)g=n-1;else return n;return 0<z?z-1:0}function D(b,n){for(var g=d(b,n.x+1)+1;g--;){var t;if(t=b[g].xMax>=n.x)t=b[g],t=n.x<=t.xMax&&n.x>=t.xMin&&n.y<=t.yMax&&n.y>=t.yMin;if(t)return g}return-1}function q(b){var d=[];if(b.length){d.push("M",b[0].start.x,b[0].start.y);for(var g=0;g<b.length;++g)d.push("L",b[g].end.x,b[g].end.y)}return d}function B(b,
d){b.yMin=w(b.yMin,d.yMin);b.yMax=u(b.yMax,d.yMax);b.xMin=w(b.xMin,d.xMin);b.xMax=u(b.xMax,d.xMax)}var C=b.extend,E=b.pick,u=Math.min,w=Math.max,A=Math.abs;return{straight:function(b,d){return{path:["M",b.x,b.y,"L",d.x,d.y],obstacles:[{start:b,end:d}]}},simpleConnect:C(function(b,d,w){function g(c,a,e,b,h){c={x:c.x,y:c.y};c[a]=e[b||a]+(h||0);return c}function n(c,a,e){var b=A(a[e]-c[e+"Min"])>A(a[e]-c[e+"Max"]);return g(a,e,c,e+(b?"Max":"Min"),b?1:-1)}var a=[],k=E(w.startDirectionX,A(d.x-b.x)>A(d.y-
b.y))?"x":"y",v=w.chartObstacles,f=D(v,b);w=D(v,d);if(-1<w){var c=v[w];w=n(c,d,k);c={start:w,end:d};var e=w}else e=d;-1<f&&(v=v[f],w=n(v,b,k),a.push({start:b,end:w}),w[k]>=b[k]===w[k]>=e[k]&&(k="y"===k?"x":"y",d=b[k]<d[k],a.push({start:w,end:g(w,k,v,k+(d?"Max":"Min"),d?1:-1)}),k="y"===k?"x":"y"));b=a.length?a[a.length-1].end:b;w=g(b,k,e);a.push({start:b,end:w});k=g(w,"y"===k?"x":"y",e);a.push({start:w,end:k});a.push(c);return{path:q(a),obstacles:a}},{requiresObstacles:!0}),fastAvoid:C(function(b,
n,z){function g(c,a,e){var h,b=c.x<a.x?1:-1;if(c.x<a.x){var f=c;var m=a}else f=a,m=c;if(c.y<a.y){var x=c;var p=a}else x=a,p=c;for(h=0>b?u(d(l,m.x),l.length-1):0;l[h]&&(0<b&&l[h].xMin<=m.x||0>b&&l[h].xMax>=f.x);){if(l[h].xMin<=m.x&&l[h].xMax>=f.x&&l[h].yMin<=p.y&&l[h].yMax>=x.y)return e?{y:c.y,x:c.x<a.x?l[h].xMin-1:l[h].xMax+1,obstacle:l[h]}:{x:c.x,y:c.y<a.y?l[h].yMin-1:l[h].yMax+1,obstacle:l[h]};h+=b}return a}function r(c,a,e,h,b){var l=b.soft,f=b.hard,m=h?"x":"y",x={x:a.x,y:a.y},p={x:a.x,y:a.y};
b=c[m+"Max"]>=l[m+"Max"];l=c[m+"Min"]<=l[m+"Min"];var d=c[m+"Max"]>=f[m+"Max"];f=c[m+"Min"]<=f[m+"Min"];var k=A(c[m+"Min"]-a[m]),G=A(c[m+"Max"]-a[m]);e=10>A(k-G)?a[m]<e[m]:G<k;p[m]=c[m+"Min"];x[m]=c[m+"Max"];c=g(a,p,h)[m]!==p[m];a=g(a,x,h)[m]!==x[m];e=c?a?e:!0:a?!1:e;e=l?b?e:!0:b?!1:e;return f?d?e:!0:d?!1:e}function a(c,b,f){if(c.x===b.x&&c.y===b.y)return[];var m=f?"x":"y",x=z.obstacleOptions.margin;var d={soft:{xMin:p,xMax:K,yMin:Q,yMax:h},hard:z.hardBounds};var k=D(l,c);if(-1<k){k=l[k];d=r(k,c,
b,f,d);B(k,z.hardBounds);var y=f?{y:c.y,x:k[d?"xMax":"xMin"]+(d?1:-1)}:{x:c.x,y:k[d?"yMax":"yMin"]+(d?1:-1)};var v=D(l,y);-1<v&&(v=l[v],B(v,z.hardBounds),y[m]=d?w(k[m+"Max"]-x+1,(v[m+"Min"]+k[m+"Max"])/2):u(k[m+"Min"]+x-1,(v[m+"Max"]+k[m+"Min"])/2),c.x===y.x&&c.y===y.y?(e&&(y[m]=d?w(k[m+"Max"],v[m+"Max"])+1:u(k[m+"Min"],v[m+"Min"])-1),e=!e):e=!1);c=[{start:c,end:y}]}else m=g(c,{x:f?b.x:c.x,y:f?c.y:b.y},f),c=[{start:c,end:{x:m.x,y:m.y}}],m[f?"x":"y"]!==b[f?"x":"y"]&&(d=r(m.obstacle,m,b,!f,d),B(m.obstacle,
z.hardBounds),d={x:f?m.x:m.obstacle[d?"xMax":"xMin"]+(d?1:-1),y:f?m.obstacle[d?"yMax":"yMin"]+(d?1:-1):m.y},f=!f,c=c.concat(a({x:m.x,y:m.y},d,f)));return c=c.concat(a(c[c.length-1].end,b,!f))}function k(c,a,e){var h=u(c.xMax-a.x,a.x-c.xMin)<u(c.yMax-a.y,a.y-c.yMin);e=r(c,a,e,h,{soft:z.hardBounds,hard:z.hardBounds});return h?{y:a.y,x:c[e?"xMax":"xMin"]+(e?1:-1)}:{x:a.x,y:c[e?"yMax":"yMin"]+(e?1:-1)}}var v=E(z.startDirectionX,A(n.x-b.x)>A(n.y-b.y)),f=v?"x":"y",c=[],e=!1,x=z.obstacleMetrics,p=u(b.x,
n.x)-x.maxWidth-10,K=w(b.x,n.x)+x.maxWidth+10,Q=u(b.y,n.y)-x.maxHeight-10,h=w(b.y,n.y)+x.maxHeight+10,l=z.chartObstacles;var m=d(l,p);x=d(l,K);l=l.slice(m,x+1);if(-1<(x=D(l,n))){var y=k(l[x],n,b);c.push({end:n,start:y});n=y}for(;-1<(x=D(l,n));)m=0>n[f]-b[f],y={x:n.x,y:n.y},y[f]=l[x][m?f+"Max":f+"Min"]+(m?1:-1),c.push({end:n,start:y}),n=y;b=a(b,n,v);b=b.concat(c.reverse());return{path:q(b),obstacles:b}},{requiresObstacles:!0})}});H(q,"parts-gantt/ArrowSymbols.js",[q["parts/Globals.js"]],function(b){b.SVGRenderer.prototype.symbols.arrow=
function(b,D,q,B){return["M",b,D+B/2,"L",b+q,D,"L",b,D+B/2,"L",b+q,D+B]};b.SVGRenderer.prototype.symbols["arrow-half"]=function(d,q,F,B){return b.SVGRenderer.prototype.symbols.arrow(d,q,F/2,B)};b.SVGRenderer.prototype.symbols["triangle-left"]=function(b,q,F,B){return["M",b+F,q,"L",b,q+B/2,"L",b+F,q+B,"Z"]};b.SVGRenderer.prototype.symbols["arrow-filled"]=b.SVGRenderer.prototype.symbols["triangle-left"];b.SVGRenderer.prototype.symbols["triangle-left-half"]=function(d,q,F,B){return b.SVGRenderer.prototype.symbols["triangle-left"](d,
q,F/2,B)};b.SVGRenderer.prototype.symbols["arrow-filled-half"]=b.SVGRenderer.prototype.symbols["triangle-left-half"]});H(q,"parts-gantt/Pathfinder.js",[q["parts/Globals.js"],q["parts/Utilities.js"],q["parts-gantt/PathfinderAlgorithms.js"]],function(b,d,q){function D(a){var c=a.shapeArgs;return c?{xMin:c.x,xMax:c.x+c.width,yMin:c.y,yMax:c.y+c.height}:(c=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-c.width/2,xMax:a.plotX+c.width/2,yMin:a.plotY-c.height/2,yMax:a.plotY+c.height/2}:null}function B(a){for(var c=
a.length,e=0,b,f,d=[],g=function(c,a,e){e=n(e,10);var b=c.yMax+e>a.yMin-e&&c.yMin-e<a.yMax+e,h=c.xMax+e>a.xMin-e&&c.xMin-e<a.xMax+e,l=b?c.xMin>a.xMax?c.xMin-a.xMax:a.xMin-c.xMax:Infinity,f=h?c.yMin>a.yMax?c.yMin-a.yMax:a.yMin-c.yMax:Infinity;return h&&b?e?g(c,a,Math.floor(e/2)):Infinity:v(l,f)};e<c;++e)for(b=e+1;b<c;++b)f=g(a[e],a[b]),80>f&&d.push(f);d.push(80);return k(Math.floor(d.sort(function(c,a){return c-a})[Math.floor(d.length/10)]/2-1),1)}function C(a,c,e){this.init(a,c,e)}function E(a){this.init(a)}
function u(f){if(f.options.pathfinder||f.series.reduce(function(c,e){e.options&&a(!0,e.options.connectors=e.options.connectors||{},e.options.pathfinder);return c||e.options&&e.options.pathfinder},!1))a(!0,f.options.connectors=f.options.connectors||{},f.options.pathfinder),b.error('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}var w=d.defined,A=d.extend,g=d.objectEach,n=d.pick,z=d.splat,t=b.deg2rad,r=b.addEvent,a=b.merge,k=Math.max,v=Math.min;
A(b.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});C.prototype={init:function(a,c,e){this.fromPoint=a;this.toPoint=c;this.options=e;this.chart=a.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(a,c,e){var b=this.chart,f=b.styledMode,d=b.pathfinder,k=!b.options.chart.forExport&&!1!==e,h=this.graphics&&this.graphics.path;
d.group||(d.group=b.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(b.seriesGroup));d.group.translate(b.plotLeft,b.plotTop);h&&h.renderer||(h=b.renderer.path().add(d.group),f||h.attr({opacity:0}));h.attr(c);a={d:a};f||(a.opacity=1);h[k?"animate":"attr"](a,e);this.graphics=this.graphics||{};this.graphics.path=h},addMarker:function(a,c,e){var b=this.fromPoint.series.chart,f=b.pathfinder;b=b.renderer;var d="start"===a?this.fromPoint:this.toPoint,k=d.getPathfinderAnchorPoint(c);
if(c.enabled){e="start"===a?{x:e[4],y:e[5]}:{x:e[e.length-5],y:e[e.length-4]};e=d.getRadiansToVector(e,k);k=d.getMarkerVector(e,c.radius,k);e=-e/t;if(c.width&&c.height){var h=c.width;var l=c.height}else h=l=2*c.radius;this.graphics=this.graphics||{};k={x:k.x-h/2,y:k.y-l/2,width:h,height:l,rotation:e,rotationOriginX:k.x,rotationOriginY:k.y};this.graphics[a]?this.graphics[a].animate(k):(this.graphics[a]=b.symbol(c.symbol).addClass("highcharts-point-connecting-path-"+a+"-marker").attr(k).add(f.group),
b.styledMode||this.graphics[a].attr({fill:c.color||this.fromPoint.color,stroke:c.lineColor,"stroke-width":c.lineWidth,opacity:0}).animate({opacity:1},d.series.options.animation))}},getPath:function(f){var c=this.pathfinder,e=this.chart,d=c.algorithms[f.type],k=c.chartObstacles;if("function"!==typeof d)b.error('"'+f.type+'" is not a Pathfinder algorithm.');else return d.requiresObstacles&&!k&&(k=c.chartObstacles=c.getChartObstacles(f),e.options.connectors.algorithmMargin=f.algorithmMargin,c.chartObstacleMetrics=
c.getObstacleMetrics(k)),d(this.fromPoint.getPathfinderAnchorPoint(f.startMarker),this.toPoint.getPathfinderAnchorPoint(f.endMarker),a({chartObstacles:k,lineObstacles:c.lineObstacles||[],obstacleMetrics:c.chartObstacleMetrics,hardBounds:{xMin:0,xMax:e.plotWidth,yMin:0,yMax:e.plotHeight},obstacleOptions:{margin:f.algorithmMargin},startDirectionX:c.getAlgorithmStartDirection(f.startMarker)},f))},render:function(){var b=this.fromPoint,c=b.series,e=c.chart,d=e.pathfinder,p=a(e.options.connectors,c.options.connectors,
b.options.connectors,this.options),g={};e.styledMode||(g.stroke=p.lineColor||b.color,g["stroke-width"]=p.lineWidth,p.dashStyle&&(g.dashstyle=p.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+b.colorIndex;p=a(g,p);w(p.marker.radius)||(p.marker.radius=v(k(Math.ceil((p.algorithmMargin||8)/2)-1,1),5));b=this.getPath(p);e=b.path;b.obstacles&&(d.lineObstacles=d.lineObstacles||[],d.lineObstacles=d.lineObstacles.concat(b.obstacles));this.renderPath(e,g,c.options.animation);this.addMarker("start",
a(p.marker,p.startMarker),e);this.addMarker("end",a(p.marker,p.endMarker),e)},destroy:function(){this.graphics&&(g(this.graphics,function(a){a.destroy()}),delete this.graphics)}};E.prototype={algorithms:q,init:function(a){this.chart=a;this.connections=[];r(a,"redraw",function(){this.pathfinder.update()})},update:function(a){var c=this.chart,e=this,f=e.connections;e.connections=[];c.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var h,l=a.options&&a.options.connect&&
z(a.options.connect);a.visible&&!1!==a.isInside&&l&&l.forEach(function(l){h=c.get("string"===typeof l?l:l.to);h instanceof b.Point&&h.series.visible&&h.visible&&!1!==h.isInside&&e.connections.push(new C(a,h,"string"===typeof l?{}:l))})})});for(var d=0,k,v,h=f.length,l=e.connections.length;d<h;++d){v=!1;for(k=0;k<l;++k)if(f[d].fromPoint===e.connections[k].fromPoint&&f[d].toPoint===e.connections[k].toPoint){e.connections[k].graphics=f[d].graphics;v=!0;break}v||f[d].destroy()}delete this.chartObstacles;
delete this.lineObstacles;e.renderConnections(a)},renderConnections:function(a){a?this.chart.series.forEach(function(c){var a=function(){var a=c.chart.pathfinder;(a&&a.connections||[]).forEach(function(a){a.fromPoint&&a.fromPoint.series===c&&a.render()});c.pathfinderRemoveRenderEvent&&(c.pathfinderRemoveRenderEvent(),delete c.pathfinderRemoveRenderEvent)};!1===c.options.animation?a():c.pathfinderRemoveRenderEvent=r(c,"afterAnimate",a)}):this.connections.forEach(function(c){c.render()})},getChartObstacles:function(a){for(var c=
[],e=this.chart.series,b=n(a.algorithmMargin,0),f,d=0,k=e.length;d<k;++d)if(e[d].visible&&!e[d].options.isInternal)for(var h=0,l=e[d].points.length,m;h<l;++h)m=e[d].points[h],m.visible&&(m=D(m))&&c.push({xMin:m.xMin-b,xMax:m.xMax+b,yMin:m.yMin-b,yMax:m.yMax+b});c=c.sort(function(c,a){return c.xMin-a.xMin});w(a.algorithmMargin)||(f=a.algorithmMargin=B(c),c.forEach(function(c){c.xMin-=f;c.xMax+=f;c.yMin-=f;c.yMax+=f}));return c},getObstacleMetrics:function(a){for(var c=0,e=0,b,f,d=a.length;d--;)b=a[d].xMax-
a[d].xMin,f=a[d].yMax-a[d].yMin,c<b&&(c=b),e<f&&(e=f);return{maxHeight:e,maxWidth:c}},getAlgorithmStartDirection:function(a){var c="top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?c?void 0:!1:c?!0:void 0}};b.Connection=C;b.Pathfinder=E;A(b.Point.prototype,{getPathfinderAnchorPoint:function(a){var c=D(this);switch(a.align){case "right":var e="xMax";break;case "left":e="xMin"}switch(a.verticalAlign){case "top":var b="yMin";break;case "bottom":b="yMax"}return{x:e?
c[e]:(c.xMin+c.xMax)/2,y:b?c[b]:(c.yMin+c.yMax)/2}},getRadiansToVector:function(a,c){w(c)||(c=D(this),c={x:(c.xMin+c.xMax)/2,y:(c.yMin+c.yMax)/2});return Math.atan2(c.y-a.y,a.x-c.x)},getMarkerVector:function(a,c,e){var b=2*Math.PI,d=D(this),f=d.xMax-d.xMin,k=d.yMax-d.yMin,h=Math.atan2(k,f),l=!1;f/=2;var m=k/2,v=d.xMin+f;d=d.yMin+m;for(var G=v,g=d,w={},J=1,n=1;a<-Math.PI;)a+=b;for(;a>Math.PI;)a-=b;b=Math.tan(a);a>-h&&a<=h?(n=-1,l=!0):a>h&&a<=Math.PI-h?n=-1:a>Math.PI-h||a<=-(Math.PI-h)?(J=-1,l=!0):
J=-1;l?(G+=J*f,g+=n*f*b):(G+=k/(2*b)*J,g+=n*m);e.x!==v&&(G=e.x);e.y!==d&&(g=e.y);w.x=G+c*Math.cos(a);w.y=g-c*Math.sin(a);return w}});b.Chart.prototype.callbacks.push(function(a){!1!==a.options.connectors.enabled&&(u(a),this.pathfinder=new E(this),this.pathfinder.update(!0))})});H(q,"modules/xrange.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var q=d.clamp,F=d.correctFloat,B=d.defined,C=d.isNumber,E=d.isObject,u=d.pick;d=b.addEvent;var w=b.color,A=b.seriesTypes.column,g=b.merge,
n=b.seriesType,z=b.Axis,t=b.Point,r=b.Series;n("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;E(a)&&(a=a.amount);if(C(a)&&0<a)return F(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],
requireSorting:!1,animate:b.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:b.noop,buildKDTree:b.noop,getColumnMetrics:function(){function a(){b.series.forEach(function(a){var c=a.xAxis;a.xAxis=a.yAxis;a.yAxis=c})}var b=this.chart;a();var d=A.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,b,d,f){b=r.prototype.cropData.call(this,this.x2Data,b,d,f);b.xData=a.slice(b.start,b.end);return b},findPointIndex:function(a){var d=this.data,v=this.points,
f=a.id,c;if(f)var e=(c=b.find(d,function(a){return a.id===f}))?c.index:void 0;"undefined"===typeof e&&(e=(c=b.find(d,function(c){return c.x===a.x&&c.x2===a.x2&&!(v[e]&&v[e].touched)}))?c.index:void 0);this.cropped&&e>=this.cropStart&&(e-=this.cropStart);return e},translatePoint:function(a){var b=this.xAxis,d=this.yAxis,f=this.columnMetrics,c=this.options,e=c.minPointLength||0,x=a.plotX,p=u(a.x2,a.x+(a.len||0)),n=b.translate(p,0,0,0,1);p=Math.abs(n-x);var w=this.chart.inverted,h=u(c.borderWidth,1)%
2/2,l=f.offset,m=Math.round(f.width);e&&(e-=p,0>e&&(e=0),x-=e/2,n+=e/2);x=Math.max(x,-10);n=q(n,-10,b.len+10);B(a.options.pointWidth)&&(l-=(Math.ceil(a.options.pointWidth)-m)/2,m=Math.ceil(a.options.pointWidth));c.pointPlacement&&C(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,c.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(x,n))+h,y:Math.floor(a.plotY+l)+h,width:Math.round(Math.abs(n-x)),height:m,r:this.options.borderRadius};c=a.shapeArgs.x;e=c+a.shapeArgs.width;0>c||e>b.len?(c=
q(c,0,b.len),e=q(e,0,b.len),n=e-c,a.dlBox=g(a.shapeArgs,{x:c,width:e-c,centerX:n?n/2:null})):a.dlBox=null;c=a.tooltipPos;e=w?1:0;n=w?0:1;c[e]=q(c[e]+p/2*(b.reversed?-1:1)*(w?-1:1),0,b.len-1);c[n]=q(c[n]+f.width/2*(w?1:-1),0,d.len-1);if(f=a.partialFill)E(f)&&(f=f.amount),C(f)||(f=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},x=Math.max(Math.round(p*f+a.plotX-x),0),a.clipRectArgs={x:b.reversed?d.x+p-x:d.x,y:d.y,width:x,height:d.height}},translate:function(){A.prototype.translate.apply(this,
arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var d=this.options,f=this.chart.renderer,c=a.graphic,e=a.shapeType,k=a.shapeArgs,p=a.partShapeArgs,n=a.clipRectArgs,r=a.partialFill,h=d.stacking&&!d.borderRadius,l=a.state,m=d.states[l||"normal"]||{},y="undefined"===typeof l?"attr":b;l=this.pointAttribs(a,l);m=u(this.chart.options.chart.animation,m.animation);if(a.isNull)c&&(a.graphic=c.destroy());else{if(c)c.rect[b](k);else a.graphic=c=f.g("point").addClass(a.getClassName()).add(a.group||
this.group),c.rect=f[e](g(k)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(c);p&&(c.partRect?(c.partRect[b](g(p)),c.partialClipRect[b](g(n))):(c.partialClipRect=f.clipRect(n.x,n.y,n.width,n.height),c.partRect=f[e](p).addClass("highcharts-partfill-overlay").add(c).clip(c.partialClipRect)));this.chart.styledMode||(c.rect[b](l,m).shadow(d.shadow,null,h),p&&(E(r)||(r={}),E(d.partialFill)&&(r=g(r,d.partialFill)),a=r.fill||w(l.fill).brighten(-.3).get()||w(a.color||this.color).brighten(-.3).get(),
l.fill=a,c.partRect[y](l,m).shadow(d.shadow,null,h)))}},drawPoints:function(){var a=this,b=a.getAnimationVerb();a.points.forEach(function(d){a.drawPoint(d,b)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var b=a.options.colors||a.chart.options.colors;var d=this.y%(b?b.length:a.chart.options.chart.colorCount);b=b&&b[d];a.chart.styledMode||(this.color=
b);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){t.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){t.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=t.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===
typeof this.x&&"number"===typeof this.x2}});d(z,"afterGetSeriesExtremes",function(){var a=this.series,b;if(this.isXAxis){var d=u(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>d&&(d=a,b=!0)})});b&&(this.dataMax=d)}});""});H(q,"parts-gantt/GanttSeries.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var q=d.isNumber,F=d.pick,B=d.splat,C=b.dateFormat,E=b.merge;d=b.seriesType;var u=b.seriesTypes.xrange;d("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},
tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var b=this.series,d=b.chart.tooltip,g=b.xAxis,n=b.tooltipOptions.dateTimeLabelFormats,u=g.options.startOfWeek,t=b.tooltipOptions,r=t.xDateFormat;b=this.options.milestone;var a="<b>"+(this.name||this.yCategory)+"</b>";if(t.pointFormat)return this.tooltipFormatter(t.pointFormat);r||(r=B(d.getDateFormat(g.closestPointRange,this.start,u,n))[0]);d=C(r,this.start);g=C(r,this.end);a+=
"<br/>";return b?a+(d+"<br/>"):a+("Start: "+d+"<br/>End: ")+(g+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(b){u.prototype.translatePoint.call(this,b);if(b.options.milestone){var d=b.shapeArgs;var g=d.height;b.shapeArgs={x:d.x-g/2,y:d.y,width:g,height:g}}},drawPoint:function(b,
d){var g=this.options,n=this.chart.renderer,w=b.shapeArgs,t=b.plotY,r=b.graphic,a=b.selected&&"select",k=g.stacking&&!g.borderRadius;if(b.options.milestone)if(q(t)&&null!==b.y){w=n.symbols.diamond(w.x,w.y,w.width,w.height);if(r)r[d]({d:w});else b.graphic=n.path(w).addClass(b.getClassName(),!0).add(b.group||this.group);this.chart.styledMode||b.graphic.attr(this.pointAttribs(b,a)).shadow(g.shadow,null,k)}else r&&(b.graphic=r.destroy());else u.prototype.drawPoint.call(this,b,d)},setData:b.Series.prototype.setData,
setGanttPointAliases:function(b){function d(d,n){"undefined"!==typeof n&&(b[d]=n)}d("x",F(b.start,b.x));d("x2",F(b.end,b.x2));d("partialFill",F(b.completed,b.partialFill));d("connect",F(b.dependency,b.connect))}},E(u.prototype.pointClass.prototype,{applyOptions:function(d,q){d=E(d);b.seriesTypes.gantt.prototype.setGanttPointAliases(d);return d=u.prototype.pointClass.prototype.applyOptions.call(this,d,q)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===
typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});H(q,"parts-gantt/GanttChart.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){var q=d.isArray,F=d.splat,B=b.merge,C=b.Chart;b.ganttChart=function(d,u,w){var A="string"===typeof d||d.nodeName,g=u.series,n=b.getOptions(),z,t=u;u=arguments[A?1:0];q(u.xAxis)||(u.xAxis=[u.xAxis||{},{}]);u.xAxis=u.xAxis.map(function(b,a){1===a&&(z=0);return B(n.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:z},b,{type:"datetime"})});u.yAxis=
F(u.yAxis||{}).map(function(b){return B(n.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:b.categories?b.type:"treegrid"},b)});u.series=null;u=B(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},u,{isGantt:!0});u.series=t.series=g;u.series.forEach(function(d){d.data.forEach(function(a){b.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});return A?new C(d,u,w):new C(u,u)}});H(q,"parts/Scrollbar.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){function q(a,
b,d){this.init(a,b,d)}var F=d.correctFloat,B=d.defined,C=d.destroyObjectProperties,E=d.pick,u=b.addEvent;d=b.Axis;var w=b.defaultOptions,A=b.fireEvent,g=b.hasTouch,n=b.merge,z=b.removeEvent,t,r={height:b.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",
trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};w.scrollbar=n(!0,r,w.scrollbar);b.swapXY=t=function(a,b){var d=a.length;if(b)for(b=0;b<d;b+=3){var f=a[b+1];a[b+1]=a[b+2];a[b+2]=f}return a};q.prototype={init:function(a,b,d){this.scrollbarButtons=[];this.renderer=a;this.userOptions=b;this.options=n(r,b);this.chart=d;this.size=E(this.options.size,this.options.height);b.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,b=this.options,
d=this.size,f=this.chart.styledMode,c;this.group=c=a.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||0,height:d,width:d}).add(c);f||this.track.attr({fill:b.trackBackgroundColor,stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(c);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:d,
width:d,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(t(["M",-3,d/4,"L",-3,2*d/3,"M",0,d/4,"L",0,2*d/3,"M",3,d/4,"L",3,2*d/3],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);f||(this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth}),this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,b,d,f){var c=this.options.vertical,e=0,k=this.rendered?"animate":"attr";this.x=a;this.y=b+this.trackBorderWidth;this.width=d;this.xOffset=this.height=f;this.yOffset=e;c?(this.width=this.yOffset=d=e=this.size,this.xOffset=b=0,this.barWidth=f-2*d,this.x=a+=this.options.margin):(this.height=this.xOffset=f=b=this.size,this.barWidth=d-2*f,this.y+=this.options.margin);this.group[k]({translateX:a,
translateY:this.y});this.track[k]({width:d,height:f});this.scrollbarButtons[1][k]({translateX:c?0:d-b,translateY:c?f-e:0})},drawScrollbarButton:function(a){var b=this.renderer,d=this.scrollbarButtons,f=this.options,c=this.size;var e=b.g().add(this.group);d.push(e);e=b.rect().addClass("highcharts-scrollbar-button").add(e);this.chart.styledMode||e.attr({stroke:f.buttonBorderColor,"stroke-width":f.buttonBorderWidth,fill:f.buttonBackgroundColor});e.attr(e.crisp({x:-.5,y:-.5,width:c+1,height:c+1,r:f.buttonBorderRadius},
e.strokeWidth()));e=b.path(t(["M",c/2+(a?-1:1),c/2-3,"L",c/2+(a?-1:1),c/2+3,"L",c/2+(a?2:-2),c/2],f.vertical)).addClass("highcharts-scrollbar-arrow").add(d[a]);this.chart.styledMode||e.attr({fill:f.buttonArrowColor})},setRange:function(a,b){var d=this.options,f=d.vertical,c=d.minWidth,e=this.barWidth,k,p=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(B(e)){a=Math.max(a,0);var g=Math.ceil(e*a);this.calculatedWidth=k=F(e*Math.min(b,1)-g);k<
c&&(g=(e-c+k)*a,k=c);c=Math.floor(g+this.xOffset+this.yOffset);e=k/2-.5;this.from=a;this.to=b;f?(this.scrollbarGroup[p]({translateY:c}),this.scrollbar[p]({height:k}),this.scrollbarRifles[p]({translateY:e}),this.scrollbarTop=c,this.scrollbarLeft=0):(this.scrollbarGroup[p]({translateX:c}),this.scrollbar[p]({width:k}),this.scrollbarRifles[p]({translateX:e}),this.scrollbarLeft=c,this.scrollbarTop=0);12>=k?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===d.showFull&&(0>=a&&1<=b?this.group.hide():
this.group.show());this.rendered=!0}},initEvents:function(){var a=this;a.mouseMoveHandler=function(b){var d=a.chart.pointer.normalize(b),f=a.options.vertical?"chartY":"chartX",c=a.initPositions;!a.grabbedCenter||b.touches&&0===b.touches[0][f]||(d=a.cursorToScrollbarPosition(d)[f],f=a[f],f=d-f,a.hasDragged=!0,a.updatePosition(c[0]+f,c[1]+f),a.hasDragged&&A(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};a.mouseUpHandler=function(b){a.hasDragged&&A(a,"changed",{from:a.from,
to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(b){var d=F(a.to-a.from)*a.options.step;a.updatePosition(F(a.from-d),F(a.to-d));A(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=function(b){var d=
(a.to-a.from)*a.options.step;a.updatePosition(a.from+d,a.to+d);A(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var d=a.chart.pointer.normalize(b),f=a.to-a.from,c=a.y+a.scrollbarTop,e=a.x+a.scrollbarLeft;a.options.vertical&&d.chartY>c||!a.options.vertical&&d.chartX>e?a.updatePosition(a.from+f,a.to+f):a.updatePosition(a.from-f,a.to-f);A(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=this.options;
b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=F(1-F(b-a)),b=1);0>a&&(b=F(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();this.init(this.chart.renderer,n(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,d=this.scrollbarGroup.element,f=this.mouseDownHandler,
c=this.mouseMoveHandler,e=this.mouseUpHandler;a=[[b[a[0]].element,"click",this.buttonToMinClick],[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[d,"mousedown",f],[d.ownerDocument,"mousemove",c],[d.ownerDocument,"mouseup",e]];g&&a.push([d,"touchstart",f],[d.ownerDocument,"touchmove",c],[d.ownerDocument,"touchend",e]);a.forEach(function(a){u.apply(null,a)});this._events=a},removeEvents:function(){this._events.forEach(function(a){z.apply(null,a)});this._events.length=
0},destroy:function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,C(a.scrollbarButtons))}};b.Scrollbar||(u(d,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new q(a.chart.renderer,
a.options.scrollbar,a.chart),u(a.scrollbar,"changed",function(d){var k=Math.min(E(a.options.min,a.min),a.min,a.dataMin),f=Math.max(E(a.options.max,a.max),a.max,a.dataMax)-k;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var c=k+f*this.to;k+=f*this.from}else c=k+f*(1-this.from),k+=f*(1-this.to);E(this.options.liveRedraw,b.svg&&!b.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===d.DOMType||!B(d.DOMType)?a.setExtremes(k,c,!0,"mousemove"!==d.DOMType,d):this.setRange(this.from,this.to)}))}),u(d,"afterRender",
function(){var a=Math.min(E(this.options.min,this.min),this.min,E(this.dataMin,this.min)),b=Math.max(E(this.options.max,this.max),this.max,E(this.dataMax,this.max)),d=this.scrollbar,f=this.axisTitleMargin+(this.titleOffset||0),c=this.chart.scrollbarsOffsets,e=this.options.margin||0;d&&(this.horiz?(this.opposite||(c[1]+=f),d.position(this.left,this.top+this.height+2+c[1]-(this.opposite?e:0),this.width,this.height),this.opposite||(c[1]+=e),f=1):(this.opposite&&(c[0]+=f),d.position(this.left+this.width+
2+c[0]-(this.opposite?0:e),this.top,this.width,this.height),this.opposite&&(c[0]+=e),f=0),c[f]+=d.size+d.options.margin,isNaN(a)||isNaN(b)||!B(this.min)||!B(this.max)||this.min===this.max?d.setRange(0,1):(c=(this.min-a)/(b-a),a=(this.max-a)/(b-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?d.setRange(c,a):d.setRange(1-a,1-c)))}),u(d,"afterGetOffset",function(){var a=this.horiz?2:1,b=this.scrollbar;b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=b.size+b.options.margin)}),
b.Scrollbar=q)});H(q,"parts/RangeSelector.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){function q(a){this.init(a)}var F=d.defined,B=d.destroyObjectProperties,C=d.discardElement,E=d.extend,u=d.isNumber,w=d.objectEach,A=d.pick,g=d.pInt,n=d.splat,z=b.addEvent,t=b.Axis;d=b.Chart;var r=b.css,a=b.createElement,k=b.defaultOptions,v=b.fireEvent,f=b.merge;E(k,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",
x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});k.lang=f(k.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});q.prototype={clickButton:function(a,b){var c=this.chart,e=this.buttonOptions[a],d=c.xAxis[0],f=c.scroller&&c.scroller.getUnionExtremes()||d||{},h=f.dataMin,l=f.dataMax,m=d&&Math.round(Math.min(d.max,A(l,d.max))),k=e.type;f=e._range;var g,r=e.dataGrouping;if(null!==h&&null!==l){c.fixedRange=f;r&&(this.forcedDataGrouping=!0,t.prototype.setDataGrouping.call(d||
{chart:this.chart},r,!1),this.frozenStates=e.preserveDataGrouping);if("month"===k||"year"===k)if(d){k={range:e,max:m,chart:c,dataMin:h,dataMax:l};var q=d.minFromRange.call(k);u(k.newMax)&&(m=k.newMax)}else f=e;else if(f)q=Math.max(m-f,h),m=Math.min(q+f,l);else if("ytd"===k)if(d)"undefined"===typeof l&&(h=Number.MAX_VALUE,l=Number.MIN_VALUE,c.series.forEach(function(a){a=a.xData;h=Math.min(a[0],h);l=Math.max(a[a.length-1],l)}),b=!1),m=this.getYTDExtremes(l,h,c.time.useUTC),q=g=m.min,m=m.max;else{this.deferredYTDClick=
a;return}else"all"===k&&d&&(q=h,m=l);q+=e._offsetMin;m+=e._offsetMax;this.setSelected(a);if(d)d.setExtremes(q,m,A(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:e});else{var J=n(c.options.xAxis)[0];var w=J.range;J.range=f;var v=J.min;J.min=g;z(c,"load",function(){J.range=w;J.min=v})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},
{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,b=a.options.rangeSelector,d=b.buttons||[].concat(c.defaultButtons),f=b.selected,k=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&v(a,"blur");b&&b.blur&&v(b,"blur")};c.chart=a;c.options=b;c.buttons=[];c.buttonOptions=d;this.unMouseDown=z(a.container,"mousedown",k);this.unResize=z(a,"resize",k);d.forEach(c.computeButtonRange);"undefined"!==typeof f&&d[f]&&this.clickButton(f,!1);z(a,"load",function(){a.xAxis&&a.xAxis[0]&&
z(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&!c.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,d=b.xAxis[0],f=Math.round(d.max-d.min),k=!d.hasVisibleSeries,g=b.scroller&&b.scroller.getUnionExtremes()||d,h=g.dataMin,l=g.dataMax;b=a.getYTDExtremes(l,h,b.time.useUTC);var m=b.min,y=b.max,G=a.selected,n=u(G),q=a.options.allButtonsEnabled,
J=a.buttons;a.buttonOptions.forEach(function(c,b){var e=c._range,p=c.type,x=c.count||1,g=J[b],r=0,I=c._offsetMax-c._offsetMin;c=b===G;var u=e>l-h,w=e<d.minRange,t=!1,v=!1;e=e===f;("month"===p||"year"===p)&&f+36E5>=864E5*{month:28,year:365}[p]*x-I&&f-36E5<=864E5*{month:31,year:366}[p]*x+I?e=!0:"ytd"===p?(e=y-m+I===f,t=!c):"all"===p&&(e=d.max-d.min>=l-h,v=!c&&n&&e);p=!q&&(u||w||v||k);x=c&&e||e&&!n&&!t||c&&a.frozenStates;p?r=3:x&&(n=!0,r=2);g.state!==r&&(g.setState(r),0===r&&G===b&&a.setSelected(null))})},
computeButtonRange:function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b;a._offsetMin=A(a.offsetMin,0);a._offsetMax=A(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var c=this.chart.options.rangeSelector,e=this.chart.time,d=this[a+"Input"];F(b)&&(d.previousValue=d.HCTime,d.HCTime=b);d.value=e.dateFormat(c.inputEditDateFormat||
"%Y-%m-%d",d.HCTime);this[a+"DateBox"].attr({text:e.dateFormat(c.inputDateFormat||"%b %e, %Y",d.HCTime)})},showInput:function(a){var c=this.inputGroup,b=this[a+"DateBox"];r(this[a+"Input"],{left:c.translateX+b.x+"px",top:c.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){r(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(c){function e(){var a=y.value,c=(h.inputDateParser||Date.parse)(a),b=p.xAxis[0],
e=p.scroller&&p.scroller.xAxis?p.scroller.xAxis:b,l=e.dataMin;e=e.dataMax;c!==y.previousValue&&(y.previousValue=c,u(c)||(c=a.split("-"),c=Date.UTC(g(c[0]),g(c[1])-1,g(c[2]))),u(c)&&(p.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),m?c>d.maxInput.HCTime?c=void 0:c<l&&(c=l):c<d.minInput.HCTime?c=void 0:c>e&&(c=e),"undefined"!==typeof c&&b.setExtremes(m?c:b.min,m?b.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,p=d.chart,n=p.renderer.style||{},q=p.renderer,h=p.options.rangeSelector,
l=d.div,m="min"===c,y,G,I=this.inputGroup;this[c+"Label"]=G=q.label(k.lang[m?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(I);I.offset+=G.width+5;this[c+"DateBox"]=q=q.label("",I.offset).addClass("highcharts-range-input").attr({padding:2,width:h.inputBoxWidth||90,height:h.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(c);d[c+"Input"].focus()});p.styledMode||q.attr({stroke:h.inputBoxBorderColor||
"#cccccc","stroke-width":1});q.add(I);I.offset+=q.width+(m?10:0);this[c+"Input"]=y=a("input",{name:c,className:"highcharts-range-selector",type:"text"},{top:p.plotTop+"px"},l);p.styledMode||(G.css(f(n,h.labelStyle)),q.css(f({color:"#333333"},n,h.inputStyle)),r(y,E({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:n.fontSize,fontFamily:n.fontFamily,top:"-9999em"},h.inputStyle)));y.onfocus=function(){d.showInput(c)};y.onblur=function(){y===b.doc.activeElement&&
e();d.hideInput(c);y.blur()};y.onchange=e;y.onkeypress=function(a){13===a.keyCode&&e()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,d){var c=this.chart.time,e=new c.Date(a),f=c.get("FullYear",e);d=d?c.Date.UTC(f,0,1):+new c.Date(f,0,1);b=Math.max(b||0,d);e=e.getTime();return{max:Math.min(a||e,e),min:b}},render:function(c,b){var e=
this,d=e.chart,f=d.renderer,g=d.container,h=d.options,l=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,m=k.lang,y=e.div,n=h.rangeSelector,q=A(h.chart.style&&h.chart.style.zIndex,0)+1;h=n.floating;var r=e.buttons;y=e.inputGroup;var J=n.buttonTheme,t=n.buttonPosition,u=n.inputPosition,w=n.inputEnabled,v=J&&J.states,z=d.plotLeft,B=e.buttonGroup;var D=e.rendered;var C=e.options.verticalAlign,E=d.legend,F=E&&E.options,H=t.y,P=u.y,R=D||!1,S=R?"animate":"attr",O=0,M=0,N;
if(!1!==n.enabled){D||(e.group=D=f.g("range-selector-group").attr({zIndex:7}).add(),e.buttonGroup=B=f.g("range-selector-buttons").add(D),e.zoomText=f.text(m.rangeSelectorZoom,0,15).add(B),d.styledMode||(e.zoomText.css(n.labelStyle),J["stroke-width"]=A(J["stroke-width"],0)),e.buttonOptions.forEach(function(a,c){r[c]=f.button(a.text,0,0,function(b){var d=a.events&&a.events.click,h;d&&(h=d.call(a,b));!1!==h&&e.clickButton(c);e.isActive=!0},J,v&&v.hover,v&&v.select,v&&v.disabled).attr({"text-align":"center"}).add(B)}),
!1!==w&&(e.div=y=a("div",null,{position:"relative",height:0,zIndex:q}),g.parentNode.insertBefore(y,g),e.inputGroup=y=f.g("input-group").add(D),y.offset=0,e.drawInput("min"),e.drawInput("max")));e.zoomText[S]({x:A(z+t.x,z)});var T=A(z+t.x,z)+e.zoomText.getBBox().width+5;e.buttonOptions.forEach(function(a,c){r[c][S]({x:T});T+=r[c].width+A(n.buttonSpacing,5)});z=d.plotLeft-d.spacing[3];e.updateButtonStates();l&&this.titleCollision(d)&&"top"===C&&"right"===t.align&&t.y+B.getBBox().height-12<(l.y||0)+
l.height&&(O=-40);"left"===t.align?N=t.x-d.spacing[3]:"right"===t.align&&(N=t.x+O-d.spacing[1]);B.align({y:t.y,width:B.getBBox().width,align:t.align,x:N},!0,d.spacingBox);e.group.placed=R;e.buttonGroup.placed=R;!1!==w&&(O=l&&this.titleCollision(d)&&"top"===C&&"right"===u.align&&u.y-y.getBBox().height-12<(l.y||0)+l.height+d.spacing[0]?-40:0,"left"===u.align?N=z:"right"===u.align&&(N=-Math.max(d.axisOffset[1],-O)),y.align({y:u.y,width:y.getBBox().width,align:u.align,x:u.x+N-2},!0,d.spacingBox),g=y.alignAttr.translateX+
y.alignOptions.x-O+y.getBBox().x+2,l=y.alignOptions.width,m=B.alignAttr.translateX+B.getBBox().x,N=B.getBBox().width+20,(u.align===t.align||m+N>g&&g+l>m&&H<P+y.getBBox().height)&&y.attr({translateX:y.alignAttr.translateX+(d.axisOffset[1]>=-O?0:-O),translateY:y.alignAttr.translateY+B.getBBox().height+10}),e.setInputValue("min",c),e.setInputValue("max",b),e.inputGroup.placed=R);e.group.align({verticalAlign:C},!0,d.spacingBox);c=e.group.getBBox().height+20;b=e.group.alignAttr.translateY;"bottom"===C&&
(E=F&&"bottom"===F.verticalAlign&&F.enabled&&!F.floating?E.legendHeight+A(F.margin,10):0,c=c+E-20,M=b-c-(h?0:n.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===C)h&&(M=0),d.titleOffset&&d.titleOffset[0]&&(M=d.titleOffset[0]),M+=d.margin[0]-d.spacing[0]||0;else if("middle"===C)if(P===H)M=0>P?b+void 0:b;else if(P||H)M=0>P||0>H?M-Math.min(P,H):b-c+NaN;e.group.translate(n.x,n.y+Math.floor(M));!1!==w&&(e.minInput.style.marginTop=e.group.translateY+"px",e.maxInput.style.marginTop=e.group.translateY+
"px");e.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,d=a.y,f=a.buttonPosition.y,k=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+d:0;b=Math.min(k,f);if(0>k&&0>f||0<k&&0<f)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var c=this.chart;f(!0,c.options.rangeSelector,a);this.destroy();this.init(c);c.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,d=a.maxInput;
a.unMouseDown();a.unResize();B(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);w(a,function(c,b){c&&"chart"!==b&&(c.destroy?c.destroy():c.nodeType&&C(this[b]));c!==q.prototype[b]&&(a[b]=null)},this)}};t.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],d=this.max,f=this.chart.time,k=function(a,c){var d=new f.Date(a),e=f.get(b,d);f.set(b,d,e+c);e===f.get(b,d)&&f.set("Date",d,0);return d.getTime()-a};if(u(a)){var g=
d-a;var h=a}else g=d+k(d,-a.count),this.chart&&(this.chart.fixedRange=d-g);var l=A(this.dataMin,Number.MIN_VALUE);u(g)||(g=l);g<=l&&(g=l,"undefined"===typeof h&&(h=k(g,a.count)),this.newMax=Math.min(g+h,this.dataMax));u(d)||(g=void 0);return g};b.RangeSelector||(z(d,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new q(this))}),z(d,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(u(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),
a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),z(d,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!F(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new q(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||
a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),z(d,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),z(d,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=
a),this.extraBottomMargin&&(this.marginBottom+=a))}),d.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();u(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector;if(d){var f=z(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var k=z(a,"redraw",b);b()}z(a,"destroy",function(){d&&(k(),f())})}),b.RangeSelector=q)});H(q,"parts/Navigator.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,d){function q(a){this.init(a)}var F=d.clamp,B=d.correctFloat,
C=d.defined,E=d.destroyObjectProperties,u=d.erase,w=d.extend,A=d.isArray,g=d.isNumber,n=d.pick,z=d.splat,t=b.addEvent,r=b.Axis;d=b.Chart;var a=b.color,k=b.defaultOptions,v=b.hasTouch,f=b.isTouchDevice,c=b.merge,e=b.removeEvent,x=b.Scrollbar,p=b.Series,H=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,g);if(b.length)return Math[a].apply(0,b)};var Q="undefined"===typeof b.seriesTypes.areaspline?"line":"areaspline";w(k,{navigator:{height:40,margin:25,maskInside:!0,
handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:Q,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",
[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,
endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});b.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height;return["M",-a-1,.5,"L",a,.5,"L",a,e+.5,"L",-a-1,e+.5,"L",-a-1,.5,"M",-b,4,"L",-b,e-3,"M",b-1,4,"L",b-1,e-3]};r.prototype.toFixedRange=function(a,b,c,d){var e=this.chart&&this.chart.fixedRange,h=(this.pointRange||0)/2;a=n(c,this.translate(a,!0,!this.horiz));b=n(d,this.translate(b,
!0,!this.horiz));var l=e&&(b-a)/e;C(c)||(a=B(a+h));C(d)||(b=B(b-h));.7<l&&1.3>l&&(d?a=b-e:b=a+e);g(a)&&g(b)||(a=b=void 0);return{min:a,max:b}};q.prototype={drawHandle:function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})},drawOutline:function(a,b,c,d){var e=this.navigatorOptions.maskInside,
h=this.outline.strokeWidth(),l=h/2;h=h%2/2;var f=this.outlineHeight,m=this.scrollbarHeight,k=this.size,g=this.left-m,n=this.top;c?(g-=l,c=n+b+h,b=n+a+h,a=["M",g+f,n-m-h,"L",g+f,c,"L",g,c,"L",g,b,"L",g+f,b,"L",g+f,n+k+m].concat(e?["M",g+f,c-l,"L",g+f,b+l]:[])):(a+=g+m-h,b+=g+m-h,n+=l,a=["M",g,n,"L",a,n,"L",a,n+f,"L",b,n+f,"L",b,n,"L",g+k+2*m,n].concat(e?["M",a-l,n,"L",b+l,n]:[]));this.outline[d]({d:a})},drawMasks:function(a,b,c,d){var e=this.left,h=this.top,l=this.height;if(c){var f=[e,e,e];var m=
[h,h+a,h+b];var k=[l,l,l];var g=[a,b-a,this.size-b]}else f=[e,e+a,e+b],m=[h,h,h],k=[a,b-a,this.size-b],g=[l,l,l];this.shades.forEach(function(a,b){a[d]({x:f[b],y:m[b],width:k[b],height:g[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,k={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,h){a.shades[h]=e.rect().addClass("highcharts-navigator-mask"+
(1===h?"-inside":"-outside")).add(f);d.styledMode||a.shades[h].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===h&&k)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+
["left","right"][c]).add(f);if(!d.styledMode){var h=b.handles;a.handles[c].attr({fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.lineWidth}).css(k)}})},update:function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();c(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,b,c,d){var e=this.chart,h=this.scrollbarHeight,f,l=this.xAxis,m=l.pointRange||0;var k=l.fake?e.xAxis[0]:l;var p=this.navigatorEnabled,
q,y=this.rendered;var r=e.inverted;var t=e.xAxis[0].minRange,u=e.xAxis[0].options.maxRange;if(!this.hasDragged||C(c)){a=B(a-m/2);b=B(b+m/2);if(!g(a)||!g(b))if(y)c=0,d=n(l.width,k.width);else return;this.left=n(l.left,e.plotLeft+h+(r?e.plotWidth:0));this.size=q=f=n(l.len,(r?e.plotHeight:e.plotWidth)-2*h);e=r?h:f+2*h;c=n(c,l.toPixels(a,!0));d=n(d,l.toPixels(b,!0));g(c)&&Infinity!==Math.abs(c)||(c=0,d=e);a=l.toValue(c,!0);b=l.toValue(d,!0);var v=Math.abs(B(b-a));v<t?this.grabbedLeft?c=l.toPixels(b-t-
m,!0):this.grabbedRight&&(d=l.toPixels(a+t+m,!0)):C(u)&&B(v-m)>u&&(this.grabbedLeft?c=l.toPixels(b-u-m,!0):this.grabbedRight&&(d=l.toPixels(a+u+m,!0)));this.zoomedMax=F(Math.max(c,d),0,q);this.zoomedMin=F(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,q);this.range=this.zoomedMax-this.zoomedMin;q=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);p&&(this.navigatorGroup.attr({visibility:"visible"}),y=y&&!this.hasDragged?"animate":"attr",this.drawMasks(c,q,r,y),this.drawOutline(c,
q,r,y),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,r,y),this.drawHandle(q,1,r,y)));this.scrollbar&&(r?(r=this.top-h,k=this.left-h+(p||!k.opposite?0:(k.titleOffset||0)+k.axisTitleMargin),h=f+2*h):(r=this.top+(p?this.height:-h),k=this.left-h),this.scrollbar.position(k,r,e,h),this.scrollbar.setRange(this.zoomedMin/(f||1),this.zoomedMax/(f||1)));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=
f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(t(b.renderTo,"mousemove",e),t(c.ownerDocument,"mouseup",f));v&&(d.push(t(b.renderTo,"touchmove",e),t(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(t(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,h){c.push(t(e.element,
a,function(a){b[d+"Mousedown"](a,h)}))})});return c},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,f=this.left,h=this.size,l=this.range,k=a.chartX;c.inverted&&(k=a.chartY,f=this.top);if(1===b)this.grabbedCenter=k,this.fixedWidth=l,this.dragOffset=k-e;else{a=k-f-l/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+l>=h)if(a=h-l,this.reversedExtremes){a-=l;var g=this.getUnionExtremes().dataMin}else var n=this.getUnionExtremes().dataMax;a!==e&&
(this.fixedWidth=l,b=d.toFixedRange(a,a+l,g,n),C(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null},onMouseMove:function(a){var c=
this,d=c.chart,e=c.left,h=c.navigatorSize,k=c.range,g=c.dragOffset,p=d.inverted;a.touches&&0===a.touches[0].pageX||(a=d.pointer.normalize(a),d=a.chartX,p&&(e=c.top,d=a.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,d-e,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,d-e)):c.grabbedCenter&&(c.hasDragged=!0,d<g?d=g:d>h+g-k&&(d=h+g-k),c.render(0,0,d-g,d-g+k)),c.hasDragged&&c.scrollbar&&n(c.scrollbar.options.liveRedraw,b.svg&&!f&&!this.chart.isBoosting)&&(a.DOMType=
a.type,setTimeout(function(){c.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a;if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var f=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var h=this.fixedExtreme;this.zoomedMax===this.size&&(h=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(f=this.reversedExtremes?d.dataMax:d.dataMin);
c=c.toFixedRange(this.zoomedMin,this.zoomedMax,f,h);C(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),
this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){e(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&e(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,d=b.navigator,e=d.enabled,f=b.scrollbar,h=f.enabled;b=e?d.height:0;var k=h?f.height:0;this.handles=[];this.shades=[];this.chart=
a;this.setBaseSeries();this.height=b;this.scrollbarHeight=k;this.scrollbarEnabled=h;this.navigatorEnabled=e;this.navigatorOptions=d;this.scrollbarOptions=f;this.outlineHeight=b+k;this.opposite=n(d.opposite,!(e||!a.inverted));var g=this;e=g.baseSeries;f=a.xAxis.length;h=a.yAxis.length;var p=e&&e[0]&&e[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;g.navigatorEnabled?(g.xAxis=new r(a,c({breaks:p.options.breaks,ordinal:p.options.ordinal},d.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,
type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[k,0,-k,0],width:b}:{offsets:[0,-k,0,k],height:b})),g.yAxis=new r(a,c(d.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),e||d.series.data?g.updateNavigatorSeries(!1):0===a.series.length&&(g.unbindRedraw=t(a,"beforeRedraw",function(){0<a.series.length&&!g.series&&(g.setBaseSeries(),
g.unbindRedraw())})),g.reversedExtremes=a.inverted&&!g.xAxis.reversed||!a.inverted&&g.xAxis.reversed,g.renderElements(),g.addMouseEvents()):g.xAxis={translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*k,h=H("min",d.options.min,e.dataMin);d=H("max",d.options.max,e.dataMax)-h;return c?b*d/f+h:f*(b-h)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:r.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=
g.scrollbar=new x(a.renderer,c(a.options.scrollbar,{margin:g.navigatorEnabled?0:10,vertical:a.inverted}),a),t(g.scrollbar,"changed",function(b){var c=g.size,d=c*this.to;c*=this.from;g.hasDragged=g.scrollbar.hasDragged;g.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){g.onMouseUp(b)})}));g.addBaseSeriesEvents();g.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,f;a&&
null===b.dataMin||(f={dataMin:n(d&&d.min,H("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:n(d&&d.max,H("max",e.max,b.dataMax,c.dataMax,c.max))});return f},setBaseSeries:function(a,c){var d=this.chart,e=this.baseSeries=[];a=a||d.options&&d.options.navigator.baseSeries||(d.series.length?b.find(d.series,function(a){return!a.options.isInternal}).index:0);(d.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||e.push(b)});
this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,c)},updateNavigatorSeries:function(a,b){var d=this,f=d.chart,h=d.baseSeries,l,g,p=d.navigatorOptions.series,q,r={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},t=d.series=(d.series||[]).filter(function(a){var b=a.baseSeries;return 0>h.indexOf(b)?(b&&(e(b,"updatedData",d.updatedDataHandler),delete b.navigatorSeries),
a.chart&&a.destroy(),!1):!0});h&&h.length&&h.forEach(function(a){var e=a.navigatorSeries,m=w({color:a.color,visible:a.visible},A(p)?k.navigator.series:p);e&&!1===d.navigatorOptions.adaptToUpdatedData||(r.name="Navigator "+h.length,l=a.options||{},q=l.navigatorOptions||{},g=c(l,r,m,q),g.pointRange=n(m.pointRange,q.pointRange,k.plotOptions[g.type||"line"].pointRange),m=q.data||m.data,d.hasNavigatorData=d.hasNavigatorData||!!m,g.data=m||l.data&&l.data.slice(0),e&&e.options?e.update(g,b):(a.navigatorSeries=
f.initSeries(g),a.navigatorSeries.baseSeries=a,t.push(a.navigatorSeries)))});if(p.data&&(!h||!h.length)||A(p))d.hasNavigatorData=!1,p=z(p),p.forEach(function(a,b){r.name="Navigator "+(t.length+1);g=c(k.navigator.series,{color:f.series[b]&&!f.series[b].options.isInternal&&f.series[b].color||f.options.colors[b]||f.options.colors[0]},r,a);g.data=a.data;g.data&&(d.hasNavigatorData=!0,t.push(f.initSeries(g)))});a&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];
b[0]&&b[0].xAxis&&t(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){t(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});t(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&t(b,"updatedData",this.updatedDataHandler);t(b,"remove",function(){this.navigatorSeries&&(u(a.series,this.navigatorSeries),C(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),
delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,
k=n(this.options.overscroll,0),p=a.series&&a.series[0],q=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var r=c;var t=r+b}f&&(t=d+k,e||(r=Math.max(t-b,a.getBaseSeriesMin(p&&p.xData?p.xData[0]:-Number.MAX_VALUE))));q&&(e||f)&&g(r)&&(this.min=this.userMin=r,this.max=this.userMax=t)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?
0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=g(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(t(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);
b&&a.render(b.min,b.max)}),t(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(u(this.chart.xAxis,this.xAxis),u(this.chart.axes,this.xAxis));this.yAxis&&(u(this.chart.yAxis,this.yAxis),u(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&
a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){E(a)},this)}};b.Navigator||(b.Navigator=q,t(r,"zoom",function(a){var b=this.chart.options,c=b.chart.zoomType,d=b.chart.pinchType,e=b.navigator;b=b.rangeSelector;this.isXAxis&&(e&&e.enabled||b&&b.enabled)&&("y"===c?a.zoomed=!1:(!f&&"xy"===c||
f&&"xy"===d)&&this.options.range&&(c=this.previousZoom,C(a.newMin)?this.previousZoom=[this.min,this.max]:c&&(a.newMin=c[0],a.newMax=c[1],delete this.previousZoom)));"undefined"!==typeof a.zoomed&&a.preventDefault()}),t(d,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!f&&"x"===a.chart.zoomType||f&&"x"===a.chart.pinchType))return!1}),t(d,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=
this.navigator=new q(this)}),t(d,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?
a.legendHeight+n(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),t(d,"update",function(a){var b=a.options.navigator||{},d=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!d.enabled||(c(!0,this.options.navigator,b),c(!0,this.options.scrollbar,d),delete a.options.navigator,delete a.options.scrollbar)}),t(d,"afterUpdate",function(a){this.navigator||
this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new q(this),n(a.redraw,!0)&&this.redraw(a.animation))}),t(d,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),t(p,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),d.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}))});
H(q,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map