/*
 Highmaps JS v7.2.1-modified (2019-11-18)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(g){"object"===typeof module&&module.exports?(g["default"]=g,module.exports=g):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(y){g(y);g.Highcharts=y;return g}):g("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(g){function y(a,b,g,r){a.hasOwnProperty(b)||(a[b]=r.apply(null,g))}g=g?g._modules:{};y(g,"parts-map/MapAxis.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.pick;b=a.addEvent;a=a.Axis;b(a,"getSeriesExtremes",
function(){var a=[];this.isXAxis&&(this.series.forEach(function(t,b){t.useMapGeometry&&(a[b]=t.xData,t.xData=[])}),this.seriesXData=a)});b(a,"afterGetSeriesExtremes",function(){var a=this.seriesXData,t;if(this.isXAxis){var b=g(this.dataMin,Number.MAX_VALUE);var p=g(this.dataMax,-Number.MAX_VALUE);this.series.forEach(function(r,l){r.useMapGeometry&&(b=Math.min(b,g(r.minX,b)),p=Math.max(p,g(r.maxX,p)),r.xData=a[l],t=!0)});t&&(this.dataMin=b,this.dataMax=p);delete this.seriesXData}});b(a,"afterSetAxisTranslation",
function(){var a=this.chart;var b=a.plotWidth/a.plotHeight;a=a.xAxis[0];var w;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(w=!0)});if(w&&(this.transA=a.transA=Math.min(this.transA,a.transA),b/=(a.max-a.min)/(this.max-this.min),b=1>b?this:a,a=(b.max-b.min)*b.transA,b.pixelPadding=b.len-a,b.minPixelPadding=b.pixelPadding/2,a=b.fixTo)){a=a[1]-b.toValue(a[0],!0);a*=b.transA;if(Math.abs(a)>b.minPixelPadding||b.min===b.dataMin&&b.max===b.dataMax)a=
0;b.minPixelPadding-=a}});b(a,"render",function(){this.fixTo=null})});y(g,"parts-map/ColorSeriesMixin.js",[g["parts/Globals.js"]],function(a){a.colorPointMixin={setVisible:function(a){var b=this,g=a?"show":"hide";b.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(b[a])b[a][g]()})}};a.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,g=this.options.nullColor,r=this.colorAxis,t=this.colorKey;(this.data.length?this.data:this.points).forEach(function(b){var w=
b[t];if(w=b.options.color||(b.isNull?g:r&&"undefined"!==typeof w?r.toColor(w,b):b.color||a.color))b.color=w})}}});y(g,"parts-map/ColorAxis.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.erase,r=b.extend,t=b.isNumber,w=b.pick,p=b.splat;b=a.addEvent;var v=a.Axis,l=a.Chart,f=a.Series,e=a.Point,k=a.color,m=a.Legend,x=a.LegendSymbolMixin,u=a.colorPointMixin,h=a.noop,c=a.merge;r(f.prototype,a.colorSeriesMixin);r(e.prototype,u);var d=a.ColorAxis=function(){this.init.apply(this,
arguments)};r(d.prototype,v.prototype);r(d.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(v.prototype.keepProps),init:function(c,n){this.coll=
"colorAxis";var q=this.buildOptions.call(c,this.defaultColorAxisOptions,n);v.prototype.init.call(this,c,q);n.dataClasses&&this.initDataClasses(n);this.initStops();this.horiz=!q.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(q){var n=this.chart,d,h=0,a=n.options.chart.colorCount,b=this.options,e=q.dataClasses.length;this.dataClasses=d=[];this.legendItems=[];q.dataClasses.forEach(function(q,z){q=c(q);d.push(q);if(n.styledMode||!q.color)"category"===b.dataClassColor?
(n.styledMode||(z=n.options.colors,a=z.length,q.color=z[h]),q.colorIndex=h,h++,h===a&&(h=0)):q.color=k(b.minColor).tweenTo(k(b.maxColor),2>e?.5:z/(e-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return v.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(c){c.color=k(c[1])})},buildOptions:function(q,
n){var d=this.options.legend,h=n.layout?"vertical"!==n.layout:"vertical"!==d.layout;return c(q,{side:h?2:1,reversed:!h},n,{opposite:!h,showEmpty:!1,title:null,visible:d.enabled&&(n?!1!==n.visible:!0)})},setOptions:function(c){v.prototype.setOptions.call(this,c);this.options.crosshair=this.options.marker},setAxisSize:function(){var c=this.legendSymbol,n=this.chart,d=n.options.legend||{},h,a;c?(this.left=d=c.attr("x"),this.top=h=c.attr("y"),this.width=a=c.attr("width"),this.height=c=c.attr("height"),
this.right=n.chartWidth-d-a,this.bottom=n.chartHeight-h-c,this.len=this.horiz?a:c,this.pos=this.horiz?d:h):this.len=(this.horiz?d.symbolWidth:d.symbolHeight)||this.defaultLegendLength},normalizedValue:function(c){this.isLog&&(c=this.val2lin(c));return 1-(this.max-c)/(this.max-this.min||1)},toColor:function(c,n){var d=this.stops,h=this.dataClasses,q;if(h)for(q=h.length;q--;){var a=h[q];var b=a.from;d=a.to;if(("undefined"===typeof b||c>=b)&&("undefined"===typeof d||c<=d)){var e=a.color;n&&(n.dataClass=
q,n.colorIndex=a.colorIndex);break}}else{c=this.normalizedValue(c);for(q=d.length;q--&&!(c>d[q][0]););b=d[q]||d[q+1];d=d[q+1]||b;c=1-(d[0]-c)/(d[0]-b[0]||1);e=b.color.tweenTo(d.color,c)}return e},getOffset:function(){var c=this.legendGroup,d=this.chart.axisOffset[this.side];c&&(this.axisParent=c,v.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=d)},setLegendColor:function(){var c=this.reversed;var d=c?1:0;c=c?
0:1;d=this.horiz?[d,0,c,0]:[0,c,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}},drawLegendSymbol:function(c,d){var n=c.padding,h=c.options,q=this.horiz,a=w(h.symbolWidth,q?this.defaultLegendLength:12),b=w(h.symbolHeight,q?12:this.defaultLegendLength),e=w(h.labelPadding,q?16:30);h=w(h.itemDistance,10);this.setLegendColor();d.legendSymbol=this.chart.renderer.rect(0,c.baseline-11,a,b).attr({zIndex:1}).add(d.legendGroup);this.legendItemWidth=a+n+(q?h:e);this.legendItemHeight=
b+n+(q?e:0)},setState:function(c){this.series.forEach(function(d){d.setState(c)})},visible:!0,setVisible:h,getSeriesExtremes:function(){var c=this.series,d=c.length,h;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var a=c[d];var b=a.colorKey=w(a.options.colorKey,a.colorKey,a.pointValKey,a.zoneAxis,"y");var e=a.pointArrayMap;var k=a[b+"Min"]&&a[b+"Max"];if(a[b+"Data"])var m=a[b+"Data"];else if(e){m=[];e=e.indexOf(b);var t=a.yData;if(0<=e&&t)for(h=0;h<t.length;h++)m.push(w(t[h][e],t[h]))}else m=
a.yData;k?(a.minColorValue=a[b+"Min"],a.maxColorValue=a[b+"Max"]):(f.prototype.getExtremes.call(a,m),a.minColorValue=a.dataMin,a.maxColorValue=a.dataMax);"undefined"!==typeof a.minColorValue&&(this.dataMin=Math.min(this.dataMin,a.minColorValue),this.dataMax=Math.max(this.dataMax,a.maxColorValue));k||f.prototype.getExtremes.call(a)}},drawCrosshair:function(c,d){var h=d&&d.plotX,a=d&&d.plotY,n=this.pos,q=this.len;if(d){var b=this.toPixels(d[d.series.colorKey]);b<n?b=n-2:b>n+q&&(b=n+q+2);d.plotX=b;d.plotY=
this.len-b;v.prototype.drawCrosshair.call(this,c,d);d.plotX=h;d.plotY=a;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(c){var d=c.translatedValue;return t(d)?this.horiz?["M",d-4,this.top-6,"L",d+4,this.top-6,d,this.top,"Z"]:["M",this.left,d,"L",this.left-6,d+6,this.left-6,d-6,"Z"]:v.prototype.getPlotLinePath.apply(this,
arguments)},update:function(d,h){var a=this.chart,q=a.legend,n=this.buildOptions.call(a,{},d);this.series.forEach(function(c){c.isDirtyData=!0});(d.dataClasses&&q.allItems||this.dataClasses)&&this.destroyItems();a.options[this.coll]=c(this.userOptions,n);v.prototype.update.call(this,n,h);this.legendItem&&(this.setLegendColor(),q.colorizeItem(this,!0))},destroyItems:function(){var c=this.chart;this.legendItem?c.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(d){c.legend.destroyItem(d)});
c.isDirtyLegend=!0},remove:function(c){this.destroyItems();v.prototype.remove.call(this,c)},getDataClassLegendSymbols:function(){var c=this,d=this.chart,a=this.legendItems,b=d.options.legend,e=b.valueDecimals,k=b.valueSuffix||"",m;a.length||this.dataClasses.forEach(function(n,q){var b=!0,z=n.from,f=n.to,A=d.numberFormatter;m="";"undefined"===typeof z?m="< ":"undefined"===typeof f&&(m="> ");"undefined"!==typeof z&&(m+=A(z,e)+k);"undefined"!==typeof z&&"undefined"!==typeof f&&(m+=" - ");"undefined"!==
typeof f&&(m+=A(f,e)+k);a.push(r({chart:d,name:m,options:{},drawLegendSymbol:x.drawRectangle,visible:!0,setState:h,isDataClass:!0,setVisible:function(){b=this.visible=!b;c.series.forEach(function(c){c.points.forEach(function(c){c.dataClass===q&&c.setVisible(b)})});d.legend.colorizeItem(this,b)}},n))});return a},beforePadding:!1,name:""});["fill","stroke"].forEach(function(c){a.Fx.prototype[c+"Setter"]=function(){this.elem.attr(c,k(this.start).tweenTo(k(this.end),this.pos),null,!0)}});b(l,"afterGetAxes",
function(){var c=this,a=c.options;this.colorAxis=[];a.colorAxis&&(a.colorAxis=p(a.colorAxis),a.colorAxis.forEach(function(a,h){a.index=h;new d(c,a)}))});b(f,"bindAxes",function(){var c=this.axisTypes;c?-1===c.indexOf("colorAxis")&&c.push("colorAxis"):this.axisTypes=["colorAxis"]});b(m,"afterGetAllItems",function(c){var d=[],a,h;(this.chart.colorAxis||[]).forEach(function(h){(a=h.options)&&a.showInLegend&&(a.dataClasses&&a.visible?d=d.concat(h.getDataClassLegendSymbols()):a.visible&&d.push(h),h.series.forEach(function(d){if(!d.options.showInLegend||
a.dataClasses)"point"===d.options.legendType?d.points.forEach(function(d){g(c.allItems,d)}):g(c.allItems,d)}))});for(h=d.length;h--;)c.allItems.unshift(d[h])});b(m,"afterColorizeItem",function(c){c.visible&&c.item.legendColor&&c.item.legendSymbol.attr({fill:c.item.legendColor})});b(m,"afterUpdate",function(){var c=this.chart.colorAxis;c&&c.forEach(function(c,d,a){c.update({},a)})});b(f,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});
y(g,"parts-map/ColorMapSeriesMixin.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.defined;b=a.noop;var r=a.seriesTypes;a.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(b){a.Point.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})}};a.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group",
"markerGroup","dataLabelsGroup"],getSymbol:b,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:r.column.prototype.pointAttribs,colorAttribs:function(a){var b={};g(a.color)&&(b[this.colorProp||"fill"]=a.color);return b}}});y(g,"parts-map/MapNavigation.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){function g(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function r(a){this.init(a)}var t=b.extend,w=b.objectEach,p=
b.pick,v=a.addEvent;b=a.Chart;var l=a.doc,f=a.merge;r.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};r.prototype.update=function(a){var b=this.chart,e=b.options.mapNavigation,l,u,h,c,d,q=function(c){this.handler.call(b,c);g(c)},n=b.mapNavButtons;a&&(e=b.options.mapNavigation=f(b.options.mapNavigation,a));for(;n.length;)n.pop().destroy();p(e.enableButtons,e.enabled)&&!b.renderer.forExport&&w(e.buttons,function(a,m){l=f(e.buttonOptions,a);b.styledMode||(u=l.theme,u.style=f(l.theme.style,
l.style),c=(h=u.states)&&h.hover,d=h&&h.select);a=b.renderer.button(l.text,0,0,q,u,c,d,0,"zoomIn"===m?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[m]).attr({width:l.width,height:l.height,title:b.options.lang[m],padding:l.padding,zIndex:5}).add();a.handler=l.onclick;a.align(t(l,{width:a.width,height:2*a.height}),null,l.alignTo);v(a.element,"dblclick",g);n.push(a)});this.updateEvents(e)};r.prototype.updateEvents=function(a){var b=
this.chart;p(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||v(b.container,"dblclick",function(a){b.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());p(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||v(b.container,"undefined"===typeof l.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){b.pointer.onContainerMouseWheel(a);g(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=
this.unbindMouseWheel())};t(b.prototype,{fitToBox:function(a,b){[["x","width"],["y","height"]].forEach(function(e){var f=e[0];e=e[1];a[f]+a[e]>b[f]+b[e]&&(a[e]>b[e]?(a[e]=b[e],a[f]=b[f]):a[f]=b[f]+b[e]-a[e]);a[e]>b[e]&&(a[e]=b[e]);a[f]<b[f]&&(a[f]=b[f])});return a},mapZoom:function(a,b,f,l,t){var h=this.xAxis[0],c=h.max-h.min,d=p(b,h.min+c/2),q=c*a;c=this.yAxis[0];var n=c.max-c.min,e=p(f,c.min+n/2);n*=a;d=this.fitToBox({x:d-q*(l?(l-h.pos)/h.len:.5),y:e-n*(t?(t-c.pos)/c.len:.5),width:q,height:n},{x:h.dataMin,
y:c.dataMin,width:h.dataMax-h.dataMin,height:c.dataMax-c.dataMin});q=d.x<=h.dataMin&&d.width>=h.dataMax-h.dataMin&&d.y<=c.dataMin&&d.height>=c.dataMax-c.dataMin;l&&(h.fixTo=[l-h.pos,b]);t&&(c.fixTo=[t-c.pos,f]);"undefined"===typeof a||q?(h.setExtremes(void 0,void 0,!1),c.setExtremes(void 0,void 0,!1)):(h.setExtremes(d.x,d.x+d.width,!1),c.setExtremes(d.y,d.y+d.height,!1));this.redraw()}});v(b,"beforeRender",function(){this.mapNavigation=new r(this);this.mapNavigation.update()});a.MapNavigation=r});
y(g,"parts-map/MapPointer.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.extend,r=b.pick;b=a.Pointer;a=a.wrap;g(b.prototype,{onContainerDblClick:function(a){var b=this.chart;a=this.normalize(a);b.options.mapNavigation.enableDoubleClickZoomTo?b.pointer.inClass(a.target,"highcharts-tracker")&&b.hoverPoint&&b.hoverPoint.zoomTo():b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(.5,b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},
onContainerMouseWheel:function(a){var b=this.chart;a=this.normalize(a);var g=a.detail||-(a.wheelDelta/120);b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(Math.pow(b.options.mapNavigation.mouseWheelSensitivity,g),b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)}});a(b.prototype,"zoomOption",function(a){var b=this.chart.options.mapNavigation;r(b.enableTouchZoom,b.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});
a(b.prototype,"pinchTranslate",function(a,b,g,r,l,f,e){a.call(this,b,g,r,l,f,e);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=r.scaleX>r.scaleY,this.pinchTranslateDirection(!a,b,g,r,l,f,e,a?r.scaleX:r.scaleY))})});y(g,"parts-map/MapSeries.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.extend,r=b.isArray,t=b.isNumber,w=b.objectEach,p=b.pick,v=b.splat;b=a.colorMapPointMixin;var l=a.merge,f=a.noop,e=a.fireEvent,k=a.Point,m=a.Series,x=a.seriesType,u=a.seriesTypes;
x("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},l(a.colorMapSeriesMixin,{type:"map",
getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:f,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(a){a=m.prototype.setOptions.call(this,a);var c=a.joinBy;null===c&&(c="_i");c=this.joinBy=v(c);c[1]||(c[1]=c[0]);return a},getBox:function(b){var c=Number.MAX_VALUE,d=-c,h=c,n=-c,e=c,f=c,m=this.xAxis,k=this.yAxis,l;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=a.splitPath(b.path));var q=b.path||[],m=q.length,k=!1,z=-c,g=c,A=-c,
B=c,C=b.properties;if(!b._foundBox){for(;m--;)t(q[m])&&(k?(z=Math.max(z,q[m]),g=Math.min(g,q[m])):(A=Math.max(A,q[m]),B=Math.min(B,q[m])),k=!k);b._midX=g+(z-g)*p(b.middleX,C&&C["hc-middle-x"],.5);b._midY=B+(A-B)*p(b.middleY,C&&C["hc-middle-y"],.5);b._maxX=z;b._minX=g;b._maxY=A;b._minY=B;b.labelrank=p(b.labelrank,(z-g)*(A-B));b._foundBox=!0}d=Math.max(d,b._maxX);h=Math.min(h,b._minX);n=Math.max(n,b._maxY);e=Math.min(e,b._minY);f=Math.min(b._maxX-b._minX,b._maxY-b._minY,f);l=!0}});l&&(this.minY=Math.min(e,
p(this.minY,c)),this.maxY=Math.max(n,p(this.maxY,-c)),this.minX=Math.min(h,p(this.minX,c)),this.maxX=Math.max(d,p(this.maxX,-c)),m&&"undefined"===typeof m.options.minRange&&(m.minRange=Math.min(5*f,(this.maxX-this.minX)/5,m.minRange||c)),k&&"undefined"===typeof k.options.minRange&&(k.minRange=Math.min(5*f,(this.maxY-this.minY)/5,k.minRange||c)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){m.prototype.getExtremes.call(this,this.valueData);this.chart.hasRendered&&
this.isDirtyData&&this.getBox(this.options.data);this.valueMin=this.dataMin;this.valueMax=this.dataMax;this.dataMin=this.minY;this.dataMax=this.maxY},translatePath:function(a){var c=!1,d=this.xAxis,b=this.yAxis,h=d.min,e=d.transA;d=d.minPixelPadding;var f=b.min,m=b.transA;b=b.minPixelPadding;var k,l=[];if(a)for(k=a.length;k--;)t(a[k])?(l[k]=c?(a[k]-h)*e+d:(a[k]-f)*m+b,c=!c):l[k]=a[k];return l},setData:function(b,c,d,q){var h=this.options,e=this.chart.options.chart,f=e&&e.map,k=h.mapData,g=this.joinBy,
u=h.keys||this.pointArrayMap,p=[],x={},v=this.chart.mapTransforms;!k&&f&&(k="string"===typeof f?a.maps[f]:f);b&&b.forEach(function(c,d){var n=0;if(t(c))b[d]={value:c};else if(r(c)){b[d]={};!h.keys&&c.length>u.length&&"string"===typeof c[0]&&(b[d]["hc-key"]=c[0],++n);for(var q=0;q<u.length;++q,++n)u[q]&&"undefined"!==typeof c[n]&&(0<u[q].indexOf(".")?a.Point.prototype.setNestedProperty(b[d],c[n],u[q]):b[d][u[q]]=c[n])}g&&"_i"===g[0]&&(b[d]._i=d)});this.getBox(b);(this.chart.mapTransforms=v=e&&e.mapTransforms||
k&&k["hc-transform"]||v)&&w(v,function(c){c.rotation&&(c.cosAngle=Math.cos(c.rotation),c.sinAngle=Math.sin(c.rotation))});if(k){"FeatureCollection"===k.type&&(this.mapTitle=k.title,k=a.geojson(k,this.type,this));this.mapData=k;this.mapMap={};for(v=0;v<k.length;v++)e=k[v],f=e.properties,e._i=v,g[0]&&f&&f[g[0]]&&(e[g[0]]=f[g[0]]),x[e[g[0]]]=e;this.mapMap=x;b&&g[1]&&b.forEach(function(c){x[c[g[1]]]&&p.push(x[c[g[1]]])});h.allAreas?(this.getBox(k),b=b||[],g[1]&&b.forEach(function(c){p.push(c[g[1]])}),
p="|"+p.map(function(c){return c&&c[g[0]]}).join("|")+"|",k.forEach(function(c){g[0]&&-1!==p.indexOf("|"+c[g[0]]+"|")||(b.push(l(c,{value:null})),q=!1)})):this.getBox(p)}m.prototype.setData.call(this,b,c,d,q)},drawGraph:f,drawDataLabels:f,doFullTranslate:function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var a=this,c=a.xAxis,d=a.yAxis,b=a.doFullTranslate();a.generatePoints();a.data.forEach(function(h){t(h._midX)&&t(h._midY)&&
(h.plotX=c.toPixels(h._midX,!0),h.plotY=d.toPixels(h._midY,!0));b&&(h.shapeType="path",h.shapeArgs={d:a.translatePath(h.path)})});e(a,"afterTranslate")},pointAttribs:function(a,c){c=a.series.chart.styledMode?this.colorAttribs(a):u.column.prototype.pointAttribs.call(this,a,c);c["stroke-width"]=p(a.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return c},drawPoints:function(){var a=this,c=a.xAxis,d=a.yAxis,b=a.group,n=a.chart,e=n.renderer,f=this.baseTrans;
a.transformGroup||(a.transformGroup=e.g().attr({scaleX:1,scaleY:1}).add(b),a.transformGroup.survive=!0);if(a.doFullTranslate())n.hasRendered&&!n.styledMode&&a.points.forEach(function(c){c.shapeArgs&&(c.shapeArgs.fill=a.pointAttribs(c,c.state).fill)}),a.group=a.transformGroup,u.column.prototype.drawPoints.apply(a),a.group=b,a.points.forEach(function(c){if(c.graphic){var d="";c.name&&(d+="highcharts-name-"+c.name.replace(/ /g,"-").toLowerCase());c.properties&&c.properties["hc-key"]&&(d+=" highcharts-key-"+
c.properties["hc-key"].toLowerCase());d&&c.graphic.addClass(d);n.styledMode&&c.graphic.css(a.pointAttribs(c,c.selected&&"select"))}}),this.baseTrans={originX:c.min-c.minPixelPadding/c.transA,originY:d.min-d.minPixelPadding/d.transA+(d.reversed?0:d.len/d.transA),transAX:c.transA,transAY:d.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var k=c.transA/f.transAX;var g=d.transA/f.transAY;var m=c.toPixels(f.originX,!0);var l=d.toPixels(f.originY,!0);.99<k&&1.01>
k&&.99<g&&1.01>g&&(g=k=1,m=Math.round(m),l=Math.round(l));var r=this.transformGroup;if(n.renderer.globalAnimation){var t=r.attr("translateX");var x=r.attr("translateY");var v=r.attr("scaleX");var w=r.attr("scaleY");r.attr({animator:0}).animate({animator:1},{step:function(c,a){r.attr({translateX:t+(m-t)*a.pos,translateY:x+(l-x)*a.pos,scaleX:v+(k-v)*a.pos,scaleY:w+(g-w)*a.pos})}})}else r.attr({translateX:m,translateY:l,scaleX:k,scaleY:g})}n.styledMode||b.element.setAttribute("stroke-width",p(a.options[a.pointAttrToOptions&&
a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(k||1));this.drawMapDataLabels()},drawMapDataLabels:function(){m.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var a=this,c=m.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?setTimeout(function(){c.call(a)}):c.call(a)},animate:function(a){var c=this.options.animation,d=this.group,b=this.xAxis,h=this.yAxis,e=b.pos,f=h.pos;this.chart.renderer.isSVG&&(!0===
c&&(c={duration:1E3}),a?d.attr({translateX:e+b.len/2,translateY:f+h.len/2,scaleX:.001,scaleY:.001}):(d.animate({translateX:e,translateY:f,scaleX:1,scaleY:1},c),this.animate=null))},animateDrilldown:function(a){var c=this.chart.plotBox,d=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],b=d.bBox,h=this.chart.options.drilldown.animation;a||(a=Math.min(b.width/c.width,b.height/c.height),d.shapeArgs={scaleX:a,scaleY:a,translateX:b.x,translateY:b.y},this.points.forEach(function(a){a.graphic&&
a.graphic.attr(d.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},h)}),this.animate=null)},drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,animateDrillupFrom:function(a){u.column.prototype.animateDrillupFrom.call(this,a)},animateDrillupTo:function(a){u.column.prototype.animateDrillupTo.call(this,a)}}),g({applyOptions:function(a,c){var d=this.series;a=k.prototype.applyOptions.call(this,a,c);c=d.joinBy;d.mapData&&((c="undefined"!==typeof a[c[1]]&&d.mapMap[a[c[1]]])?(d.xyFromShape&&
(a.x=c._midX,a.y=c._midY),g(a,c)):a.value=a.value||null);return a},onMouseOver:function(b){a.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)k.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,this._maxY,!1);a.chart.redraw()}},b));""});y(g,"parts-map/MapLineSeries.js",[g["parts/Globals.js"]],function(a){var b=a.seriesType,g=a.seriesTypes;
b("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,b){a=g.map.prototype.pointAttribs.call(this,a,b);a.fill=this.options.fillColor;return a},drawLegendSymbol:g.line.prototype.drawLegendSymbol});""});y(g,"parts-map/MapPointSeries.js",[g["parts/Globals.js"]],function(a){var b=a.merge,g=a.Point;a=a.seriesType;a("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},
overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0},{applyOptions:function(a,t){a="undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?b(a,this.series.chart.fromLatLonToPoint(a)):a;return g.prototype.applyOptions.call(this,a,t)}});""});y(g,"parts-more/BubbleLegend.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.arrayMax,r=b.arrayMin,t=b.isNumber,w=b.objectEach,p=b.pick;b=a.Series;var v=a.Legend,l=a.Chart,f=a.addEvent,e=a.wrap,k=a.color,m=a.merge,x=a.noop,
u=a.stableSort,h=a.setOptions;h({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});
a.BubbleLegend=function(a,d){this.init(a,d)};a.BubbleLegend.prototype={init:function(a,d){this.options=a;this.visible=!0;this.chart=d.chart;this.legend=d},setState:x,addToLegend:function(a){a.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(a){var c=this.chart,b=this.options,n=p(a.options.itemDistance,20),h=b.ranges;var e=b.connectorDistance;this.fontMetrics=c.renderer.fontMetrics(b.labels.style.fontSize.toString()+"px");h&&h.length&&t(h[0].value)?(u(h,function(a,c){return c.value-
a.value}),this.ranges=h,this.setOptions(),this.render(),c=this.getMaxLabelSize(),h=this.ranges[0].radius,a=2*h,e=e-h+c.width,e=0<e?e:0,this.maxLabel=c,this.movementX="left"===b.labels.align?e:0,this.legendItemWidth=a+e+n,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0},setOptions:function(){var a=this.ranges,d=this.options,b=this.chart.series[d.seriesIndex],h=this.legend.baseline,e={"z-index":d.zIndex,"stroke-width":d.borderWidth},f={"z-index":d.zIndex,"stroke-width":d.connectorWidth},
g=this.getLabelStyles(),l=b.options.marker.fillOpacity,u=this.chart.styledMode;a.forEach(function(c,n){u||(e.stroke=p(c.borderColor,d.borderColor,b.color),e.fill=p(c.color,d.color,1!==l?k(b.color).setOpacity(l).get("rgba"):b.color),f.stroke=p(c.connectorColor,d.connectorColor,b.color));a[n].radius=this.getRangeRadius(c.value);a[n]=m(a[n],{center:a[0].radius-a[n].radius+h});u||m(!0,a[n],{bubbleStyle:m(!1,e),connectorStyle:m(!1,f),labelStyle:g})},this)},getLabelStyles:function(){var a=this.options,
b={},h="left"===a.labels.align,n=this.legend.options.rtl;w(a.labels.style,function(a,c){"color"!==c&&"fontSize"!==c&&"z-index"!==c&&(b[c]=a)});return m(!1,b,{"font-size":a.labels.style.fontSize,fill:p(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:n||h?"right":"left"})},getRangeRadius:function(a){var c=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,c.ranges[c.ranges.length-1].value,c.ranges[0].value,c.minSize,c.maxSize,a)},render:function(){var a=this.chart.renderer,
b=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(a){var c=this.options,b=c.labels,h=this.chart.renderer,e=this.symbols,
f=e.labels,k=a.center,g=Math.abs(a.radius),m=c.connectorDistance,l=b.align,u=b.style.fontSize;m=this.legend.options.rtl||"left"===l?-m:m;b=c.connectorWidth;var p=this.ranges[0].radius,t=k-g-c.borderWidth/2+b/2;u=u/2-(this.fontMetrics.h-u)/2;var r=h.styledMode;"center"===l&&(m=0,c.connectorDistance=0,a.labelStyle.align="center");l=t+c.labels.y;var x=p+m+c.labels.x;e.bubbleItems.push(h.circle(p,k+((t%1?1:.5)-(b%2?0:.5)),g).attr(r?{}:a.bubbleStyle).addClass((r?"highcharts-color-"+this.options.seriesIndex+
" ":"")+"highcharts-bubble-legend-symbol "+(c.className||"")).add(this.legendSymbol));e.connectors.push(h.path(h.crispLine(["M",p,t,"L",p+m,t],c.connectorWidth)).attr(r?{}:a.connectorStyle).addClass((r?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(c.connectorClassName||"")).add(this.legendSymbol));a=h.text(this.formatLabel(a),x,l+u).attr(r?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(c.labels.className||"")).add(this.legendSymbol);f.push(a);
a.placed=!0;a.alignAttr={x:x,y:l+u}},getMaxLabelSize:function(){var a,b;this.symbols.labels.forEach(function(c){b=c.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}},formatLabel:function(c){var b=this.options,h=b.labels.formatter;b=b.labels.format;var e=this.chart.numberFormatter;return b?a.format(b,c):h?h.call(c):e(c.value,1)},hideOverlappingLabels:function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),b.labels.forEach(function(a,c){a.newOpacity?
a.newOpacity!==a.oldOpacity&&b.connectors[c].show():b.connectors[c].hide()}))},getRanges:function(){var a=this.legend.bubbleLegend,b=a.options.ranges,h,e=Number.MAX_VALUE,f=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(h=a.zData.filter(t),h.length&&(e=p(a.options.zMin,Math.min(e,Math.max(r(h),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),f=p(a.options.zMax,Math.max(f,g(h)))))});var k=e===f?[{value:f}]:[{value:e},{value:(e+f)/2},{value:f,
autoRanges:!0}];b.length&&b[0].radius&&k.reverse();k.forEach(function(a,c){b&&b[c]&&(k[c]=m(!1,b[c],a))});return k},predictBubbleSizes:function(){var a=this.chart,b=this.fontMetrics,h=a.legend.options,e="horizontal"===h.layout,f=e?a.legend.lastLineHeight:0,k=a.plotSizeX,g=a.plotSizeY,m=a.series[this.options.seriesIndex];a=Math.ceil(m.minPxSize);var l=Math.ceil(m.maxPxSize);m=m.options.maxSize;var u=Math.min(g,k);if(h.floating||!/%$/.test(m))b=l;else if(m=parseFloat(m),b=(u+f-b.h/2)*m/100/(m/100+1),
e&&g-b>=k||!e&&k-b>=g)b=l;return[a,Math.ceil(b)]},updateRanges:function(a,b){var c=this.legend.options.bubbleLegend;c.minSize=a;c.maxSize=b;c.ranges=this.getRanges()},correctSizes:function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())}};f(a.Legend,"afterGetAllItems",function(b){var c=this.bubbleLegend,h=this.options,e=h.bubbleLegend,f=this.chart.getVisibleBubbleSeriesIndex();
c&&c.ranges&&c.ranges.length&&(e.ranges.length&&(e.autoRanges=!!e.ranges[0].autoRanges),this.destroyItem(c));0<=f&&h.enabled&&e.enabled&&(e.seriesIndex=f,this.bubbleLegend=new a.BubbleLegend(e,this),this.bubbleLegend.addToLegend(b.allItems))});l.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};v.prototype.getLinesHeights=function(){var a=this.allItems,b=[],h=a.length,e,f=0;for(e=0;e<
h;e++)if(a[e].legendItemHeight&&(a[e].itemHeight=a[e].legendItemHeight),a[e]===a[h-1]||a[e+1]&&a[e]._legendItemPos[1]!==a[e+1]._legendItemPos[1]){b.push({height:0});var k=b[b.length-1];for(f;f<=e;f++)a[f].itemHeight>k.height&&(k.height=a[f].itemHeight);k.step=e}return b};v.prototype.retranslateItems=function(a){var b,c,e,h=this.options.rtl,f=0;this.allItems.forEach(function(d,k){b=d.legendGroup.translateX;c=d._legendItemPos[1];if((e=d.movementX)||h&&d.ranges)e=h?b-d.options.maxSize/2:b+e,d.legendGroup.attr({translateX:e});
k>a[f].step&&f++;d.legendGroup.attr({translateY:Math.round(c+a[f].height/2)});d._legendItemPos[1]=c+a[f].height/2})};f(b,"legendItemClick",function(){var a=this.chart,b=this.visible,e=this.chart.legend;e&&e.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),e.bubbleLegend.visible!==a&&(e.update({bubbleLegend:{enabled:a}}),e.bubbleLegend.visible=a),this.visible=b)});e(l.prototype,"drawChartBox",function(a,b,e){var c=this.legend,d=0<=this.getVisibleBubbleSeriesIndex();
if(c&&c.options.enabled&&c.bubbleLegend&&c.options.bubbleLegend.autoRanges&&d){var h=c.bubbleLegend.options;d=c.bubbleLegend.predictBubbleSizes();c.bubbleLegend.updateRanges(d[0],d[1]);h.placed||(c.group.placed=!1,c.allItems.forEach(function(a){a.legendGroup.translateY=null}));c.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();h.placed||(a.setScale(),a.updateNames(),w(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});h.placed=!0;this.getMargins();a.call(this,b,e);c.bubbleLegend.correctSizes();
c.retranslateItems(c.getLinesHeights())}else a.call(this,b,e),c&&c.options.enabled&&c.bubbleLegend&&(c.render(),c.retranslateItems(c.getLinesHeights()))})});y(g,"parts-more/BubbleSeries.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.arrayMax,r=b.arrayMin,t=b.clamp,w=b.extend,p=b.isNumber,v=b.pick,l=b.pInt;b=a.Axis;var f=a.color,e=a.noop,k=a.Point,m=a.Series,x=a.seriesType,u=a.seriesTypes;x("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,
verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,
pointAttribs:function(a,b){var c=this.options.marker.fillOpacity;a=m.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=f(a.fill).setOpacity(c).get("rgba"));return a},getRadii:function(a,b,d){var c=this.zData,e=this.yData,h=d.minPxSize,f=d.maxPxSize,k=[];var g=0;for(d=c.length;g<d;g++){var m=c[g];k.push(this.getRadius(a,b,h,f,m,e[g]))}this.radii=k},getRadius:function(a,b,d,e,f,k){var c=this.options,h="width"!==c.sizeBy,g=c.zThreshold,m=b-a,l=.5;if(null===k||null===f)return null;if(p(f)){c.sizeByAbsoluteValue&&
(f=Math.abs(f-g),m=Math.max(b-g,Math.abs(a-g)),a=0);if(f<a)return d/2-1;0<m&&(l=(f-a)/m)}h&&0<=l&&(l=Math.sqrt(l));return Math.ceil(d+l*(e-d))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var b=a.graphic;if(b&&b.width){var c={x:b.x,y:b.y,width:b.width,height:b.height};b.attr({x:a.plotX,y:a.plotY,width:1,height:1});b.animate(c,this.options.animation)}},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,
b=this.data,d=this.radii;u.scatter.prototype.translate.call(this);for(a=b.length;a--;){var e=b[a];var f=d?d[a]:0;p(f)&&f>=this.minPxSize/2?(e.marker=w(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*f,height:2*f}):e.shapeArgs=e.plotY=e.dlBox=void 0}},alignDataLabel:u.column.prototype.alignDataLabel,buildKDTree:e,applyZones:e},{haloPath:function(a){return k.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});b.prototype.beforePadding=
function(){var a=this,b=this.len,e=this.chart,f=0,k=b,m=this.isXAxis,u=m?"xData":"yData",x=this.min,w={},y=Math.min(e.plotWidth,e.plotHeight),E=Number.MAX_VALUE,F=-Number.MAX_VALUE,G=this.max-x,D=b/G,H=[];this.series.forEach(function(b){var c=b.options;!b.bubblePadding||!b.visible&&e.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,H.push(b),m&&(["minSize","maxSize"].forEach(function(a){var b=c[a],e=/%$/.test(b);b=l(b);w[a]=e?y*b/100:b}),b.minPxSize=w.minSize,b.maxPxSize=Math.max(w.maxSize,
w.minSize),b=b.zData.filter(p),b.length&&(E=v(c.zMin,t(r(b),!1===c.displayNegative?c.zThreshold:-Number.MAX_VALUE,E)),F=v(c.zMax,Math.max(F,g(b))))))});H.forEach(function(b){var c=b[u],e=c.length;m&&b.getRadii(E,F,b);if(0<G)for(;e--;)if(p(c[e])&&a.dataMin<=c[e]&&c[e]<=a.dataMax){var d=b.radii?b.radii[e]:0;f=Math.min((c[e]-x)*D-d,f);k=Math.max((c[e]-x)*D+d,k)}});H.length&&0<G&&!this.isLog&&(k-=b,D*=(b+Math.max(0,f)-Math.min(k,b))/b,[["min","userMin",f],["max","userMax",k]].forEach(function(b){"undefined"===
typeof v(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/D)}))};""});y(g,"parts-map/MapBubbleSeries.js",[g["parts/Globals.js"]],function(a){var b=a.merge,g=a.Point,r=a.seriesType,t=a.seriesTypes;t.bubble&&r("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:t.map.prototype.getMapData,getBox:t.map.prototype.getBox,setData:t.map.prototype.setData,setOptions:t.map.prototype.setOptions},{applyOptions:function(a,
p){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?g.prototype.applyOptions.call(this,b(a,this.series.chart.fromLatLonToPoint(a)),p):t.map.prototype.pointClass.prototype.applyOptions.call(this,a,p)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});y(g,"parts-map/HeatmapSeries.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){var g=b.clamp,r=b.extend,t=b.pick;b=a.colorMapPointMixin;var w=a.merge,p=a.noop,v=a.fireEvent,l=a.Series,f=a.seriesType,e=
a.seriesTypes;f("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:null,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},w(a.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){e.scatter.prototype.init.apply(this,
arguments);var a=this.options;a.pointRange=t(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1},translate:function(){var a=this.options,b=this.xAxis,e=this.yAxis,f=a.pointPadding||0,h=this.pointPlacementToXValue();this.generatePoints();this.points.forEach(function(c){var d=(a.colsize||1)/2,k=(a.rowsize||1)/2,m=g(Math.round(b.len-b.translate(c.x-d,0,1,0,1,-h)),-b.len,2*b.len);d=g(Math.round(b.len-b.translate(c.x+d,0,1,0,1,-h)),-b.len,2*b.len);var l=g(Math.round(e.translate(c.y-k,0,
1,0,1)),-e.len,2*e.len);k=g(Math.round(e.translate(c.y+k,0,1,0,1)),-e.len,2*e.len);var u=t(c.pointPadding,f);c.plotX=c.clientX=(m+d)/2;c.plotY=(l+k)/2;c.shapeType="rect";c.shapeArgs={x:Math.min(m,d)+u,y:Math.min(l,k)+u,width:Math.max(Math.abs(d-m)-2*u,0),height:Math.max(Math.abs(k-l)-2*u,0)}});v(this,"afterTranslate")},drawPoints:function(){var a=this.chart.styledMode?"css":"animate";e.column.prototype.drawPoints.call(this);this.points.forEach(function(b){b.graphic[a](this.colorAttribs(b))},this)},
hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return l.prototype.getValidPoints.call(this,a,b,!0)},animate:p,getBox:p,drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,alignDataLabel:e.column.prototype.alignDataLabel,getExtremes:function(){l.prototype.getExtremes.call(this,this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;l.prototype.getExtremes.call(this)}}),r({haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-
a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]}},b));""});y(g,"parts-map/GeoJSON.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(a,b){function g(a,b){var e,f=!1,g=a.x,l=a.y;a=0;for(e=b.length-1;a<b.length;e=a++){var u=b[a][1]>l;var h=b[e][1]>l;u!==h&&g<(b[e][0]-b[a][0])*(l-b[a][1])/(b[e][1]-b[a][1])+b[a][0]&&(f=!f)}return f}var r=b.extend;b=a.Chart;var t=a.format,w=a.merge,p=a.win,v=a.wrap;b.prototype.transformFromLatLon=function(b,f){if("undefined"===
typeof p.proj4)return a.error(21,!1,this),{x:0,y:null};b=p.proj4(f.crs,[b.lon,b.lat]);var e=f.cosAngle||f.rotation&&Math.cos(f.rotation),g=f.sinAngle||f.rotation&&Math.sin(f.rotation);b=f.rotation?[b[0]*e+b[1]*g,-b[0]*g+b[1]*e]:b;return{x:((b[0]-(f.xoffset||0))*(f.scale||1)+(f.xpan||0))*(f.jsonres||1)+(f.jsonmarginX||0),y:(((f.yoffset||0)-b[1])*(f.scale||1)+(f.ypan||0))*(f.jsonres||1)-(f.jsonmarginY||0)}};b.prototype.transformToLatLon=function(b,f){if("undefined"===typeof p.proj4)a.error(21,!1,this);
else{b={x:((b.x-(f.jsonmarginX||0))/(f.jsonres||1)-(f.xpan||0))/(f.scale||1)+(f.xoffset||0),y:((-b.y-(f.jsonmarginY||0))/(f.jsonres||1)+(f.ypan||0))/(f.scale||1)+(f.yoffset||0)};var e=f.cosAngle||f.rotation&&Math.cos(f.rotation),g=f.sinAngle||f.rotation&&Math.sin(f.rotation);f=p.proj4(f.crs,"WGS84",f.rotation?{x:b.x*e+b.y*-g,y:b.x*g+b.y*e}:b);return{lat:f.y,lon:f.x}}};b.prototype.fromPointToLatLon=function(b){var f=this.mapTransforms,e;if(f){for(e in f)if(Object.hasOwnProperty.call(f,e)&&f[e].hitZone&&
g({x:b.x,y:-b.y},f[e].hitZone.coordinates[0]))return this.transformToLatLon(b,f[e]);return this.transformToLatLon(b,f["default"])}a.error(22,!1,this)};b.prototype.fromLatLonToPoint=function(b){var f=this.mapTransforms,e;if(!f)return a.error(22,!1,this),{x:0,y:null};for(e in f)if(Object.hasOwnProperty.call(f,e)&&f[e].hitZone){var k=this.transformFromLatLon(b,f[e]);if(g({x:k.x,y:-k.y},f[e].hitZone.coordinates[0]))return k}return this.transformFromLatLon(b,f["default"])};a.geojson=function(a,b,e){var f=
[],g=[],l=function(a){var b,c=a.length;g.push("M");for(b=0;b<c;b++)1===b&&g.push("L"),g.push(a[b][0],-a[b][1])};b=b||"map";a.features.forEach(function(a){var e=a.geometry,c=e.type;e=e.coordinates;a=a.properties;var d;g=[];"map"===b||"mapbubble"===b?("Polygon"===c?(e.forEach(l),g.push("Z")):"MultiPolygon"===c&&(e.forEach(function(a){a.forEach(l)}),g.push("Z")),g.length&&(d={path:g})):"mapline"===b?("LineString"===c?l(e):"MultiLineString"===c&&e.forEach(l),g.length&&(d={path:g})):"mappoint"===b&&"Point"===
c&&(d={x:e[0],y:-e[1]});d&&f.push(r(d,{name:a.name||a.NAME,properties:a}))});e&&a.copyrightShort&&(e.chart.mapCredits=t(e.chart.options.credits.mapText,{geojson:a}),e.chart.mapCreditsFull=t(e.chart.options.credits.mapTextFull,{geojson:a}));return f};v(b.prototype,"addCredits",function(a,b){b=w(!0,this.options.credits,b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});y(g,"parts-map/Map.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],
function(a,b){function g(a,b,f,g,l,h,c,d){return["M",a+l,b,"L",a+f-h,b,"C",a+f-h/2,b,a+f,b+h/2,a+f,b+h,"L",a+f,b+g-c,"C",a+f,b+g-c/2,a+f-c/2,b+g,a+f-c,b+g,"L",a+d,b+g,"C",a+d/2,b+g,a,b+g-d/2,a,b+g-d,"L",a,b+l,"C",a,b+l/2,a+l/2,b,a+l,b,"Z"]}var r=b.extend,t=b.pick,w=a.Chart;b=a.defaultOptions;var p=a.merge,v=a.Renderer,l=a.SVGRenderer,f=a.VMLRenderer;r(b.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});b.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,
padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};a.splitPath=function(a){var b;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(b=0;b<a.length;b++)/[a-zA-Z]/.test(a[b])||(a[b]=parseFloat(a[b]));return a};a.maps={};l.prototype.symbols.topbutton=
function(a,b,f,l,p){return g(a-1,b-1,f,l,p.r,p.r,0,0)};l.prototype.symbols.bottombutton=function(a,b,f,l,p){return g(a-1,b-1,f,l,0,0,p.r,p.r)};v===f&&["topbutton","bottombutton"].forEach(function(a){f.prototype.symbols[a]=l.prototype.symbols[a]});a.Map=a.mapChart=function(b,f,g){var e="string"===typeof b||b.nodeName,k=arguments[e?1:0],h=k,c={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},d=a.getOptions().credits;var l=k.series;k.series=null;k=p({chart:{panning:"xy",type:"map"},
credits:{mapText:t(d.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:t(d.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:c,yAxis:p(c,{reversed:!0})},k,{chart:{inverted:!1,alignTicks:!1}});k.series=h.series=l;return e?new w(b,k,g):new w(k,f)}});y(g,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map