/*
 Highstock JS v7.2.1-modified (2019-11-18)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?(p["default"]=p,module.exports=p):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(H){p(H);p.Highcharts=H;return p}):p("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(p){function H(f,k,p,C){f.hasOwnProperty(k)||(f[k]=C.apply(null,p))}p=p?p._modules:{};H(p,"parts/Scrollbar.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){function p(a,c,r){this.init(a,c,r)}var C=k.correctFloat,
A=k.defined,D=k.destroyObjectProperties,E=k.pick,u=f.addEvent;k=f.Axis;var x=f.defaultOptions,y=f.fireEvent,e=f.hasTouch,t=f.merge,l=f.removeEvent,m,g={height:f.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",
trackBorderColor:"#f2f2f2",trackBorderWidth:1};x.scrollbar=t(!0,g,x.scrollbar);f.swapXY=m=function(a,c){var r=a.length;if(c)for(c=0;c<r;c+=3){var e=a[c+1];a[c+1]=a[c+2];a[c+2]=e}return a};p.prototype={init:function(a,c,r){this.scrollbarButtons=[];this.renderer=a;this.userOptions=c;this.options=t(g,c);this.chart=r;this.size=E(this.options.size,this.options.height);c.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,c=this.options,r=this.size,e=this.chart.styledMode,
d;this.group=d=a.g("scrollbar").attr({zIndex:c.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:c.trackBorderRadius||0,height:r,width:r}).add(d);e||this.track.attr({fill:c.trackBackgroundColor,stroke:c.trackBorderColor,"stroke-width":c.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(d);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:r,
width:r,r:c.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(m(["M",-3,r/4,"L",-3,2*r/3,"M",0,r/4,"L",0,2*r/3,"M",3,r/4,"L",3,2*r/3],c.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);e||(this.scrollbar.attr({fill:c.barBackgroundColor,stroke:c.barBorderColor,"stroke-width":c.barBorderWidth}),this.scrollbarRifles.attr({stroke:c.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,c,r,e){var d=this.options.vertical,h=0,q=this.rendered?"animate":"attr";this.x=a;this.y=c+this.trackBorderWidth;this.width=r;this.xOffset=this.height=e;this.yOffset=h;d?(this.width=this.yOffset=r=h=this.size,this.xOffset=c=0,this.barWidth=e-2*r,this.x=a+=this.options.margin):(this.height=this.xOffset=e=c=this.size,this.barWidth=r-2*e,this.y+=this.options.margin);this.group[q]({translateX:a,
translateY:this.y});this.track[q]({width:r,height:e});this.scrollbarButtons[1][q]({translateX:d?0:r-c,translateY:d?e-h:0})},drawScrollbarButton:function(a){var c=this.renderer,e=this.scrollbarButtons,g=this.options,d=this.size;var h=c.g().add(this.group);e.push(h);h=c.rect().addClass("highcharts-scrollbar-button").add(h);this.chart.styledMode||h.attr({stroke:g.buttonBorderColor,"stroke-width":g.buttonBorderWidth,fill:g.buttonBackgroundColor});h.attr(h.crisp({x:-.5,y:-.5,width:d+1,height:d+1,r:g.buttonBorderRadius},
h.strokeWidth()));h=c.path(m(["M",d/2+(a?-1:1),d/2-3,"L",d/2+(a?-1:1),d/2+3,"L",d/2+(a?2:-2),d/2],g.vertical)).addClass("highcharts-scrollbar-arrow").add(e[a]);this.chart.styledMode||h.attr({fill:g.buttonArrowColor})},setRange:function(a,c){var e=this.options,g=e.vertical,d=e.minWidth,h=this.barWidth,q,v=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(A(h)){a=Math.max(a,0);var t=Math.ceil(h*a);this.calculatedWidth=q=C(h*Math.min(c,1)-t);q<
d&&(t=(h-d+q)*a,q=d);d=Math.floor(t+this.xOffset+this.yOffset);h=q/2-.5;this.from=a;this.to=c;g?(this.scrollbarGroup[v]({translateY:d}),this.scrollbar[v]({height:q}),this.scrollbarRifles[v]({translateY:h}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[v]({translateX:d}),this.scrollbar[v]({width:q}),this.scrollbarRifles[v]({translateX:h}),this.scrollbarLeft=d,this.scrollbarTop=0);12>=q?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===e.showFull&&(0>=a&&1<=c?this.group.hide():
this.group.show());this.rendered=!0}},initEvents:function(){var a=this;a.mouseMoveHandler=function(c){var e=a.chart.pointer.normalize(c),g=a.options.vertical?"chartY":"chartX",d=a.initPositions;!a.grabbedCenter||c.touches&&0===c.touches[0][g]||(e=a.cursorToScrollbarPosition(e)[g],g=a[g],g=e-g,a.hasDragged=!0,a.updatePosition(d[0]+g,d[1]+g),a.hasDragged&&y(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c}))};a.mouseUpHandler=function(c){a.hasDragged&&y(a,"changed",{from:a.from,
to:a.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(c){c=a.chart.pointer.normalize(c);c=a.cursorToScrollbarPosition(c);a.chartX=c.chartX;a.chartY=c.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(c){var e=C(a.to-a.from)*a.options.step;a.updatePosition(C(a.from-e),C(a.to-e));y(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.buttonToMaxClick=function(c){var e=
(a.to-a.from)*a.options.step;a.updatePosition(a.from+e,a.to+e);y(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.trackClick=function(c){var e=a.chart.pointer.normalize(c),g=a.to-a.from,d=a.y+a.scrollbarTop,h=a.x+a.scrollbarLeft;a.options.vertical&&e.chartY>d||!a.options.vertical&&e.chartX>h?a.updatePosition(a.from+g,a.to+g):a.updatePosition(a.from-g,a.to-g);y(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})}},cursorToScrollbarPosition:function(a){var c=this.options;
c=c.minWidth>this.calculatedWidth?c.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-c),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-c)}},updatePosition:function(a,c){1<c&&(a=C(1-C(c-a)),c=1);0>a&&(c=C(c-a),a=0);this.from=a;this.to=c},update:function(a){this.destroy();this.init(this.chart.renderer,t(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],c=this.scrollbarButtons,g=this.scrollbarGroup.element,t=this.mouseDownHandler,
d=this.mouseMoveHandler,h=this.mouseUpHandler;a=[[c[a[0]].element,"click",this.buttonToMinClick],[c[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[g,"mousedown",t],[g.ownerDocument,"mousemove",d],[g.ownerDocument,"mouseup",h]];e&&a.push([g,"touchstart",t],[g.ownerDocument,"touchmove",d],[g.ownerDocument,"touchend",h]);a.forEach(function(a){u.apply(null,a)});this._events=a},removeEvents:function(){this._events.forEach(function(a){l.apply(null,a)});this._events.length=
0},destroy:function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,D(a.scrollbarButtons))}};f.Scrollbar||(u(k,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new p(a.chart.renderer,
a.options.scrollbar,a.chart),u(a.scrollbar,"changed",function(c){var e=Math.min(E(a.options.min,a.min),a.min,a.dataMin),g=Math.max(E(a.options.max,a.max),a.max,a.dataMax)-e;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var d=e+g*this.to;e+=g*this.from}else d=e+g*(1-this.from),e+=g*(1-this.to);E(this.options.liveRedraw,f.svg&&!f.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===c.DOMType||!A(c.DOMType)?a.setExtremes(e,d,!0,"mousemove"!==c.DOMType,c):this.setRange(this.from,this.to)}))}),u(k,"afterRender",
function(){var a=Math.min(E(this.options.min,this.min),this.min,E(this.dataMin,this.min)),c=Math.max(E(this.options.max,this.max),this.max,E(this.dataMax,this.max)),e=this.scrollbar,g=this.axisTitleMargin+(this.titleOffset||0),d=this.chart.scrollbarsOffsets,h=this.options.margin||0;e&&(this.horiz?(this.opposite||(d[1]+=g),e.position(this.left,this.top+this.height+2+d[1]-(this.opposite?h:0),this.width,this.height),this.opposite||(d[1]+=h),g=1):(this.opposite&&(d[0]+=g),e.position(this.left+this.width+
2+d[0]-(this.opposite?0:h),this.top,this.width,this.height),this.opposite&&(d[0]+=h),g=0),d[g]+=e.size+e.options.margin,isNaN(a)||isNaN(c)||!A(this.min)||!A(this.max)||this.min===this.max?e.setRange(0,1):(d=(this.min-a)/(c-a),a=(this.max-a)/(c-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?e.setRange(d,a):e.setRange(1-a,1-d)))}),u(k,"afterGetOffset",function(){var a=this.horiz?2:1,c=this.scrollbar;c&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=c.size+c.options.margin)}),
f.Scrollbar=p)});H(p,"parts/Navigator.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){function p(b){this.init(b)}var C=k.clamp,A=k.correctFloat,D=k.defined,E=k.destroyObjectProperties,u=k.erase,x=k.extend,y=k.isArray,e=k.isNumber,t=k.pick,l=k.splat,m=f.addEvent,g=f.Axis;k=f.Chart;var a=f.color,c=f.defaultOptions,r=f.hasTouch,F=f.isTouchDevice,d=f.merge,h=f.removeEvent,q=f.Scrollbar,v=f.Series,G=function(b){for(var n=[],z=1;z<arguments.length;z++)n[z-1]=arguments[z];n=[].filter.call(n,
e);if(n.length)return Math[b].apply(0,n)};var w="undefined"===typeof f.seriesTypes.areaspline?"line":"areaspline";x(c,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:w,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,
smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,
labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});f.Renderer.prototype.symbols["navigator-handle"]=function(b,n,z,a,d){b=d.width/2;n=Math.round(b/3)+.5;d=d.height;return["M",-b-1,.5,"L",b,.5,"L",b,d+.5,"L",-b-1,d+.5,"L",-b-1,.5,"M",-n,4,"L",-n,d-3,"M",n-1,4,"L",n-1,d-3]};g.prototype.toFixedRange=
function(b,n,a,d){var z=this.chart&&this.chart.fixedRange,B=(this.pointRange||0)/2;b=t(a,this.translate(b,!0,!this.horiz));n=t(d,this.translate(n,!0,!this.horiz));var c=z&&(n-b)/z;D(a)||(b=A(b+B));D(d)||(n=A(n-B));.7<c&&1.3>c&&(d?b=n-z:n=b+z);e(b)&&e(n)||(b=n=void 0);return{min:b,max:n}};p.prototype={drawHandle:function(b,n,a,d){var z=this.navigatorOptions.handles.height;this.handles[n][d](a?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(b,10)+.5-z)}:{translateX:Math.round(this.left+
parseInt(b,10)),translateY:Math.round(this.top+this.height/2-z/2-1)})},drawOutline:function(b,n,a,d){var z=this.navigatorOptions.maskInside,B=this.outline.strokeWidth(),c=B/2;B=B%2/2;var e=this.outlineHeight,h=this.scrollbarHeight,g=this.size,q=this.left-h,w=this.top;a?(q-=c,a=w+n+B,n=w+b+B,b=["M",q+e,w-h-B,"L",q+e,a,"L",q,a,"L",q,n,"L",q+e,n,"L",q+e,w+g+h].concat(z?["M",q+e,a-c,"L",q+e,n+c]:[])):(b+=q+h-B,n+=q+h-B,w+=c,b=["M",q,w,"L",b,w,"L",b,w+e,"L",n,w+e,"L",n,w,"L",q+g+2*h,w].concat(z?["M",b-
c,w,"L",n+c,w]:[]));this.outline[d]({d:b})},drawMasks:function(b,n,a,d){var z=this.left,B=this.top,c=this.height;if(a){var e=[z,z,z];var h=[B,B+b,B+n];var q=[c,c,c];var g=[b,n-b,this.size-n]}else e=[z,z+b,z+n],h=[B,B,B],q=[b,n-b,this.size-n],g=[c,c,c];this.shades.forEach(function(b,n){b[d]({x:e[n],y:h[n],width:q[n],height:g[n]})})},renderElements:function(){var b=this,n=b.navigatorOptions,a=n.maskInside,d=b.chart,c=d.renderer,e,h={cursor:d.inverted?"ns-resize":"ew-resize"};b.navigatorGroup=e=c.g("navigator").attr({zIndex:8,
visibility:"hidden"}).add();[!a,a,!a].forEach(function(a,z){b.shades[z]=c.rect().addClass("highcharts-navigator-mask"+(1===z?"-inside":"-outside")).add(e);d.styledMode||b.shades[z].attr({fill:a?n.maskFill:"rgba(0,0,0,0)"}).css(1===z&&h)});b.outline=c.path().addClass("highcharts-navigator-outline").add(e);d.styledMode||b.outline.attr({"stroke-width":n.outlineWidth,stroke:n.outlineColor});n.handles.enabled&&[0,1].forEach(function(a){n.handles.inverted=d.inverted;b.handles[a]=c.symbol(n.handles.symbols[a],
-n.handles.width/2-1,0,n.handles.width,n.handles.height,n.handles);b.handles[a].attr({zIndex:7-a}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][a]).add(e);if(!d.styledMode){var z=n.handles;b.handles[a].attr({fill:z.backgroundColor,stroke:z.borderColor,"stroke-width":z.lineWidth}).css(h)}})},update:function(b){(this.series||[]).forEach(function(b){b.baseSeries&&delete b.baseSeries.navigatorSeries});this.destroy();d(!0,this.chart.options.navigator,this.options,
b);this.init(this.chart)},render:function(b,n,a,d){var z=this.chart,c=this.scrollbarHeight,B,h=this.xAxis,q=h.pointRange||0;var g=h.fake?z.xAxis[0]:h;var w=this.navigatorEnabled,v,m=this.rendered;var r=z.inverted;var f=z.xAxis[0].minRange,l=z.xAxis[0].options.maxRange;if(!this.hasDragged||D(a)){b=A(b-q/2);n=A(n+q/2);if(!e(b)||!e(n))if(m)a=0,d=t(h.width,g.width);else return;this.left=t(h.left,z.plotLeft+c+(r?z.plotWidth:0));this.size=v=B=t(h.len,(r?z.plotHeight:z.plotWidth)-2*c);z=r?c:B+2*c;a=t(a,
h.toPixels(b,!0));d=t(d,h.toPixels(n,!0));e(a)&&Infinity!==Math.abs(a)||(a=0,d=z);b=h.toValue(a,!0);n=h.toValue(d,!0);var k=Math.abs(A(n-b));k<f?this.grabbedLeft?a=h.toPixels(n-f-q,!0):this.grabbedRight&&(d=h.toPixels(b+f+q,!0)):D(l)&&A(k-q)>l&&(this.grabbedLeft?a=h.toPixels(n-l-q,!0):this.grabbedRight&&(d=h.toPixels(b+l+q,!0)));this.zoomedMax=C(Math.max(a,d),0,v);this.zoomedMin=C(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(a,d),0,v);this.range=this.zoomedMax-this.zoomedMin;v=Math.round(this.zoomedMax);
a=Math.round(this.zoomedMin);w&&(this.navigatorGroup.attr({visibility:"visible"}),m=m&&!this.hasDragged?"animate":"attr",this.drawMasks(a,v,r,m),this.drawOutline(a,v,r,m),this.navigatorOptions.handles.enabled&&(this.drawHandle(a,0,r,m),this.drawHandle(v,1,r,m)));this.scrollbar&&(r?(r=this.top-c,g=this.left-c+(w||!g.opposite?0:(g.titleOffset||0)+g.axisTitleMargin),c=B+2*c):(r=this.top+(w?this.height:-c),g=this.left-c),this.scrollbar.position(g,r,z,c),this.scrollbar.setRange(this.zoomedMin/(B||1),this.zoomedMax/
(B||1)));this.rendered=!0}},addMouseEvents:function(){var b=this,n=b.chart,a=n.container,d=[],c,e;b.mouseMoveHandler=c=function(n){b.onMouseMove(n)};b.mouseUpHandler=e=function(n){b.onMouseUp(n)};d=b.getPartsEvents("mousedown");d.push(m(n.renderTo,"mousemove",c),m(a.ownerDocument,"mouseup",e));r&&(d.push(m(n.renderTo,"touchmove",c),m(a.ownerDocument,"touchend",e)),d.concat(b.getPartsEvents("touchstart")));b.eventsToUnbind=d;b.series&&b.series[0]&&d.push(m(b.series[0].xAxis,"foundExtremes",function(){n.navigator.modifyNavigatorAxisExtremes()}))},
getPartsEvents:function(b){var n=this,a=[];["shades","handles"].forEach(function(d){n[d].forEach(function(z,c){a.push(m(z.element,b,function(b){n[d+"Mousedown"](b,c)}))})});return a},shadesMousedown:function(b,n){b=this.chart.pointer.normalize(b);var a=this.chart,d=this.xAxis,c=this.zoomedMin,e=this.left,h=this.size,q=this.range,g=b.chartX;a.inverted&&(g=b.chartY,e=this.top);if(1===n)this.grabbedCenter=g,this.fixedWidth=q,this.dragOffset=g-c;else{b=g-e-q/2;if(0===n)b=Math.max(0,b);else if(2===n&&
b+q>=h)if(b=h-q,this.reversedExtremes){b-=q;var w=this.getUnionExtremes().dataMin}else var v=this.getUnionExtremes().dataMax;b!==c&&(this.fixedWidth=q,n=d.toFixedRange(b,b+q,w,v),D(n.min)&&a.xAxis[0].setExtremes(Math.min(n.min,n.max),Math.max(n.min,n.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(b,n){this.chart.pointer.normalize(b);b=this.chart;var a=b.xAxis[0],d=this.reversedExtremes;0===n?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?a.min:a.max):
(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?a.max:a.min);b.fixedRange=null},onMouseMove:function(b){var n=this,a=n.chart,d=n.left,c=n.navigatorSize,e=n.range,h=n.dragOffset,q=a.inverted;b.touches&&0===b.touches[0].pageX||(b=a.pointer.normalize(b),a=b.chartX,q&&(d=n.top,a=b.chartY),n.grabbedLeft?(n.hasDragged=!0,n.render(0,0,a-d,n.otherHandlePos)):n.grabbedRight?(n.hasDragged=!0,n.render(0,0,n.otherHandlePos,a-d)):n.grabbedCenter&&(n.hasDragged=!0,a<h?a=h:a>c+h-e&&
(a=c+h-e),n.render(0,0,a-h,a-h+e)),n.hasDragged&&n.scrollbar&&t(n.scrollbar.options.liveRedraw,f.svg&&!F&&!this.chart.isBoosting)&&(b.DOMType=b.type,setTimeout(function(){n.onMouseUp(b)},0)))},onMouseUp:function(b){var n=this.chart,a=this.xAxis,d=this.scrollbar,c=b.DOMEvent||b;if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===b.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var e=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var h=this.fixedExtreme;
this.zoomedMax===this.size&&(h=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(e=this.reversedExtremes?d.dataMax:d.dataMin);a=a.toFixedRange(this.zoomedMin,this.zoomedMax,e,h);D(a.min)&&n.xAxis[0].setExtremes(Math.min(a.min,a.max),Math.max(a.min,a.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:c})}"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=
this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(b){b()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var b=this.baseSeries||[];this.navigatorEnabled&&b[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&b.forEach(function(b){h(b,"updatedData",this.updatedDataHandler)},this),b[0].xAxis&&h(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(b){var a=b.options,
z=a.navigator,c=z.enabled,e=a.scrollbar,h=e.enabled;a=c?z.height:0;var w=h?e.height:0;this.handles=[];this.shades=[];this.chart=b;this.setBaseSeries();this.height=a;this.scrollbarHeight=w;this.scrollbarEnabled=h;this.navigatorEnabled=c;this.navigatorOptions=z;this.scrollbarOptions=e;this.outlineHeight=a+w;this.opposite=t(z.opposite,!(c||!b.inverted));var v=this;c=v.baseSeries;e=b.xAxis.length;h=b.yAxis.length;var r=c&&c[0]&&c[0].xAxis||b.xAxis[0]||{options:{}};b.isDirtyBox=!0;v.navigatorEnabled?(v.xAxis=
new g(b,d({breaks:r.options.breaks,ordinal:r.options.ordinal},z.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},b.inverted?{offsets:[w,0,-w,0],width:a}:{offsets:[0,-w,0,w],height:a})),v.yAxis=new g(b,d(z.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,zoomEnabled:!1},b.inverted?{width:a}:{height:a})),c||z.series.data?v.updateNavigatorSeries(!1):
0===b.series.length&&(v.unbindRedraw=m(b,"beforeRedraw",function(){0<b.series.length&&!v.series&&(v.setBaseSeries(),v.unbindRedraw())})),v.reversedExtremes=b.inverted&&!v.xAxis.reversed||!b.inverted&&v.xAxis.reversed,v.renderElements(),v.addMouseEvents()):v.xAxis={translate:function(a,n){var d=b.xAxis[0],c=d.getExtremes(),z=d.len-2*w,e=G("min",d.options.min,c.dataMin);d=G("max",d.options.max,c.dataMax)-e;return n?a*d/z+e:z*(a-e)/d},toPixels:function(b){return this.translate(b)},toValue:function(b){return this.translate(b,
!0)},toFixedRange:g.prototype.toFixedRange,fake:!0};b.options.scrollbar.enabled&&(b.scrollbar=v.scrollbar=new q(b.renderer,d(b.options.scrollbar,{margin:v.navigatorEnabled?0:10,vertical:b.inverted}),b),m(v.scrollbar,"changed",function(a){var n=v.size,d=n*this.to;n*=this.from;v.hasDragged=v.scrollbar.hasDragged;v.render(0,0,n,d);(b.options.scrollbar.liveRedraw||"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType)&&setTimeout(function(){v.onMouseUp(a)})}));v.addBaseSeriesEvents();v.addChartEvents()},getUnionExtremes:function(b){var a=
this.chart.xAxis[0],d=this.xAxis,c=d.options,e=a.options,h;b&&null===a.dataMin||(h={dataMin:t(c&&c.min,G("min",e.min,a.dataMin,d.dataMin,d.min)),dataMax:t(c&&c.max,G("max",e.max,a.dataMax,d.dataMax,d.max))});return h},setBaseSeries:function(b,a){var d=this.chart,n=this.baseSeries=[];b=b||d.options&&d.options.navigator.baseSeries||(d.series.length?f.find(d.series,function(b){return!b.options.isInternal}).index:0);(d.series||[]).forEach(function(a,d){a.options.isInternal||!a.options.showInNavigator&&
(d!==b&&a.options.id!==b||!1===a.options.showInNavigator)||n.push(a)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,a)},updateNavigatorSeries:function(b,a){var n=this,e=n.chart,q=n.baseSeries,g,w,v=n.navigatorOptions.series,r,m={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},f=n.series=(n.series||[]).filter(function(b){var a=b.baseSeries;
return 0>q.indexOf(a)?(a&&(h(a,"updatedData",n.updatedDataHandler),delete a.navigatorSeries),b.chart&&b.destroy(),!1):!0});q&&q.length&&q.forEach(function(b){var z=b.navigatorSeries,h=x({color:b.color,visible:b.visible},y(v)?c.navigator.series:v);z&&!1===n.navigatorOptions.adaptToUpdatedData||(m.name="Navigator "+q.length,g=b.options||{},r=g.navigatorOptions||{},w=d(g,m,h,r),w.pointRange=t(h.pointRange,r.pointRange,c.plotOptions[w.type||"line"].pointRange),h=r.data||h.data,n.hasNavigatorData=n.hasNavigatorData||
!!h,w.data=h||g.data&&g.data.slice(0),z&&z.options?z.update(w,a):(b.navigatorSeries=e.initSeries(w),b.navigatorSeries.baseSeries=b,f.push(b.navigatorSeries)))});if(v.data&&(!q||!q.length)||y(v))n.hasNavigatorData=!1,v=l(v),v.forEach(function(b,a){m.name="Navigator "+(f.length+1);w=d(c.navigator.series,{color:e.series[a]&&!e.series[a].options.isInternal&&e.series[a].color||e.options.colors[a]||e.options.colors[0]},m,b);w.data=b.data;w.data&&(n.hasNavigatorData=!0,f.push(e.initSeries(w)))});b&&this.addBaseSeriesEvents()},
addBaseSeriesEvents:function(){var b=this,a=b.baseSeries||[];a[0]&&a[0].xAxis&&m(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);a.forEach(function(a){m(a,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});m(a,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&a.xAxis&&m(a,"updatedData",this.updatedDataHandler);m(a,"remove",function(){this.navigatorSeries&&(u(b.series,this.navigatorSeries),
D(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(b){return this.baseSeries.reduce(function(b,a){return Math.min(b,a.xData?a.xData[0]:b)},b)},modifyNavigatorAxisExtremes:function(){var b=this.xAxis,a;"undefined"!==typeof b.getExtremes&&(!(a=this.getUnionExtremes(!0))||a.dataMin===b.min&&a.dataMax===b.max||(b.min=a.dataMin,b.max=a.dataMax))},modifyBaseAxisExtremes:function(){var b=this.chart.navigator,a=this.getExtremes(),
d=a.dataMin,c=a.dataMax;a=a.max-a.min;var h=b.stickToMin,q=b.stickToMax,g=t(this.options.overscroll,0),w=b.series&&b.series[0],v=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(h){var r=d;var m=r+a}q&&(m=c+g,h||(r=Math.max(m-a,b.getBaseSeriesMin(w&&w.xData?w.xData[0]:-Number.MAX_VALUE))));v&&(h||q)&&e(r)&&(this.min=this.userMin=r,this.max=this.userMax=m)}b.stickToMin=b.stickToMax=null},updatedDataHandler:function(){var b=this.chart.navigator,a=this.navigatorSeries,
d=b.getBaseSeriesMin(this.xData[0]);b.stickToMax=b.reversedExtremes?0===Math.round(b.zoomedMin):Math.round(b.zoomedMax)>=Math.round(b.size);b.stickToMin=e(this.xAxis.min)&&this.xAxis.min<=d&&(!this.chart.fixedRange||!b.stickToMax);a&&!b.hasNavigatorData&&(a.options.pointStart=this.xData[0],a.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(m(this.chart,"redraw",function(){var b=this.navigator,a=b&&(b.baseSeries&&
b.baseSeries[0]&&b.baseSeries[0].xAxis||b.scrollbar&&this.xAxis[0]);a&&b.render(a.min,a.max)}),m(this.chart,"getMargins",function(){var b=this.navigator,a=b.opposite?"plotTop":"marginBottom";this.inverted&&(a=b.opposite?"marginRight":"plotLeft");this[a]=(this[a]||0)+(b.navigatorEnabled||!this.inverted?b.outlineHeight:0)+b.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(u(this.chart.xAxis,this.xAxis),u(this.chart.axes,this.xAxis));this.yAxis&&(u(this.chart.yAxis,this.yAxis),
u(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(b){b.destroy&&b.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(b){this[b]&&this[b].destroy&&this[b].destroy();this[b]=null},this);[this.handles].forEach(function(b){E(b)},this)}};f.Navigator||(f.Navigator=p,m(g,"zoom",function(b){var a=this.chart.options,d=a.chart.zoomType,c=a.chart.pinchType,e=a.navigator;a=a.rangeSelector;
this.isXAxis&&(e&&e.enabled||a&&a.enabled)&&("y"===d?b.zoomed=!1:(!F&&"xy"===d||F&&"xy"===c)&&this.options.range&&(d=this.previousZoom,D(b.newMin)?this.previousZoom=[this.min,this.max]:d&&(b.newMin=d[0],b.newMax=d[1],delete this.previousZoom)));"undefined"!==typeof b.zoomed&&b.preventDefault()}),m(k,"beforeShowResetZoom",function(){var b=this.options,a=b.navigator,d=b.rangeSelector;if((a&&a.enabled||d&&d.enabled)&&(!F&&"x"===b.chart.zoomType||F&&"x"===b.chart.pinchType))return!1}),m(k,"beforeRender",
function(){var b=this.options;if(b.navigator.enabled||b.scrollbar.enabled)this.scroller=this.navigator=new p(this)}),m(k,"afterSetChartSize",function(){var b=this.legend,a=this.navigator;if(a){var d=b&&b.options;var c=a.xAxis;var e=a.yAxis;var h=a.scrollbarHeight;this.inverted?(a.left=a.opposite?this.chartWidth-h-a.height:this.spacing[3]+h,a.top=this.plotTop+h):(a.left=this.plotLeft+h,a.top=a.navigatorOptions.top||this.chartHeight-a.height-h-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?
this.rangeSelector.getHeight():0)-(d&&"bottom"===d.verticalAlign&&d.enabled&&!d.floating?b.legendHeight+t(d.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));c&&e&&(this.inverted?c.options.left=e.options.left=a.left:c.options.top=e.options.top=a.top,c.setAxisSize(),e.setAxisSize())}}),m(k,"update",function(b){var a=b.options.navigator||{},c=b.options.scrollbar||{};this.navigator||this.scroller||!a.enabled&&!c.enabled||(d(!0,this.options.navigator,a),d(!0,this.options.scrollbar,c),delete b.options.navigator,
delete b.options.scrollbar)}),m(k,"afterUpdate",function(b){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new p(this),t(b.redraw,!0)&&this.redraw(b.animation))}),m(k,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),m(v,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),k.prototype.callbacks.push(function(b){var a=b.navigator;
a&&b.xAxis[0]&&(b=b.xAxis[0].getExtremes(),a.render(b.min,b.max))}))});H(p,"parts/OrdinalAxis.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){var p=k.defined,C=k.extend,A=k.pick;k=f.addEvent;var D=f.Axis,E=f.Chart,u=f.css,x=f.noop,y=f.timeUnits;k(f.Series,"updatedData",function(){var e=this.xAxis;e&&e.options.ordinal&&delete e.ordinalIndex});D.prototype.getTimeTicks=function(e,t,f,m,g,a,c){var r=0,l,d,h={},q=[],v=-Number.MAX_VALUE,k=this.options.tickPixelInterval,w=this.chart.time,
b=[];if(!this.options.ordinal&&!this.options.breaks||!g||3>g.length||"undefined"===typeof t)return w.getTimeTicks.apply(w,arguments);var n=g.length;for(l=0;l<n;l++){var z=l&&g[l-1]>f;g[l]<t&&(r=l);if(l===n-1||g[l+1]-g[l]>5*a||z){if(g[l]>v){for(d=w.getTimeTicks(e,g[r],g[l],m);d.length&&d[0]<=v;)d.shift();d.length&&(v=d[d.length-1]);b.push(q.length);q=q.concat(d)}r=l+1}if(z)break}d=d.info;if(c&&d.unitRange<=y.hour){l=q.length-1;for(r=1;r<l;r++)if(w.dateFormat("%d",q[r])!==w.dateFormat("%d",q[r-1])){h[q[r]]=
"day";var B=!0}B&&(h[q[0]]="day");d.higherRanks=h}d.segmentStarts=b;q.info=d;if(c&&p(k)){r=b=q.length;B=[];var I;for(w=[];r--;)l=this.translate(q[r]),I&&(w[r]=I-l),B[r]=I=l;w.sort();w=w[Math.floor(w.length/2)];w<.6*k&&(w=null);r=q[b-1]>f?b-1:b;for(I=void 0;r--;)l=B[r],b=Math.abs(I-l),I&&b<.8*k&&(null===w||b<.8*w)?(h[q[r]]&&!h[q[r+1]]?(b=r+1,I=l):b=r,q.splice(b,1)):I=l}return q};C(D.prototype,{beforeSetTickPositions:function(){var e=[],t,l=!1,m=this.getExtremes(),g=m.min,a=m.max,c,r=this.isXAxis&&
!!this.options.breaks;m=this.options.ordinal;var f=Number.MAX_VALUE,d=this.chart.options.chart.ignoreHiddenSeries,h;if(m||r){this.series.forEach(function(a,c){t=[];if(!(d&&!1===a.visible||!1===a.takeOrdinalPosition&&!r)&&(e=e.concat(a.processedXData),q=e.length,e.sort(function(b,a){return b-a}),f=Math.min(f,A(a.closestPointRange,f)),q)){for(c=0;c<q-1;)e[c]!==e[c+1]&&t.push(e[c+1]),c++;t[0]!==e[0]&&t.unshift(e[0]);e=t}a.isSeriesBoosting&&(h=!0)});h&&(e.length=0);var q=e.length;if(2<q){var v=e[1]-e[0];
for(c=q-1;c--&&!l;)e[c+1]-e[c]!==v&&(l=!0);!this.options.keepOrdinalPadding&&(e[0]-g>v||a-e[e.length-1]>v)&&(l=!0)}else this.options.overscroll&&(2===q?f=e[1]-e[0]:1===q?(f=this.options.overscroll,e=[e[0],e[0]+f]):f=this.overscrollPointsRange);l?(this.options.overscroll&&(this.overscrollPointsRange=f,e=e.concat(this.getOverscrollPositions())),this.ordinalPositions=e,v=this.ordinal2lin(Math.max(g,e[0]),!0),c=Math.max(this.ordinal2lin(Math.min(a,e[e.length-1]),!0),1),this.ordinalSlope=a=(a-g)/(c-v),
this.ordinalOffset=g-v*a):(this.overscrollPointsRange=A(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=m&&l;this.groupIntervalFactor=null},val2lin:function(e,t){var l=this.ordinalPositions;if(l){var m=l.length,g;for(g=m;g--;)if(l[g]===e){var a=g;break}for(g=m-1;g--;)if(e>l[g]||0===g){e=(e-l[g])/(l[g+1]-l[g]);a=g+e;break}t=t?a:this.ordinalSlope*(a||0)+this.ordinalOffset}else t=e;return t},lin2val:function(e,t){var l=
this.ordinalPositions;if(l){var m=this.ordinalSlope,g=this.ordinalOffset,a=l.length-1;if(t)if(0>e)e=l[0];else if(e>a)e=l[a];else{a=Math.floor(e);var c=e-a}else for(;a--;)if(t=m*a+g,e>=t){m=m*(a+1)+g;c=(e-t)/(m-t);break}return"undefined"!==typeof c&&"undefined"!==typeof l[a]?l[a]+(c?c*(l[a+1]-l[a]):0):e}return e},getExtendedPositions:function(){var e=this,t=e.chart,l=e.series[0].currentDataGrouping,m=e.ordinalIndex,g=l?l.count+l.unitName:"raw",a=e.options.overscroll,c=e.getExtremes(),r;m||(m=e.ordinalIndex=
{});if(!m[g]){var f={series:[],chart:t,getExtremes:function(){return{min:c.dataMin,max:c.dataMax+a}},options:{ordinal:!0},val2lin:D.prototype.val2lin,ordinal2lin:D.prototype.ordinal2lin};e.series.forEach(function(a){r={xAxis:f,xData:a.xData.slice(),chart:t,destroyGroupedData:x};r.xData=r.xData.concat(e.getOverscrollPositions());r.options={dataGrouping:l?{enabled:!0,forced:!0,approximation:"open",units:[[l.unitName,[l.count]]]}:{enabled:!1}};a.processData.apply(r);f.series.push(r)});e.beforeSetTickPositions.apply(f);
m[g]=f.ordinalPositions}return m[g]},getOverscrollPositions:function(){var e=this.options.overscroll,f=this.overscrollPointsRange,l=[],m=this.dataMax;if(p(f))for(l.push(m);m<=this.dataMax+e;)m+=f,l.push(m);return l},getGroupIntervalFactor:function(e,f,l){l=l.processedXData;var m=l.length,g=[];var a=this.groupIntervalFactor;if(!a){for(a=0;a<m-1;a++)g[a]=l[a+1]-l[a];g.sort(function(a,e){return a-e});g=g[Math.floor(m/2)];e=Math.max(e,l[0]);f=Math.min(f,l[m-1]);this.groupIntervalFactor=a=m*g/(f-e)}return a},
postProcessTickInterval:function(e){var f=this.ordinalSlope;return f?this.options.breaks?this.closestPointRange||e:e/(f/this.closestPointRange):e}});D.prototype.ordinal2lin=D.prototype.val2lin;k(E,"pan",function(e){var f=this.xAxis[0],l=f.options.overscroll,m=e.originalEvent.chartX,g=!1;if(f.options.ordinal&&f.series.length){var a=this.mouseDownX,c=f.getExtremes(),r=c.dataMax,k=c.min,d=c.max,h=this.hoverPoints,q=f.closestPointRange||f.overscrollPointsRange;a=(a-m)/(f.translationSlope*(f.ordinalSlope||
q));var v={ordinalPositions:f.getExtendedPositions()};q=f.lin2val;var G=f.val2lin;if(!v.ordinalPositions)g=!0;else if(1<Math.abs(a)){h&&h.forEach(function(b){b.setState()});if(0>a){h=v;var w=f.ordinalPositions?f:v}else h=f.ordinalPositions?f:v,w=v;v=w.ordinalPositions;r>v[v.length-1]&&v.push(r);this.fixedRange=d-k;a=f.toFixedRange(null,null,q.apply(h,[G.apply(h,[k,!0])+a,!0]),q.apply(w,[G.apply(w,[d,!0])+a,!0]));a.min>=Math.min(c.dataMin,k)&&a.max<=Math.max(r,d)+l&&f.setExtremes(a.min,a.max,!0,!1,
{trigger:"pan"});this.mouseDownX=m;u(this.container,{cursor:"move"})}}else g=!0;g?l&&(f.max=f.dataMax+l):e.preventDefault()});k(D,"foundExtremes",function(){this.isXAxis&&p(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&p(this.userMin)&&(this.min+=this.options.overscroll))});k(D,"afterSetScale",function(){this.horiz&&!this.isDirty&&
(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)})});H(p,"modules/broken-axis.src.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){var p=k.extend,C=k.isArray,A=k.pick;k=f.addEvent;var D=f.find,E=f.fireEvent,u=f.Axis,x=f.Series,y=function(e,f){return D(f,function(f){return f.from<e&&e<f.to})};p(u.prototype,{isInBreak:function(e,f){var l=e.repeat||Infinity,m=e.from,g=e.to-e.from;f=f>=m?(f-m)%l:l-(m-f)%l;return e.inclusive?f<=g:f<g&&0!==f},
isInAnyBreak:function(e,f){var l=this.options.breaks,m=l&&l.length,g;if(m){for(;m--;)if(this.isInBreak(l[m],e)){var a=!0;g||(g=A(l[m].showPoints,!this.isXAxis))}var c=a&&f?a&&!g:a}return c}});k(u,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});k(u,"afterSetTickPositions",function(){if(this.isBroken){var e=this.tickPositions,f=this.tickPositions.info,l=[],m;for(m=0;m<e.length;m++)this.isInAnyBreak(e[m])||l.push(e[m]);this.tickPositions=l;this.tickPositions.info=
f}});k(u,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});u.prototype.setBreaks=function(e,f){function l(a){var c=a,e;for(e=0;e<g.breakArray.length;e++){var d=g.breakArray[e];if(d.to<=a)c-=d.len;else if(d.from>=a)break;else if(g.isInBreak(d,a)){c-=a-d.from;break}}return c}function m(a){var c;for(c=0;c<g.breakArray.length;c++){var e=g.breakArray[c];if(e.from>=a)break;else e.to<a?a+=e.len:g.isInBreak(e,a)&&(a+=e.len)}return a}var g=this,a=C(e)&&!!e.length;g.isDirty=g.isBroken!==
a;g.isBroken=a;g.options.breaks=g.userOptions.breaks=e;g.forceRedraw=!0;a||g.val2lin!==l||(delete g.val2lin,delete g.lin2val);a&&(g.userOptions.ordinal=!1,g.val2lin=l,g.lin2val=m,g.setExtremes=function(a,e,g,d,h){if(this.isBroken){for(var c,f=this.options.breaks;c=y(a,f);)a=c.to;for(;c=y(e,f);)e=c.from;e<a&&(e=a)}u.prototype.setExtremes.call(this,a,e,g,d,h)},g.setAxisTranslation=function(a){u.prototype.setAxisTranslation.call(this,a);this.unitLength=null;if(this.isBroken){a=g.options.breaks;var c=
[],e=[],d=0,h,q=g.userMin||g.min,f=g.userMax||g.max,l=A(g.pointRangePadding,0),w;a.forEach(function(a){h=a.repeat||Infinity;g.isInBreak(a,q)&&(q+=a.to%h-q%h);g.isInBreak(a,f)&&(f-=f%h-a.from%h)});a.forEach(function(a){n=a.from;for(h=a.repeat||Infinity;n-h>q;)n-=h;for(;n<q;)n+=h;for(w=n;w<f;w+=h)c.push({value:w,move:"in"}),c.push({value:w+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var b=0;var n=
q;c.forEach(function(a){b+="in"===a.move?1:-1;1===b&&"in"===a.move&&(n=a.value);0===b&&(e.push({from:n,to:a.value,len:a.value-n-(a.size||0)}),d+=a.value-n-(a.size||0))});g.breakArray=e;g.unitLength=f-q-d+l;E(g,"afterBreaks");g.staticScale?g.transA=g.staticScale:g.unitLength&&(g.transA*=(f-g.min+l)/g.unitLength);l&&(g.minPixelPadding=g.transA*g.minPointOffset);g.min=q;g.max=f}});A(f,!0)&&this.chart.redraw()};k(x,"afterGeneratePoints",function(){var e=this.xAxis,f=this.yAxis,l=this.points,m=l.length,
g=this.options.connectNulls;if(e&&f&&(e.options.breaks||f.options.breaks))for(;m--;){var a=l[m];var c=null===a.y&&!1===g;c||!e.isInAnyBreak(a.x,!0)&&!f.isInAnyBreak(a.y,!0)||(l.splice(m,1),this.data[m]&&this.data[m].destroyElements())}});k(x,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))});f.Series.prototype.drawBreaks=function(e,f){var l=this,m=l.points,g,a,c,r;e&&f.forEach(function(f){g=e.breakArray||[];a=e.isXAxis?e.min:A(l.options.threshold,
e.min);m.forEach(function(d){r=A(d["stack"+f.toUpperCase()],d[f]);g.forEach(function(h){c=!1;if(a<h.from&&r>h.to||a>h.from&&r<h.from)c="pointBreak";else if(a<h.from&&r>h.from&&r<h.to||a>h.from&&r>h.to&&r<h.from)c="pointInBreak";c&&E(e,c,{point:d,brk:h})})})})};f.Series.prototype.gappedPath=function(){var e=this.currentDataGrouping,k=e&&e.gapSize;e=this.options.gapSize;var l=this.points.slice(),m=l.length-1,g=this.yAxis;if(e&&0<m)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),k&&k>e&&
k>=this.basePointRange&&(e=k);m--;)l[m+1].x-l[m].x>e&&(k=(l[m].x+l[m+1].x)/2,l.splice(m+1,0,{isNull:!0,x:k}),this.options.stacking&&(k=g.stacks[this.stackKey][k]=new f.StackItem(g,g.options.stackLabels,!1,k,this.stack),k.total=0));return this.getGraphPath(l)}});H(p,"masters/modules/broken-axis.src.js",[],function(){});H(p,"parts/DataGrouping.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){var p=k.arrayMax,C=k.arrayMin,A=k.correctFloat,D=k.defined,E=k.extend,u=k.isNumber,x=k.pick;
k=f.addEvent;var y=f.Axis,e=f.defaultPlotOptions,t=f.format,l=f.merge,m=f.Point,g=f.Series,a=f.Tooltip,c=f.approximations={sum:function(a){var b=a.length;if(!b&&a.hasNulls)var d=null;else if(b)for(d=0;b--;)d+=a[b];return d},average:function(a){var b=a.length;a=c.sum(a);u(a)&&b&&(a=A(a/b));return a},averages:function(){var a=[];[].forEach.call(arguments,function(b){a.push(c.average(b))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?
p(a):a.hasNulls?null:void 0},low:function(a){return a.length?C(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,d,e,h){a=c.open(a);d=c.high(d);e=c.low(e);h=c.close(h);if(u(a)||u(d)||u(e)||u(h))return[a,d,e,h]},range:function(a,d){a=c.low(a);d=c.high(d);if(u(a)||u(d))return[a,d];if(null===a&&null===d)return null}},r=function(a,d,e,h){var b=this,n=b.data,q=b.options&&b.options.data,g=[],f=[],w=[],v=a.length,z=!!d,B=[],m=b.pointArrayMap,
k=m&&m.length,r=["x"].concat(m||["y"]),G=0,t=0,y;h="function"===typeof h?h:c[h]?c[h]:c[b.getDGApproximation&&b.getDGApproximation()||"average"];k?m.forEach(function(){B.push([])}):B.push([]);var p=k||1;for(y=0;y<=v&&!(a[y]>=e[0]);y++);for(y;y<=v;y++){for(;"undefined"!==typeof e[G+1]&&a[y]>=e[G+1]||y===v;){var x=e[G];b.dataGroupInfo={start:b.cropStart+t,length:B[0].length};var E=h.apply(b,B);b.pointClass&&!D(b.dataGroupInfo.options)&&(b.dataGroupInfo.options=l(b.pointClass.prototype.optionsToObject.call({series:b},
b.options.data[b.cropStart+t])),r.forEach(function(a){delete b.dataGroupInfo.options[a]}));"undefined"!==typeof E&&(g.push(x),f.push(E),w.push(b.dataGroupInfo));t=y;for(x=0;x<p;x++)B[x].length=0,B[x].hasNulls=!1;G+=1;if(y===v)break}if(y===v)break;if(m)for(x=b.cropStart+y,E=n&&n[x]||b.pointClass.prototype.applyOptions.apply({series:b},[q[x]]),x=0;x<k;x++){var A=E[m[x]];u(A)?B[x].push(A):null===A&&(B[x].hasNulls=!0)}else x=z?d[y]:null,u(x)?B[0].push(x):null===x&&(B[0].hasNulls=!0)}return{groupedXData:g,
groupedYData:f,groupMap:w}},F={approximations:c,groupData:r},d=g.prototype,h=d.processData,q=d.generatePoints,v={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e",
"-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},G={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},w=f.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];d.getDGApproximation=function(){return f.seriesTypes.arearange&&
this instanceof f.seriesTypes.arearange?"range":f.seriesTypes.ohlc&&this instanceof f.seriesTypes.ohlc?"ohlc":f.seriesTypes.column&&this instanceof f.seriesTypes.column?"sum":"average"};d.groupData=r;d.processData=function(){var a=this.chart,e=this.options.dataGrouping,c=!1!==this.allowDG&&e&&x(e.enabled,a.options.isStock),q=this.visible||!a.options.chart.ignoreHiddenSeries,g,f=this.currentDataGrouping,v=!1;this.forceCrop=c;this.groupPixelWidth=null;this.hasProcessed=!0;c&&!this.requireSorting&&(this.requireSorting=
v=!0);c=!1===h.apply(this,arguments)||!c;v&&(this.requireSorting=!1);if(!c){this.destroyGroupedData();c=e.groupAll?this.xData:this.processedXData;var m=e.groupAll?this.yData:this.processedYData,l=a.plotSizeX;a=this.xAxis;var k=a.options.ordinal,r=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(r){this.isDirty=g=!0;this.points=null;v=a.getExtremes();var G=v.min;v=v.max;k=k&&a.getGroupIntervalFactor(G,v,this)||1;r=r*(v-G)/l*k;l=a.getTimeTicks(a.normalizeTimeTickInterval(r,e.units||
w),Math.min(G,c[0]),Math.max(v,c[c.length-1]),a.options.startOfWeek,c,this.closestPointRange);m=d.groupData.apply(this,[c,m,l,e.approximation]);c=m.groupedXData;k=m.groupedYData;var u=0;if(e.smoothed&&c.length){var t=c.length-1;for(c[t]=Math.min(c[t],v);t--&&0<t;)c[t]+=r/2;c[0]=Math.max(c[0],G)}for(t=1;t<l.length;t++)l.info.segmentStarts&&-1!==l.info.segmentStarts.indexOf(t)||(u=Math.max(l[t]-l[t-1],u));G=l.info;G.gapSize=u;this.closestPointRange=l.info.totalRange;this.groupMap=m.groupMap;if(D(c[0])&&
c[0]<a.min&&q){if(!D(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(c[0],a.min);a.dataMin=c[0]}e.groupAll&&(e=this.cropData(c,k,a.min,a.max,1),c=e.xData,k=e.yData);this.processedXData=c;this.processedYData=k}else this.groupMap=null;this.hasGroupedData=g;this.currentDataGrouping=G;this.preventGraphAnimation=(f&&f.totalRange)!==(G&&G.totalRange)}};d.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,d){a&&(this.groupedData[d]=a.destroy?a.destroy():
null)},this),this.groupedData.length=0)};d.generatePoints=function(){q.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};k(m,"update",function(){if(this.dataGroup)return f.error(24,!1,this.series.chart),!1});k(a,"headerFormatter",function(a){var b=this.chart,d=b.time,c=a.labelConfig,e=c.series,h=e.tooltipOptions,q=e.options.dataGrouping,g=h.xDateFormat,f=e.xAxis,w=h[(a.isFooter?"footer":"header")+"Format"];if(f&&"datetime"===f.options.type&&q&&u(c.key)){var l=
e.currentDataGrouping;q=q.dateTimeLabelFormats||v.dateTimeLabelFormats;if(l)if(h=q[l.unitName],1===l.count)g=h[0];else{g=h[1];var m=h[2]}else!g&&q&&(g=this.getXDateFormat(c,h,f));g=d.dateFormat(g,c.key);m&&(g+=d.dateFormat(m,c.key+l.totalRange-1));e.chart.styledMode&&(w=this.styledModeFormat(w));a.text=t(w,{point:E(c.point,{key:g}),series:e},b);a.preventDefault()}});k(g,"destroy",d.destroyGroupedData);k(g,"afterSetOptions",function(a){a=a.options;var b=this.type,d=this.chart.options.plotOptions,c=
e[b].dataGrouping,h=this.useCommonDataGrouping&&v;if(G[b]||h)c||(c=l(v,G[b])),a.dataGrouping=l(h,c,d.series&&d.series.dataGrouping,d[b].dataGrouping,this.userOptions.dataGrouping)});k(y,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});y.prototype.getGroupPixelWidth=function(){var a=this.series,d=a.length,c,e=0,h=!1,q;for(c=d;c--;)(q=a[c].options.dataGrouping)&&(e=Math.max(e,x(q.groupPixelWidth,v.groupPixelWidth)));for(c=d;c--;)(q=a[c].options.dataGrouping)&&a[c].hasProcessed&&
(d=(a[c].processedXData||a[c].data).length,a[c].groupPixelWidth||d>this.chart.plotSizeX/e||d&&q.forced)&&(h=!0);return h?e:0};y.prototype.setDataGrouping=function(a,d){var b;d=x(d,!0);a||(a={forced:!1,units:null});if(this instanceof y)for(b=this.series.length;b--;)this.series[b].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(b){b.dataGrouping=a},!1);this.ordinalSlope=null;d&&this.chart.redraw()};f.dataGrouping=F;"";return F});H(p,"parts/OHLCSeries.js",[p["parts/Globals.js"]],
function(f){var k=f.Point,p=f.seriesType,C=f.seriesTypes;p("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(f){return[f.open,f.high,f.low,f.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color",
"stroke-width":"lineWidth"},init:function(){C.column.prototype.init.apply(this,arguments);this.options.stacking=!1},pointAttribs:function(f,k){k=C.column.prototype.pointAttribs.call(this,f,k);var p=this.options;delete k.fill;!f.options.color&&p.upColor&&f.open<f.close&&(k.stroke=p.upColor);return k},translate:function(){var f=this,k=f.yAxis,p=!!f.modifyValue,u=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];C.column.prototype.translate.apply(f);f.points.forEach(function(x){[x.open,x.high,
x.low,x.close,x.low].forEach(function(y,e){null!==y&&(p&&(y=f.modifyValue(y)),x[u[e]]=k.toPixels(y,!0))});x.tooltipPos[1]=x.plotHigh+k.pos-f.chart.plotTop})},drawPoints:function(){var f=this,k=f.chart;f.points.forEach(function(p){var u=p.graphic,x=!u;if("undefined"!==typeof p.plotY){u||(p.graphic=u=k.renderer.path().add(f.group));k.styledMode||u.attr(f.pointAttribs(p,p.selected&&"select"));var y=u.strokeWidth()%2/2;var e=Math.round(p.plotX)-y;var t=Math.round(p.shapeArgs.width/2);var l=["M",e,Math.round(p.yBottom),
"L",e,Math.round(p.plotHigh)];if(null!==p.open){var m=Math.round(p.plotOpen)+y;l.push("M",e,m,"L",e-t,m)}null!==p.close&&(m=Math.round(p.plotClose)+y,l.push("M",e,m,"L",e+t,m));u[x?"attr":"animate"]({d:l}).addClass(p.getClassName(),!0)}})},animate:null},{getClassName:function(){return k.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});H(p,"parts/CandlestickSeries.js",[p["parts/Globals.js"]],function(f){var k=f.defaultPlotOptions,p=f.merge,
C=f.seriesType,A=f.seriesTypes;C("candlestick","ohlc",p(k.column,{states:{hover:{lineWidth:2}},tooltip:k.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(f,k){var u=A.column.prototype.pointAttribs.call(this,f,k),p=this.options,y=f.open<f.close,e=p.lineColor||this.color;u["stroke-width"]=p.lineWidth;u.fill=f.options.color||(y?p.upColor||this.color:this.color);u.stroke=f.options.lineColor||(y?p.upLineColor||e:e);k&&(f=p.states[k],
u.fill=f.color||u.fill,u.stroke=f.lineColor||u.stroke,u["stroke-width"]=f.lineWidth||u["stroke-width"]);return u},drawPoints:function(){var f=this,k=f.chart,p=f.yAxis.reversed;f.points.forEach(function(u){var y=u.graphic,e=!y;if("undefined"!==typeof u.plotY){y||(u.graphic=y=k.renderer.path().add(f.group));f.chart.styledMode||y.attr(f.pointAttribs(u,u.selected&&"select")).shadow(f.options.shadow);var t=y.strokeWidth()%2/2;var l=Math.round(u.plotX)-t;var m=u.plotOpen;var g=u.plotClose;var a=Math.min(m,
g);m=Math.max(m,g);var c=Math.round(u.shapeArgs.width/2);g=p?m!==u.yBottom:Math.round(a)!==Math.round(u.plotHigh);var r=p?Math.round(a)!==Math.round(u.plotHigh):m!==u.yBottom;a=Math.round(a)+t;m=Math.round(m)+t;t=[];t.push("M",l-c,m,"L",l-c,a,"L",l+c,a,"L",l+c,m,"Z","M",l,a,"L",l,g?Math.round(p?u.yBottom:u.plotHigh):a,"M",l,m,"L",l,r?Math.round(p?u.plotHigh:u.yBottom):m);y[e?"attr":"animate"]({d:t}).addClass(u.getClassName(),!0)}})}});""});H(p,"mixins/on-series.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],
function(f,k){var p=k.defined,C=f.seriesTypes,A=f.stableSort;return{getPlotBox:function(){return f.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){C.column.prototype.translate.apply(this);var f=this,k=f.options,u=f.chart,x=f.points,y=x.length-1,e,t=k.onSeries;t=t&&u.get(t);k=k.onKey||"y";var l=t&&t.options.step,m=t&&t.points,g=m&&m.length,a=u.inverted,c=f.xAxis,r=f.yAxis,F=0,d;if(t&&t.visible&&g){F=(t.pointXOffset||0)+(t.barW||
0)/2;u=t.currentDataGrouping;var h=m[g-1].x+(u?u.totalRange:0);A(x,function(a,d){return a.x-d.x});for(k="plot"+k[0].toUpperCase()+k.substr(1);g--&&x[y];){var q=m[g];u=x[y];u.y=q.y;if(q.x<=u.x&&"undefined"!==typeof q[k]){if(u.x<=h&&(u.plotY=q[k],q.x<u.x&&!l&&(d=m[g+1])&&"undefined"!==typeof d[k])){var v=(u.x-q.x)/(d.x-q.x);u.plotY+=v*(d[k]-q[k]);u.y+=v*(d.y-q.y)}y--;g++;if(0>y)break}}}x.forEach(function(d,h){d.plotX+=F;if("undefined"===typeof d.plotY||a)0<=d.plotX&&d.plotX<=c.len?a?(d.plotY=c.translate(d.x,
0,1,0,1),d.plotX=p(d.y)?r.translate(d.y,0,0,0,1):0):d.plotY=(c.opposite?0:f.yAxis.len)+c.offset:d.shapeArgs={};if((e=x[h-1])&&e.plotX===d.plotX){"undefined"===typeof e.stackIndex&&(e.stackIndex=0);var b=e.stackIndex+1}d.stackIndex=b});this.onSeries=t}}});H(p,"parts/FlagsSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["mixins/on-series.js"]],function(f,k,p){function C(a){g[a+"pin"]=function(c,e,f,d,h){var q=h&&h.anchorX;h=h&&h.anchorY;"circle"===a&&d>f&&(c-=Math.round((d-f)/2),f=d);var v=
g[a](c,e,f,d);q&&h&&(v.push("M","circle"===a?c+f/2:v[1]+v[4]/2,e>h?e:e+d,"L",q,h),v=v.concat(g.circle(q-1,h-1,2,2)));return v}}var A=k.defined,D=k.isNumber,E=k.objectEach,u=f.addEvent,x=f.merge;k=f.noop;var y=f.Renderer,e=f.Series,t=f.seriesType,l=f.TrackerMixin,m=f.VMLRenderer,g=f.SVGRenderer.prototype.symbols;t("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,
states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:e.prototype.init,pointAttribs:function(a,c){var e=this.options,f=a&&a.color||this.color,d=e.lineColor,h=a&&a.lineWidth;a=a&&a.fillColor||e.fillColor;c&&(a=e.states[c].fillColor,d=e.states[c].lineColor,h=e.states[c].lineWidth);return{fill:a||f,stroke:d||f,"stroke-width":h||e.lineWidth||0}},
translate:p.translate,getPlotBox:p.getPlotBox,drawPoints:function(){var a=this.points,c=this.chart,e=c.renderer,g=c.inverted,d=this.options,h=d.y,q,v=this.yAxis,k={},w=[];for(q=a.length;q--;){var b=a[q];var n=(g?b.plotY:b.plotX)>this.xAxis.len;var l=b.plotX;var m=b.stackIndex;var u=b.options.shape||d.shape;var p=b.plotY;"undefined"!==typeof p&&(p=b.plotY+h-("undefined"!==typeof m&&m*d.stackDistance));b.anchorX=m?void 0:b.plotX;var t=m?void 0:b.plotY;var y="flag"!==u;m=b.graphic;"undefined"!==typeof p&&
0<=l&&!n?(m||(m=b.graphic=e.label("",null,null,u,null,null,d.useHTML),c.styledMode||m.attr(this.pointAttribs(b)).css(x(d.style,b.style)),m.attr({align:y?"center":"left",width:d.width,height:d.height,"text-align":d.textAlign}).addClass("highcharts-point").add(this.markerGroup),b.graphic.div&&(b.graphic.div.point=b),c.styledMode||m.shadow(d.shadow),m.isNew=!0),0<l&&(l-=m.strokeWidth()%2),u={y:p,anchorY:t},d.allowOverlapX&&(u.x=l,u.anchorX=b.anchorX),m.attr({text:b.options.title||d.title||"A"})[m.isNew?
"attr":"animate"](u),d.allowOverlapX||(k[b.plotX]?k[b.plotX].size=Math.max(k[b.plotX].size,m.width):k[b.plotX]={align:y?.5:0,size:m.width,target:l,anchorX:l}),b.tooltipPos=[l,p+v.pos-c.plotTop]):m&&(b.graphic=m.destroy())}d.allowOverlapX||(E(k,function(a){a.plotX=a.anchorX;w.push(a)}),f.distribute(w,g?v.len:this.xAxis.len,100),a.forEach(function(a){var b=a.graphic&&k[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos+b.align*b.size,anchorX:a.anchorX}),A(b.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,
anchorX:-9999}),a.graphic.isNew=!0))}));d.useHTML&&f.wrap(this.markerGroup,"on",function(a){return f.SVGElement.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;l.drawTrackerPoint.apply(this);a.forEach(function(c){var e=c.graphic;e&&u(e.element,"mouseover",function(){0<c.stackIndex&&!c.raised&&(c._y=e.y,e.attr({y:c._y-8}),c.raised=!0);a.forEach(function(a){a!==c&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=
!1)})})})},animate:function(a){a?this.setClip():this.animate=null},setClip:function(){e.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:k,invertGroups:k},{isValid:function(){return D(this.y)||"undefined"===typeof this.y}});g.flag=function(a,c,e,f,d){var h=d&&d.anchorX||a;d=d&&d.anchorY||c;return g.circle(h-1,d-1,2,2).concat(["M",h,d,"L",a,c+f,a,c,a+e,c,a+e,c+f,a,c+f,"Z"])};C("circle");C("square");
y===m&&["circlepin","flag","squarepin"].forEach(function(a){m.prototype.symbols[a]=g[a]});""});H(p,"parts/RangeSelector.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(f,k){function p(a){this.init(a)}var C=k.defined,A=k.destroyObjectProperties,D=k.discardElement,E=k.extend,u=k.isNumber,x=k.objectEach,y=k.pick,e=k.pInt,t=k.splat,l=f.addEvent,m=f.Axis;k=f.Chart;var g=f.css,a=f.createElement,c=f.defaultOptions,r=f.fireEvent,F=f.merge;E(c,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,
height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});c.lang=F(c.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});p.prototype={clickButton:function(a,e){var d=this.chart,c=this.buttonOptions[a],f=d.xAxis[0],h=d.scroller&&d.scroller.getUnionExtremes()||f||{},b=h.dataMin,n=h.dataMax,g=f&&Math.round(Math.min(f.max,y(n,f.max))),k=c.type;h=c._range;var p,r=
c.dataGrouping;if(null!==b&&null!==n){d.fixedRange=h;r&&(this.forcedDataGrouping=!0,m.prototype.setDataGrouping.call(f||{chart:this.chart},r,!1),this.frozenStates=c.preserveDataGrouping);if("month"===k||"year"===k)if(f){k={range:c,max:g,chart:d,dataMin:b,dataMax:n};var x=f.minFromRange.call(k);u(k.newMax)&&(g=k.newMax)}else h=c;else if(h)x=Math.max(g-h,b),g=Math.min(x+h,n);else if("ytd"===k)if(f)"undefined"===typeof n&&(b=Number.MAX_VALUE,n=Number.MIN_VALUE,d.series.forEach(function(a){a=a.xData;
b=Math.min(a[0],b);n=Math.max(a[a.length-1],n)}),e=!1),g=this.getYTDExtremes(n,b,d.time.useUTC),x=p=g.min,g=g.max;else{this.deferredYTDClick=a;return}else"all"===k&&f&&(x=b,g=n);x+=c._offsetMin;g+=c._offsetMax;this.setSelected(a);if(f)f.setExtremes(x,g,y(e,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:c});else{var M=t(d.options.xAxis)[0];var V=M.range;M.range=h;var A=M.min;M.min=p;l(d,"load",function(){M.range=V;M.min=A})}}},setSelected:function(a){this.selected=this.options.selected=
a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var d=this,c=a.options.rangeSelector,e=c.buttons||[].concat(d.defaultButtons),f=c.selected,g=function(){var a=d.minInput,c=d.maxInput;a&&a.blur&&r(a,"blur");c&&c.blur&&r(c,"blur")};d.chart=a;d.options=c;d.buttons=[];d.buttonOptions=e;this.unMouseDown=l(a.container,"mousedown",g);this.unResize=
l(a,"resize",g);e.forEach(d.computeButtonRange);"undefined"!==typeof f&&e[f]&&this.clickButton(f,!1);l(a,"load",function(){a.xAxis&&a.xAxis[0]&&l(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&d.forcedDataGrouping&&!d.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,c=this.chart,e=c.xAxis[0],f=Math.round(e.max-e.min),g=!e.hasVisibleSeries,k=c.scroller&&c.scroller.getUnionExtremes()||
e,b=k.dataMin,n=k.dataMax;c=a.getYTDExtremes(n,b,c.time.useUTC);var m=c.min,l=c.max,p=a.selected,r=u(p),t=a.options.allButtonsEnabled,y=a.buttons;a.buttonOptions.forEach(function(d,c){var h=d._range,q=d.type,k=d.count||1,w=y[c],v=0,B=d._offsetMax-d._offsetMin;d=c===p;var u=h>n-b,z=h<e.minRange,x=!1,G=!1;h=h===f;("month"===q||"year"===q)&&f+36E5>=864E5*{month:28,year:365}[q]*k-B&&f-36E5<=864E5*{month:31,year:366}[q]*k+B?h=!0:"ytd"===q?(h=l-m+B===f,x=!d):"all"===q&&(h=e.max-e.min>=n-b,G=!d&&r&&h);q=
!t&&(u||z||G||g);k=d&&h||h&&!r&&!x||d&&a.frozenStates;q?v=3:k&&(r=!0,v=2);w.state!==v&&(w.setState(v),0===v&&p===c&&a.setSelected(null))})},computeButtonRange:function(a){var d=a.type,c=a.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[d])a._range=e[d]*c;else if("month"===d||"year"===d)a._range=864E5*{month:30,year:365}[d]*c;a._offsetMin=y(a.offsetMin,0);a._offsetMax=y(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,c){var d=this.chart.options.rangeSelector,
e=this.chart.time,f=this[a+"Input"];C(c)&&(f.previousValue=f.HCTime,f.HCTime=c);f.value=e.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",f.HCTime);this[a+"DateBox"].attr({text:e.dateFormat(d.inputDateFormat||"%b %e, %Y",f.HCTime)})},showInput:function(a){var d=this.inputGroup,c=this[a+"DateBox"];g(this[a+"Input"],{left:d.translateX+c.x+"px",top:d.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){g(this[a+"Input"],{border:0,width:"1px",height:"1px"});
this.setInputValue(a)},drawInput:function(d){function h(){var a=p.value,d=(b.inputDateParser||Date.parse)(a),c=k.xAxis[0],f=k.scroller&&k.scroller.xAxis?k.scroller.xAxis:c,h=f.dataMin;f=f.dataMax;d!==p.previousValue&&(p.previousValue=d,u(d)||(d=a.split("-"),d=Date.UTC(e(d[0]),e(d[1])-1,e(d[2]))),u(d)&&(k.time.useUTC||(d+=6E4*(new Date).getTimezoneOffset()),l?d>q.maxInput.HCTime?d=void 0:d<h&&(d=h):d<q.minInput.HCTime?d=void 0:d>f&&(d=f),"undefined"!==typeof d&&c.setExtremes(l?d:c.min,l?c.max:d,void 0,
void 0,{trigger:"rangeSelectorInput"})))}var q=this,k=q.chart,m=k.renderer.style||{},w=k.renderer,b=k.options.rangeSelector,n=q.div,l="min"===d,p,r,t=this.inputGroup;this[d+"Label"]=r=w.label(c.lang[l?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);t.offset+=r.width+5;this[d+"DateBox"]=w=w.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:b.inputBoxWidth||90,height:b.inputBoxHeight||17,"text-align":"center"}).on("click",
function(){q.showInput(d);q[d+"Input"].focus()});k.styledMode||w.attr({stroke:b.inputBoxBorderColor||"#cccccc","stroke-width":1});w.add(t);t.offset+=w.width+(l?10:0);this[d+"Input"]=p=a("input",{name:d,className:"highcharts-range-selector",type:"text"},{top:k.plotTop+"px"},n);k.styledMode||(r.css(F(m,b.labelStyle)),w.css(F({color:"#333333"},m,b.inputStyle)),g(p,E({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:m.fontSize,fontFamily:m.fontFamily,top:"-9999em"},
b.inputStyle)));p.onfocus=function(){q.showInput(d)};p.onblur=function(){p===f.doc.activeElement&&h();q.hideInput(d);p.blur()};p.onchange=h;p.onkeypress=function(a){13===a.keyCode&&h()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,e){var d=this.chart.time,f=new d.Date(a),h=d.get("FullYear",f);e=e?d.Date.UTC(h,0,1):+new d.Date(h,
0,1);c=Math.max(c||0,e);f=f.getTime();return{max:Math.min(a||f,f),min:c}},render:function(d,e){var f=this,h=f.chart,g=h.renderer,k=h.container,b=h.options,n=b.exporting&&!1!==b.exporting.enabled&&b.navigation&&b.navigation.buttonOptions,m=c.lang,l=f.div,p=b.rangeSelector,r=y(b.chart.style&&b.chart.style.zIndex,0)+1;b=p.floating;var u=f.buttons;l=f.inputGroup;var t=p.buttonTheme,x=p.buttonPosition,A=p.inputPosition,C=p.inputEnabled,D=t&&t.states,E=h.plotLeft,F=f.buttonGroup;var H=f.rendered;var N=
f.options.verticalAlign,P=h.legend,Q=P&&P.options,R=x.y,O=A.y,S=H||!1,T=S?"animate":"attr",L=0,J=0,K;if(!1!==p.enabled){H||(f.group=H=g.g("range-selector-group").attr({zIndex:7}).add(),f.buttonGroup=F=g.g("range-selector-buttons").add(H),f.zoomText=g.text(m.rangeSelectorZoom,0,15).add(F),h.styledMode||(f.zoomText.css(p.labelStyle),t["stroke-width"]=y(t["stroke-width"],0)),f.buttonOptions.forEach(function(a,b){u[b]=g.button(a.text,0,0,function(d){var c=a.events&&a.events.click,e;c&&(e=c.call(a,d));
!1!==e&&f.clickButton(b);f.isActive=!0},t,D&&D.hover,D&&D.select,D&&D.disabled).attr({"text-align":"center"}).add(F)}),!1!==C&&(f.div=l=a("div",null,{position:"relative",height:0,zIndex:r}),k.parentNode.insertBefore(l,k),f.inputGroup=l=g.g("input-group").add(H),l.offset=0,f.drawInput("min"),f.drawInput("max")));f.zoomText[T]({x:y(E+x.x,E)});var U=y(E+x.x,E)+f.zoomText.getBBox().width+5;f.buttonOptions.forEach(function(a,b){u[b][T]({x:U});U+=u[b].width+y(p.buttonSpacing,5)});E=h.plotLeft-h.spacing[3];
f.updateButtonStates();n&&this.titleCollision(h)&&"top"===N&&"right"===x.align&&x.y+F.getBBox().height-12<(n.y||0)+n.height&&(L=-40);"left"===x.align?K=x.x-h.spacing[3]:"right"===x.align&&(K=x.x+L-h.spacing[1]);F.align({y:x.y,width:F.getBBox().width,align:x.align,x:K},!0,h.spacingBox);f.group.placed=S;f.buttonGroup.placed=S;!1!==C&&(L=n&&this.titleCollision(h)&&"top"===N&&"right"===A.align&&A.y-l.getBBox().height-12<(n.y||0)+n.height+h.spacing[0]?-40:0,"left"===A.align?K=E:"right"===A.align&&(K=-Math.max(h.axisOffset[1],
-L)),l.align({y:A.y,width:l.getBBox().width,align:A.align,x:A.x+K-2},!0,h.spacingBox),k=l.alignAttr.translateX+l.alignOptions.x-L+l.getBBox().x+2,n=l.alignOptions.width,m=F.alignAttr.translateX+F.getBBox().x,K=F.getBBox().width+20,(A.align===x.align||m+K>k&&k+n>m&&R<O+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(h.axisOffset[1]>=-L?0:-L),translateY:l.alignAttr.translateY+F.getBBox().height+10}),f.setInputValue("min",d),f.setInputValue("max",e),f.inputGroup.placed=S);f.group.align({verticalAlign:N},
!0,h.spacingBox);d=f.group.getBBox().height+20;e=f.group.alignAttr.translateY;"bottom"===N&&(P=Q&&"bottom"===Q.verticalAlign&&Q.enabled&&!Q.floating?P.legendHeight+y(Q.margin,10):0,d=d+P-20,J=e-d-(b?0:p.y)-(h.titleOffset?h.titleOffset[2]:0)-10);if("top"===N)b&&(J=0),h.titleOffset&&h.titleOffset[0]&&(J=h.titleOffset[0]),J+=h.margin[0]-h.spacing[0]||0;else if("middle"===N)if(O===R)J=0>O?e+void 0:e;else if(O||R)J=0>O||0>R?J-Math.min(O,R):e-d+NaN;f.group.translate(p.x,p.y+Math.floor(J));!1!==C&&(f.minInput.style.marginTop=
f.group.translateY+"px",f.maxInput.style.marginTop=f.group.translateY+"px");f.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,e=a.y,f=a.buttonPosition.y,g=a.inputPosition.y;if(a.height)return a.height;a=c?c.getBBox(!0).height+13+e:0;c=Math.min(g,f);if(0>g&&0>f||0<g&&0<f)a+=Math.abs(c);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var d=this.chart;F(!0,d.options.rangeSelector,a);this.destroy();this.init(d);d.rangeSelector.render()},
destroy:function(){var a=this,c=a.minInput,e=a.maxInput;a.unMouseDown();a.unResize();A(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);e&&(e.onfocus=e.onblur=e.onchange=null);x(a,function(d,c){d&&"chart"!==c&&(d.destroy?d.destroy():d.nodeType&&D(this[c]));d!==p.prototype[c]&&(a[c]=null)},this)}};m.prototype.minFromRange=function(){var a=this.range,c={month:"Month",year:"FullYear"}[a.type],e=this.max,f=this.chart.time,g=function(a,b){var d=new f.Date(a),e=f.get(c,d);f.set(c,d,e+b);e===f.get(c,d)&&
f.set("Date",d,0);return d.getTime()-a};if(u(a)){var k=e-a;var b=a}else k=e+g(e,-a.count),this.chart&&(this.chart.fixedRange=e-k);var n=y(this.dataMin,Number.MIN_VALUE);u(k)||(k=n);k<=n&&(k=n,"undefined"===typeof b&&(b=g(k,a.count)),this.newMax=Math.min(k+b,this.dataMax));u(e)||(k=void 0);return k};f.RangeSelector||(l(k,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new p(this))}),l(k,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(u(c.deferredYTDClick)&&
(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,c.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),l(k,"update",function(a){var d=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,e=this.extraTopMargin;d&&d.enabled&&!C(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new p(this));this.extraTopMargin=
this.extraBottomMargin=!1;a&&(a.render(),d=d&&d.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===d?this.extraBottomMargin=!0:"middle"!==d&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)}),l(k,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),l(k,"getMargins",function(){var a=
this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),k.prototype.callbacks.push(function(a){function c(){d=a.xAxis[0].getExtremes();u(d.min)&&e.render(d.min,d.max)}var d,e=a.rangeSelector;if(e){var f=l(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var g=l(a,"redraw",c);c()}l(a,"destroy",function(){e&&(g(),f())})}),f.RangeSelector=p)});H(p,"parts/StockChart.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],
function(f,k){var p=k.arrayMax,C=k.arrayMin,A=k.clamp,D=k.defined,E=k.extend,u=k.isNumber,x=k.isString,y=k.pick,e=k.splat;k=f.addEvent;var t=f.Axis,l=f.Chart,m=f.format,g=f.merge,a=f.Point,c=f.Renderer,r=f.Series,F=f.SVGRenderer,d=f.VMLRenderer,h=r.prototype,q=h.init,v=h.processData,G=a.prototype.tooltipFormatter;f.StockChart=f.stockChart=function(a,b,c){var d=x(a)||a.nodeName,h=arguments[d?1:0],n=h,k=h.series,m=f.getOptions(),w,q=y(h.navigator&&h.navigator.enabled,m.navigator.enabled,!0),p=q?{startOnTick:!1,
endOnTick:!1}:null;h.xAxis=e(h.xAxis||{}).map(function(a,b){return g({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},m.xAxis,m.xAxis&&m.xAxis[b],a,{type:"datetime",categories:null},p)});h.yAxis=e(h.yAxis||{}).map(function(a,b){w=y(a.opposite,!0);return g({labels:{y:-2},opposite:w,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},m.yAxis,m.yAxis&&m.yAxis[b],a)});h.series=null;h=g({chart:{panning:!0,pinchType:"x"},
navigator:{enabled:q},scrollbar:{enabled:y(m.scrollbar.enabled,!0)},rangeSelector:{enabled:y(m.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:y(m.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},h,{isStock:!0});h.series=n.series=k;return d?new l(a,h,c):new l(h,b)};k(r,"setOptions",function(a){function b(a){return f.seriesTypes[a]&&c instanceof f.seriesTypes[a]}var c=this,d;this.chart.options.isStock&&(b("column")||b("columnrange")?d={borderWidth:0,shadow:!1}:!b("line")||b("scatter")||
b("sma")||(d={marker:{enabled:!1,radius:2}}),d&&(a.plotOptions[this.type]=g(a.plotOptions[this.type],d)))});k(t,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),b[c]=this,a.align="right",a.preventDefault()))});k(t,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+
","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});k(t,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return u(a)?[e[b][a]]:x(a)?[e.get(a)]:d.map(function(a){return a[b]})}var c=this,d=this.isLinked&&!this.series?this.linkedParent.series:this.series,e=c.chart,g=e.renderer,h=c.left,k=c.top,m,l,q,p,w=[],r=[],t=a.translatedValue,v=a.value,C=a.force;if(e.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===
c.coll){a.preventDefault();r=b(c.coll);var E=c.isXAxis?e.yAxis:e.xAxis;E.forEach(function(a){if(D(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=D(a.options[b])?e[b][a.options[b]]:e[b][0];c===b&&r.push(a)}});var F=r.length?[]:[c.isXAxis?e.yAxis[0]:e.xAxis[0]];r.forEach(function(a){-1!==F.indexOf(a)||f.find(F,function(b){return b.pos===a.pos&&b.len===a.len})||F.push(a)});var G=y(t,c.translate(v,null,null,a.old));u(G)&&(c.horiz?F.forEach(function(a){var b;
l=a.pos;p=l+a.len;m=q=Math.round(G+c.transB);"pass"!==C&&(m<h||m>h+c.width)&&(C?m=q=A(m,h,h+c.width):b=!0);b||w.push("M",m,l,"L",q,p)}):F.forEach(function(a){var b;m=a.pos;q=m+a.len;l=p=Math.round(k+c.height-G);"pass"!==C&&(l<k||l>k+c.height)&&(C?l=p=A(l,k,k+c.height):b=!0);b||w.push("M",m,l,"L",q,p)}));a.path=0<w.length?g.crispPolyLine(w,a.lineWidth||1):null}});F.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===
a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};c===d&&(d.prototype.crispPolyLine=F.prototype.crispPolyLine);k(t,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});k(t,"afterDrawCrosshair",function(a){var b,c;if(D(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.options.crosshair.label,f=this.horiz,h=this.opposite,g=this.left,k=this.top,l=this.crossLabel,q=e.format,p="",r="inside"===this.options.tickPosition,
w=!1!==this.crosshair.snap,t=0,u=a.e||this.cross&&this.cross.e,v=a.point;var x=this.lin2log;if(this.isLog){a=x(this.min);var A=x(this.max)}else a=this.min,A=this.max;x=f?"center":h?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";l||(l=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||x,padding:y(e.padding,8),r:y(e.borderRadius,
3),zIndex:2}).add(this.labelGroup),d.styledMode||l.attr({fill:e.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:e.borderColor||"","stroke-width":e.borderWidth||0}).css(E({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},e.style)));f?(x=w?v.plotX+g:u.chartX,k+=h?0:this.height):(x=h?this.width+g:0,k=w?v.plotY+k:u.chartY);q||e.formatter||(this.isDatetimeAxis&&(p="%b %d, %Y"),q="{value"+(p?":"+p:"")+"}");p=w?v[this.isXAxis?"x":"y"]:this.toValue(f?u.chartX:
u.chartY);l.attr({text:q?m(q,{value:p},d):e.formatter.call(this,p),x:x,y:k,visibility:p<a||p>A?"hidden":"visible"});e=l.getBBox();if(f){if(r&&!h||!r&&h)k=l.y-e.height}else k=l.y-e.height/2;f?(b=g-e.x,c=g+this.width-e.x):(b="left"===this.labelAlign?g:0,c="right"===this.labelAlign?g+this.width:d.chartWidth);l.translateX<b&&(t=b-l.translateX);l.translateX+e.width>=c&&(t=-(l.translateX+e.width-c));l.attr({x:x+t,y:k,anchorX:f?x:this.opposite?0:d.chartWidth,anchorY:f?this.opposite?d.chartHeight:0:k+e.height/
2})}});h.init=function(){q.apply(this,arguments);this.setCompare(this.options.compare)};h.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};h.processData=function(a){var b,c=-1,d=!0===this.options.compareStart?0:1;v.apply(this,arguments);
if(this.xAxis&&this.processedYData){var e=this.processedXData;var f=this.processedYData;var h=f.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<h-d;b++){var g=f[b]&&-1<c?f[b][c]:f[b];if(u(g)&&e[b+d]>=this.xAxis.min&&0!==g){this.compareValue=g;break}}}};k(r,"afterGetExtremes",function(){if(this.modifyValue){var a=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=C(a);this.dataMax=p(a)}});t.prototype.setCompare=
function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),y(b,!0)&&this.chart.redraw())};a.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,y(this.series.tooltipOptions.changeDecimals,2)));return G.apply(this,[a])};k(r,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+
a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}!this.clipBox&&this.animate?(this.clipBox=g(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});k(l,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(g(!0,this.options.scrollbar,
a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})});H(p,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map