/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(D){b(D);b.Highcharts=D;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function D(k,g,b,n){k.hasOwnProperty(g)||(k[g]=n.apply(null,b))}b=b?b._modules:{};D(b,"mixins/draw-point.js",[],function(){var k=function(g){var k=this,b=k.graphic,y=g.animatableAttribs,m=g.onComplete,t=g.css,x=g.renderer;
if(k.shouldDraw())b||(k.graphic=b=x[g.shapeType](g.shapeArgs).add(g.group)),b.css(t).attr(g.attribs).animate(y,g.isNew?!1:void 0,m);else if(b){var E=function(){k.graphic=b=b.destroy();"function"===typeof m&&m()};Object.keys(y).length?b.animate(y,void 0,function(){E()}):E()}};return function(b){(b.attribs=b.attribs||{})["class"]=this.getClassName();k.call(this,b)}});D(b,"mixins/tree-series.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,g){var k=g.extend,n=g.isArray,y=g.isNumber,m=g.isObject,
t=g.pick,x=b.merge;return{getColor:function(k,h){var g=h.index,m=h.mapOptionsToLevel,p=h.parentColor,E=h.parentColorIndex,n=h.series,v=h.colors,N=h.siblings,u=n.points,y=n.chart.options.chart,A;if(k){u=u[k.i];k=m[k.level]||{};if(m=u&&k.colorByPoint){var x=u.index%(v?v.length:y.colorCount);var e=v&&v[x]}if(!n.chart.styledMode){v=u&&u.options.color;y=k&&k.color;if(A=p)A=(A=k&&k.colorVariation)&&"brightness"===A.key?b.color(p).brighten(g/N*A.to).get():p;A=t(v,y,e,A,n.color)}var f=t(u&&u.options.colorIndex,
k&&k.colorIndex,x,E,h.colorIndex)}return{color:A,colorIndex:f}},getLevelOptions:function(b){var h=null;if(m(b)){h={};var g=y(b.from)?b.from:1;var t=b.levels;var p={};var F=m(b.defaults)?b.defaults:{};n(t)&&(p=t.reduce(function(b,h){if(m(h)&&y(h.level)){var p=x({},h);var n="boolean"===typeof p.levelIsConstant?p.levelIsConstant:F.levelIsConstant;delete p.levelIsConstant;delete p.level;h=h.level+(n?0:g-1);m(b[h])?k(b[h],p):b[h]=p}return b},{}));t=y(b.to)?b.to:1;for(b=0;b<=t;b++)h[b]=x({},F,m(p[b])?p[b]:
{})}return h},setTreeValues:function M(b,g){var h=g.before,m=g.idRoot,n=g.mapIdToNode[m],v=g.points[b.i],y=v&&v.options||{},u=0,x=[];k(b,{levelDynamic:b.level-(("boolean"===typeof g.levelIsConstant?g.levelIsConstant:1)?0:n.level),name:t(v&&v.name,""),visible:m===b.id||("boolean"===typeof g.visible?g.visible:!1)});"function"===typeof h&&(b=h(b,g));b.children.forEach(function(h,m){var e=k({},g);k(e,{index:m,siblings:b.children.length,visible:b.visible});h=M(h,e);x.push(h);h.visible&&(u+=h.val)});b.visible=
0<u||b.visible;h=t(y.value,u);k(b,{children:x,childrenTotal:u,isLeaf:b.visible&&!u,val:h});return b},updateRootId:function(b){if(m(b)){var k=m(b.options)?b.options:{};k=t(b.rootNode,k.rootId,"");m(b.userOptions)&&(b.userOptions.rootId=k);b.rootNode=k}return k}}});D(b,"modules/treemap.src.js",[b["parts/Globals.js"],b["mixins/tree-series.js"],b["mixins/draw-point.js"],b["parts/Utilities.js"]],function(b,g,D,n){var k=n.correctFloat,m=n.defined,t=n.extend,x=n.isArray,E=n.isNumber,h=n.isObject,L=n.isString,
M=n.objectEach,p=n.pick;n=b.seriesType;var F=b.seriesTypes,P=b.addEvent,v=b.merge,N=b.error,u=b.noop,Q=b.fireEvent,A=g.getColor,R=g.getLevelOptions,e=b.Series,f=b.stableSort,w=b.Color,J=function(a,c,d){d=d||this;M(a,function(q,r){c.call(d,q,r,a)})},H=function(a,c,d){d=d||this;a=c.call(d,a);!1!==a&&H(a,c,d)},z=g.updateRootId;n("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?
this.point:{};return L(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",
brightness:F.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:u,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=x(a)?a:[];var d=x(c)?c:[];c=a.reduce(function(a,c,d){c=p(c.parent,"");"undefined"===typeof a[c]&&(a[c]=[]);a[c].push(d);return a},{"":[]});J(c,function(a,c,b){""!==c&&-1===d.indexOf(c)&&(a.forEach(function(a){b[""].push(a)}),
delete b[c])});return c},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,c){var d=b.colorMapSeriesMixin;d&&(this.colorAttribs=d.colorAttribs);P(this,"setOptions",function(a){a=a.userOptions;m(a.allowDrillToNode)&&!m(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);m(a.drillUpButton)&&
!m(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});e.prototype.init.call(this,a,c);this.options.allowTraversingTree&&P(this,"click",this.onClickDrillToNode)},buildNode:function(a,c,d,b,r){var e=this,q=[],f=e.points[c],G=0,I;(b[a]||[]).forEach(function(c){I=e.buildNode(e.points[c].id,c,d+1,b,a);G=Math.max(I.height+1,G);q.push(I)});c={id:a,i:c,children:q,height:G,level:d,parent:r,visible:!1};e.nodeMap[c.id]=c;f&&(f.node=c);return c},setTreeValues:function(a){var c=
this,d=c.options,b=c.nodeMap[c.rootNode];d="boolean"===typeof d.levelIsConstant?d.levelIsConstant:!0;var e=0,O=[],l=c.points[a.i];a.children.forEach(function(a){a=c.setTreeValues(a);O.push(a);a.ignore||(e+=a.val)});f(O,function(a,c){return a.sortIndex-c.sortIndex});var C=p(l&&l.options.value,e);l&&(l.value=C);t(a,{children:O,childrenTotal:e,ignore:!(p(l&&l.visible,!0)&&0<C),isLeaf:a.visible&&!e,levelDynamic:a.level-(d?0:b.level),name:p(l&&l.name,""),sortIndex:p(l&&l.sortIndex,-C),val:C});return a},
calculateChildrenAreas:function(a,c){var d=this,e=d.options,b=d.mapOptionsToLevel[a.level+1],O=p(d[b&&b.layoutAlgorithm]&&b.layoutAlgorithm,e.layoutAlgorithm),l=e.alternateStartingDirection,f=[];a=a.children.filter(function(a){return!a.ignore});b&&b.layoutStartingDirection&&(c.direction="vertical"===b.layoutStartingDirection?0:1);f=d[O](c,a);a.forEach(function(a,b){b=f[b];a.values=v(b,{val:a.childrenTotal,direction:l?1-c.direction:c.direction});a.pointValues=v(b,{x:b.x/d.axisRatio,width:b.width/d.axisRatio});
a.children.length&&d.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,c=a.xAxis,d=a.yAxis;a.points.forEach(function(b){var e=b.node,q=e.pointValues,l=0;a.chart.styledMode||(l=(a.pointAttribs(b)["stroke-width"]||0)%2/2);if(q&&e.visible){e=Math.round(c.translate(q.x,0,0,0,1))-l;var f=Math.round(c.translate(q.x+q.width,0,0,0,1))-l;var g=Math.round(d.translate(q.y,0,0,0,1))-l;q=Math.round(d.translate(q.y+q.height,0,0,0,1))-l;b.shapeArgs={x:Math.min(e,f),y:Math.min(g,q),width:Math.abs(f-
e),height:Math.abs(q-g)};b.plotX=b.shapeArgs.x+b.shapeArgs.width/2;b.plotY=b.shapeArgs.y+b.shapeArgs.height/2}else delete b.plotX,delete b.plotY})},setColorRecursive:function(a,c,d,b,e){var r=this,q=r&&r.chart;q=q&&q.options&&q.options.colors;if(a){var f=A(a,{colors:q,index:b,mapOptionsToLevel:r.mapOptionsToLevel,parentColor:c,parentColorIndex:d,series:r,siblings:e});if(c=r.points[a.i])c.color=f.color,c.colorIndex=f.colorIndex;(a.children||[]).forEach(function(c,d){r.setColorRecursive(c,f.color,f.colorIndex,
d,a.children.length)})}},algorithmGroup:function(a,c,d,b){this.height=a;this.width=c;this.plot=b;this.startDirection=this.direction=d;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),
this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,d,b){var e,q,f,g,w=d.lW,I=d.lH,h=d.plot,m=0,z=d.elArr.length-
1;if(c)w=d.nW,I=d.nH;else var K=d.elArr[d.elArr.length-1];d.elArr.forEach(function(a){if(c||m<z)0===d.direction?(e=h.x,q=h.y,f=w,g=a/f):(e=h.x,q=h.y,g=I,f=a/g),b.push({x:e,y:q,width:f,height:k(g)}),0===d.direction?h.y+=g:h.x+=f;m+=1});d.reset();0===d.direction?d.width-=w:d.height-=I;h.y=h.parent.y+(h.parent.height-d.height);h.x=h.parent.x+(h.parent.width-d.width);a&&(d.direction=1-d.direction);c||d.addElement(K)},algorithmLowAspectRatio:function(a,c,d){var b=[],e=this,f,g={x:c.x,y:c.y,parent:c},h=
0,k=d.length-1,w=new this.algorithmGroup(c.height,c.width,c.direction,g);d.forEach(function(d){f=d.val/c.val*c.height*c.width;w.addElement(f);w.lP.nR>w.lP.lR&&e.algorithmCalcPoints(a,!1,w,b,g);h===k&&e.algorithmCalcPoints(a,!0,w,b,g);h+=1});return b},algorithmFill:function(a,c,d){var b=[],e,f=c.direction,g=c.x,h=c.y,w=c.width,k=c.height,m,z,n,K;d.forEach(function(d){e=d.val/c.val*c.height*c.width;m=g;z=h;0===f?(K=k,n=e/K,w-=n,g+=n):(n=w,K=e/n,k-=K,h+=K);b.push({x:m,y:z,width:n,height:K});a&&(f=1-
f)});return b},strip:function(a,c){return this.algorithmLowAspectRatio(!1,a,c)},squarified:function(a,c){return this.algorithmLowAspectRatio(!0,a,c)},sliceAndDice:function(a,c){return this.algorithmFill(!0,a,c)},stripes:function(a,c){return this.algorithmFill(!1,a,c)},translate:function(){var a=this,c=a.options,d=z(a);e.prototype.translate.call(a);var b=a.tree=a.getTree();var f=a.nodeMap[d];a.renderTraverseUpButton(d);a.mapOptionsToLevel=R({from:f.level+1,levels:c.levels,to:b.height,defaults:{levelIsConstant:a.options.levelIsConstant,
colorByPoint:c.colorByPoint}});""===d||f&&f.children.length||(a.setRootNode("",!1),d=a.rootNode,f=a.nodeMap[d]);H(a.nodeMap[a.rootNode],function(c){var b=!1,d=c.parent;c.visible=!0;if(d||""===d)b=a.nodeMap[d];return b});H(a.nodeMap[a.rootNode].children,function(a){var c=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(c=(c||[]).concat(a.children))});return c});a.setTreeValues(b);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=d={x:0,y:0,width:100,height:100};a.nodeMap[""].values=
d=v(d,{width:d.width*a.axisRatio,direction:"vertical"===c.layoutStartingDirection?0:1,val:b.val});a.calculateChildrenAreas(b,d);a.colorAxis||c.colorByPoint||a.setColorRecursive(a.tree);c.allowTraversingTree&&(c=f.pointValues,a.xAxis.setExtremes(c.x,c.x+c.width,!1),a.yAxis.setExtremes(c.y,c.y+c.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,c=a.mapOptionsToLevel,b,f;a.points.filter(function(a){return a.node.visible}).forEach(function(d){f=
c[d.node.level];b={style:{}};d.node.isLeaf||(b.enabled=!1);f&&f.dataLabels&&(b=v(b,f.dataLabels),a._hasPointLabels=!0);d.shapeArgs&&(b.style.width=d.shapeArgs.width,d.dataLabel&&d.dataLabel.css({width:d.shapeArgs.width+"px"}));d.dlOptions=v(b,d.options.dataLabels)});e.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,c,b){var d=b.style;!m(d.textOverflow)&&c.text&&c.getBBox().width>c.text.textWidth&&c.css({textOverflow:"ellipsis",width:d.width+="px"});F.column.prototype.alignDataLabel.apply(this,
arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,c){var b=h(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=a&&b[a.node.level]||{};b=this.options;var f=c&&b.states[c]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||e.borderColor||f.borderColor||b.borderColor,"stroke-width":p(a&&a.borderWidth,e.borderWidth,f.borderWidth,b.borderWidth),dashstyle:a&&a.borderDashStyle||e.borderDashStyle||f.borderDashStyle||b.borderDashStyle,fill:a&&a.color||
this.color};-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(c=p(f.opacity,b.opacity),a.fill=w(a.fill).setOpacity(c).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":c&&(a.fill=w(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=this,c=a.chart,b=c.renderer,e=c.styledMode,f=a.options,g=e?{}:f.shadow,h=f.borderRadius,w=c.pointCount<f.animationLimit,k=f.allowTraversingTree;
a.points.forEach(function(c){var d=c.node.levelDynamic,q={},m={},r={},z="level-group-"+d,n=!!c.graphic,l=w&&n,p=c.shapeArgs;c.shouldDraw()&&(h&&(m.r=h),v(!0,l?q:m,n?p:{},e?{}:a.pointAttribs(c,c.selected&&"select")),a.colorAttribs&&e&&t(r,a.colorAttribs(c)),a[z]||(a[z]=b.g(z).attr({zIndex:1E3-d}).add(a.group),a[z].survive=!0));c.draw({animatableAttribs:q,attribs:m,css:r,group:a[z],renderer:b,shadow:g,shapeArgs:p,shapeType:"rect"});k&&c.graphic&&(c.drillId=f.interactByLeaf?a.drillToByLeaf(c):a.drillToByGroup(c))})},
onClickDrillToNode:function(a){var c=(a=a.point)&&a.drillId;L(c)&&(a.setState(""),this.setRootNode(c,!0,{trigger:"click"}))},drillToByGroup:function(a){var c=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(c=a.id);return c},drillToByLeaf:function(a){var c=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!c;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(c=a.id);return c},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&L(a.parent)&&this.setRootNode(a.parent,
!0,{trigger:"traverseUpButton"})},drillToNode:function(a,c){N("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,c)},setRootNode:function(a,c,b){a=t({newRootId:a,previousRootId:this.rootNode,redraw:p(c,!0),series:this},b);Q(this,"setRootNode",a,function(a){var c=a.series;c.idPreviousRoot=a.previousRootId;c.rootNode=a.newRootId;c.isDirty=!0;a.redraw&&c.chart.redraw()})},renderTraverseUpButton:function(a){var c=
this,b=c.options.traverseUpButton,e=p(b.text,c.nodeMap[a].name,"< Back");if(""===a)c.drillUpButton&&(c.drillUpButton=c.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:e}).align();else{var f=(a=b.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(e,null,null,function(){c.drillUp()},a,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:b.position.align,zIndex:7}).add().align(b.position,!1,b.relativeTo||
"plotBox")}},buildKDTree:u,drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,getExtremes:function(){e.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;e.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};e.prototype.bindAxes.call(this);t(this.yAxis.options,a);t(this.xAxis.options,
a)},setState:function(a){this.options.inactiveOtherPoints=!0;e.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:H}},{draw:D,setVisible:F.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=b.Point.prototype.getClassName.call(this),c=this.series,e=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||p(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):
a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||E(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return E(this.plotY)&&null!==this.y}});""});D(b,"modules/sunburst.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/draw-point.js"],b["mixins/tree-series.js"]],function(b,g,D,n){var k=g.extend,m=g.isNumber,t=g.isObject,x=g.isString;g=b.CenteredSeriesMixin;
var E=b.Series,h=g.getCenter,L=n.getColor,M=n.getLevelOptions,p=g.getStartAndEndRadians,F=b.merge,P=180/Math.PI;g=b.seriesType;var v=n.setTreeValues,N=n.updateRootId,u=function(b,f){var e=[];if(m(b)&&m(f)&&b<=f)for(;b<=f;b++)e.push(b);return e},Q=function(b,f){f=t(f)?f:{};var e=0,g;if(t(b)){var h=F({},b);b=m(f.from)?f.from:0;var k=m(f.to)?f.to:0;var a=u(b,k);b=Object.keys(h).filter(function(b){return-1===a.indexOf(+b)});var c=g=m(f.diffRadius)?f.diffRadius:0;a.forEach(function(a){a=h[a];var b=a.levelSize.unit,
d=a.levelSize.value;"weight"===b?e+=d:"percentage"===b?(a.levelSize={unit:"pixels",value:d/100*c},g-=a.levelSize.value):"pixels"===b&&(g-=d)});a.forEach(function(a){var b=h[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,h[a].levelSize={unit:"pixels",value:b/e*g})});b.forEach(function(a){h[a].levelSize={value:0,unit:"pixels"}})}return h},A=function(b){var e=b.level;return{from:0<e?e:1,to:e+b.height}},R=function(b,f){var e=f.mapIdToNode[b.parent],g=f.series,h=g.chart,k=g.points[b.i];e=L(b,{colors:g.options.colors||
h&&h.options.colors,colorIndex:g.colorIndex,index:f.index,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:e&&e.color,parentColorIndex:e&&e.colorIndex,series:f.series,siblings:f.siblings});b.color=e.color;b.colorIndex=e.colorIndex;k&&(k.color=b.color,k.colorIndex=b.colorIndex,b.sliced=b.id!==f.idRoot?k.sliced:!1);return b};g("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",style:{textOverflow:"ellipsis"}},rootId:void 0,
levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var b=this,f=b.mapOptionsToLevel,g=b.shapeRoot,h=b.group,n=b.hasRendered,z=b.rootNode,a=b.idPreviousRoot,c=b.nodeMap,d=c[a],q=d&&d.shapeArgs;d=b.points;var p=b.startAndEndRadians,v=b.chart,l=v&&v.options&&v.options.chart||{},u="boolean"===typeof l.animation?l.animation:!0,G=b.center[3]/2,I=b.chart.renderer,x=!1,y=!1;if(l=!!(u&&n&&z!==a&&b.dataLabelsGroup)){b.dataLabelsGroup.attr({opacity:0});
var A=function(){x=!0;b.dataLabelsGroup&&b.dataLabelsGroup.animate({opacity:1,visibility:"visible"})}}d.forEach(function(d){var e=d.node,l=f[e.level];var w=d.shapeExisting||{};var r=e.shapeArgs||{},x=!(!e.visible||!e.shapeArgs);if(n&&u){var J={};var H={end:r.end,start:r.start,innerR:r.innerR,r:r.r,x:r.x,y:r.y};x?!d.graphic&&q&&(J=z===d.id?{start:p.start,end:p.end}:q.end<=r.start?{start:p.end,end:p.end}:{start:p.start,end:p.start},J.innerR=J.r=G):d.graphic&&(a===d.id?H={innerR:G,r:G}:g&&(H=g.end<=
w.start?{innerR:G,r:G,start:p.end,end:p.end}:{innerR:G,r:G,start:p.start,end:p.start}));w=J}else H=r,w={};J=[r.plotX,r.plotY];if(!d.node.isLeaf)if(z===d.id){var B=c[z];B=B.parent}else B=d.id;k(d,{shapeExisting:r,tooltipPos:J,drillId:B,name:""+(d.name||d.id||d.index),plotX:r.plotX,plotY:r.plotY,value:e.val,isNull:!x});B=d.options;e=t(r)?r:{};B=t(B)?B.dataLabels:{};l=t(l)?l.dataLabels:{};l=F({style:{}},l,B);var C;B=l.rotationMode;m(l.rotation)||("auto"===B&&(1>d.innerArcLength&&d.outerArcLength>e.radius?
C=0:B=1<d.innerArcLength&&d.outerArcLength>1.5*e.radius?"parallel":"perpendicular"),"auto"!==B&&(C=e.end-(e.end-e.start)/2),l.style.width="parallel"===B?Math.min(2.5*e.radius,(d.outerArcLength+d.innerArcLength)/2):e.radius,"perpendicular"===B&&d.series.chart.renderer.fontMetrics(l.style.fontSize).h>d.outerArcLength&&(l.style.width=1),l.style.width=Math.max(l.style.width-2*(l.padding||0),1),C=C*P%180,"parallel"===B&&(C-=90),90<C?C-=180:-90>C&&(C+=180),l.rotation=C);0===l.rotation&&(l.rotation=.001);
d.dlOptions=l;if(!y&&x){y=!0;var D=A}d.draw({animatableAttribs:H,attribs:k(w,!v.styledMode&&b.pointAttribs(d,d.selected&&"select")),onComplete:D,group:h,renderer:I,shapeType:"arc",shapeArgs:r})});l&&y?(b.hasRendered=!1,b.options.dataLabels.defer=!0,E.prototype.drawDataLabels.call(b),b.hasRendered=!0,x&&A()):E.prototype.drawDataLabels.call(b)},pointAttribs:b.seriesTypes.column.prototype.pointAttribs,layoutAlgorithm:function(b,f,g){var e=b.start,h=b.end-e,k=b.val,a=b.x,c=b.y,d=g&&t(g.levelSize)&&m(g.levelSize.value)?
g.levelSize.value:0,n=b.r,p=n+d,w=g&&m(g.slicedOffset)?g.slicedOffset:0;return(f||[]).reduce(function(b,f){var g=1/k*f.val*h,l=e+g/2,m=a+Math.cos(l)*w;l=c+Math.sin(l)*w;f={x:f.sliced?m:a,y:f.sliced?l:c,innerR:n,r:p,radius:d,start:e,end:e+g};b.push(f);e=f.end;return b},[])},setShapeArgs:function(b,f,g){var e=[],h=g[b.level+1];b=b.children.filter(function(b){return b.visible});e=this.layoutAlgorithm(f,b,h);b.forEach(function(b,a){a=e[a];var c=a.start+(a.end-a.start)/2,d=a.innerR+(a.r-a.innerR)/2,f=
a.end-a.start;d=0===a.innerR&&6.28<f?{x:a.x,y:a.y}:{x:a.x+Math.cos(c)*d,y:a.y+Math.sin(c)*d};var h=b.val?b.childrenTotal>b.val?b.childrenTotal:b.val:b.childrenTotal;this.points[b.i]&&(this.points[b.i].innerArcLength=f*a.innerR,this.points[b.i].outerArcLength=f*a.r);b.shapeArgs=F(a,{plotX:d.x,plotY:d.y+4*Math.abs(Math.cos(c))});b.values=F(a,{val:h});b.children.length&&this.setShapeArgs(b,b.values,g)},this)},translate:function(){var e=this,f=e.options,g=e.center=h.call(e),k=e.startAndEndRadians=p(f.startAngle,
f.endAngle),m=g[3]/2,n=g[2]/2-m,a=N(e),c=e.nodeMap,d=c&&c[a],q={};e.shapeRoot=d&&d.shapeArgs;E.prototype.translate.call(e);var r=e.tree=e.getTree();e.renderTraverseUpButton(a);c=e.nodeMap;d=c[a];var t=x(d.parent)?d.parent:"";t=c[t];var l=A(d);var u=l.from,y=l.to;l=M({from:u,levels:e.options.levels,to:y,defaults:{colorByPoint:f.colorByPoint,dataLabels:f.dataLabels,levelIsConstant:f.levelIsConstant,levelSize:f.levelSize,slicedOffset:f.slicedOffset}});l=Q(l,{diffRadius:n,from:u,to:y});v(r,{before:R,
idRoot:a,levelIsConstant:f.levelIsConstant,mapOptionsToLevel:l,mapIdToNode:c,points:e.points,series:e});f=c[""].shapeArgs={end:k.end,r:m,start:k.start,val:d.val,x:g[0],y:g[1]};this.setShapeArgs(t,f,l);e.mapOptionsToLevel=l;e.data.forEach(function(a){q[a.id]&&b.error(31,!1,e.chart);q[a.id]=!0});q={}},animate:function(b){var e=this.chart,g=[e.plotWidth/2,e.plotHeight/2],h=e.plotLeft,k=e.plotTop;e=this.group;b?(b={translateX:g[0]+h,translateY:g[1]+k,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},e.attr(b)):
(b={translateX:h,translateY:k,scaleX:1,scaleY:1,rotation:0,opacity:1},e.animate(b,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:Q,getLevelFromAndTo:A,range:u}},{draw:D,shouldDraw:function(){return!this.isNull},isValid:function(){return!0}})});D(b,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map