/*
 Highcharts Gantt JS v7.2.1-modified (2019-11-18)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(C){e(C);e.Highcharts=C;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function C(n,r,e,x){n.hasOwnProperty(r)||(n[r]=x.apply(null,e))}e=e?e._modules:{};C(e,"parts-gantt/GridAxis.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(n,r){var e=r.defined,x=r.erase,z=r.isArray,
v=r.isNumber,y=r.pick,u=n.addEvent,c=n.dateFormat,f=function(b){return r.isObject(b,!0)},d=n.merge,h=n.wrap,q=n.Chart,l=n.Axis,a=n.Tick,p=function(b){var k=b.options;k.labels||(k.labels={});k.labels.align=y(k.labels.align,"center");b.categories||(k.showLastLabel=!1);b.labelRotation=0;k.labels.rotation=0},A={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};l.prototype.isOuterAxis=function(){var b=this,k=b.columnIndex,g=b.linkedParent&&b.linkedParent.columns||b.columns,a=k?b.linkedParent:
b,d=-1,f=0;b.chart[b.coll].forEach(function(k,g){k.side!==b.side||k.options.isInternal||(f=g,k===a&&(d=g))});return f===d&&(v(k)?g.length===k:!0)};l.prototype.getMaxLabelDimensions=function(b,k){var g={width:0,height:0};k.forEach(function(k){k=b[k];if(f(k)){var a=f(k.label)?k.label:{};k=a.getBBox?a.getBBox().height:0;a.textStr&&!v(a.textPxLength)&&(a.textPxLength=a.getBBox().width);a=v(a.textPxLength)?Math.round(a.textPxLength):0;g.height=Math.max(k,g.height);g.width=Math.max(a,g.width)}});return g};
n.dateFormats.W=function(b){b=new Date(b);b.setHours(0,0,0,0);b.setDate(b.getDate()-(b.getDay()||7));var k=new Date(b.getFullYear(),0,1);return Math.ceil(((b-k)/864E5+1)/7)};n.dateFormats.E=function(b){return c("%a",b,!0).charAt(0)};u(a,"afterGetLabelPosition",function(b){var k=this.label,g=this.axis,a=g.reversed,d=g.chart,h=g.options,l=h&&f(h.grid)?h.grid:{};h=g.options.labels;var p=h.align,m=A[g.side],w=b.tickmarkOffset,t=g.tickPositions,B=this.pos-w;t=v(t[b.index+1])?t[b.index+1]-w:g.max+w;var q=
g.tickSize("tick",!0);w=z(q)?q[0]:0;q=q&&q[1]/2;if(!0===l.enabled){if("top"===m){l=g.top+g.offset;var c=l-w}else"bottom"===m?(c=d.chartHeight-g.bottom+g.offset,l=c+w):(l=g.top+g.len-g.translate(a?t:B),c=g.top+g.len-g.translate(a?B:t));"right"===m?(m=d.chartWidth-g.right+g.offset,a=m+w):"left"===m?(a=g.left+g.offset,m=a-w):(m=Math.round(g.left+g.translate(a?t:B))-q,a=Math.round(g.left+g.translate(a?B:t))-q);this.slotWidth=a-m;b.pos.x="left"===p?m:"right"===p?a:m+(a-m)/2;b.pos.y=c+(l-c)/2;d=d.renderer.fontMetrics(h.style.fontSize,
k.element);k=k.getBBox().height;h.useHTML?b.pos.y+=d.b+-(k/2):(k=Math.round(k/d.h),b.pos.y+=(d.b-(d.h-d.f))/2+-((k-1)*d.h/2));b.pos.x+=g.horiz&&h.x||0}});u(l,"afterTickSize",function(b){var k=this.defaultLeftAxisOptions,g=this.horiz,a=this.options.grid;a=void 0===a?{}:a;var d=this.maxLabelDimensions;a.enabled&&(k=2*Math.abs(k.labels.x),g=g?a.cellHeight||k+d.height:k+d.width,z(b.tickSize)?b.tickSize[0]=g:b.tickSize=[g])});u(l,"afterGetTitlePosition",function(b){var k=this.options;if(!0===(k&&f(k.grid)?
k.grid:{}).enabled){var a=this.axisTitle,d=a&&a.getBBox().width,h=this.horiz,m=this.left,l=this.top,q=this.width,p=this.height,w=k.title;k=this.opposite;var t=this.offset,B=this.tickSize()||[0],c=w.x||0,n=w.y||0,H=y(w.margin,h?5:10);a=this.chart.renderer.fontMetrics(w.style&&w.style.fontSize,a).f;B=(h?l+p:m)+B[0]/2*(k?-1:1)*(h?1:-1)+(this.side===A.bottom?a:0);b.titlePosition.x=h?m-d/2-H+c:B+(k?q:0)+t+c;b.titlePosition.y=h?B-(k?p:0)+(k?a:-a)/2+t+n:l-H+n}});h(l.prototype,"unsquish",function(b){var k=
this.options;return!0===(k&&f(k.grid)?k.grid:{}).enabled&&this.categories?this.tickInterval:b.apply(this,Array.prototype.slice.call(arguments,1))});u(l,"afterSetOptions",function(b){var k=this.options;b=b.userOptions;var a=k&&f(k.grid)?k.grid:{};if(!0===a.enabled){var h=d(!0,{className:"highcharts-grid-axis "+(b.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},
labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},b);"xAxis"===this.coll&&(e(b.linkedTo)&&!e(b.tickPixelInterval)&&(h.tickPixelInterval=350),e(b.tickPixelInterval)||!e(b.linkedTo)||e(b.tickPositioner)||e(b.tickInterval)||(h.tickPositioner=function(b,k){var a=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;
if(a){var g,d=h.units;for(g=0;g<d.length;g++)if(d[g][0]===a.unitName){var w=g;break}if(d[w+1]){var t=d[w+1][0];var B=(d[w+1][1]||[1])[0]}else"year"===a.unitName&&(t="year",B=10*a.count);a=n.timeUnits[t];this.tickInterval=a*B;return this.getTimeTicks({unitRange:a,count:B,unitName:t},b,k,this.options.startOfWeek)}}));d(!0,this.options,h);this.horiz&&(k.minPadding=y(b.minPadding,0),k.maxPadding=y(b.maxPadding,0));v(k.grid.borderWidth)&&(k.tickWidth=k.lineWidth=a.borderWidth)}});u(l,"afterSetAxisTranslation",
function(){var b=this.options,a=b&&f(b.grid)?b.grid:{},g=this.tickPositions&&this.tickPositions.info,d=this.userOptions.labels||{};this.horiz&&(!0===a.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),g&&(!1===b.dateTimeLabelFormats[g.unitName].range||1<g.count)&&!e(d.align)&&(b.labels.align="left",e(d.x)||(b.labels.x=3)))});u(l,"trimTicks",function(){var b=this.options,a=b&&f(b.grid)?b.grid:{},d=this.categories,h=this.tickPositions,m=h[0],l=h[h.length-1],q=this.linkedParent&&this.linkedParent.min||
this.min,p=this.linkedParent&&this.linkedParent.max||this.max,c=this.tickInterval;!0!==a.enabled||d||!this.horiz&&!this.isLinked||(m<q&&m+c>q&&!b.startOnTick&&(h[0]=q),l>p&&l-c<p&&!b.endOnTick&&(h[h.length-1]=p))});u(l,"afterRender",function(){var b=this.options,a=b&&f(b.grid)?b.grid:{},d=this.chart.renderer;if(!0===a.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var h=b.lineWidth;
if(h){var m=this.getLinePath(h);var l=m.indexOf("M")+1;var q=m.indexOf("L")+1;a=m.indexOf("M")+2;var p=m.indexOf("L")+2;var c=(this.tickSize("tick")[0]-1)*(this.side===A.top||this.side===A.left?-1:1);this.horiz?(m[a]+=c,m[p]+=c):(m[l]+=c,m[q]+=c);this.axisLineExtra?this.axisLineExtra.animate({d:m}):(this.axisLineExtra=d.path(m).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),d.styledMode||this.axisLineExtra.attr({stroke:b.lineColor,"stroke-width":h}));this.axisLine[this.showAxis?
"show":"hide"](!0)}}(this.columns||[]).forEach(function(b){b.render()})}});var m={afterGetOffset:function(){(this.columns||[]).forEach(function(b){b.getOffset()})},afterInit:function(){var b=this.chart,a=this.userOptions,g=this.options;g=g&&f(g.grid)?g.grid:{};g.enabled&&(p(this),h(this,"labelFormatter",function(b){var a=this.axis,k=a.tickPositions,d=this.value,t=(a.isLinked?a.linkedParent:a).series[0],g=d===k[0];k=d===k[k.length-1];t=t&&n.find(t.options.data,function(b){return b[a.isXAxis?"x":"y"]===
d});this.isFirst=g;this.isLast=k;this.point=t;return b.call(this)}));if(g.columns)for(var m=this.columns=[],q=this.columnIndex=0;++q<g.columns.length;){var c=d(a,g.columns[g.columns.length-q-1],{linkedTo:0,type:"category"});delete c.grid.columns;c=new l(this.chart,c,!0);c.isColumn=!0;c.columnIndex=q;x(b.axes,c);x(b[this.coll],c);m.push(c)}},afterSetOptions:function(b){b=(b=b.userOptions)&&f(b.grid)?b.grid:{};var a=b.columns;b.enabled&&a&&d(!0,this.options,a[a.length-1])},afterSetScale:function(){(this.columns||
[]).forEach(function(b){b.setScale()})},destroy:function(b){(this.columns||[]).forEach(function(a){a.destroy(b.keepEvents)})},init:function(b){var a=(b=b.userOptions)&&f(b.grid)?b.grid:{};a.enabled&&e(a.borderColor)&&(b.tickColor=b.lineColor=a.borderColor)}};Object.keys(m).forEach(function(b){u(l,b,m[b])});u(q,"afterSetChartSize",function(){this.axes.forEach(function(b){(b.columns||[]).forEach(function(b){b.setAxisSize();b.setAxisTranslation()})})})});C(e,"parts-gantt/Tree.js",[e["parts/Utilities.js"]],
function(n){var e=n.extend,D=n.isNumber,x=n.pick,z=function(n,e){var c=n.reduce(function(c,d){var h=x(d.parent,"");"undefined"===typeof c[h]&&(c[h]=[]);c[h].push(d);return c},{});Object.keys(c).forEach(function(f,d){var h=c[f];""!==f&&-1===e.indexOf(f)&&(h.forEach(function(h){d[""].push(h)}),delete d[f])});return c},v=function(n,r,c,f,d,h){var q=0,l=0,a=h&&h.after,p=h&&h.before;r={data:f,depth:c-1,id:n,level:c,parent:r};var A,m;"function"===typeof p&&p(r,h);p=(d[n]||[]).map(function(b){var a=v(b.id,
n,c+1,b,d,h),g=b.start;b=!0===b.milestone?g:b.end;A=!D(A)||g<A?g:A;m=!D(m)||b>m?b:m;q=q+1+a.descendants;l=Math.max(a.height+1,l);return a});f&&(f.start=x(f.start,A),f.end=x(f.end,m));e(r,{children:p,descendants:q,height:l});"function"===typeof a&&a(r,h);return r};return{getListOfParents:z,getNode:v,getTree:function(n,e){var c=n.map(function(c){return c.id});n=z(n,c);return v("",null,1,null,n,e)}}});C(e,"mixins/tree-series.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(n,e){var r=e.extend,
x=e.isArray,z=e.isNumber,v=e.isObject,y=e.pick,u=n.merge;return{getColor:function(c,f){var d=f.index,h=f.mapOptionsToLevel,q=f.parentColor,l=f.parentColorIndex,a=f.series,p=f.colors,A=f.siblings,m=a.points,b=a.chart.options.chart,k;if(c){m=m[c.i];c=h[c.level]||{};if(h=m&&c.colorByPoint){var g=m.index%(p?p.length:b.colorCount);var e=p&&p[g]}if(!a.chart.styledMode){p=m&&m.options.color;b=c&&c.color;if(k=q)k=(k=c&&c.colorVariation)&&"brightness"===k.key?n.color(q).brighten(d/A*k.to).get():q;k=y(p,b,
e,k,a.color)}var r=y(m&&m.options.colorIndex,c&&c.colorIndex,g,l,f.colorIndex)}return{color:k,colorIndex:r}},getLevelOptions:function(c){var f=null;if(v(c)){f={};var d=z(c.from)?c.from:1;var h=c.levels;var q={};var l=v(c.defaults)?c.defaults:{};x(h)&&(q=h.reduce(function(a,h){if(v(h)&&z(h.level)){var c=u({},h);var m="boolean"===typeof c.levelIsConstant?c.levelIsConstant:l.levelIsConstant;delete c.levelIsConstant;delete c.level;h=h.level+(m?0:d-1);v(a[h])?r(a[h],c):a[h]=c}return a},{}));h=z(c.to)?
c.to:1;for(c=0;c<=h;c++)f[c]=u({},l,v(q[c])?q[c]:{})}return f},setTreeValues:function h(f,d){var q=d.before,l=d.idRoot,a=d.mapIdToNode[l],p=d.points[f.i],n=p&&p.options||{},m=0,b=[];r(f,{levelDynamic:f.level-(("boolean"===typeof d.levelIsConstant?d.levelIsConstant:1)?0:a.level),name:y(p&&p.name,""),visible:l===f.id||("boolean"===typeof d.visible?d.visible:!1)});"function"===typeof q&&(f=q(f,d));f.children.forEach(function(a,g){var k=r({},d);r(k,{index:g,siblings:f.children.length,visible:f.visible});
a=h(a,k);b.push(a);a.visible&&(m+=a.val)});f.visible=0<m||f.visible;q=y(n.value,m);r(f,{children:b,childrenTotal:m,isLeaf:f.visible&&!m,val:q});return f},updateRootId:function(f){if(v(f)){var d=v(f.options)?f.options:{};d=y(f.rootNode,d.rootId,"");v(f.userOptions)&&(f.userOptions.rootId=d);f.rootNode=d}return d}}});C(e,"modules/broken-axis.src.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(n,e){var r=e.extend,x=e.isArray,z=e.pick;e=n.addEvent;var v=n.find,y=n.fireEvent,u=n.Axis,c=n.Series,
f=function(d,h){return v(h,function(h){return h.from<d&&d<h.to})};r(u.prototype,{isInBreak:function(d,h){var c=d.repeat||Infinity,l=d.from,a=d.to-d.from;h=h>=l?(h-l)%c:c-(l-h)%c;return d.inclusive?h<=a:h<a&&0!==h},isInAnyBreak:function(d,h){var c=this.options.breaks,l=c&&c.length,a;if(l){for(;l--;)if(this.isInBreak(c[l],d)){var f=!0;a||(a=z(c[l].showPoints,!this.isXAxis))}var e=f&&h?f&&!a:f}return e}});e(u,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,
!1)});e(u,"afterSetTickPositions",function(){if(this.isBroken){var d=this.tickPositions,h=this.tickPositions.info,c=[],l;for(l=0;l<d.length;l++)this.isInAnyBreak(d[l])||c.push(d[l]);this.tickPositions=c;this.tickPositions.info=h}});e(u,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});u.prototype.setBreaks=function(d,h){function c(d){var h=d,b;for(b=0;b<a.breakArray.length;b++){var c=a.breakArray[b];if(c.to<=d)h-=c.len;else if(c.from>=d)break;else if(a.isInBreak(c,d)){h-=d-c.from;
break}}return h}function l(d){var c;for(c=0;c<a.breakArray.length;c++){var b=a.breakArray[c];if(b.from>=d)break;else b.to<d?d+=b.len:a.isInBreak(b,d)&&(d+=b.len)}return d}var a=this,e=x(d)&&!!d.length;a.isDirty=a.isBroken!==e;a.isBroken=e;a.options.breaks=a.userOptions.breaks=d;a.forceRedraw=!0;e||a.val2lin!==c||(delete a.val2lin,delete a.lin2val);e&&(a.userOptions.ordinal=!1,a.val2lin=c,a.lin2val=l,a.setExtremes=function(a,d,b,c,h){if(this.isBroken){for(var g,k=this.options.breaks;g=f(a,k);)a=g.to;
for(;g=f(d,k);)d=g.from;d<a&&(d=a)}u.prototype.setExtremes.call(this,a,d,b,c,h)},a.setAxisTranslation=function(d){u.prototype.setAxisTranslation.call(this,d);this.unitLength=null;if(this.isBroken){d=a.options.breaks;var c=[],b=[],h=0,g,l=a.userMin||a.min,f=a.userMax||a.max,e=z(a.pointRangePadding,0),n;d.forEach(function(b){g=b.repeat||Infinity;a.isInBreak(b,l)&&(l+=b.to%g-l%g);a.isInBreak(b,f)&&(f-=f%g-b.from%g)});d.forEach(function(a){p=a.from;for(g=a.repeat||Infinity;p-g>l;)p-=g;for(;p<l;)p+=g;
for(n=p;n<f;n+=g)c.push({value:n,move:"in"}),c.push({value:n+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var q=0;var p=l;c.forEach(function(a){q+="in"===a.move?1:-1;1===q&&"in"===a.move&&(p=a.value);0===q&&(b.push({from:p,to:a.value,len:a.value-p-(a.size||0)}),h+=a.value-p-(a.size||0))});a.breakArray=b;a.unitLength=f-l-h+e;y(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:a.unitLength&&
(a.transA*=(f-a.min+e)/a.unitLength);e&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=l;a.max=f}});z(h,!0)&&this.chart.redraw()};e(c,"afterGeneratePoints",function(){var d=this.xAxis,c=this.yAxis,f=this.points,l=f.length,a=this.options.connectNulls;if(d&&c&&(d.options.breaks||c.options.breaks))for(;l--;){var e=f[l];var n=null===e.y&&!1===a;n||!d.isInAnyBreak(e.x,!0)&&!c.isInAnyBreak(e.y,!0)||(f.splice(l,1),this.data[l]&&this.data[l].destroyElements())}});e(c,"afterRender",function(){this.drawBreaks(this.xAxis,
["x"]);this.drawBreaks(this.yAxis,z(this.pointArrayMap,["y"]))});n.Series.prototype.drawBreaks=function(d,c){var h=this,f=h.points,a,e,n,m;d&&c.forEach(function(b){a=d.breakArray||[];e=d.isXAxis?d.min:z(h.options.threshold,d.min);f.forEach(function(c){m=z(c["stack"+b.toUpperCase()],c[b]);a.forEach(function(a){n=!1;if(e<a.from&&m>a.to||e>a.from&&m<a.from)n="pointBreak";else if(e<a.from&&m>a.from&&m<a.to||e>a.from&&m>a.to&&m<a.from)n="pointInBreak";n&&y(d,n,{point:c,brk:a})})})})};n.Series.prototype.gappedPath=
function(){var d=this.currentDataGrouping,c=d&&d.gapSize;d=this.options.gapSize;var f=this.points.slice(),e=f.length-1,a=this.yAxis;if(d&&0<e)for("value"!==this.options.gapUnit&&(d*=this.basePointRange),c&&c>d&&c>=this.basePointRange&&(d=c);e--;)f[e+1].x-f[e].x>d&&(c=(f[e].x+f[e+1].x)/2,f.splice(e+1,0,{isNull:!0,x:c}),this.options.stacking&&(c=a.stacks[this.stackKey][c]=new n.StackItem(a,a.options.stackLabels,!1,c,this.stack),c.total=0));return this.getGraphPath(f)}});C(e,"parts-gantt/TreeGrid.js",
[e["parts/Globals.js"],e["parts/Utilities.js"],e["parts-gantt/Tree.js"],e["mixins/tree-series.js"]],function(e,r,C,x){var n=r.defined,v=r.extend,y=r.isNumber,u=r.isString,c=r.pick,f=e.addEvent,d=function(a){return Array.prototype.slice.call(a,1)},h=e.find,q=e.fireEvent,l=x.getLevelOptions,a=e.merge,p=function(a){return r.isObject(a,!0)},A=e.wrap;x=e.Axis;var m=e.Tick,b=function(a,b){var c;for(c in b)if(Object.hasOwnProperty.call(b,c)){var d=b[c];A(a,c,d)}},k=function(a,b){var c=a.collapseStart;a=
a.collapseEnd;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}},g=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(b,c){c=+c;a.min<=c&&a.max>=c&&!a.isInAnyBreak(c)&&b.push(c);return b},[])},D=function(a,b){var c=a.options.breaks||[],d=k(b,a.max);return c.some(function(a){return a.from===d.from&&a.to===d.to})},E=function(a,b){var c=a.options.breaks||[];a=k(b,a.max);c.push(a);return c},F=function(a,b){var c=a.options.breaks||[],d=k(b,a.max);return c.reduce(function(a,b){b.to===d.to&&
b.from===d.from||a.push(b);return a},[])},I=function(a,b){var d=a.labelIcon,e=!d,h=b.renderer,f=b.xy,g=b.options,k=g.width,t=g.height,l=f.x-k/2-g.padding;f=f.y-t/2;var m=b.collapsed?90:180,n=b.show&&y(f);e&&(a.labelIcon=d=h.path(h.symbols[g.type](g.x,g.y,k,t)).addClass("highcharts-label-icon").add(b.group));n||d.attr({y:-9999});h.styledMode||d.attr({"stroke-width":1,fill:c(b.color,"#666666")}).css({cursor:"pointer",stroke:g.lineColor,strokeWidth:g.lineWidth});d[e?"attr":"animate"]({translateX:l,translateY:f,
rotation:m})},J=function(a,b,c){var d=[],e=[],f={},g={},k=-1,t="boolean"===typeof b?b:!1;a=C.getTree(a,{after:function(a){a=g[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=a.descendants+1;b=Math.max(a.height+1,b)});a.descendants=c;a.height=b;a.collapsed&&e.push(a)},before:function(a){var b=p(a.data)?a.data:{},c=u(b.name)?b.name:"",e=f[a.parent];e=p(e)?g[e.pos]:null;var l=function(a){return a.name===c},m;t&&p(e)&&(m=h(e.children,l))?(l=m.pos,m.nodes.push(a)):l=k++;g[l]||(g[l]=m={depth:e?e.depth+
1:0,name:c,nodes:[a],children:[],pos:l},-1!==l&&d.push(c),p(e)&&e.children.push(m));u(a.id)&&(f[a.id]=a);!0===b.collapsed&&(m.collapsed=!0);a.pos=l}});g=function(a,b){var c=function(a,d,e){var g=d+(-1===d?0:b-1),f=(g-d)/2,h=d+f;a.nodes.forEach(function(a){var b=a.data;p(b)&&(b.y=d+b.seriesIndex,delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=f+.5;a.collapseStart=g+.5;a.children.forEach(function(a){c(a,g+1,e);g=a.collapseEnd-.5});a.collapseEnd=g+.5;return e};return c(a["-1"],-1,{})}(g,
c);return{categories:d,mapOfIdToNode:f,mapOfPosToGridNode:g,collapsedNodes:e,tree:a}},G=function(b){b.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(c){var d=c.options||{},g=d.labels,h,f=d.uniqueNames,k=0;if(!c.mapOfPosToGridNode||c.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){d=c.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){p(b)&&(b.seriesIndex=k,a.push(b))}),!0===f&&k++);return a},[]);var m=J(d,f,!0===
f?k:1);c.categories=m.categories;c.mapOfPosToGridNode=m.mapOfPosToGridNode;c.hasNames=!0;c.tree=m.tree;c.series.forEach(function(b){var c=b.options.data.map(function(b){return p(b)?a(b):b});b.visible&&b.setData(c,!1)});c.mapOptionsToLevel=l({defaults:g,from:1,levels:g.levels,to:c.tree.height});"beforeRender"===b.type&&(h=e.addEvent(c,"foundExtremes",function(){m.collapsedNodes.forEach(function(a){a=E(c,a);c.setBreaks(a,!1)});h()}))}})};b(x.prototype,{init:function(b,c,d){var e="treegrid"===d.type;
e&&(f(c,"beforeRender",G),f(c,"beforeRedraw",G),d=a({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[c,d]);e&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(a){var b=this.options,c=b&&b.labels;b=c&&y(c.indentation)?b.labels.indentation:0;c=a.apply(this,d(arguments));if("treegrid"===
this.options.type&&this.mapOfPosToGridNode){var e=this.mapOfPosToGridNode[-1].height;c.width+=b*(e-1)}return c},generateTick:function(a,b){var c=p(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=this.ticks,g=e[b],f;if("treegrid"===this.options.type){var h=this.mapOfPosToGridNode[b];(c=c[h.depth])&&(f={labels:c});g?(g.parameters.category=h.name,g.options=f,g.addLabel()):e[b]=new m(this,b,null,void 0,{category:h.name,tickmarkOffset:h.tickmarkOffset,options:f})}else a.apply(this,d(arguments))},setTickInterval:function(a){var b=
this.options;"treegrid"===b.type?(this.min=c(this.userMin,b.min,this.dataMin),this.max=c(this.userMax,b.max,this.dataMax),q(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?g(this):[]):a.apply(this,d(arguments))}});b(m.prototype,{getLabelPosition:function(a,b,d,e,g,h,f,k,m){var l=c(this.options&&this.options.labels,h);h=this.pos;var n=this.axis,t="treegrid"===n.options.type;a=a.apply(this,[b,d,e,g,l,f,k,m]);t&&
(b=l&&p(l.symbol)?l.symbol:{},l=l&&y(l.indentation)?l.indentation:0,h=(h=(n=n.mapOfPosToGridNode)&&n[h])&&h.depth||1,a.x+=b.width+2*b.padding+(h-1)*l);return a},renderLabel:function(a){var b=this,h=b.pos,g=b.axis,f=b.label,k=g.mapOfPosToGridNode,l=g.options,m=c(b.options&&b.options.labels,l&&l.labels),q=m&&p(m.symbol)?m.symbol:{},r=(k=k&&k[h])&&k.depth;l="treegrid"===l.type;var w=!(!f||!f.element),u=-1<g.tickPositions.indexOf(h);h=g.chart.styledMode;l&&k&&w&&f.addClass("highcharts-treegrid-node-level-"+
r);a.apply(b,d(arguments));l&&k&&w&&0<k.descendants&&(g=D(g,k),I(b,{color:!h&&f.styles.color,collapsed:g,group:f.parentGroup,options:q,renderer:f.renderer,show:u,xy:f.xy}),q="highcharts-treegrid-node-"+(g?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(g?"collapsed":"expanded")).removeClass(q),h||f.css({cursor:"pointer"}),[f,b.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(e.addEvent(a.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||
f.css({textDecoration:"underline"})}),e.addEvent(a.element,"mouseout",function(){var a=n(m.style)?m.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}),e.addEvent(a.element,"click",function(){b.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}});v(m.prototype,{collapse:function(a){var b=this.axis,d=E(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(d,c(a,!0))},expand:function(a){var b=this.axis,d=F(b,b.mapOfPosToGridNode[this.pos]);
b.setBreaks(d,c(a,!0))},toggleCollapse:function(a){var b=this.axis;var d=b.mapOfPosToGridNode[this.pos];d=D(b,d)?F(b,d):E(b,d);b.setBreaks(d,c(a,!0))}});x.prototype.utils={getNode:C.getNode}});C(e,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map