/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(n){b(n);b.Highcharts=n;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function n(p,d,b,h){p.hasOwnProperty(d)||(p[d]=h.apply(null,b))}b=b?b._modules:{};n(b,"mixins/tree-series.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,d){var p=d.extend,h=d.isArray,x=d.isNumber,g=
d.isObject,v=d.pick,n=b.merge;return{getColor:function(e,k){var d=k.index,p=k.mapOptionsToLevel,l=k.parentColor,h=k.parentColorIndex,g=k.series,r=k.colors,G=k.siblings,q=g.points,n=g.chart.options.chart,w;if(e){q=q[e.i];e=p[e.level]||{};if(p=q&&e.colorByPoint){var x=q.index%(r?r.length:n.colorCount);var y=r&&r[x]}if(!g.chart.styledMode){r=q&&q.options.color;n=e&&e.color;if(w=l)w=(w=e&&e.colorVariation)&&"brightness"===w.key?b.color(l).brighten(d/G*w.to).get():l;w=v(r,n,y,w,g.color)}var C=v(q&&q.options.colorIndex,
e&&e.colorIndex,x,h,k.colorIndex)}return{color:w,colorIndex:C}},getLevelOptions:function(e){var k=null;if(g(e)){k={};var d=x(e.from)?e.from:1;var b=e.levels;var l={};var v=g(e.defaults)?e.defaults:{};h(b)&&(l=b.reduce(function(k,e){if(g(e)&&x(e.level)){var b=n({},e);var h="boolean"===typeof b.levelIsConstant?b.levelIsConstant:v.levelIsConstant;delete b.levelIsConstant;delete b.level;e=e.level+(h?0:d-1);g(k[e])?p(k[e],b):k[e]=b}return k},{}));b=x(e.to)?e.to:1;for(e=0;e<=b;e++)k[e]=n({},v,g(l[e])?l[e]:
{})}return k},setTreeValues:function E(k,b){var d=b.before,h=b.idRoot,g=b.mapIdToNode[h],r=b.points[k.i],n=r&&r.options||{},q=0,x=[];p(k,{levelDynamic:k.level-(("boolean"===typeof b.levelIsConstant?b.levelIsConstant:1)?0:g.level),name:v(r&&r.name,""),visible:h===k.id||("boolean"===typeof b.visible?b.visible:!1)});"function"===typeof d&&(k=d(k,b));k.children.forEach(function(d,h){var g=p({},b);p(g,{index:h,siblings:k.children.length,visible:k.visible});d=E(d,g);x.push(d);d.visible&&(q+=d.val)});k.visible=
0<q||k.visible;d=v(n.value,q);p(k,{children:x,childrenTotal:q,isLeaf:k.visible&&!q,val:d});return k},updateRootId:function(b){if(g(b)){var d=g(b.options)?b.options:{};d=v(b.rootNode,d.rootId,"");g(b.userOptions)&&(b.userOptions.rootId=d);b.rootNode=d}return d}}});n(b,"mixins/draw-point.js",[],function(){var b=function(b){var d=this,h=d.graphic,p=b.animatableAttribs,g=b.onComplete,n=b.css,A=b.renderer;if(d.shouldDraw())h||(d.graphic=h=A[b.shapeType](b.shapeArgs).add(b.group)),h.css(n).attr(b.attribs).animate(p,
b.isNew?!1:void 0,g);else if(h){var e=function(){d.graphic=h=h.destroy();"function"===typeof g&&g()};Object.keys(p).length?h.animate(p,void 0,function(){e()}):e()}};return function(d){(d.attribs=d.attribs||{})["class"]=this.getClassName();b.call(this,d)}});n(b,"modules/treemap.src.js",[b["parts/Globals.js"],b["mixins/tree-series.js"],b["mixins/draw-point.js"],b["parts/Utilities.js"]],function(b,d,n,h){var p=h.correctFloat,g=h.defined,v=h.extend,A=h.isArray,e=h.isNumber,k=h.isObject,D=h.isString,E=
h.objectEach,l=h.pick;h=b.seriesType;var F=b.seriesTypes,I=b.addEvent,r=b.merge,G=b.error,q=b.noop,C=b.fireEvent,w=d.getColor,K=d.getLevelOptions,y=b.Series,L=b.stableSort,J=b.Color,M=function(a,c,f){f=f||this;E(a,function(b,m){c.call(f,b,m,a)})},B=function(a,c,f){f=f||this;a=c.call(f,a);!1!==a&&B(a,c,f)},N=d.updateRootId;h("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?
this.point:{};return D(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",
brightness:F.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:q,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=A(a)?a:[];var f=A(c)?c:[];c=a.reduce(function(a,c,f){c=l(c.parent,"");"undefined"===typeof a[c]&&(a[c]=[]);a[c].push(f);return a},{"":[]});M(c,function(a,c,b){""!==c&&-1===f.indexOf(c)&&(a.forEach(function(a){b[""].push(a)}),
delete b[c])});return c},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,c){var f=b.colorMapSeriesMixin;f&&(this.colorAttribs=f.colorAttribs);I(this,"setOptions",function(a){a=a.userOptions;g(a.allowDrillToNode)&&!g(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);g(a.drillUpButton)&&
!g(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});y.prototype.init.call(this,a,c);this.options.allowTraversingTree&&I(this,"click",this.onClickDrillToNode)},buildNode:function(a,c,f,b,m){var u=this,t=[],d=u.points[c],e=0,z;(b[a]||[]).forEach(function(c){z=u.buildNode(u.points[c].id,c,f+1,b,a);e=Math.max(z.height+1,e);t.push(z)});c={id:a,i:c,children:t,height:e,level:f,parent:m,visible:!1};u.nodeMap[c.id]=c;d&&(d.node=c);return c},setTreeValues:function(a){var c=
this,f=c.options,b=c.nodeMap[c.rootNode];f="boolean"===typeof f.levelIsConstant?f.levelIsConstant:!0;var m=0,H=[],t=c.points[a.i];a.children.forEach(function(a){a=c.setTreeValues(a);H.push(a);a.ignore||(m+=a.val)});L(H,function(a,c){return a.sortIndex-c.sortIndex});var d=l(t&&t.options.value,m);t&&(t.value=d);v(a,{children:H,childrenTotal:m,ignore:!(l(t&&t.visible,!0)&&0<d),isLeaf:a.visible&&!m,levelDynamic:a.level-(f?0:b.level),name:l(t&&t.name,""),sortIndex:l(t&&t.sortIndex,-d),val:d});return a},
calculateChildrenAreas:function(a,c){var f=this,b=f.options,m=f.mapOptionsToLevel[a.level+1],d=l(f[m&&m.layoutAlgorithm]&&m.layoutAlgorithm,b.layoutAlgorithm),t=b.alternateStartingDirection,e=[];a=a.children.filter(function(a){return!a.ignore});m&&m.layoutStartingDirection&&(c.direction="vertical"===m.layoutStartingDirection?0:1);e=f[d](c,a);a.forEach(function(a,b){b=e[b];a.values=r(b,{val:a.childrenTotal,direction:t?1-c.direction:c.direction});a.pointValues=r(b,{x:b.x/f.axisRatio,width:b.width/f.axisRatio});
a.children.length&&f.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,c=a.xAxis,f=a.yAxis;a.points.forEach(function(b){var m=b.node,d=m.pointValues,t=0;a.chart.styledMode||(t=(a.pointAttribs(b)["stroke-width"]||0)%2/2);if(d&&m.visible){m=Math.round(c.translate(d.x,0,0,0,1))-t;var e=Math.round(c.translate(d.x+d.width,0,0,0,1))-t;var u=Math.round(f.translate(d.y,0,0,0,1))-t;d=Math.round(f.translate(d.y+d.height,0,0,0,1))-t;b.shapeArgs={x:Math.min(m,e),y:Math.min(u,d),width:Math.abs(e-
m),height:Math.abs(d-u)};b.plotX=b.shapeArgs.x+b.shapeArgs.width/2;b.plotY=b.shapeArgs.y+b.shapeArgs.height/2}else delete b.plotX,delete b.plotY})},setColorRecursive:function(a,c,b,d,m){var f=this,e=f&&f.chart;e=e&&e.options&&e.options.colors;if(a){var u=w(a,{colors:e,index:d,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:c,parentColorIndex:b,series:f,siblings:m});if(c=f.points[a.i])c.color=u.color,c.colorIndex=u.colorIndex;(a.children||[]).forEach(function(c,b){f.setColorRecursive(c,u.color,u.colorIndex,
b,a.children.length)})}},algorithmGroup:function(a,c,b,d){this.height=a;this.width=c;this.plot=d;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),
this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,b,d){var f,e,u,k,h=b.lW,z=b.lH,g=b.plot,n=0,l=b.elArr.length-
1;if(c)h=b.nW,z=b.nH;else var r=b.elArr[b.elArr.length-1];b.elArr.forEach(function(a){if(c||n<l)0===b.direction?(f=g.x,e=g.y,u=h,k=a/u):(f=g.x,e=g.y,k=z,u=a/k),d.push({x:f,y:e,width:u,height:p(k)}),0===b.direction?g.y+=k:g.x+=u;n+=1});b.reset();0===b.direction?b.width-=h:b.height-=z;g.y=g.parent.y+(g.parent.height-b.height);g.x=g.parent.x+(g.parent.width-b.width);a&&(b.direction=1-b.direction);c||b.addElement(r)},algorithmLowAspectRatio:function(a,c,b){var f=[],m=this,d,e={x:c.x,y:c.y,parent:c},g=
0,k=b.length-1,h=new this.algorithmGroup(c.height,c.width,c.direction,e);b.forEach(function(b){d=b.val/c.val*c.height*c.width;h.addElement(d);h.lP.nR>h.lP.lR&&m.algorithmCalcPoints(a,!1,h,f,e);g===k&&m.algorithmCalcPoints(a,!0,h,f,e);g+=1});return f},algorithmFill:function(a,b,f){var c=[],d,e=b.direction,g=b.x,h=b.y,k=b.width,n=b.height,l,r,p,q;f.forEach(function(f){d=f.val/b.val*b.height*b.width;l=g;r=h;0===e?(q=n,p=d/q,k-=p,g+=p):(p=k,q=d/p,n-=q,h+=q);c.push({x:l,y:r,width:p,height:q});a&&(e=1-
e)});return c},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,f=N(a);y.prototype.translate.call(a);var d=a.tree=a.getTree();var e=a.nodeMap[f];a.renderTraverseUpButton(f);a.mapOptionsToLevel=K({from:e.level+1,levels:b.levels,to:d.height,defaults:{levelIsConstant:a.options.levelIsConstant,
colorByPoint:b.colorByPoint}});""===f||e&&e.children.length||(a.setRootNode("",!1),f=a.rootNode,e=a.nodeMap[f]);B(a.nodeMap[a.rootNode],function(b){var c=!1,f=b.parent;b.visible=!0;if(f||""===f)c=a.nodeMap[f];return c});B(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(d);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=f={x:0,y:0,width:100,height:100};a.nodeMap[""].values=
f=r(f,{width:f.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:d.val});a.calculateChildrenAreas(d,f);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=e.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,f,d;a.points.filter(function(a){return a.node.visible}).forEach(function(c){d=
b[c.node.level];f={style:{}};c.node.isLeaf||(f.enabled=!1);d&&d.dataLabels&&(f=r(f,d.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(f.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=r(f,c.options.dataLabels)});y.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,b,f){var c=f.style;!g(c.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:c.width+="px"});F.column.prototype.alignDataLabel.apply(this,
arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=k(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{};c=this.options;var e=b&&c.states[b]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||e.borderColor||c.borderColor,"stroke-width":l(a&&a.borderWidth,d.borderWidth,e.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||e.borderDashStyle||c.borderDashStyle,fill:a&&a.color||
this.color};-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(b=l(e.opacity,c.opacity),a.fill=J(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=J(a.fill).brighten(e.brightness).get());return a},drawPoints:function(){var a=this,b=a.chart,f=b.renderer,d=b.styledMode,e=a.options,g=d?{}:e.shadow,h=e.borderRadius,k=b.pointCount<e.animationLimit,n=e.allowTraversingTree;
a.points.forEach(function(b){var c=b.node.levelDynamic,m={},u={},p={},l="level-group-"+c,q=!!b.graphic,t=k&&q,w=b.shapeArgs;b.shouldDraw()&&(h&&(u.r=h),r(!0,t?m:u,q?w:{},d?{}:a.pointAttribs(b,b.selected&&"select")),a.colorAttribs&&d&&v(p,a.colorAttribs(b)),a[l]||(a[l]=f.g(l).attr({zIndex:1E3-c}).add(a.group),a[l].survive=!0));b.draw({animatableAttribs:m,attribs:u,css:p,group:a[l],renderer:f,shadow:g,shapeArgs:w,shapeType:"rect"});n&&b.graphic&&(b.drillId=e.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},
onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;D(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&D(a.parent)&&this.setRootNode(a.parent,
!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){G("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,b)},setRootNode:function(a,b,d){a=v({newRootId:a,previousRootId:this.rootNode,redraw:l(b,!0),series:this},d);C(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})},renderTraverseUpButton:function(a){var b=
this,d=b.options.traverseUpButton,e=l(d.text,b.nodeMap[a].name,"< Back");if(""===a)b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:e}).align();else{var g=(a=d.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(e,null,null,function(){b.drillUp()},a,g&&g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:d.position.align,zIndex:7}).add().align(d.position,!1,d.relativeTo||
"plotBox")}},buildKDTree:q,drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,getExtremes:function(){y.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;y.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};y.prototype.bindAxes.call(this);v(this.yAxis.options,a);v(this.xAxis.options,
a)},setState:function(a){this.options.inactiveOtherPoints=!0;y.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:B}},{draw:n,setVisible:F.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=b.Point.prototype.getClassName.call(this),c=this.series,d=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||l(d.interactByLeaf,!d.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):
a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||e(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return e(this.plotY)&&null!==this.y}});""});n(b,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map