/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 X-range series

 (c) 2010-2019 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/xrange",["highcharts"],function(h){b(h);b.Highcharts=h;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function h(q,b,B,h){q.hasOwnProperty(b)||(q[b]=h.apply(null,B))}b=b?b._modules:{};h(b,"modules/xrange.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.clamp,q=k.correctFloat,C=k.defined,
t=k.isNumber,v=k.isObject,w=k.pick;k=b.addEvent;var y=b.color,z=b.seriesTypes.column,u=b.merge,D=b.seriesType,E=b.Axis,x=b.Point,F=b.Series;D("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;v(a)&&(a=a.amount);if(t(a)&&0<a)return q(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},
borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:b.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:b.noop,buildKDTree:b.noop,getColumnMetrics:function(){function a(){e.series.forEach(function(a){var c=a.xAxis;a.xAxis=a.yAxis;a.yAxis=c})}var e=this.chart;a();var d=z.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,e,d,b){e=F.prototype.cropData.call(this,this.x2Data,e,d,b);e.xData=a.slice(e.start,
e.end);return e},findPointIndex:function(a){var e=this.data,d=this.points,A=a.id,c;if(A)var f=(c=b.find(e,function(a){return a.id===A}))?c.index:void 0;"undefined"===typeof f&&(f=(c=b.find(e,function(c){return c.x===a.x&&c.x2===a.x2&&!(d[f]&&d[f].touched)}))?c.index:void 0);this.cropped&&f>=this.cropStart&&(f-=this.cropStart);return f},translatePoint:function(a){var e=this.xAxis,d=this.yAxis,b=this.columnMetrics,c=this.options,f=c.minPointLength||0,m=a.plotX,r=w(a.x2,a.x+(a.len||0)),g=e.translate(r,
0,0,0,1);r=Math.abs(g-m);var n=this.chart.inverted,k=w(c.borderWidth,1)%2/2,l=b.offset,p=Math.round(b.width);f&&(f-=r,0>f&&(f=0),m-=f/2,g+=f/2);m=Math.max(m,-10);g=h(g,-10,e.len+10);C(a.options.pointWidth)&&(l-=(Math.ceil(a.options.pointWidth)-p)/2,p=Math.ceil(a.options.pointWidth));c.pointPlacement&&t(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,c.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(m,g))+k,y:Math.floor(a.plotY+l)+k,width:Math.round(Math.abs(g-m)),height:p,r:this.options.borderRadius};
c=a.shapeArgs.x;f=c+a.shapeArgs.width;0>c||f>e.len?(c=h(c,0,e.len),f=h(f,0,e.len),g=f-c,a.dlBox=u(a.shapeArgs,{x:c,width:f-c,centerX:g?g/2:null})):a.dlBox=null;c=a.tooltipPos;f=n?1:0;g=n?0:1;c[f]=h(c[f]+r/2*(e.reversed?-1:1)*(n?-1:1),0,e.len-1);c[g]=h(c[g]+b.width/2*(n?1:-1),0,d.len-1);if(b=a.partialFill)v(b)&&(b=b.amount),t(b)||(b=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},m=Math.max(Math.round(r*b+a.plotX-m),0),a.clipRectArgs={x:e.reversed?
d.x+r-m:d.x,y:d.y,width:m,height:d.height}},translate:function(){z.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var d=this.options,e=this.chart.renderer,c=a.graphic,f=a.shapeType,h=a.shapeArgs,k=a.partShapeArgs,g=a.clipRectArgs,n=a.partialFill,q=d.stacking&&!d.borderRadius,l=a.state,p=d.states[l||"normal"]||{},t="undefined"===typeof l?"attr":b;l=this.pointAttribs(a,l);p=w(this.chart.options.chart.animation,p.animation);
if(a.isNull)c&&(a.graphic=c.destroy());else{if(c)c.rect[b](h);else a.graphic=c=e.g("point").addClass(a.getClassName()).add(a.group||this.group),c.rect=e[f](u(h)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(c);k&&(c.partRect?(c.partRect[b](u(k)),c.partialClipRect[b](u(g))):(c.partialClipRect=e.clipRect(g.x,g.y,g.width,g.height),c.partRect=e[f](k).addClass("highcharts-partfill-overlay").add(c).clip(c.partialClipRect)));this.chart.styledMode||(c.rect[b](l,p).shadow(d.shadow,
null,q),k&&(v(n)||(n={}),v(d.partialFill)&&(n=u(n,d.partialFill)),a=n.fill||y(l.fill).brighten(-.3).get()||y(a.color||this.color).brighten(-.3).get(),l.fill=a,c.partRect[t](l,p).shadow(d.shadow,null,q)))}},drawPoints:function(){var a=this,b=a.getAnimationVerb();a.points.forEach(function(e){a.drawPoint(e,b)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var b=
a.options.colors||a.chart.options.colors;var d=this.y%(b?b.length:a.chart.options.chart.colorCount);b=b&&b[d];a.chart.styledMode||(this.color=b);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){x.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){x.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=x.prototype.getLabelConfig.call(this),
b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});k(E,"afterGetSeriesExtremes",function(){var a=this.series,b;if(this.isXAxis){var d=w(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>d&&(d=a,b=!0)})});b&&(this.dataMax=d)}});""});h(b,"masters/modules/xrange.src.js",[],function(){})});
//# sourceMappingURL=xrange.js.map