/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?(q["default"]=q,module.exports=q):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(B){q(B);q.Highcharts=B;return q}):q("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(q){function B(b,h,z,q){b.hasOwnProperty(h)||(b[h]=q.apply(null,z))}q=q?q._modules:{};B(q,"parts-3d/Math.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){var z=h.pick,q=b.deg2rad;b.perspective3D=function(b,
g,w){g=0<w&&w<Number.POSITIVE_INFINITY?w/(b.z+g.z+w):1;return{x:b.x*g,y:b.y*g}};b.perspective=function(x,g,w){var t=g.options.chart.options3d,v=w?g.inverted:!1,h={x:g.plotWidth/2,y:g.plotHeight/2,z:t.depth/2,vd:z(t.depth,1)*z(t.viewDistance,0)},y=g.scale3d||1,l=q*t.beta*(v?-1:1);t=q*t.alpha*(v?-1:1);var a=Math.cos(t),c=Math.cos(-l),k=Math.sin(t),p=Math.sin(-l);w||(h.x+=g.plotLeft,h.y+=g.plotTop);return x.map(function(d){var e=(v?d.y:d.x)-h.x;var m=(v?d.x:d.y)-h.y;d=(d.z||0)-h.z;e={x:c*e-p*d,y:-k*
p*e+a*m-c*k*d,z:a*p*e+k*m+a*c*d};m=b.perspective3D(e,h,h.vd);m.x=m.x*y+h.x;m.y=m.y*y+h.y;m.z=e.z*y+h.z;return{x:v?m.y:m.x,y:v?m.x:m.y,z:m.z}})};b.pointCameraDistance=function(b,g){var h=g.options.chart.options3d,t=g.plotWidth/2;g=g.plotHeight/2;h=z(h.depth,1)*z(h.viewDistance,0)+h.depth;return Math.sqrt(Math.pow(t-b.plotX,2)+Math.pow(g-b.plotY,2)+Math.pow(h-b.plotZ,2))};b.shapeArea=function(b){var g=0,h;for(h=0;h<b.length;h++){var t=(h+1)%b.length;g+=b[h].x*b[t].y-b[t].x*b[h].y}return g/2};b.shapeArea3d=
function(h,g,w){return b.shapeArea(b.perspective(h,g,w))}});B(q,"parts-3d/SVGRenderer.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){function q(a,d,f,F,C,c,b,m){var n=[],G=c-C;return c>C&&c-C>Math.PI/2+.0001?(n=n.concat(q(a,d,f,F,C,C+Math.PI/2,b,m)),n=n.concat(q(a,d,f,F,C+Math.PI/2,c,b,m))):c<C&&C-c>Math.PI/2+.0001?(n=n.concat(q(a,d,f,F,C,C-Math.PI/2,b,m)),n=n.concat(q(a,d,f,F,C-Math.PI/2,c,b,m))):["C",a+f*Math.cos(C)-f*e*G*Math.sin(C)+b,d+F*Math.sin(C)+F*e*G*Math.cos(C)+m,a+f*
Math.cos(c)+f*e*G*Math.sin(c)+b,d+F*Math.sin(c)-F*e*G*Math.cos(c)+m,a+f*Math.cos(c)+b,d+F*Math.sin(c)+m]}var r=h.animObject,x=h.defined,g=h.extend,w=h.objectEach,t=h.pick,v=Math.cos,A=Math.PI,y=Math.sin,l=b.charts,a=b.color,c=b.deg2rad,k=b.merge,p=b.perspective,d=b.SVGElement;h=b.SVGRenderer;var e=4*(Math.sqrt(2)-1)/3/(A/2);h.prototype.toLinePath=function(a,d){var f=[];a.forEach(function(a){f.push("L",a.x,a.y)});a.length&&(f[0]="M",d&&f.push("Z"));return f};h.prototype.toLineSegments=function(a){var d=
[],f=!0;a.forEach(function(a){d.push(f?"M":"L",a.x,a.y);f=!f});return d};h.prototype.face3d=function(a){var e=this,f=this.createElement("path");f.vertexes=[];f.insidePlotArea=!1;f.enabled=!0;f.attr=function(a){if("object"===typeof a&&(x(a.enabled)||x(a.vertexes)||x(a.insidePlotArea))){this.enabled=t(a.enabled,this.enabled);this.vertexes=t(a.vertexes,this.vertexes);this.insidePlotArea=t(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;var f=p(this.vertexes,
l[e.chartIndex],this.insidePlotArea),n=e.toLinePath(f,!0);f=b.shapeArea(f);f=this.enabled&&0<f?"visible":"hidden";a.d=n;a.visibility=f}return d.prototype.attr.apply(this,arguments)};f.animate=function(a){if("object"===typeof a&&(x(a.enabled)||x(a.vertexes)||x(a.insidePlotArea))){this.enabled=t(a.enabled,this.enabled);this.vertexes=t(a.vertexes,this.vertexes);this.insidePlotArea=t(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;var f=p(this.vertexes,
l[e.chartIndex],this.insidePlotArea),n=e.toLinePath(f,!0);f=b.shapeArea(f);f=this.enabled&&0<f?"visible":"hidden";a.d=n;this.attr("visibility",f)}return d.prototype.animate.apply(this,arguments)};return f.attr(a)};h.prototype.polyhedron=function(a){var e=this,f=this.g(),n=f.destroy;this.styledMode||f.attr({"stroke-linejoin":"round"});f.faces=[];f.destroy=function(){for(var a=0;a<f.faces.length;a++)f.faces[a].destroy();return n.call(this)};f.attr=function(a,n,c,b){if("object"===typeof a&&x(a.faces)){for(;f.faces.length>
a.faces.length;)f.faces.pop().destroy();for(;f.faces.length<a.faces.length;)f.faces.push(e.face3d().add(f));for(var m=0;m<a.faces.length;m++)e.styledMode&&delete a.faces[m].fill,f.faces[m].attr(a.faces[m],null,c,b);delete a.faces}return d.prototype.attr.apply(this,arguments)};f.animate=function(a,n,c){if(a&&a.faces){for(;f.faces.length>a.faces.length;)f.faces.pop().destroy();for(;f.faces.length<a.faces.length;)f.faces.push(e.face3d().add(f));for(var b=0;b<a.faces.length;b++)f.faces[b].animate(a.faces[b],
n,c);delete a.faces}return d.prototype.animate.apply(this,arguments)};return f.attr(a)};var m={initArgs:function(a){var d=this,f=d.renderer,e=f[d.pathType+"Path"](a),n=e.zIndexes;d.parts.forEach(function(a){d[a]=f.path(e[a]).attr({"class":"highcharts-3d-"+a,zIndex:n[a]||0}).add(d)});d.attr({"stroke-linejoin":"round",zIndex:n.group});d.originalDestroy=d.destroy;d.destroy=d.destroyParts},singleSetterForParts:function(a,d,f,e,c,b){var n={};e=[null,null,e||"attr",c,b];var m=f&&f.zIndexes;f?(w(f,function(d,
e){n[e]={};n[e][a]=d;m&&(n[e].zIndex=f.zIndexes[e]||0)}),e[1]=n):(n[a]=d,e[0]=n);return this.processParts.apply(this,e)},processParts:function(a,d,f,e,c){var n=this;n.parts.forEach(function(b){d&&(a=t(d[b],!1));if(!1!==a)n[b][f](a,e,c)});return n},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};var u=b.merge(m,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,e,f,c){if("string"===typeof a&&"undefined"!==typeof e){var n=a;a={};a[n]=e}return a.shapeArgs||
x(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):d.prototype.attr.call(this,a,void 0,f,c)},animate:function(a,e,f){x(a.x)&&x(a.y)?(a=this.renderer[this.pathType+"Path"](a),this.singleSetterForParts("d",null,a,"animate",e,f),this.attr({zIndex:a.zIndexes.group})):d.prototype.animate.call(this,a,e,f);return this},fillSetter:function(d){this.singleSetterForParts("fill",null,{front:d,top:a(d).brighten(.1).get(),side:a(d).brighten(-.1).get()});this.color=this.fill=
d;return this}});h.prototype.elements3d={base:m,cuboid:u};h.prototype.element3d=function(a,d){var f=this.g();g(f,this.elements3d[a]);f.initArgs(d);return f};h.prototype.cuboid=function(a){return this.element3d("cuboid",a)};b.SVGRenderer.prototype.cuboidPath=function(a){function d(a){return g[a]}var f=a.x,e=a.y,c=a.z,m=a.height,n=a.width,k=a.depth,u=l[this.chartIndex],y=u.options.chart.options3d.alpha,h=0,g=[{x:f,y:e,z:c},{x:f+n,y:e,z:c},{x:f+n,y:e+m,z:c},{x:f,y:e+m,z:c},{x:f,y:e+m,z:c+k},{x:f+n,y:e+
m,z:c+k},{x:f+n,y:e,z:c+k},{x:f,y:e,z:c+k}];g=p(g,u,a.insidePlotArea);var v=function(a,f){var e=[[],-1];a=a.map(d);f=f.map(d);0>b.shapeArea(a)?e=[a,0]:0>b.shapeArea(f)&&(e=[f,1]);return e};var t=v([3,2,1,0],[7,6,5,4]);a=t[0];n=t[1];t=v([1,6,7,0],[4,5,2,3]);m=t[0];k=t[1];t=v([1,2,5,6],[0,7,4,3]);v=t[0];t=t[1];1===t?h+=1E4*(1E3-f):t||(h+=1E4*f);h+=10*(!k||0<=y&&180>=y||360>y&&357.5<y?u.plotHeight-e:10+e);1===n?h+=100*c:n||(h+=100*(1E3-c));return{front:this.toLinePath(a,!0),top:this.toLinePath(m,!0),
side:this.toLinePath(v,!0),zIndexes:{group:Math.round(h)},isFront:n,isTop:k}};b.SVGRenderer.prototype.arc3d=function(e){function m(a){var f=!1,e={},d;a=k(a);for(d in a)-1!==u.indexOf(d)&&(e[d]=a[d],delete a[d],f=!0);return f?e:!1}var f=this.g(),n=f.renderer,u="x y r innerR start end".split(" ");e=k(e);e.alpha=(e.alpha||0)*c;e.beta=(e.beta||0)*c;f.top=n.path();f.side1=n.path();f.side2=n.path();f.inn=n.path();f.out=n.path();f.onAdd=function(){var a=f.parentGroup,e=f.attr("class");f.top.add(f);["out",
"inn","side1","side2"].forEach(function(d){f[d].attr({"class":e+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){f[a]=function(){var e=arguments;["top","out","inn","side1","side2"].forEach(function(d){f[d][a].apply(f[d],e)})}});f.setPaths=function(a){var e=f.renderer.arc3dPath(a),d=100*e.zTop;f.attribs=a;f.top.attr({d:e.top,zIndex:e.zTop});f.inn.attr({d:e.inn,zIndex:e.zInn});f.out.attr({d:e.out,zIndex:e.zOut});f.side1.attr({d:e.side1,zIndex:e.zSide1});f.side2.attr({d:e.side2,
zIndex:e.zSide2});f.zIndex=d;f.attr({zIndex:d});a.center&&(f.top.setRadialReference(a.center),delete a.center)};f.setPaths(e);f.fillSetter=function(e){var d=a(e).brighten(-.1).get();this.fill=e;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:e});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){f[a+"Setter"]=function(a,e){f[e]=a;["out","inn","side1","side2","top"].forEach(function(d){f[d].attr(e,
a)})}});f.attr=function(a){var e;"object"===typeof a&&(e=m(a))&&(g(f.attribs,e),f.setPaths(f.attribs));return d.prototype.attr.apply(f,arguments)};f.animate=function(a,e,c){var n=this.attribs,u="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.depth;delete a.alpha;delete a.beta;var l=r(t(e,this.renderer.globalAnimation));if(l.duration){var p=m(a);f[u]=0;a[u]=1;f[u+"Setter"]=b.noop;p&&(l.step=function(a,e){function d(a){return n[a]+(t(p[a],n[a])-n[a])*e.pos}e.prop===
u&&e.elem.setPaths(k(n,{x:d("x"),y:d("y"),r:d("r"),innerR:d("innerR"),start:d("start"),end:d("end")}))});e=l}return d.prototype.animate.call(this,a,e,c)};f.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return d.prototype.destroy.call(this)};f.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};f.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);
this.side2.show(a)};return f};h.prototype.arc3dPath=function(a){function e(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var d=a.x,c=a.y,m=a.start,b=a.end-.00001,k=a.r,n=a.innerR||0,u=a.depth||0,l=a.alpha,p=a.beta,h=Math.cos(m),g=Math.sin(m);a=Math.cos(b);var t=Math.sin(b),w=k*Math.cos(p);k*=Math.cos(l);var x=n*Math.cos(p),r=n*Math.cos(l);n=u*Math.sin(p);var z=u*Math.sin(l);u=["M",d+w*h,c+k*g];u=u.concat(q(d,c,w,k,m,b,0,0));u=u.concat(["L",d+x*a,c+r*t]);u=u.concat(q(d,c,x,r,b,m,0,0));u=u.concat(["Z"]);
var B=0<p?Math.PI/2:0;p=0<l?0:Math.PI/2;B=m>-B?m:b>-B?-B:m;var D=b<A-p?b:m<A-p?A-p:b,E=2*A-p;l=["M",d+w*v(B),c+k*y(B)];l=l.concat(q(d,c,w,k,B,D,0,0));b>E&&m<E?(l=l.concat(["L",d+w*v(D)+n,c+k*y(D)+z]),l=l.concat(q(d,c,w,k,D,E,n,z)),l=l.concat(["L",d+w*v(E),c+k*y(E)]),l=l.concat(q(d,c,w,k,E,b,0,0)),l=l.concat(["L",d+w*v(b)+n,c+k*y(b)+z]),l=l.concat(q(d,c,w,k,b,E,n,z)),l=l.concat(["L",d+w*v(E),c+k*y(E)]),l=l.concat(q(d,c,w,k,E,D,0,0))):b>A-p&&m<A-p&&(l=l.concat(["L",d+w*Math.cos(D)+n,c+k*Math.sin(D)+
z]),l=l.concat(q(d,c,w,k,D,b,n,z)),l=l.concat(["L",d+w*Math.cos(b),c+k*Math.sin(b)]),l=l.concat(q(d,c,w,k,b,D,0,0)));l=l.concat(["L",d+w*Math.cos(D)+n,c+k*Math.sin(D)+z]);l=l.concat(q(d,c,w,k,D,B,n,z));l=l.concat(["Z"]);p=["M",d+x*h,c+r*g];p=p.concat(q(d,c,x,r,m,b,0,0));p=p.concat(["L",d+x*Math.cos(b)+n,c+r*Math.sin(b)+z]);p=p.concat(q(d,c,x,r,b,m,n,z));p=p.concat(["Z"]);h=["M",d+w*h,c+k*g,"L",d+w*h+n,c+k*g+z,"L",d+x*h+n,c+r*g+z,"L",d+x*h,c+r*g,"Z"];d=["M",d+w*a,c+k*t,"L",d+w*a+n,c+k*t+z,"L",d+x*
a+n,c+r*t+z,"L",d+x*a,c+r*t,"Z"];t=Math.atan2(z,-n);c=Math.abs(b+t);a=Math.abs(m+t);m=Math.abs((m+b)/2+t);c=e(c);a=e(a);m=e(m);m*=1E5;b=1E5*a;c*=1E5;return{top:u,zTop:1E5*Math.PI+1,out:l,zOut:Math.max(m,b,c),inn:p,zInn:Math.max(m,b,c),side1:h,zSide1:.99*c,side2:d,zSide2:.99*b}}});B(q,"parts-3d/Chart.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){function q(b,l){var a=b.plotLeft,c=b.plotWidth+a,k=b.plotTop,p=b.plotHeight+k,d=a+b.plotWidth/2,e=k+b.plotHeight/2,m=Number.MAX_VALUE,
u=-Number.MAX_VALUE,n=Number.MAX_VALUE,h=-Number.MAX_VALUE,f=1;var g=[{x:a,y:k,z:0},{x:a,y:k,z:l}];[0,1].forEach(function(a){g.push({x:c,y:g[a].y,z:g[a].z})});[0,1,2,3].forEach(function(a){g.push({x:g[a].x,y:p,z:g[a].z})});g=t(g,b,!1);g.forEach(function(a){m=Math.min(m,a.x);u=Math.max(u,a.x);n=Math.min(n,a.y);h=Math.max(h,a.y)});a>m&&(f=Math.min(f,1-Math.abs((a+d)/(m+d))%1));c<u&&(f=Math.min(f,(c-d)/(u-d)));k>n&&(f=0>n?Math.min(f,(k+e)/(-n+k+e)):Math.min(f,1-(k+e)/(n+e)%1));p<h&&(f=Math.min(f,Math.abs((p-
e)/(h-e))));return f}var r=h.isArray,x=h.pick;h=b.addEvent;var g=b.Chart,w=b.merge,t=b.perspective,v=b.wrap;g.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};g.prototype.propsRequireDirtyBox.push("chart.options3d");g.prototype.propsRequireUpdateSeries.push("chart.options3d");h(g,"afterInit",function(){var b=this.options;this.is3d()&&(b.series||[]).forEach(function(l){"scatter"===(l.type||b.chart.type||b.chart.defaultSeriesType)&&(l.type="scatter3d")})});
h(g,"addSeries",function(b){this.is3d()&&"scatter"===b.options.type&&(b.options.type="scatter3d")});b.wrap(b.Chart.prototype,"isInsidePlot",function(b){return this.is3d()||b.apply(this,[].slice.call(arguments,1))});var A=b.getOptions();w(!0,A,{chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});h(g,"afterGetContainer",function(){this.styledMode&&(this.renderer.definition({tagName:"style",
textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(b){this.renderer.definition({tagName:"filter",id:"highcharts-"+b.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",slope:b.slope},{tagName:"feFuncG",type:"linear",slope:b.slope},{tagName:"feFuncB",type:"linear",slope:b.slope}]}]})},this))});v(g.prototype,"setClassName",
function(b){b.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")});h(b.Chart,"afterSetChartSize",function(){var b=this.options.chart.options3d;if(this.is3d()){var l=this.inverted,a=this.clipBox,c=this.margin;a[l?"y":"x"]=-(c[3]||0);a[l?"x":"y"]=-(c[0]||0);a[l?"height":"width"]=this.chartWidth+(c[3]||0)+(c[1]||0);a[l?"width":"height"]=this.chartHeight+(c[0]||0)+(c[2]||0);this.scale3d=1;!0===b.fitToPlot&&(this.scale3d=q(this,b.depth));this.frame3d=
this.get3dFrame()}});h(g,"beforeRedraw",function(){this.is3d()&&(this.isDirtyBox=!0)});h(g,"beforeRender",function(){this.is3d()&&(this.frame3d=this.get3dFrame())});v(g.prototype,"renderSeries",function(b){var l=this.series.length;if(this.is3d())for(;l--;)b=this.series[l],b.translate(),b.render();else b.call(this)});h(g,"afterDrawChartBox",function(){if(this.is3d()){var h=this.renderer,l=this.options.chart.options3d,a=this.get3dFrame(),c=this.plotLeft,k=this.plotLeft+this.plotWidth,p=this.plotTop,
d=this.plotTop+this.plotHeight;l=l.depth;var e=c-(a.left.visible?a.left.size:0),m=k+(a.right.visible?a.right.size:0),u=p-(a.top.visible?a.top.size:0),n=d+(a.bottom.visible?a.bottom.size:0),g=0-(a.front.visible?a.front.size:0),f=l+(a.back.visible?a.back.size:0),t=this.hasRendered?"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:h.polyhedron().add(),top:h.polyhedron().add(),left:h.polyhedron().add(),right:h.polyhedron().add(),back:h.polyhedron().add(),front:h.polyhedron().add()});
this.frameShapes.bottom[t]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:e,y:n,z:g},{x:m,y:n,z:g},{x:m,y:n,z:f},{x:e,y:n,z:f}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:c,y:d,z:l},{x:k,y:d,z:l},{x:k,y:d,z:0},{x:c,y:d,z:0}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:e,y:n,z:g},{x:e,y:n,z:f},
{x:c,y:d,z:l},{x:c,y:d,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:m,y:n,z:f},{x:m,y:n,z:g},{x:k,y:d,z:0},{x:k,y:d,z:l}],enabled:a.bottom.visible&&!a.right.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:m,y:n,z:g},{x:e,y:n,z:g},{x:c,y:d,z:0},{x:k,y:d,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:e,y:n,z:f},{x:m,y:n,z:f},{x:k,y:d,z:l},{x:c,y:d,z:l}],enabled:a.bottom.visible&&
!a.back.visible}]});this.frameShapes.top[t]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:e,y:u,z:f},{x:m,y:u,z:f},{x:m,y:u,z:g},{x:e,y:u,z:g}],enabled:a.top.visible},{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:c,y:p,z:0},{x:k,y:p,z:0},{x:k,y:p,z:l},{x:c,y:p,z:l}],enabled:a.top.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:e,y:u,z:f},{x:e,y:u,z:g},{x:c,
y:p,z:0},{x:c,y:p,z:l}],enabled:a.top.visible&&!a.left.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:m,y:u,z:g},{x:m,y:u,z:f},{x:k,y:p,z:l},{x:k,y:p,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:e,y:u,z:g},{x:m,y:u,z:g},{x:k,y:p,z:0},{x:c,y:p,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:m,y:u,z:f},{x:e,y:u,z:f},{x:c,y:p,z:l},{x:k,y:p,z:l}],enabled:a.top.visible&&!a.back.visible}]});
this.frameShapes.left[t]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:e,y:n,z:g},{x:c,y:d,z:0},{x:c,y:d,z:l},{x:e,y:n,z:f}],enabled:a.left.visible&&!a.bottom.visible},{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:e,y:u,z:f},{x:c,y:p,z:l},{x:c,y:p,z:0},{x:e,y:u,z:g}],enabled:a.left.visible&&!a.top.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:e,y:n,
z:f},{x:e,y:u,z:f},{x:e,y:u,z:g},{x:e,y:n,z:g}],enabled:a.left.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:c,y:p,z:l},{x:c,y:d,z:l},{x:c,y:d,z:0},{x:c,y:p,z:0}],enabled:a.left.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:e,y:n,z:g},{x:e,y:u,z:g},{x:c,y:p,z:0},{x:c,y:d,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:e,y:u,z:f},{x:e,y:n,z:f},{x:c,y:d,z:l},{x:c,y:p,z:l}],enabled:a.left.visible&&!a.back.visible}]});this.frameShapes.right[t]({"class":"highcharts-3d-frame highcharts-3d-frame-right",
zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:m,y:n,z:f},{x:k,y:d,z:l},{x:k,y:d,z:0},{x:m,y:n,z:g}],enabled:a.right.visible&&!a.bottom.visible},{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:m,y:u,z:g},{x:k,y:p,z:0},{x:k,y:p,z:l},{x:m,y:u,z:f}],enabled:a.right.visible&&!a.top.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:k,y:p,z:0},{x:k,y:d,z:0},{x:k,y:d,z:l},{x:k,y:p,z:l}],enabled:a.right.visible},{fill:b.color(a.right.color).brighten(-.1).get(),
vertexes:[{x:m,y:n,z:g},{x:m,y:u,z:g},{x:m,y:u,z:f},{x:m,y:n,z:f}],enabled:a.right.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:m,y:u,z:g},{x:m,y:n,z:g},{x:k,y:d,z:0},{x:k,y:p,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:m,y:n,z:f},{x:m,y:u,z:f},{x:k,y:p,z:l},{x:k,y:d,z:l}],enabled:a.right.visible&&!a.back.visible}]});this.frameShapes.back[t]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.back.color).brighten(.1).get(),
vertexes:[{x:m,y:n,z:f},{x:e,y:n,z:f},{x:c,y:d,z:l},{x:k,y:d,z:l}],enabled:a.back.visible&&!a.bottom.visible},{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:e,y:u,z:f},{x:m,y:u,z:f},{x:k,y:p,z:l},{x:c,y:p,z:l}],enabled:a.back.visible&&!a.top.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:e,y:n,z:f},{x:e,y:u,z:f},{x:c,y:p,z:l},{x:c,y:d,z:l}],enabled:a.back.visible&&!a.left.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:m,y:u,z:f},{x:m,y:n,
z:f},{x:k,y:d,z:l},{x:k,y:p,z:l}],enabled:a.back.visible&&!a.right.visible},{fill:b.color(a.back.color).get(),vertexes:[{x:c,y:p,z:l},{x:k,y:p,z:l},{x:k,y:d,z:l},{x:c,y:d,z:l}],enabled:a.back.visible},{fill:b.color(a.back.color).get(),vertexes:[{x:e,y:n,z:f},{x:m,y:n,z:f},{x:m,y:u,z:f},{x:e,y:u,z:f}],enabled:a.back.visible}]});this.frameShapes.front[t]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.front.color).brighten(.1).get(),
vertexes:[{x:e,y:n,z:g},{x:m,y:n,z:g},{x:k,y:d,z:0},{x:c,y:d,z:0}],enabled:a.front.visible&&!a.bottom.visible},{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:m,y:u,z:g},{x:e,y:u,z:g},{x:c,y:p,z:0},{x:k,y:p,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:e,y:u,z:g},{x:e,y:n,z:g},{x:c,y:d,z:0},{x:c,y:p,z:0}],enabled:a.front.visible&&!a.left.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:m,y:n,z:g},{x:m,
y:u,z:g},{x:k,y:p,z:0},{x:k,y:d,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:b.color(a.front.color).get(),vertexes:[{x:k,y:p,z:0},{x:c,y:p,z:0},{x:c,y:d,z:0},{x:k,y:d,z:0}],enabled:a.front.visible},{fill:b.color(a.front.color).get(),vertexes:[{x:m,y:n,z:g},{x:e,y:n,z:g},{x:e,y:u,z:g},{x:m,y:u,z:g}],enabled:a.front.visible}]})}});g.prototype.retrieveStacks=function(b){var l=this.series,a={},c,k=1;this.series.forEach(function(g){c=x(g.options.stack,b?0:l.length-1-g.index);a[c]?a[c].series.push(g):
(a[c]={series:[g],position:k},k++)});a.totalStacks=k+1;return a};g.prototype.get3dFrame=function(){var g=this,l=g.options.chart.options3d,a=l.frame,c=g.plotLeft,k=g.plotLeft+g.plotWidth,p=g.plotTop,d=g.plotTop+g.plotHeight,e=l.depth,m=function(a){a=b.shapeArea3d(a,g);return.5<a?1:-.5>a?-1:0},u=m([{x:c,y:d,z:e},{x:k,y:d,z:e},{x:k,y:d,z:0},{x:c,y:d,z:0}]),n=m([{x:c,y:p,z:0},{x:k,y:p,z:0},{x:k,y:p,z:e},{x:c,y:p,z:e}]),h=m([{x:c,y:p,z:0},{x:c,y:p,z:e},{x:c,y:d,z:e},{x:c,y:d,z:0}]),f=m([{x:k,y:p,z:e},
{x:k,y:p,z:0},{x:k,y:d,z:0},{x:k,y:d,z:e}]),w=m([{x:c,y:d,z:0},{x:k,y:d,z:0},{x:k,y:p,z:0},{x:c,y:p,z:0}]);m=m([{x:c,y:p,z:e},{x:k,y:p,z:e},{x:k,y:d,z:e},{x:c,y:d,z:e}]);var v=!1,q=!1,r=!1,z=!1;[].concat(g.xAxis,g.yAxis,g.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?q=!0:v=!0:a.opposite?z=!0:r=!0)});var A=function(a,d,e){for(var b=["size","color","visible"],c={},f=0;f<b.length;f++)for(var m=b[f],k=0;k<a.length;k++)if("object"===typeof a[k]){var l=a[k][m];if("undefined"!==typeof l&&null!==l){c[m]=
l;break}}a=e;!0===c.visible||!1===c.visible?a=c.visible:"auto"===c.visible&&(a=0<d);return{size:x(c.size,1),color:x(c.color,"none"),frontFacing:0<d,visible:a}};a={axes:{},bottom:A([a.bottom,a.top,a],u,v),top:A([a.top,a.bottom,a],n,q),left:A([a.left,a.right,a.side,a],h,r),right:A([a.right,a.left,a.side,a],f,z),back:A([a.back,a.front,a],m,!0),front:A([a.front,a.back,a],w,!1)};"auto"===l.axisLabelPosition?(f=function(a,d){return a.visible!==d.visible||a.visible&&d.visible&&a.frontFacing!==d.frontFacing},
l=[],f(a.left,a.front)&&l.push({y:(p+d)/2,x:c,z:0,xDir:{x:1,y:0,z:0}}),f(a.left,a.back)&&l.push({y:(p+d)/2,x:c,z:e,xDir:{x:0,y:0,z:-1}}),f(a.right,a.front)&&l.push({y:(p+d)/2,x:k,z:0,xDir:{x:0,y:0,z:1}}),f(a.right,a.back)&&l.push({y:(p+d)/2,x:k,z:e,xDir:{x:-1,y:0,z:0}}),u=[],f(a.bottom,a.front)&&u.push({x:(c+k)/2,y:d,z:0,xDir:{x:1,y:0,z:0}}),f(a.bottom,a.back)&&u.push({x:(c+k)/2,y:d,z:e,xDir:{x:-1,y:0,z:0}}),n=[],f(a.top,a.front)&&n.push({x:(c+k)/2,y:p,z:0,xDir:{x:1,y:0,z:0}}),f(a.top,a.back)&&n.push({x:(c+
k)/2,y:p,z:e,xDir:{x:-1,y:0,z:0}}),h=[],f(a.bottom,a.left)&&h.push({z:(0+e)/2,y:d,x:c,xDir:{x:0,y:0,z:-1}}),f(a.bottom,a.right)&&h.push({z:(0+e)/2,y:d,x:k,xDir:{x:0,y:0,z:1}}),d=[],f(a.top,a.left)&&d.push({z:(0+e)/2,y:p,x:c,xDir:{x:0,y:0,z:-1}}),f(a.top,a.right)&&d.push({z:(0+e)/2,y:p,x:k,xDir:{x:0,y:0,z:1}}),c=function(a,d,e){if(0===a.length)return null;if(1===a.length)return a[0];for(var c=0,b=t(a,g,!1),f=1;f<b.length;f++)e*b[f][d]>e*b[c][d]?c=f:e*b[f][d]===e*b[c][d]&&b[f].z<b[c].z&&(c=f);return a[c]},
a.axes={y:{left:c(l,"x",-1),right:c(l,"x",1)},x:{top:c(n,"y",-1),bottom:c(u,"y",1)},z:{top:c(d,"y",-1),bottom:c(h,"y",1)}}):a.axes={y:{left:{x:c,z:0,xDir:{x:1,y:0,z:0}},right:{x:k,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:p,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:d,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:r?k:c,y:p,xDir:r?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:r?k:c,y:d,xDir:r?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return a};b.Fx.prototype.matrixSetter=function(){if(1>this.pos&&(r(this.start)||r(this.end))){var b=this.start||
[1,0,0,1,0,0],l=this.end||[1,0,0,1,0,0];var a=[];for(var c=0;6>c;c++)a.push(this.pos*l[c]+(1-this.pos)*b[c])}else a=this.end;this.elem.attr(this.prop,a,null,!0)};""});B(q,"parts-3d/Axis.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){function q(d,e,b){if(!d.chart.is3d()||"colorAxis"===d.coll)return e;var c=d.chart,m=v*c.options.chart.options3d.alpha,k=v*c.options.chart.options3d.beta,f=x(b&&d.options.title.position3d,d.options.labels.position3d);b=x(b&&d.options.title.skew3d,d.options.labels.skew3d);
var l=c.frame3d,g=c.plotLeft,p=c.plotWidth+g,h=c.plotTop,t=c.plotHeight+h;c=!1;var w=0,q=0,r={x:0,y:1,z:0};e=d.swapZ({x:e.x,y:e.y,z:0});if(d.isZAxis)if(d.opposite){if(null===l.axes.z.top)return{};q=e.y-h;e.x=l.axes.z.top.x;e.y=l.axes.z.top.y;g=l.axes.z.top.xDir;c=!l.top.frontFacing}else{if(null===l.axes.z.bottom)return{};q=e.y-t;e.x=l.axes.z.bottom.x;e.y=l.axes.z.bottom.y;g=l.axes.z.bottom.xDir;c=!l.bottom.frontFacing}else if(d.horiz)if(d.opposite){if(null===l.axes.x.top)return{};q=e.y-h;e.y=l.axes.x.top.y;
e.z=l.axes.x.top.z;g=l.axes.x.top.xDir;c=!l.top.frontFacing}else{if(null===l.axes.x.bottom)return{};q=e.y-t;e.y=l.axes.x.bottom.y;e.z=l.axes.x.bottom.z;g=l.axes.x.bottom.xDir;c=!l.bottom.frontFacing}else if(d.opposite){if(null===l.axes.y.right)return{};w=e.x-p;e.x=l.axes.y.right.x;e.z=l.axes.y.right.z;g=l.axes.y.right.xDir;g={x:g.z,y:g.y,z:-g.x}}else{if(null===l.axes.y.left)return{};w=e.x-g;e.x=l.axes.y.left.x;e.z=l.axes.y.left.z;g=l.axes.y.left.xDir}"chart"!==f&&("flap"===f?d.horiz?(k=Math.sin(m),
m=Math.cos(m),d.opposite&&(k=-k),c&&(k=-k),r={x:g.z*k,y:m,z:-g.x*k}):g={x:Math.cos(k),y:0,z:Math.sin(k)}:"ortho"===f?d.horiz?(r=Math.cos(m),f=Math.sin(k)*r,m=-Math.sin(m),k=-r*Math.cos(k),r={x:g.y*k-g.z*m,y:g.z*f-g.x*k,z:g.x*m-g.y*f},m=1/Math.sqrt(r.x*r.x+r.y*r.y+r.z*r.z),c&&(m=-m),r={x:m*r.x,y:m*r.y,z:m*r.z}):g={x:Math.cos(k),y:0,z:Math.sin(k)}:d.horiz?r={x:Math.sin(k)*Math.sin(m),y:Math.cos(m),z:-Math.cos(k)*Math.sin(m)}:g={x:Math.cos(k),y:0,z:Math.sin(k)});e.x+=w*g.x+q*r.x;e.y+=w*g.y+q*r.y;e.z+=
w*g.z+q*r.z;c=y([e],d.chart)[0];b&&(0>a(y([e,{x:e.x+g.x,y:e.y+g.y,z:e.z+g.z},{x:e.x+r.x,y:e.y+r.y,z:e.z+r.z}],d.chart))&&(g={x:-g.x,y:-g.y,z:-g.z}),d=y([{x:e.x,y:e.y,z:e.z},{x:e.x+g.x,y:e.y+g.y,z:e.z+g.z},{x:e.x+r.x,y:e.y+r.y,z:e.z+r.z}],d.chart),c.matrix=[d[1].x-d[0].x,d[1].y-d[0].y,d[2].x-d[0].x,d[2].y-d[0].y,c.x,c.y],c.matrix[4]-=c.x*c.matrix[0]+c.y*c.matrix[2],c.matrix[5]-=c.x*c.matrix[1]+c.y*c.matrix[3]);return c}var r=h.extend,x=h.pick,g=h.splat;h=b.addEvent;var w=b.Axis,t=b.Chart,v=b.deg2rad,
A=b.merge,y=b.perspective,l=b.perspective3D,a=b.shapeArea,c=b.Tick,k=b.wrap;A(!0,w.prototype.defaultOptions,{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}});h(w,"afterSetOptions",function(){if(this.chart.is3d&&this.chart.is3d()&&"colorAxis"!==this.coll){var a=this.options;a.tickWidth=x(a.tickWidth,0);a.gridLineWidth=x(a.gridLineWidth,1)}});k(w.prototype,"getPlotLinePath",function(a){var d=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||"colorAxis"===this.coll||
null===d)return d;var c=this.chart,b=c.options.chart.options3d;b=this.isZAxis?c.plotWidth:b.depth;c=c.frame3d;d=[this.swapZ({x:d[1],y:d[2],z:0}),this.swapZ({x:d[1],y:d[2],z:b}),this.swapZ({x:d[4],y:d[5],z:0}),this.swapZ({x:d[4],y:d[5],z:b})];b=[];this.horiz?(this.isZAxis?(c.left.visible&&b.push(d[0],d[2]),c.right.visible&&b.push(d[1],d[3])):(c.front.visible&&b.push(d[0],d[2]),c.back.visible&&b.push(d[1],d[3])),c.top.visible&&b.push(d[0],d[1]),c.bottom.visible&&b.push(d[2],d[3])):(c.front.visible&&
b.push(d[0],d[2]),c.back.visible&&b.push(d[1],d[3]),c.left.visible&&b.push(d[0],d[1]),c.right.visible&&b.push(d[2],d[3]));b=y(b,this.chart,!1);return this.chart.renderer.toLineSegments(b)});k(w.prototype,"getLinePath",function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))});k(w.prototype,"getPlotBandPath",function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var d=arguments,c=d[2],b=[];d=this.getPlotLinePath({value:d[1]});
c=this.getPlotLinePath({value:c});if(d&&c)for(var g=0;g<d.length;g+=6)b.push("M",d[g+1],d[g+2],"L",d[g+4],d[g+5],"L",c[g+4],c[g+5],"L",c[g+1],c[g+2],"Z");return b});k(c.prototype,"getMarkPath",function(a){var d=a.apply(this,[].slice.call(arguments,1));d=[q(this.axis,{x:d[1],y:d[2],z:0}),q(this.axis,{x:d[4],y:d[5],z:0})];return this.axis.chart.renderer.toLineSegments(d)});h(c,"afterGetLabelPosition",function(a){r(a.pos,q(this.axis,a.pos))});k(w.prototype,"getTitlePosition",function(a){var d=a.apply(this,
[].slice.call(arguments,1));return q(this,d,!0)});h(w,"drawCrosshair",function(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)});h(w,"destroy",function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)});w.prototype.swapZ=function(a,c){return this.isZAxis?(c=c?0:this.chart.plotLeft,{x:c+a.z,y:a.y,z:a.x-c}):a};var p=b.ZAxis=function(){this.init.apply(this,arguments)};
r(p.prototype,w.prototype);r(p.prototype,{isZAxis:!0,setOptions:function(a){a=A({offset:0,lineWidth:0},a);w.prototype.setOptions.call(this,a);this.coll="zAxis"},setAxisSize:function(){w.prototype.setAxisSize.call(this);this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},getSeriesExtremes:function(){var a=this,c=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();
a.series.forEach(function(d){if(d.visible||!c.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,d=d.zData,d.length&&(a.dataMin=Math.min(x(a.dataMin,d[0]),Math.min.apply(null,d)),a.dataMax=Math.max(x(a.dataMax,d[0]),Math.max.apply(null,d)))})}});h(t,"afterGetAxes",function(){var a=this,c=this.options;c=c.zAxis=g(c.zAxis||{});a.is3d()&&(this.zAxis=[],c.forEach(function(d,c){d.index=c;d.isX=!0;(new p(a,d)).setScale()}))});k(w.prototype,"getSlotWidth",function(a,c){if(this.chart.is3d()&&c&&c.label&&
this.categories&&this.chart.frameShapes){var d=this.chart,b=this.ticks,e=this.gridGroup.element.childNodes[0].getBBox(),g=d.frameShapes.left.getBBox(),f=d.options.chart.options3d;d={x:d.plotWidth/2,y:d.plotHeight/2,z:f.depth/2,vd:x(f.depth,1)*x(f.viewDistance,0)};var k,p;f=c.pos;var h=b[f-1];b=b[f+1];0!==f&&h&&h.label.xy&&(k=l({x:h.label.xy.x,y:h.label.xy.y,z:null},d,d.vd));b&&b.label.xy&&(p=l({x:b.label.xy.x,y:b.label.xy.y,z:null},d,d.vd));b={x:c.label.xy.x,y:c.label.xy.y,z:null};b=l(b,d,d.vd);return Math.abs(k?
b.x-k.x:p?p.x-b.x:e.x-g.x)}return a.apply(this,[].slice.call(arguments,1))})});B(q,"parts-3d/Series.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){var q=h.pick;h=b.addEvent;var r=b.perspective;h(b.Series,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});b.Series.prototype.translate3dPoints=function(){var b=this.chart,g=q(this.zAxis,b.options.zAxis[0]),h=[],t;for(t=0;t<this.data.length;t++){var v=this.data[t];if(g&&g.translate){var A=g.isLog&&g.val2lin?g.val2lin(v.z):
v.z;v.plotZ=g.translate(A);v.isInside=v.isInside?A>=g.min&&A<=g.max:!1}else v.plotZ=0;v.axisXpos=v.plotX;v.axisYpos=v.plotY;v.axisZpos=v.plotZ;h.push({x:v.plotX,y:v.plotY,z:v.plotZ})}b=r(h,b,!0);for(t=0;t<this.data.length;t++)v=this.data[t],g=b[t],v.plotX=g.x,v.plotY=g.y,v.plotZ=g.z}});B(q,"parts-3d/Column.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){function q(b){var a=b.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(a.stroke=this.options.edgeColor||
a.fill,a["stroke-width"]=g(this.options.edgeWidth,1));return a}function r(b,a,c){var g=this.chart.is3d&&this.chart.is3d();g&&(this.options.inactiveOtherPoints=!0);b.call(this,a,c);g&&(this.options.inactiveOtherPoints=!1)}function x(b){for(var a=[],c=1;c<arguments.length;c++)a[c-1]=arguments[c];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:b.apply(this,a)}var g=h.pick;h=b.addEvent;var w=b.perspective,t=b.Series,v=b.seriesTypes,A=b.svg,y=b.wrap;y(v.column.prototype,
"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});y(b.Series.prototype,"alignDataLabel",function(b){arguments[3].outside3dPlot=arguments[1].outside3dPlot;b.apply(this,[].slice.call(arguments,1))});y(b.Series.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,1))});v.column.prototype.translate3dPoints=function(){};v.column.prototype.translate3dShapes=function(){var b=this,a=
b.chart,c=b.options,g=c.depth||25,h=(c.stacking?c.stack||0:b.index)*(g+(c.groupZPadding||1)),d=b.borderWidth%2?.5:0;a.inverted&&!b.yAxis.reversed&&(d*=-1);!1!==c.grouping&&(h=0);h+=c.groupZPadding||1;b.data.forEach(function(c){c.outside3dPlot=null;if(null!==c.y){var e=c.shapeArgs,k=c.tooltipPos,l;[["x","width"],["y","height"]].forEach(function(a){l=e[a[0]]-d;0>l&&(e[a[1]]+=e[a[0]]+d,e[a[0]]=-d,l=0);l+e[a[1]]>b[a[0]+"Axis"].len&&0!==e[a[1]]&&(e[a[1]]=b[a[0]+"Axis"].len-e[a[0]]);if(0!==e[a[1]]&&(e[a[0]]>=
b[a[0]+"Axis"].len||e[a[0]]+e[a[1]]<=d)){for(var f in e)e[f]=0;c.outside3dPlot=!0}});"rect"===c.shapeType&&(c.shapeType="cuboid");e.z=h;e.depth=g;e.insidePlotArea=!0;k=w([{x:k[0],y:k[1],z:h}],a,!0)[0];c.tooltipPos=[k.x,k.y]}});b.z=h};y(v.column.prototype,"animate",function(b){if(this.chart.is3d()){var a=arguments[1],c=this.yAxis,g=this,l=this.yAxis.reversed;A&&(a?g.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,l||(a.shapeArgs.y=a.stackY?
a.plotY+c.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(g.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,g.options.animation))}),this.drawDataLabels(),g.animate=null))}else b.apply(this,[].slice.call(arguments,1))});y(v.column.prototype,"plotGroup",function(b,a,c,g,h,d){"dataLabelsGroup"!==a&&this.chart.is3d()&&(this[a]&&delete this[a],d&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(d)),
this[a]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[a].survive=!0,"group"===a||"markerGroup"===a))&&(arguments[3]="visible");return b.apply(this,Array.prototype.slice.call(arguments,1))});y(v.column.prototype,"setVisible",function(b,a){var c=this,k;c.chart.is3d()&&c.data.forEach(function(b){k=(b.visible=b.options.visible=a="undefined"===typeof a?!g(c.visible,b.visible):a)?"visible":"hidden";c.options.data[c.data.indexOf(b)]=b.options;b.graphic&&b.graphic.attr({visibility:k})});
b.apply(this,Array.prototype.slice.call(arguments,1))});v.column.prototype.handle3dGrouping=!0;h(t,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,a=b.grouping,c=b.stacking,k=g(this.yAxis.options.reversedStacks,!0),h=0;if("undefined"===typeof a||a){a=this.chart.retrieveStacks(c);h=b.stack||0;for(c=0;c<a[h].series.length&&a[h].series[c]!==this;c++);h=10*(a.totalStacks-a[h].position)+(k?c:-c);this.xAxis.reversed||(h=10*a.totalStacks-h)}b.zIndex=h}});y(v.column.prototype,
"pointAttribs",q);y(v.column.prototype,"setState",r);y(v.column.prototype.pointClass.prototype,"hasNewShapeType",x);v.columnrange&&(y(v.columnrange.prototype,"pointAttribs",q),y(v.columnrange.prototype,"setState",r),y(v.columnrange.prototype.pointClass.prototype,"hasNewShapeType",x),v.columnrange.prototype.plotGroup=v.column.prototype.plotGroup,v.columnrange.prototype.setVisible=v.column.prototype.setVisible);y(t.prototype,"alignDataLabel",function(b){if(this.chart.is3d()&&this instanceof v.column){var a=
arguments,c=a[4];a=a[1];var g={x:c.x,y:c.y,z:this.z};g=w([g],this.chart,!0)[0];c.x=g.x;c.y=a.outside3dPlot?-9E9:g.y}b.apply(this,[].slice.call(arguments,1))});y(b.StackItem.prototype,"getStackBox",function(g,a){var c=g.apply(this,[].slice.call(arguments,1));if(a.is3d()){var k={x:c.x,y:c.y,z:0};k=b.perspective([k],a,!0)[0];c.x=k.x;c.y=k.y}return c})});B(q,"parts-3d/Pie.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,h){var q=h.pick,r=b.deg2rad;h=b.seriesTypes;var x=b.svg;b=b.wrap;b(h.pie.prototype,
"translate",function(b){b.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var g=this,h=g.options,q=h.depth||0,x=g.chart.options.chart.options3d,y=x.alpha,l=x.beta,a=h.stacking?(h.stack||0)*q:g._i*q;a+=q/2;!1!==h.grouping&&(a=0);g.data.forEach(function(b){var c=b.shapeArgs;b.shapeType="arc3d";c.z=a;c.depth=.75*q;c.alpha=y;c.beta=l;c.center=g.center;c=(c.end+c.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(c)*h.slicedOffset*Math.cos(y*r)),translateY:Math.round(Math.sin(c)*
h.slicedOffset*Math.cos(y*r))}})}});b(h.pie.prototype.pointClass.prototype,"haloPath",function(b){var g=arguments;return this.series.chart.is3d()?[]:b.call(this,g[1])});b(h.pie.prototype,"pointAttribs",function(b,h,t){b=b.call(this,h,t);t=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=t.edgeColor||h.color||this.color,b["stroke-width"]=q(t.edgeWidth,1));return b});b(h.pie.prototype,"drawDataLabels",function(b){if(this.chart.is3d()){var g=this.chart.options.chart.options3d;this.data.forEach(function(b){var h=
b.shapeArgs,q=h.r,t=(h.start+h.end)/2;b=b.labelPosition;var l=b.connectorPosition,a=-q*(1-Math.cos((h.alpha||g.alpha)*r))*Math.sin(t),c=q*(Math.cos((h.beta||g.beta)*r)-1)*Math.cos(t);[b.natural,l.breakAt,l.touchingSliceAt].forEach(function(b){b.x+=c;b.y+=a})})}b.apply(this,[].slice.call(arguments,1))});b(h.pie.prototype,"addPoint",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});b(h.pie.prototype,"animate",function(b){if(this.chart.is3d()){var g=
arguments[1],h=this.options.animation,q=this.center,r=this.group,y=this.markerGroup;x&&(!0===h&&(h={}),g?(r.oldtranslateX=r.translateX,r.oldtranslateY=r.translateY,g={translateX:q[0],translateY:q[1],scaleX:.001,scaleY:.001},r.attr(g),y&&(y.attrSetters=r.attrSetters,y.attr(g))):(g={translateX:r.oldtranslateX,translateY:r.oldtranslateY,scaleX:1,scaleY:1},r.animate(g,h),y&&y.animate(g,h),this.animate=null))}else b.apply(this,[].slice.call(arguments,1))})});B(q,"parts-3d/Scatter.js",[q["parts/Globals.js"]],
function(b){var h=b.Point,q=b.seriesType,r=b.seriesTypes;q("scatter3d","scatter",{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}},{pointAttribs:function(h){var g=r.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&h&&(g.zIndex=b.pointCameraDistance(h,this.chart));return g},axisTypes:["xAxis","yAxis","zAxis"],pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],directTouch:!0},{applyOptions:function(){h.prototype.applyOptions.apply(this,
arguments);"undefined"===typeof this.z&&(this.z=0);return this}});""});B(q,"parts-3d/VMLRenderer.js",[q["parts/Globals.js"]],function(b){var h=b.addEvent,q=b.Axis,r=b.SVGRenderer,x=b.VMLRenderer;x&&(b.setOptions({animate:!1}),x.prototype.face3d=r.prototype.face3d,x.prototype.polyhedron=r.prototype.polyhedron,x.prototype.elements3d=r.prototype.elements3d,x.prototype.element3d=r.prototype.element3d,x.prototype.cuboid=r.prototype.cuboid,x.prototype.cuboidPath=r.prototype.cuboidPath,x.prototype.toLinePath=
r.prototype.toLinePath,x.prototype.toLineSegments=r.prototype.toLineSegments,x.prototype.arc3d=function(b){b=r.prototype.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b},b.VMLRenderer.prototype.arc3dPath=b.SVGRenderer.prototype.arc3dPath,h(q,"render",function(){this.sideFrame&&(this.sideFrame.css({zIndex:0}),this.sideFrame.front.attr({fill:this.sideFrame.color}));this.bottomFrame&&(this.bottomFrame.css({zIndex:1}),this.bottomFrame.front.attr({fill:this.bottomFrame.color}));this.backFrame&&(this.backFrame.css({zIndex:0}),
this.backFrame.front.attr({fill:this.backFrame.color}))}))});B(q,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map