/*
 Highcharts JS v7.2.1-modified (2019-11-18)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(z){e(z);e.Highcharts=z;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function z(c,b,r,h){c.hasOwnProperty(b)||(c[b]=h.apply(null,r))}e=e?e._modules:{};z(e,"parts-more/Pane.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){function r(b,a){this.init(b,a)}var h=b.extend,
m=b.splat,u=c.CenteredSeriesMixin,x=c.merge;h(r.prototype,{coll:"pane",init:function(b,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(b)},setOptions:function(b){this.options=x(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)},render:function(){var b=this.options,a=this.options.background,d=this.chart.renderer;this.group||(this.group=d.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(a)for(a=m(a),b=Math.max(a.length,this.background.length||
0),d=0;d<b;d++)a[d]&&this.axis?this.renderBackground(x(this.defaultBackgroundOptions,a[d]),d):this.background[d]&&(this.background[d]=this.background[d].destroy(),this.background.splice(d,1))},renderBackground:function(b,a){var d="animate",l={"class":"highcharts-pane "+(b.className||"")};this.chart.styledMode||h(l,{fill:b.backgroundColor,stroke:b.borderColor,"stroke-width":b.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),d="attr");this.background[a][d]({d:this.axis.getPlotBandPath(b.from,
b.to,b)}).attr(l)},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"},updateCenter:function(b){this.center=(b||this.axis||{}).center=u.getCenter.call(this)},update:function(b,a){x(!0,this.options,b);x(!0,this.chart.options.pane,b);this.setOptions(this.options);
this.render();this.chart.axes.forEach(function(b){b.pane===this&&(b.pane=null,b.update({},a))},this)}});c.Pane=r});z(e,"parts-more/RadialAxis.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.correctFloat,h=b.extend,m=b.pick,u=b.pInt;b=c.addEvent;var x=c.Axis,e=c.merge,a=c.noop,d=c.Tick,l=c.wrap,t=x.prototype,g=d.prototype;var w={getOffset:a,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},createLabelCollector:function(){return!1},setScale:a,setCategories:a,
setTitle:a};var A={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",labels:{align:"right",
x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(a){a=this.options=e(this.defaultOptions,this.defaultRadialOptions,a);a.plotBands||(a.plotBands=[]);c.fireEvent(this,"afterSetOptions")},getOffset:function(){t.getOffset.call(this);this.chart.axisOffset[this.side]=0},getLinePath:function(a,n){a=this.center;var k=this.chart,f=m(n,a[2]/2-this.offset);this.isCircular||"undefined"!==typeof n?(n=this.chart.renderer.symbols.arc(this.left+a[0],this.top+a[1],f,f,{start:this.startAngleRad,
end:this.endAngleRad,open:!0,innerR:0}),n.xBounds=[this.left+a[0]],n.yBounds=[this.top+a[1]-f]):(n=this.postTranslate(this.angleRad,f),n=["M",a[0]+k.plotLeft,a[1]+k.plotTop,"L",n.x,n.y]);return n},setAxisTranslation:function(){t.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){if(this.autoConnect=
this.isCircular&&"undefined"===typeof m(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===r(2*Math.PI))this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0},setAxisSize:function(){t.setAxisSize.call(this);this.isRadial&&(this.pane.updateCenter(this),this.isCircular&&(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*m(this.sector,1)/2)},getPosition:function(a,n){return this.postTranslate(this.isCircular?this.translate(a):
this.angleRad,m(this.isCircular?n:this.translate(a),this.center[2]/2)-this.offset)},postTranslate:function(a,n){var k=this.chart,f=this.center;a=this.startAngleRad+a;return{x:k.plotLeft+f[0]+Math.cos(a)*n,y:k.plotTop+f[1]+Math.sin(a)*n}},getPlotBandPath:function(a,n,k){var f=this.center,p=this.startAngleRad,b=f[2]/2,v=[m(k.outerRadius,"100%"),k.innerRadius,m(k.thickness,10)],q=Math.min(this.offset,0),d=/%$/;var g=this.isCircular;if("polygon"===this.options.gridLineInterpolation)v=this.getPlotLinePath({value:a}).concat(this.getPlotLinePath({value:n,
reverse:!0}));else{a=Math.max(a,this.min);n=Math.min(n,this.max);g||(v[0]=this.translate(a),v[1]=this.translate(n));v=v.map(function(f){d.test(f)&&(f=u(f,10)*b/100);return f});if("circle"!==k.shape&&g)a=p+this.translate(a),n=p+this.translate(n);else{a=-Math.PI/2;n=1.5*Math.PI;var l=!0}v[0]-=q;v[2]-=q;v=this.chart.renderer.symbols.arc(this.left+f[0],this.top+f[1],v[0],v[0],{start:Math.min(a,n),end:Math.max(a,n),innerR:m(v[1],v[0]-v[2]),open:l});g&&(g=(n+a)/2,q=this.left+f[0]+f[2]/2*Math.cos(g),v.xBounds=
g>-Math.PI/2&&g<Math.PI/2?[q,this.chart.plotWidth]:[0,q],v.yBounds=[this.top+f[1]+f[2]/2*Math.sin(g)],v.yBounds[0]+=g>-Math.PI&&0>g||g>Math.PI?-10:10)}return v},getPlotLinePath:function(a){var n=this,k=n.center,f=n.chart,p=a.value;a=a.reverse;var b=n.getPosition(p),v=n.pane.options.background?n.pane.options.background[0]||n.pane.options.background:{},q=v.innerRadius||"0%",d=v.outerRadius||"100%";v=k[0]+f.plotLeft;k=k[1]+f.plotTop;var g=b.x;b=b.y;var l,t;if(n.isCircular){f="string"===typeof q?c.relativeLength(q,
1):q/Math.sqrt(Math.pow(g-v,2)+Math.pow(b-k,2));a="string"===typeof d?c.relativeLength(d,1):d/Math.sqrt(Math.pow(g-v,2)+Math.pow(b-k,2));var h=["M",v+f*(g-v),k-f*(k-b),"L",g-(1-a)*(g-v),b+(1-a)*(k-b)]}else"circle"===n.options.gridLineInterpolation?(p=n.translate(p),h=n.getLinePath(0,p)):(f.xAxis.forEach(function(f){f.pane===n.pane&&(l=f)}),h=[],p=n.translate(p),f=l.tickPositions,l.autoConnect&&(f=f.concat([f[0]])),a&&(f=[].concat(f).reverse()),f.forEach(function(f,a){t=l.getPosition(f,p);h.push(a?
"L":"M",t.x,t.y)}));return h},getTitlePosition:function(){var a=this.center,n=this.chart,k=this.options.title;return{x:n.plotLeft+a[0]+(k.x||0),y:n.plotTop+a[1]-{high:.5,middle:.25,low:0}[k.align]*a[2]+(k.y||0)}},createLabelCollector:function(){var a=this;return function(){if(a.isRadial&&a.tickPositions&&!0!==a.options.labels.allowOverlap)return a.tickPositions.map(function(n){return a.ticks[n]&&a.ticks[n].label}).filter(function(a){return!!a})}}};b(x,"init",function(a){var n=this.chart,k=n.angular,
f=n.polar,p=this.isXAxis,b=k&&p,v,d=n.options;a=a.userOptions.pane||0;a=this.pane=n.pane&&n.pane[a];if("colorAxis"===this.coll)this.isRadial=!1;else{if(k){if(h(this,b?w:A),v=!p)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else f&&(h(this,A),this.defaultRadialOptions=(v=p)?this.defaultRadialXOptions:e(this.defaultYAxisOptions,this.defaultRadialYOptions));k||f?(this.isRadial=!0,n.inverted=!1,d.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&
n.labelCollectors.push(this.labelCollector)):this.isRadial=!1;a&&v&&(a.axis=this);this.isCircular=v}});b(x,"afterInit",function(){var a=this.chart,n=this.options,k=this.pane,f=k&&k.options;a.angular&&this.isXAxis||!k||!a.angular&&!a.polar||(this.angleRad=(n.angle||0)*Math.PI/180,this.startAngleRad=(f.startAngle-90)*Math.PI/180,this.endAngleRad=(m(f.endAngle,f.startAngle+360)-90)*Math.PI/180,this.offset=n.offset||0)});b(x,"autoLabelAlign",function(a){this.isRadial&&(a.align=void 0,a.preventDefault())});
b(x,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var a=this.chart.labelCollectors.indexOf(this.labelCollector);0<=a&&this.chart.labelCollectors.splice(a,1)}});b(d,"afterGetPosition",function(a){this.axis.getPosition&&h(a.pos,this.axis.getPosition(this.pos))});b(d,"afterGetLabelPosition",function(a){var n=this.axis,k=this.label,f=k.getBBox(),p=n.options.labels,b=p.y,v=20,d=p.align,g=(n.translate(this.pos)+n.startAngleRad+Math.PI/2)/Math.PI*180%360,l=Math.round(g),q="end",t=0>l?l+
360:l,h=t,r=0,w=0,u=null===p.y?.3*-f.height:0;if(n.isRadial){var x=n.getPosition(this.pos,n.center[2]/2+c.relativeLength(m(p.distance,-25),n.center[2]/2,-n.center[2]/2));"auto"===p.rotation?k.attr({rotation:g}):null===b&&(b=n.chart.renderer.fontMetrics(k.styles&&k.styles.fontSize).b-f.height/2);null===d&&(n.isCircular?(f.width>n.len*n.tickInterval/(n.max-n.min)&&(v=0),d=g>v&&g<180-v?"left":g>180+v&&g<360-v?"right":"center"):d="center",k.attr({align:d}));if("auto"===d&&2===n.tickPositions.length&&
n.isCircular){90<t&&180>t?t=180-t:270<t&&360>=t&&(t=540-t);180<h&&360>=h&&(h=360-h);if(n.pane.options.startAngle===l||n.pane.options.startAngle===l+360||n.pane.options.startAngle===l-360)q="start";d=-90<=l&&90>=l||-360<=l&&-270>=l||270<=l&&360>=l?"start"===q?"right":"left":"start"===q?"left":"right";70<h&&110>h&&(d="center");15>t||180<=t&&195>t?r=.3*f.height:15<=t&&35>=t?r="start"===q?0:.75*f.height:195<=t&&215>=t?r="start"===q?.75*f.height:0:35<t&&90>=t?r="start"===q?.25*-f.height:f.height:215<t&&
270>=t&&(r="start"===q?f.height:.25*-f.height);15>h?w="start"===q?.15*-f.height:.15*f.height:165<h&&180>=h&&(w="start"===q?.15*f.height:.15*-f.height);k.attr({align:d});k.translate(w,r+u)}a.pos.x=x.x+p.x;a.pos.y=x.y+b}});l(g,"getMarkPath",function(a,n,k,f,p,b,d){var v=this.axis;v.isRadial?(a=v.getPosition(this.pos,v.center[2]/2+f),n=["M",n,k,"L",a.x,a.y]):n=a.call(this,n,k,f,p,b,d);return n})});z(e,"parts-more/AreaRangeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=
b.defined,h=b.extend,m=b.isArray,u=b.isNumber,x=b.pick;b=c.seriesType;var e=c.seriesTypes,a=c.Series.prototype,d=c.Point.prototype;b("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(a){return[a.low,
a.high]},highToXY:function(a){var b=this.chart,d=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=d.x-b.plotLeft;a.plotHigh=d.y-b.plotTop;a.plotLowX=a.plotX},translate:function(){var a=this,b=a.yAxis,d=!!a.modifyValue;e.area.prototype.translate.apply(a);a.points.forEach(function(g){var t=g.high,q=g.plotY;g.isNull?g.plotY=null:(g.plotLow=q,g.plotHigh=b.translate(d?a.modifyValue(t,g):t,0,1,0,1),d&&(g.yBottom=g.plotHigh))});this.chart.polar&&this.points.forEach(function(b){a.highToXY(b);
b.tooltipPos=[(b.plotHighX+b.plotLowX)/2,(b.plotHigh+b.plotLow)/2]})},getGraphPath:function(a){var b=[],d=[],l,h=e.area.prototype.getGraphPath;var q=this.options;var n=this.chart.polar&&!1!==q.connectEnds,k=q.connectNulls,f=q.step;a=a||this.points;for(l=a.length;l--;){var p=a[l];p.isNull||n||k||a[l+1]&&!a[l+1].isNull||d.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1});var D={polarPlotY:p.polarPlotY,rectPlotX:p.rectPlotX,yBottom:p.yBottom,plotX:x(p.plotHighX,p.plotX),plotY:p.plotHigh,isNull:p.isNull};
d.push(D);b.push(D);p.isNull||n||k||a[l-1]&&!a[l-1].isNull||d.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1})}a=h.call(this,a);f&&(!0===f&&(f="left"),q.step={left:"right",center:"center",right:"left"}[f]);b=h.call(this,b);d=h.call(this,d);q.step=f;q=[].concat(a,b);this.chart.polar||"M"!==d[0]||(d[0]="L");this.graphPath=q;this.areaPath=a.concat(d);q.isArea=!0;q.xMap=a.xMap;this.areaPath.xMap=a.xMap;return q},drawDataLabels:function(){var b=this.points,d=b.length,g,c=[],r=this.options.dataLabels,q,n=
this.chart.inverted;if(m(r))if(1<r.length){var k=r[0];var f=r[1]}else k=r[0],f={enabled:!1};else k=h({},r),k.x=r.xHigh,k.y=r.yHigh,f=h({},r),f.x=r.xLow,f.y=r.yLow;if(k.enabled||this._hasPointLabels){for(g=d;g--;)if(q=b[g]){var p=k.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow;q.y=q.high;q._plotY=q.plotY;q.plotY=q.plotHigh;c[g]=q.dataLabel;q.dataLabel=q.dataLabelUpper;q.below=p;n?k.align||(k.align=p?"right":"left"):k.verticalAlign||(k.verticalAlign=p?"top":"bottom")}this.options.dataLabels=k;a.drawDataLabels&&
a.drawDataLabels.apply(this,arguments);for(g=d;g--;)if(q=b[g])q.dataLabelUpper=q.dataLabel,q.dataLabel=c[g],delete q.dataLabels,q.y=q.low,q.plotY=q._plotY}if(f.enabled||this._hasPointLabels){for(g=d;g--;)if(q=b[g])p=f.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow,q.below=!p,n?f.align||(f.align=p?"left":"right"):f.verticalAlign||(f.verticalAlign=p?"bottom":"top");this.options.dataLabels=f;a.drawDataLabels&&a.drawDataLabels.apply(this,arguments)}if(k.enabled)for(g=d;g--;)if(q=b[g])q.dataLabels=[q.dataLabelUpper,
q.dataLabel].filter(function(f){return!!f});this.options.dataLabels=r},alignDataLabel:function(){e.column.prototype.alignDataLabel.apply(this,arguments)},drawPoints:function(){var b=this.points.length,d;a.drawPoints.apply(this,arguments);for(d=0;d<b;){var g=this.points[d];g.origProps={plotY:g.plotY,plotX:g.plotX,isInside:g.isInside,negative:g.negative,zone:g.zone,y:g.y};g.lowerGraphic=g.graphic;g.graphic=g.upperGraphic;g.plotY=g.plotHigh;r(g.plotHighX)&&(g.plotX=g.plotHighX);g.y=g.high;g.negative=
g.high<(this.options.threshold||0);g.zone=this.zones.length&&g.getZone();this.chart.polar||(g.isInside=g.isTopInside="undefined"!==typeof g.plotY&&0<=g.plotY&&g.plotY<=this.yAxis.len&&0<=g.plotX&&g.plotX<=this.xAxis.len);d++}a.drawPoints.apply(this,arguments);for(d=0;d<b;)g=this.points[d],g.upperGraphic=g.graphic,g.graphic=g.lowerGraphic,h(g,g.origProps),delete g.origProps,d++},setStackedPoints:c.noop},{setState:function(){var a=this.state,b=this.series,g=b.chart.polar;r(this.plotHigh)||(this.plotHigh=
b.yAxis.toPixels(this.high,!0));r(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;g&&(this.plotX=this.plotHighX);d.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;g&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,
b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);d.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,b=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(b=d.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(b=b.concat(d.haloPath.apply(this,arguments)));return b},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=
this[a].destroy())},this);this.graphic=null;return d.destroyElements.apply(this,arguments)},isValid:function(){return u(this.low)&&u(this.high)}});""});z(e,"parts-more/AreaSplineRangeSeries.js",[e["parts/Globals.js"]],function(c){var b=c.seriesType;b("areasplinerange","arearange",null,{getPointSpline:c.seriesTypes.spline.prototype.getPointSpline});""});z(e,"parts-more/ColumnRangeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.clamp,h=b.pick;b=c.defaultPlotOptions;
var m=c.merge,u=c.noop,x=c.seriesType,e=c.seriesTypes.column.prototype;x("columnrange","arearange",m(b.column,b.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var a=this,b=a.yAxis,l=a.xAxis,t=l.startAngleRad,g,c=a.chart,m=a.xAxis.isRadial,q=Math.max(c.chartWidth,c.chartHeight)+999,n;e.translate.apply(a);a.points.forEach(function(k){var f=k.shapeArgs,p=a.options.minPointLength;k.plotHigh=n=r(b.translate(k.high,0,1,0,1),-q,q);k.plotLow=r(k.plotY,-q,q);var d=
n;var v=h(k.rectPlotY,k.plotY)-n;Math.abs(v)<p?(p-=v,v+=p,d-=p/2):0>v&&(v*=-1,d-=v);m?(g=k.barX+t,k.shapeType="path",k.shapeArgs={d:a.polarArc(d+v,d,g,g+k.pointWidth)}):(f.height=v,f.y=d,k.tooltipPos=c.inverted?[b.len+b.pos-c.plotLeft-d-v/2,l.len+l.pos-c.plotTop-f.x-f.width/2,v]:[l.left-c.plotLeft+f.x+f.width/2,b.pos-c.plotTop+d+v/2,v])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:u,getSymbol:u,crispCol:function(){return e.crispCol.apply(this,arguments)},drawPoints:function(){return e.drawPoints.apply(this,
arguments)},drawTracker:function(){return e.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return e.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return e.pointAttribs.apply(this,arguments)},animate:function(){return e.animate.apply(this,arguments)},polarArc:function(){return e.polarArc.apply(this,arguments)},translate3dPoints:function(){return e.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return e.translate3dShapes.apply(this,arguments)}},
{setState:e.pointClass.prototype.setState});""});z(e,"parts-more/ColumnPyramidSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.clamp,h=b.pick;b=c.seriesType;var m=c.seriesTypes.column.prototype;b("columnpyramid","column",{},{translate:function(){var b=this,c=b.chart,e=b.options,a=b.dense=2>b.closestPointRange*b.xAxis.transA;a=b.borderWidth=h(e.borderWidth,a?0:1);var d=b.yAxis,l=e.threshold,t=b.translatedThreshold=d.getThreshold(l),g=h(e.minPointLength,5),w=b.getColumnMetrics(),
A=w.width,q=b.barW=Math.max(A,1+2*a),n=b.pointXOffset=w.offset;c.inverted&&(t-=.5);e.pointPadding&&(q=Math.ceil(q));m.translate.apply(b);b.points.forEach(function(a){var f=h(a.yBottom,t),p=999+Math.abs(f),k=r(a.plotY,-p,d.len+p);p=a.plotX+n;var v=q/2,B=Math.min(k,f);f=Math.max(k,f)-B;a.barX=p;a.pointWidth=A;a.tooltipPos=c.inverted?[d.len+d.pos-c.plotLeft-k,b.xAxis.len-p-v,f]:[p+v,k+d.pos-c.plotTop,f];k=l+(a.total||a.y);"percent"===e.stacking&&(k=l+(0>a.y)?-100:100);k=d.toPixels(k,!0);var y=c.plotHeight-
k-(c.plotHeight-t);var m=v*(B-k)/y;var u=v*(B+f-k)/y;y=p-m+v;m=p+m+v;var x=p+u+v;u=p-u+v;var w=B-g;var C=B+f;0>a.y&&(w=B,C=B+f+g);c.inverted&&(x=c.plotWidth-B,y=k-(c.plotWidth-t),m=v*(k-x)/y,u=v*(k-(x-f))/y,y=p+v+m,m=y-2*m,x=p-u+v,u=p+u+v,w=B,C=B+f-g,0>a.y&&(C=B+f+g));a.shapeType="path";a.shapeArgs={x:y,y:w,width:m-y,height:f,d:["M",y,w,"L",m,w,x,C,u,C,"Z"]}})}});""});z(e,"parts-more/GaugeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.clamp,h=b.isNumber,m=b.pick,
u=b.pInt,x=c.merge,e=c.Series;b=c.seriesType;var a=c.TrackerMixin;b("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:c.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,b=this.options,c=a.center;this.generatePoints();this.points.forEach(function(d){var g=
x(b.dial,d.dial),t=u(m(g.radius,"80%"))*c[2]/200,q=u(m(g.baseLength,"70%"))*t/100,n=u(m(g.rearLength,"10%"))*t/100,k=g.baseWidth||3,f=g.topWidth||1,p=b.overshoot,D=a.startAngleRad+a.translate(d.y,null,null,null,!0);if(h(p)||!1===b.wrap)p=h(p)?p/180*Math.PI:0,D=r(D,a.startAngleRad-p,a.endAngleRad+p);D=180*D/Math.PI;d.shapeType="path";d.shapeArgs={d:g.path||["M",-n,-k/2,"L",q,-k/2,t,-f/2,t,f/2,q,k/2,-n,k/2,"z"],translateX:c[0],translateY:c[1],rotation:D};d.plotX=c[0];d.plotY=c[1]})},drawPoints:function(){var a=
this,b=a.chart,c=a.yAxis.center,g=a.pivot,h=a.options,r=h.pivot,q=b.renderer;a.points.forEach(function(n){var k=n.graphic,f=n.shapeArgs,p=f.d,d=x(h.dial,n.dial);k?(k.animate(f),f.d=p):n.graphic=q[n.shapeType](f).attr({rotation:f.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!b.styledMode)n.graphic[k?"animate":"attr"]({stroke:d.borderColor||"none","stroke-width":d.borderWidth||0,fill:d.backgroundColor||"#000000"})});g?g.animate({translateX:c[0],translateY:c[1]}):(a.pivot=q.circle(0,
0,m(r.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(c[0],c[1]).add(a.group),b.styledMode||a.pivot.attr({"stroke-width":r.borderWidth||0,stroke:r.borderColor||"#cccccc",fill:r.backgroundColor||"#000000"}))},animate:function(a){var b=this;a||(b.points.forEach(function(a){var d=a.graphic;d&&(d.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),d.animate({rotation:a.shapeArgs.rotation},b.options.animation))}),b.animate=null)},render:function(){this.group=this.plotGroup("group","series",
this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);e.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,b){e.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();m(b,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:a&&a.drawTrackerPoint},{setState:function(a){this.state=a}});""});z(e,"parts-more/BoxPlotSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.pick;
b=c.noop;var h=c.seriesType,m=c.seriesTypes;h("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(b){return[b.low,b.q1,b.median,b.q3,
b.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:b,translate:function(){var b=this.yAxis,c=this.pointArrayMap;m.column.prototype.translate.apply(this);this.points.forEach(function(h){c.forEach(function(a){null!==h[a]&&(h[a+"Plot"]=b.translate(h[a],0,1,0,1))})})},drawPoints:function(){var b=this,c=b.options,h=b.chart,a=h.renderer,d,m,t,g,e,A,q=0,n,k,f,p,D=!1!==b.doQuartiles,v,B=b.options.whiskerLength;b.points.forEach(function(y){var l=y.graphic,u=l?"animate":"attr",x=y.shapeArgs,
w={},C={},F={},H={},G=y.color||b.color;"undefined"!==typeof y.plotY&&(n=x.width,k=Math.floor(x.x),f=k+n,p=Math.round(n/2),d=Math.floor(D?y.q1Plot:y.lowPlot),m=Math.floor(D?y.q3Plot:y.lowPlot),t=Math.floor(y.highPlot),g=Math.floor(y.lowPlot),l||(y.graphic=l=a.g("point").add(b.group),y.stem=a.path().addClass("highcharts-boxplot-stem").add(l),B&&(y.whiskers=a.path().addClass("highcharts-boxplot-whisker").add(l)),D&&(y.box=a.path(void 0).addClass("highcharts-boxplot-box").add(l)),y.medianShape=a.path(void 0).addClass("highcharts-boxplot-median").add(l)),
h.styledMode||(C.stroke=y.stemColor||c.stemColor||G,C["stroke-width"]=r(y.stemWidth,c.stemWidth,c.lineWidth),C.dashstyle=y.stemDashStyle||c.stemDashStyle,y.stem.attr(C),B&&(F.stroke=y.whiskerColor||c.whiskerColor||G,F["stroke-width"]=r(y.whiskerWidth,c.whiskerWidth,c.lineWidth),y.whiskers.attr(F)),D&&(w.fill=y.fillColor||c.fillColor||G,w.stroke=c.lineColor||G,w["stroke-width"]=c.lineWidth||0,y.box.attr(w)),H.stroke=y.medianColor||c.medianColor||G,H["stroke-width"]=r(y.medianWidth,c.medianWidth,c.lineWidth),
y.medianShape.attr(H)),A=y.stem.strokeWidth()%2/2,q=k+p+A,y.stem[u]({d:["M",q,m,"L",q,t,"M",q,d,"L",q,g]}),D&&(A=y.box.strokeWidth()%2/2,d=Math.floor(d)+A,m=Math.floor(m)+A,k+=A,f+=A,y.box[u]({d:["M",k,m,"L",k,d,"L",f,d,"L",f,m,"L",k,m,"z"]})),B&&(A=y.whiskers.strokeWidth()%2/2,t+=A,g+=A,v=/%$/.test(B)?p*parseFloat(B)/100:B/2,y.whiskers[u]({d:["M",q-v,t,"L",q+v,t,"M",q-v,g,"L",q+v,g]})),e=Math.round(y.medianPlot),A=y.medianShape.strokeWidth()%2/2,e+=A,y.medianShape[u]({d:["M",k,e,"L",f,e]}))})},setStackedPoints:b});
""});z(e,"parts-more/ErrorBarSeries.js",[e["parts/Globals.js"]],function(c){var b=c.noop,r=c.seriesType,h=c.seriesTypes;r("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(b){return[b.low,b.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:h.arearange?function(){var b=
this.pointValKey;h.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(c){c.y=c[b]})}:b,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||h.column.prototype.getColumnMetrics.call(this)}});""});z(e,"parts-more/WaterfallSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.arrayMax,h=b.arrayMin,m=b.correctFloat,u=b.isNumber,e=b.objectEach,E=b.pick;b=c.addEvent;var a=c.Axis,d=c.Chart,l=c.Point,t=c.Series,g=c.StackItem,
w=c.seriesType,A=c.seriesTypes;b(a,"afterInit",function(){this.isXAxis||(this.waterfallStacks={changed:!1})});b(a,"afterBuildStacks",function(){this.waterfallStacks.changed=!1;delete this.waterfallStacks.alreadyChanged});b(d,"beforeRedraw",function(){for(var a=this.axes,b=this.series,k=b.length;k--;)b[k].options.stacking&&(a.forEach(function(a){a.isXAxis||(a.waterfallStacks.changed=!0)}),k=0)});b(a,"afterRender",function(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfallStacks&&this.renderWaterfallStackTotals()});
a.prototype.renderWaterfallStackTotals=function(){var a=this.waterfallStacks,b=this.stackTotalGroup,k=new g(this,this.options.stackLabels,!1,0,void 0);this.dummyStackItem=k;e(a,function(a){e(a,function(a){k.total=a.stackTotal;a.label&&(k.label=a.label);g.prototype.render.call(k,b);a.label=k.label;delete k.label})});k.total=null};w("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,
generatePoints:function(){var a;A.column.prototype.generatePoints.apply(this);var b=0;for(a=this.points.length;b<a;b++){var k=this.points[b];var f=this.processedYData[b];if(k.isIntermediateSum||k.isSum)k.y=m(f)}},translate:function(){var a=this.options,b=this.yAxis,k,f=E(a.minPointLength,5),p=f/2,d=a.threshold,v=a.stacking,g=b.waterfallStacks[this.stackKey];A.column.prototype.translate.apply(this);var c=k=d;var h=this.points;var t=0;for(a=h.length;t<a;t++){var m=h[t];var r=this.processedYData[t];
var l=m.shapeArgs;var u=[0,r];var e=m.y;if(v){if(g){u=g[t];if("overlap"===v){var w=u.stackState[u.stateIndex--];w=0<=e?w:w-e;Object.hasOwnProperty.call(u,"absolutePos")&&delete u.absolutePos;Object.hasOwnProperty.call(u,"absoluteNeg")&&delete u.absoluteNeg}else 0<=e?(w=u.threshold+u.posTotal,u.posTotal-=e):(w=u.threshold+u.negTotal,u.negTotal-=e,w-=e),!u.posTotal&&Object.hasOwnProperty.call(u,"absolutePos")&&(u.posTotal=u.absolutePos,delete u.absolutePos),!u.negTotal&&Object.hasOwnProperty.call(u,
"absoluteNeg")&&(u.negTotal=u.absoluteNeg,delete u.absoluteNeg);m.isSum||(u.connectorThreshold=u.threshold+u.stackTotal);b.reversed?(r=0<=e?w-e:w+e,e=w):(r=w,e=w-e);m.below=r<=E(d,0);l.y=b.translate(r,0,1,0,1);l.height=Math.abs(l.y-b.translate(e,0,1,0,1))}if(e=b.dummyStackItem)e.x=t,e.label=g[t].label,e.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[t],this.stackedYPos[t])}else w=Math.max(c,c+e)+u[0],l.y=b.translate(w,0,1,0,1),m.isSum?(l.y=b.translate(u[1],0,1,0,1),l.height=Math.min(b.translate(u[0],
0,1,0,1),b.len)-l.y):m.isIntermediateSum?(0<=e?(r=u[1]+k,e=k):(r=k,e=u[1]+k),b.reversed&&(r^=e,e^=r,r^=e),l.y=b.translate(r,0,1,0,1),l.height=Math.abs(l.y-Math.min(b.translate(e,0,1,0,1),b.len)),k+=u[1]):(l.height=0<r?b.translate(c,0,1,0,1)-l.y:b.translate(c,0,1,0,1)-b.translate(c-r,0,1,0,1),c+=r,m.below=c<E(d,0)),0>l.height&&(l.y+=l.height,l.height*=-1);m.plotY=l.y=Math.round(l.y)-this.borderWidth%2/2;l.height=Math.max(Math.round(l.height),.001);m.yBottom=l.y+l.height;l.height<=f&&!m.isNull?(l.height=
f,l.y-=p,m.plotY=l.y,m.minPointLengthOffset=0>m.y?-p:p):(m.isNull&&(l.width=0),m.minPointLengthOffset=0);l=m.plotY+(m.negative?l.height:0);this.chart.inverted?m.tooltipPos[0]=b.len-l:m.tooltipPos[1]=l}},processData:function(a){var b=this.options,k=this.yData,f=b.data,p=k.length,d=b.threshold||0,v,g,c,h,l;for(l=g=v=c=h=0;l<p;l++){var q=k[l];var r=f&&f[l]?f[l]:{};"sum"===q||r.isSum?k[l]=m(g):"intermediateSum"===q||r.isIntermediateSum?(k[l]=m(v),v=0):(g+=q,v+=q);c=Math.min(g,c);h=Math.max(g,h)}t.prototype.processData.call(this,
a);b.stacking||(this.dataMin=c+d,this.dataMax=h)},toYData:function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y},updateParallelArrays:function(a,b){t.prototype.updateParallelArrays.call(this,a,b);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null},pointAttribs:function(a,b){var k=this.options.upColor;k&&!a.options.color&&(a.color=0<a.y?k:null);a=A.column.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a},getGraphPath:function(){return["M",
0,0]},getCrispPath:function(){var a=this.data,b=this.yAxis,k=a.length,f=Math.round(this.graph.strokeWidth())%2/2,p=Math.round(this.borderWidth)%2/2,d=this.xAxis.reversed,v=this.yAxis.reversed,g=this.options.stacking,c=[],h;for(h=1;h<k;h++){var l=a[h].shapeArgs;var m=a[h-1];var r=a[h-1].shapeArgs;var t=b.waterfallStacks[this.stackKey];var u=0<m.y?-r.height:0;if(t){t=t[h-1];g?(t=t.connectorThreshold,u=Math.round(b.translate(t,0,1,0,1)+(v?u:0))-f):u=r.y+m.minPointLengthOffset+p-f;var e=["M",r.x+(d?0:
r.width),u,"L",l.x+(d?l.width:0),u]}if(!g&&e&&0>m.y&&!v||0<m.y&&v)e[2]+=r.height,e[5]+=r.height;c=c.concat(e)}return c},drawGraph:function(){t.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function a(a,f,b,k){if(z)for(b;b<z;b++)w.stackState[b]+=k;else w.stackState[0]=a,z=w.stackState.length;w.stackState.push(w.stackState[z-1]+f)}var b=this.options,k=this.yAxis.waterfallStacks,f=b.threshold,p=f||0,d=p,v=this.stackKey,g=this.xData,c=g.length,h,
l,m;this.yAxis.usePercentage=!1;var r=l=m=p;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var t=k.changed;(h=k.alreadyChanged)&&0>h.indexOf(v)&&(t=!0);k[v]||(k[v]={});h=k[v];for(var u=0;u<c;u++){var e=g[u];if(!h[e]||t)h[e]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:t&&h[e]?h[e].label:void 0};var w=h[e];var x=this.yData[u];0<=x?w.posTotal+=x:w.negTotal+=x;var A=b.data[u];e=w.absolutePos=w.posTotal;var E=w.absoluteNeg=w.negTotal;w.stackTotal=e+
E;var z=w.stackState.length;A&&A.isIntermediateSum?(a(m,l,0,m),m=l,l=f,p^=d,d^=p,p^=d):A&&A.isSum?(a(f,r,z),p=f):(a(p,x,0,r),A&&(r+=x,l+=x));w.stateIndex++;w.threshold=p;p+=w.stackTotal}k.changed=!1;k.alreadyChanged||(k.alreadyChanged=[]);k.alreadyChanged.push(v)}},getExtremes:function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfallStacks;var k=this.stackedYNeg=[];var f=this.stackedYPos=[];"overlap"===a?e(b[this.stackKey],function(a){k.push(h(a.stackState));f.push(r(a.stackState))}):
e(b[this.stackKey],function(a){k.push(a.negTotal+a.threshold);f.push(a.posTotal+a.threshold)});this.dataMin=h(k);this.dataMax=r(f)}}},{getClassName:function(){var a=l.prototype.getClassName.call(this);this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a},isValid:function(){return u(this.y)||this.isSum||this.isIntermediateSum}});""});z(e,"parts-more/PolygonSeries.js",[e["parts/Globals.js"]],function(c){var b=c.Series,r=c.seriesType,h=c.seriesTypes;r("polygon",
"scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var c=b.prototype.getGraphPath.call(this),h=c.length+1;h--;)(h===c.length||"M"===c[h])&&0<h&&c.splice(h,0,"z");return this.areaPath=c},drawGraph:function(){this.options.fillColor=this.color;h.area.prototype.drawGraph.call(this)},drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,drawTracker:b.prototype.drawTracker,setStackedPoints:c.noop});
""});z(e,"parts-more/BubbleLegend.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.arrayMax,h=b.arrayMin,m=b.isNumber,u=b.objectEach,e=b.pick;b=c.Series;var E=c.Legend,a=c.Chart,d=c.addEvent,l=c.wrap,t=c.color,g=c.merge,w=c.noop,A=c.stableSort,q=c.setOptions;q({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,
format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});c.BubbleLegend=function(a,b){this.init(a,b)};c.BubbleLegend.prototype={init:function(a,b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b},setState:w,addToLegend:function(a){a.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(a){var b=
this.chart,f=this.options,p=e(a.options.itemDistance,20),d=f.ranges;var n=f.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(f.labels.style.fontSize.toString()+"px");d&&d.length&&m(d[0].value)?(A(d,function(a,f){return f.value-a.value}),this.ranges=d,this.setOptions(),this.render(),b=this.getMaxLabelSize(),d=this.ranges[0].radius,a=2*d,n=n-d+b.width,n=0<n?n:0,this.maxLabel=b,this.movementX="left"===f.labels.align?n:0,this.legendItemWidth=a+n+p,this.legendItemHeight=a+this.fontMetrics.h/2):
a.options.bubbleLegend.autoRanges=!0},setOptions:function(){var a=this.ranges,b=this.options,f=this.chart.series[b.seriesIndex],p=this.legend.baseline,d={"z-index":b.zIndex,"stroke-width":b.borderWidth},c={"z-index":b.zIndex,"stroke-width":b.connectorWidth},h=this.getLabelStyles(),l=f.options.marker.fillOpacity,m=this.chart.styledMode;a.forEach(function(k,n){m||(d.stroke=e(k.borderColor,b.borderColor,f.color),d.fill=e(k.color,b.color,1!==l?t(f.color).setOpacity(l).get("rgba"):f.color),c.stroke=e(k.connectorColor,
b.connectorColor,f.color));a[n].radius=this.getRangeRadius(k.value);a[n]=g(a[n],{center:a[0].radius-a[n].radius+p});m||g(!0,a[n],{bubbleStyle:g(!1,d),connectorStyle:g(!1,c),labelStyle:h})},this)},getLabelStyles:function(){var a=this.options,b={},f="left"===a.labels.align,p=this.legend.options.rtl;u(a.labels.style,function(a,f){"color"!==f&&"fontSize"!==f&&"z-index"!==f&&(b[f]=a)});return g(!1,b,{"font-size":a.labels.style.fontSize,fill:e(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:p||
f?"right":"left"})},getRangeRadius:function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)},render:function(){var a=this.chart.renderer,b=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=
b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(a){var b=this.options,f=b.labels,p=this.chart.renderer,d=this.symbols,n=d.labels,c=a.center,g=Math.abs(a.radius),h=b.connectorDistance,l=f.align,m=f.style.fontSize;h=this.legend.options.rtl||"left"===l?-h:h;f=b.connectorWidth;var r=this.ranges[0].radius,t=c-g-b.borderWidth/2+f/2;m=m/2-(this.fontMetrics.h-m)/2;var q=p.styledMode;"center"===l&&
(h=0,b.connectorDistance=0,a.labelStyle.align="center");l=t+b.labels.y;var e=r+h+b.labels.x;d.bubbleItems.push(p.circle(r,c+((t%1?1:.5)-(f%2?0:.5)),g).attr(q?{}:a.bubbleStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendSymbol));d.connectors.push(p.path(p.crispLine(["M",r,t,"L",r+h,t],b.connectorWidth)).attr(q?{}:a.connectorStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+
(b.connectorClassName||"")).add(this.legendSymbol));a=p.text(this.formatLabel(a),e,l+m).attr(q?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);n.push(a);a.placed=!0;a.alignAttr={x:e,y:l+m}},getMaxLabelSize:function(){var a,b;this.symbols.labels.forEach(function(f){b=f.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}},formatLabel:function(a){var b=this.options,f=b.labels.formatter;b=b.labels.format;var p=this.chart.numberFormatter;return b?
c.format(b,a):f?f.call(a):p(a.value,1)},hideOverlappingLabels:function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),b.labels.forEach(function(a,p){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[p].show():b.connectors[p].hide()}))},getRanges:function(){var a=this.legend.bubbleLegend,b=a.options.ranges,f,p=Number.MAX_VALUE,d=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(f=a.zData.filter(m),f.length&&
(p=e(a.options.zMin,Math.min(p,Math.max(h(f),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),d=e(a.options.zMax,Math.max(d,r(f)))))});var c=p===d?[{value:d}]:[{value:p},{value:(p+d)/2},{value:d,autoRanges:!0}];b.length&&b[0].radius&&c.reverse();c.forEach(function(a,f){b&&b[f]&&(c[f]=g(!1,b[f],a))});return c},predictBubbleSizes:function(){var a=this.chart,b=this.fontMetrics,f=a.legend.options,d="horizontal"===f.layout,c=d?a.legend.lastLineHeight:0,g=a.plotSizeX,h=a.plotSizeY,
l=a.series[this.options.seriesIndex];a=Math.ceil(l.minPxSize);var m=Math.ceil(l.maxPxSize);l=l.options.maxSize;var r=Math.min(h,g);if(f.floating||!/%$/.test(l))b=m;else if(l=parseFloat(l),b=(r+c-b.h/2)*l/100/(l/100+1),d&&h-b>=g||!d&&g-b>=h)b=m;return[a,Math.ceil(b)]},updateRanges:function(a,b){var f=this.legend.options.bubbleLegend;f.minSize=a;f.maxSize=b;f.ranges=this.getRanges()},correctSizes:function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-
this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())}};d(c.Legend,"afterGetAllItems",function(a){var b=this.bubbleLegend,f=this.options,d=f.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(b));0<=g&&f.enabled&&d.enabled&&(d.seriesIndex=g,this.bubbleLegend=new c.BubbleLegend(d,this),this.bubbleLegend.addToLegend(a.allItems))});a.prototype.getVisibleBubbleSeriesIndex=
function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};E.prototype.getLinesHeights=function(){var a=this.allItems,b=[],f=a.length,d,c=0;for(d=0;d<f;d++)if(a[d].legendItemHeight&&(a[d].itemHeight=a[d].legendItemHeight),a[d]===a[f-1]||a[d+1]&&a[d]._legendItemPos[1]!==a[d+1]._legendItemPos[1]){b.push({height:0});var g=b[b.length-1];for(c;c<=d;c++)a[c].itemHeight>g.height&&(g.height=a[c].itemHeight);g.step=d}return b};E.prototype.retranslateItems=
function(a){var b,f,d,c=this.options.rtl,g=0;this.allItems.forEach(function(p,h){b=p.legendGroup.translateX;f=p._legendItemPos[1];if((d=p.movementX)||c&&p.ranges)d=c?b-p.options.maxSize/2:b+d,p.legendGroup.attr({translateX:d});h>a[g].step&&g++;p.legendGroup.attr({translateY:Math.round(f+a[g].height/2)});p._legendItemPos[1]=f+a[g].height/2})};d(b,"legendItemClick",function(){var a=this.chart,b=this.visible,f=this.chart.legend;f&&f.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),
f.bubbleLegend.visible!==a&&(f.update({bubbleLegend:{enabled:a}}),f.bubbleLegend.visible=a),this.visible=b)});l(a.prototype,"drawChartBox",function(a,b,f){var d=this.legend,c=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&c){var g=d.bubbleLegend.options;c=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(c[0],c[1]);g.placed||(d.group.placed=!1,d.allItems.forEach(function(a){a.legendGroup.translateY=null}));d.render();
this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();g.placed||(a.setScale(),a.updateNames(),u(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});g.placed=!0;this.getMargins();a.call(this,b,f);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else a.call(this,b,f),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))})});z(e,"parts-more/BubbleSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var r=b.arrayMax,
h=b.arrayMin,m=b.clamp,e=b.extend,x=b.isNumber,E=b.pick,a=b.pInt;b=c.Axis;var d=c.color,l=c.noop,t=c.Point,g=c.Series,w=c.seriesType,A=c.seriesTypes;w("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},
turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,b){var c=this.options.marker.fillOpacity;a=g.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=d(a.fill).setOpacity(c).get("rgba"));return a},getRadii:function(a,b,d){var f=this.zData,c=this.yData,g=d.minPxSize,h=d.maxPxSize,l=[];var k=0;for(d=f.length;k<d;k++){var m=
f[k];l.push(this.getRadius(a,b,g,h,m,c[k]))}this.radii=l},getRadius:function(a,b,d,f,c,g){var p=this.options,h="width"!==p.sizeBy,l=p.zThreshold,k=b-a,m=.5;if(null===g||null===c)return null;if(x(c)){p.sizeByAbsoluteValue&&(c=Math.abs(c-l),k=Math.max(b-l,Math.abs(a-l)),a=0);if(c<a)return d/2-1;0<k&&(m=(c-a)/k)}h&&0<=m&&(m=Math.sqrt(m));return Math.ceil(d+m*(f-d))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var b=a.graphic;if(b&&b.width){var f=
{x:b.x,y:b.y,width:b.width,height:b.height};b.attr({x:a.plotX,y:a.plotY,width:1,height:1});b.animate(f,this.options.animation)}},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,b=this.data,d=this.radii;A.scatter.prototype.translate.call(this);for(a=b.length;a--;){var f=b[a];var c=d?d[a]:0;x(c)&&c>=this.minPxSize/2?(f.marker=e(f.marker,{radius:c,width:2*c,height:2*c}),f.dlBox={x:f.plotX-c,y:f.plotY-c,width:2*c,height:2*c}):f.shapeArgs=f.plotY=
f.dlBox=void 0}},alignDataLabel:A.column.prototype.alignDataLabel,buildKDTree:l,applyZones:l},{haloPath:function(a){return t.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});b.prototype.beforePadding=function(){var b=this,d=this.len,c=this.chart,f=0,g=d,l=this.isXAxis,v=l?"xData":"yData",t=this.min,e={},u=Math.min(c.plotWidth,c.plotHeight),w=Number.MAX_VALUE,A=-Number.MAX_VALUE,z=this.max-t,C=d/z,F=[];this.series.forEach(function(f){var d=f.options;!f.bubblePadding||
!f.visible&&c.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=!0,F.push(f),l&&(["minSize","maxSize"].forEach(function(b){var f=d[b],c=/%$/.test(f);f=a(f);e[b]=c?u*f/100:f}),f.minPxSize=e.minSize,f.maxPxSize=Math.max(e.maxSize,e.minSize),f=f.zData.filter(x),f.length&&(w=E(d.zMin,m(h(f),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE,w)),A=E(d.zMax,Math.max(A,r(f))))))});F.forEach(function(a){var d=a[v],c=d.length;l&&a.getRadii(w,A,a);if(0<z)for(;c--;)if(x(d[c])&&b.dataMin<=d[c]&&d[c]<=
b.dataMax){var p=a.radii?a.radii[c]:0;f=Math.min((d[c]-t)*C-p,f);g=Math.max((d[c]-t)*C+p,g)}});F.length&&0<z&&!this.isLog&&(g-=d,C*=(d+Math.max(0,f)-Math.min(g,d))/d,[["min","userMin",f],["max","userMax",g]].forEach(function(a){"undefined"===typeof E(b.options[a[0]],b[a[1]])&&(b[a[0]]+=a[2]/C)}))};""});z(e,"modules/networkgraph/integrations.js",[e["parts/Globals.js"]],function(c){c.networkgraphIntegrations={verlet:{attractiveForceFunction:function(b,c){return(c-b)/b},repulsiveForceFunction:function(b,
c){return(c-b)/b*(c>b?1:0)},barycenter:function(){var b=this.options.gravitationalConstant,c=this.barycenter.xFactor,h=this.barycenter.yFactor;c=(c-(this.box.left+this.box.width)/2)*b;h=(h-(this.box.top+this.box.height)/2)*b;this.nodes.forEach(function(b){b.fixedPosition||(b.plotX-=c/b.mass/b.degree,b.plotY-=h/b.mass/b.degree)})},repulsive:function(b,c,h){c=c*this.diffTemperature/b.mass/b.degree;b.fixedPosition||(b.plotX+=h.x*c,b.plotY+=h.y*c)},attractive:function(b,c,h){var m=b.getMass(),r=-h.x*
c*this.diffTemperature;c=-h.y*c*this.diffTemperature;b.fromNode.fixedPosition||(b.fromNode.plotX-=r*m.fromNode/b.fromNode.degree,b.fromNode.plotY-=c*m.fromNode/b.fromNode.degree);b.toNode.fixedPosition||(b.toNode.plotX+=r*m.toNode/b.toNode.degree,b.toNode.plotY+=c*m.toNode/b.toNode.degree)},integrate:function(b,c){var h=-b.options.friction,m=b.options.maxSpeed,e=(c.plotX+c.dispX-c.prevX)*h;h*=c.plotY+c.dispY-c.prevY;var r=Math.abs,z=r(e)/(e||1);r=r(h)/(h||1);e=z*Math.min(m,Math.abs(e));h=r*Math.min(m,
Math.abs(h));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=e;c.plotY+=h;c.temperature=b.vectorLength({x:e,y:h})},getK:function(b){return Math.pow(b.box.width*b.box.height/b.nodes.length,.5)}},euler:{attractiveForceFunction:function(b,c){return b*b/c},repulsiveForceFunction:function(b,c){return c*c/b},barycenter:function(){var b=this.options.gravitationalConstant,c=this.barycenter.xFactor,h=this.barycenter.yFactor;this.nodes.forEach(function(m){if(!m.fixedPosition){var e=m.getDegree();e*=
1+e/2;m.dispX+=(c-m.plotX)*b*e/m.degree;m.dispY+=(h-m.plotY)*b*e/m.degree}})},repulsive:function(b,c,h,m){b.dispX+=h.x/m*c/b.degree;b.dispY+=h.y/m*c/b.degree},attractive:function(b,c,h,m){var e=b.getMass(),r=h.x/m*c;c*=h.y/m;b.fromNode.fixedPosition||(b.fromNode.dispX-=r*e.fromNode/b.fromNode.degree,b.fromNode.dispY-=c*e.fromNode/b.fromNode.degree);b.toNode.fixedPosition||(b.toNode.dispX+=r*e.toNode/b.toNode.degree,b.toNode.dispY+=c*e.toNode/b.toNode.degree)},integrate:function(b,c){c.dispX+=c.dispX*
b.options.friction;c.dispY+=c.dispY*b.options.friction;var h=c.temperature=b.vectorLength({x:c.dispX,y:c.dispY});0!==h&&(c.plotX+=c.dispX/h*Math.min(Math.abs(c.dispX),b.temperature),c.plotY+=c.dispY/h*Math.min(Math.abs(c.dispY),b.temperature))},getK:function(b){return Math.pow(b.box.width*b.box.height/b.nodes.length,.3)}}}});z(e,"modules/networkgraph/QuadTree.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){b=b.extend;var e=c.QuadTreeNode=function(b){this.box=b;this.boxSize=Math.min(b.width,
b.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};b(e.prototype,{insert:function(b,c){this.isInternal?this.nodes[this.getBoxPosition(b)].insert(b,c-1):(this.isEmpty=!1,this.body?c?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,c-1),this.body=!0),this.nodes[this.getBoxPosition(b)].insert(b,c-1)):(c=new e({top:b.plotX,left:b.plotY,width:.1,height:.1}),c.body=b,c.isInternal=!1,this.nodes.push(c)):(this.isInternal=
!1,this.body=b))},updateMassAndCenter:function(){var b=0,c=0,e=0;this.isInternal?(this.nodes.forEach(function(h){h.isEmpty||(b+=h.mass,c+=h.plotX*h.mass,e+=h.plotY*h.mass)}),c/=b,e/=b):this.body&&(b=this.body.mass,c=this.body.plotX,e=this.body.plotY);this.mass=b;this.plotX=c;this.plotY=e},divideBox:function(){var b=this.box.width/2,c=this.box.height/2;this.nodes[0]=new e({left:this.box.left,top:this.box.top,width:b,height:c});this.nodes[1]=new e({left:this.box.left+b,top:this.box.top,width:b,height:c});
this.nodes[2]=new e({left:this.box.left+b,top:this.box.top+c,width:b,height:c});this.nodes[3]=new e({left:this.box.left,top:this.box.top+c,width:b,height:c})},getBoxPosition:function(b){var c=b.plotY<this.box.top+this.box.height/2;return b.plotX<this.box.left+this.box.width/2?c?0:3:c?1:2}});c=c.QuadTree=function(b,c,u,r){this.box={left:b,top:c,width:u,height:r};this.maxDepth=25;this.root=new e(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};b(c.prototype,{insertNodes:function(b){b.forEach(function(b){this.root.insert(b,
this.maxDepth)},this)},visitNodeRecursive:function(b,c,e){var h;b||(b=this.root);b===this.root&&c&&(h=c(b));!1!==h&&(b.nodes.forEach(function(b){if(b.isInternal){c&&(h=c(b));if(!1===h)return;this.visitNodeRecursive(b,c,e)}else b.body&&c&&c(b.body);e&&e(b)},this),b===this.root&&e&&e(b))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(b){b.updateMassAndCenter()})}})});z(e,"modules/networkgraph/layouts.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var e=
b.clamp,h=b.defined,m=b.extend,u=b.pick,x=b.setAnimation;b=c.addEvent;var z=c.Chart;c.layouts={"reingold-fruchterman":function(){}};m(c.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=c.networkgraphIntegrations[a.integration];this.attractiveForce=u(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=u(a.repulsiveForce,this.integration.repulsiveForceFunction);
this.approximation=a.approximation},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.render()}));this.setK();this.resetSimulation(b);b.enableSimulation&&this.step()},step:function(){var a=this,b=this.series,l=this.options;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});
a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();l.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&c.win.cancelAnimationFrame(a.simulation),a.simulation=c.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&c.win.cancelAnimationFrame(this.simulation)},
setArea:function(a,b,c,h){this.box={left:a,top:b,width:c,height:h}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();
this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=u(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new c.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);
this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;c.isFunction(a)?(a.call(this),this.nodes.forEach(function(a){h(a.prevX)||(a.prevX=a.plotX);h(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(b){m[b.toNode.id]||(m[b.toNode.id]=!0,e.push(b.toNode),a(b.toNode))})}var b=this.box,c=this.nodes,h=2*Math.PI/(c.length+
1),g=c.filter(function(a){return 0===a.linksTo.length}),e=[],m={},q=this.options.initialPositionRadius;g.forEach(function(b){e.push(b);a(b)});e.length?c.forEach(function(a){-1===e.indexOf(a)&&e.push(a)}):e=c;e.forEach(function(a,c){a.plotX=a.prevX=u(a.plotX,b.width/2+q*Math.cos(c*h));a.plotY=a.prevY=u(a.plotY,b.height/2+q*Math.sin(c*h));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,c=this.nodes,e=c.length+1;c.forEach(function(c,
d){c.plotX=c.prevX=u(c.plotX,b.width*a(d));c.plotY=c.prevY=u(c.plotY,b.height*a(e+d));c.dispX=0;c.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,b=0,c=0;this.nodes.forEach(function(d){b+=d.plotX*d.mass;c+=d.plotY*d.mass;a+=d.mass});return this.barycenter={x:b,y:c,xFactor:b/a,yFactor:c/a}},barnesHutApproximation:function(a,b){var c=this.getDistXY(a,
b),d=this.vectorLength(c);if(a!==b&&0!==d)if(b.isInternal)if(b.boxSize/d<this.options.theta&&0!==d){var g=this.repulsiveForce(d,this.k);this.force("repulsive",a,g*b.mass,c,d);var e=!1}else e=!0;else g=this.repulsiveForce(d,this.k),this.force("repulsive",a,g*b.mass,c,d);return e},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){if(b!==
c&&!b.fixedPosition){var d=a.getDistXY(b,c);var g=a.vectorLength(d);if(0!==g){var e=a.repulsiveForce(g,a.k);a.force("repulsive",b,e*c.mass,d,g)}}})})},attractiveForces:function(){var a=this,b,c,e;a.links.forEach(function(d){d.fromNode&&d.toNode&&(b=a.getDistXY(d.fromNode,d.toNode),c=a.vectorLength(b),0!==c&&(e=a.attractiveForce(c,a.k),a.force("attractive",d,e,b,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),
b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,b){var c=a.radius;a.plotX=e(a.plotX,b.left+c,b.width-c);a.plotY=e(a.plotY,b.top+c,b.height-c)},coolDown:function(a,b,c){return a-b*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);
return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});b(z,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});b(z,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.options.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),c=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){x(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!c;){var c=
!0;this.graphLayoutsLookup.forEach(a)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}})});z(e,"modules/networkgraph/draggable-nodes.js",[e["parts/Globals.js"]],function(c){var b=c.Chart,e=c.addEvent;c.dragNodesMixin={onMouseDown:function(b,c){c=this.chart.pointer.normalize(c);b.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:b.plotX,plotY:b.plotY};b.inDragMode=!0},onMouseMove:function(b,c){if(b.fixedPosition&&b.inDragMode){var e=this.chart,h=e.pointer.normalize(c);c=b.fixedPosition.chartX-
h.chartX;h=b.fixedPosition.chartY-h.chartY;if(5<Math.abs(c)||5<Math.abs(h))c=b.fixedPosition.plotX-c,h=b.fixedPosition.plotY-h,e.isInsidePlot(c,h)&&(b.plotX=c,b.plotY=h,b.hasDragged=!0,this.redrawHalo(b),this.layout.simulation?this.layout.resetSimulation():(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(b,c){b.fixedPosition&&b.hasDragged&&(this.layout.enableSimulation?
this.layout.start():this.chart.redraw(),b.inDragMode=b.hasDragged=!1,this.options.fixedDraggable||delete b.fixedPosition)},redrawHalo:function(b){b&&this.halo&&this.halo.attr({d:b.haloPath(this.options.states.hover.halo.size)})}};e(b,"load",function(){var b=this,c,r,x;b.container&&(c=e(b.container,"mousedown",function(c){var a=b.hoverPoint;a&&a.series&&a.series.hasDraggableNodes&&a.series.options.draggable&&(a.series.onMouseDown(a,c),r=e(b.container,"mousemove",function(b){return a&&a.series&&a.series.onMouseMove(a,
b)}),x=e(b.container.ownerDocument,"mouseup",function(b){r();x();return a&&a.series&&a.series.onMouseUp(a,b)}))}));e(b,"destroy",function(){c()})})});z(e,"parts-more/PackedBubbleSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var e=b.clamp,h=b.defined,m=b.extend,u=b.extendClass,x=b.isArray,z=b.isNumber,a=b.pick;b=c.seriesType;var d=c.Series,l=c.Point,t=c.addEvent,g=c.fireEvent,w=c.Chart,A=c.Color,q=c.layouts["reingold-fruchterman"],n=c.seriesTypes.bubble.prototype.pointClass,
k=c.dragNodesMixin;c.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,c,d){return Math.min(a,(c.marker.radius+d.marker.radius)/2)},barycenter:function(){var a=this,b=a.options.gravitationalConstant,c=a.box,d=a.nodes,g,e;d.forEach(function(f){a.options.splitSeries&&!f.isParentNode?(g=f.series.parentNode.plotX,e=f.series.parentNode.plotY):(g=c.width/2,e=c.height/2);f.fixedPosition||(f.plotX-=(f.plotX-g)*b/(f.mass*Math.sqrt(d.length)),f.plotY-=(f.plotY-e)*b/(f.mass*Math.sqrt(d.length)))})},
repulsive:function(a,b,c,d){var f=b*this.diffTemperature/a.mass/a.degree;b=c.x*f;c=c.y*f;a.fixedPosition||(a.plotX+=b,a.plotY+=c);d.fixedPosition||(d.plotX-=b,d.plotY-=c)},integrate:c.networkgraphIntegrations.verlet.integrate,getK:c.noop};c.layouts.packedbubble=u(q,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var b=this,c=b.box,d=b.nodes,g=2*Math.PI/(d.length+1),e,h,l=b.options.initialPositionRadius;d.forEach(function(f,
d){b.options.splitSeries&&!f.isParentNode?(e=f.series.parentNode.plotX,h=f.series.parentNode.plotY):(e=c.width/2,h=c.height/2);f.plotX=f.prevX=a(f.plotX,e+l*Math.cos(f.index||d*g));f.plotY=f.prevY=a(f.plotY,h+l*Math.sin(f.index||d*g));f.dispX=0;f.dispY=0})},repulsiveForces:function(){var a=this,b,c,d,g=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(e){b=0;f===e||f.fixedPosition||!a.options.seriesInteraction&&f.series!==e.series||(d=a.getDistXY(f,
e),c=a.vectorLength(d)-(f.marker.radius+e.marker.radius+g),0>c&&(f.degree+=.01,f.neighbours++,b=a.repulsiveForce(-c/Math.sqrt(f.neighbours),a.k,f,e)),a.force("repulsive",f,b*e.mass,d,e,c))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var b=this.getDistXY(a,a.series.parentNode);var c=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(b);0>c&&c>-2*a.marker.radius&&(a.plotX-=.01*b.x,a.plotY-=.01*b.y)}q.prototype.applyLimitBox.apply(this,
arguments)},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature||0<this.systemTemperature&&.02>this.systemTemperature/this.nodes.length&&this.enableSimulation}});b("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},
padding:0},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},
{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,requireSorting:!1,directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:c.noop,accumulateAllPoints:function(a){var b=a.chart,c=[],f,d;for(f=0;f<b.series.length;f++)if(a=b.series[f],a.visible||!b.options.chart.ignoreHiddenSeries)for(d=0;d<a.yData.length;d++)c.push([null,null,a.yData[d],a.index,d,{id:d,marker:{radius:0}}]);return c},init:function(){d.prototype.init.apply(this,arguments);
t(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},render:function(){var a=[];d.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){x(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;d.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&
a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;d.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix=
"parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,d.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,c=Math.min,d,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){h(a.plotX)&&h(a.plotY)&&a.marker.radius&&(d=a.marker.radius,e[0]=c(e[0],a.plotX-d),e[1]=b(e[1],a.plotX+d),e[2]=c(e[2],a.plotY-
d),e[3]=b(e[3],a.plotY+d))});return z(e.width/e.height)?e:null},calculateParentRadius:function(){var a=this.seriesBox();this.parentNodeRadius=e(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;
b={fill:b.fillColor||A(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var d=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",d,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();d=c.merge({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},
b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(d)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,e=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new n).init(this,
{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addElementsToCollection([a],c.series),c.addElementsToCollection([e],c.nodes))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,e=c.merge(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});
var g=b[a.type+"-series"];g||(b[a.type+"-series"]=g=new c.layouts[a.type],g.init(e),d.splice(g.index,0,g));this.parentNodeLayout=g;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,e=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=d=[]);var g=b[a.type];g||(a.enableSimulation=h(e.forExport)?!e.forExport:a.enableSimulation,b[a.type]=g=new c.layouts[a.type],
g.init(a),d.splice(g.index,0,g));this.layout=g;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});g.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);g.addElementsToCollection([this],g.series);g.addElementsToCollection(this.points,g.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=
this.xData;this.generatePoints();h(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(e)var l=a.allDataPoints;else l=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<l.length;d++)if(l[d][3]===c){var k=b[l[d][4]];var t=l[d][2];e||(k.plotX=l[d][0]-a.plotLeft+a.diffX,k.plotY=l[d][1]-a.plotTop+a.diffY);k.marker=m(k.marker,{radius:t,width:2*t,height:2*t});k.radius=t}e&&this.deferLayout();g(this,"afterTranslate")},checkOverlap:function(a,b){var c=
a[0]-b[0],d=a[1]-b[1];return-.001>Math.sqrt(c*c+d*d)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,c){var d=Math.sqrt,f=Math.asin,e=Math.acos,g=Math.pow,l=Math.abs;d=d(g(a[0]-b[0],2)+g(a[1]-b[1],2));e=e((g(d,2)+g(c[2]+b[2],2)-g(c[2]+a[2],2))/(2*(c[2]+b[2])*d));f=f(l(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+e+f*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var b=this.checkOverlap,c=this.positionBubble,d=
[],f=1,e=0,g=0;var l=[];var h;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),h=2;h<a.length;h++)a[h][2]=a[h][2]||1,l=c(d[f][e],d[f-1][g],a[h]),b(l,d[f][0])?(d.push([]),g=0,d[f+1].push(c(d[f][e],d[f][0],a[h])),f++,e=0):1<f&&d[f-1][g+1]&&b(l,d[f-1][g+1])?(g++,d[f].push(c(d[f][e],d[f-1][g],a[h])),e++):(e++,d[f].push(l));this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],
d);this.resizeRadius();l=this.chart.rawPositions}return l},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,e=a.plotLeft,g=a.plotTop,l=a.plotHeight,h=a.plotWidth,k,t,m;var n=k=Number.POSITIVE_INFINITY;var q=t=Number.NEGATIVE_INFINITY;for(m=0;m<b.length;m++){var r=b[m][2];n=c(n,b[m][0]-r);q=d(q,b[m][0]+r);k=c(k,b[m][1]-r);t=d(t,b[m][1]+r)}m=[q-n,t-k];c=c.apply([],[(h-e)/m[0],(l-g)/m[1]]);if(1e-10<Math.abs(c-1)){for(m=0;m<b.length;m++)b[m][2]*=c;this.placeBubbles(b)}else a.diffY=
l/2+g-k-(t-k)/2,a.diffX=h/2+e-n-(q-n)/2},calculateZExtremes:function(){var b=this.options.zMin,c=this.options.zMax,d=Infinity,e=-Infinity;if(b&&c)return[b,c];this.chart.series.forEach(function(a){a.yData.forEach(function(a){h(a)&&(a>e&&(e=a),a<d&&(d=a))})});b=a(b,d);c=a(c,e);return[b,c]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,d=c.useSimulation,g=Math.min(b.plotWidth,b.plotHeight),l={},h=[],k=b.allDataPoints,m,t,n,q;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],
10),d=/%$/.test(c[a]);l[a]=d?g*b/100:b*Math.sqrt(k.length)});b.minRadius=m=l.minSize/Math.sqrt(k.length);b.maxRadius=t=l.maxSize/Math.sqrt(k.length);var r=d?a.calculateZExtremes():[m,t];(k||[]).forEach(function(b,c){n=d?e(b[2],r[0],r[1]):b[2];q=a.getRadius(r[0],r[1],m,t,n);0===q&&(q=null);k[c][2]=q;h.push(q)});a.radii=h},redrawHalo:k.redrawHalo,onMouseDown:k.onMouseDown,onMouseMove:k.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,d,f=this.layout,e=this.parentNodeLayout;e&&
f.options.dragBetweenSeries&&e.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(b=f.getDistXY(a,e),d=f.vectorLength(b)-e.marker.radius-a.marker.radius,0>d&&(e.series.addPoint(c.merge(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),f.removeElementFromCollection(a,f.nodes),a.remove()))});k.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&
(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));c.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:c.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return l.prototype.destroy.apply(this,arguments)}});t(w,"beforeRedraw",function(){this.allDataPoints&&
delete this.allDataPoints});""});z(e,"parts-more/Polar.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(c,b){var e=b.pick,h=b.splat,m=c.Series,u=c.seriesTypes;b=c.wrap;var x=m.prototype,z=c.Pointer.prototype;x.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};x.getConnectors=function(a,b,c,e){var d=e?1:0;var l=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:
0;b=0>l-1?a.length-(1+d):l-1;d=l+1>a.length-1?d:l+1;var h=a[b];d=a[d];var m=h.plotX;h=h.plotY;var t=d.plotX;var k=d.plotY;d=a[l].plotX;l=a[l].plotY;m=(1.5*d+m)/2.5;h=(1.5*l+h)/2.5;t=(1.5*d+t)/2.5;var f=(1.5*l+k)/2.5;k=Math.sqrt(Math.pow(m-d,2)+Math.pow(h-l,2));var p=Math.sqrt(Math.pow(t-d,2)+Math.pow(f-l,2));m=Math.atan2(h-l,m-d);f=Math.PI/2+(m+Math.atan2(f-l,t-d))/2;Math.abs(m-f)>Math.PI/2&&(f-=Math.PI);m=d+Math.cos(f)*k;h=l+Math.sin(f)*k;t=d+Math.cos(Math.PI+f)*p;f=l+Math.sin(Math.PI+f)*p;d={rightContX:t,
rightContY:f,leftContX:m,leftContY:h,plotX:d,plotY:l};c&&(d.prevPointCont=this.getConnectors(a,b,!1,e));return d};x.toXY=function(a){var b=this.chart,c=a.plotX;var e=a.plotY;a.rectPlotX=c;a.rectPlotY=e;e=this.xAxis.postTranslate(a.plotX,this.yAxis.len-e);a.plotX=a.polarPlotX=e.x-b.plotLeft;a.plotY=a.polarPlotY=e.y-b.plotTop;this.kdByAngle?(b=(c/Math.PI*180+this.xAxis.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};u.spline&&(b(u.spline.prototype,"getPointSpline",function(a,
b,c,e){this.chart.polar?e?(a=this.getConnectors(b,e,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,e);return a}),u.areasplinerange&&(u.areasplinerange.prototype.getPointSpline=u.spline.prototype.getPointSpline));c.addEvent(m,"afterTranslate",function(){var a=this.chart,b;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:
this.options.findNearestPointBy="xy";if(!this.preventPostTranslate){var e=this.points;for(b=e.length;b--;)this.toXY(e[b]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&e[b].y<this.yAxis.min&&(e[b].isNull=!0)}this.hasClipCircleSetter||(this.hasClipCircleSetter=!!c.addEvent(this,"afterRender",function(){if(a.polar){var b=this.yAxis.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2);this.group.clip(this.clipCircle);this.setClip=
c.noop}}))}},{order:2});b(x,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var h=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));h&&b.pop();return d});m=function(a,b){var c=this.chart,d=this.options.animation,e=this.group,h=this.markerGroup,m=
this.xAxis.center,q=c.plotLeft,n=c.plotTop;c.polar?c.renderer.isSVG&&(!0===d&&(d={}),b?(a={translateX:m[0]+q,translateY:m[1]+n,scaleX:.001,scaleY:.001},e.attr(a),h&&h.attr(a)):(a={translateX:q,translateY:n,scaleX:1,scaleY:1},e.animate(a,d),h&&h.animate(a,d),this.animate=null)):a.call(this,b)};b(x,"animate",m);u.column&&(u=u.column.prototype,u.polarArc=function(a,b,c,h){var d=this.xAxis.center,l=this.yAxis.len;return this.chart.renderer.symbols.arc(d[0],d[1],l-b,null,{start:c,end:h,innerR:l-e(a,l)})},
b(u,"animate",m),b(u,"translate",function(a){var b=this.xAxis,c=b.startAngleRad,e;this.preventPostTranslate=!0;a.call(this);if(b.isRadial){var g=this.points;for(e=g.length;e--;){var h=g[e];a=h.barX+c;h.shapeType="path";h.shapeArgs={d:this.polarArc(h.yBottom,h.plotY,a,a+h.pointWidth)};this.toXY(h);h.tooltipPos=[h.plotX,h.plotY];h.ttBelow=h.plotY>b.center[1]}}}),b(u,"alignDataLabel",function(a,b,c,e,g,h){this.chart.polar?(a=b.rectPlotX/Math.PI*180,null===e.align&&(e.align=20<a&&160>a?"left":200<a&&
340>a?"right":"center"),null===e.verticalAlign&&(e.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle"),x.alignDataLabel.call(this,b,c,e,g,h)):a.call(this,b,c,e,g,h)}));b(z,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,g=a.center;if("colorAxis"!==a.coll){var h=b.chartX-g[0]-c.plotLeft;g=b.chartY-g[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(h,g):Math.sqrt(Math.pow(h,2)+Math.pow(g,
2)),!0)})}}):d=a.call(this,b);return d});c.SVGRenderer.prototype.clipCircle=function(a,b,e){var d=c.uniqueKey(),g=this.createElement("clipPath").attr({id:d}).add(this.defs);a=this.circle(a,b,e).add(g);a.id=d;a.clipPath=g;return a};c.addEvent(c.Chart,"getAxes",function(){this.pane||(this.pane=[]);h(this.options.pane).forEach(function(a){new c.Pane(a,this)},this)});c.addEvent(c.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});b(c.Chart.prototype,"get",function(a,b){return c.find(this.pane,
function(a){return a.options.id===b})||a.call(this,b)})});z(e,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map