/*
 Highstock JS v7.2.1-modified (2019-11-18)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(u){b(u);b.Highcharts=u;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function u(h,k,b,l){h.hasOwnProperty(k)||(h[k]=l.apply(null,b))}b=b?b._modules:{};u(b,"mixins/indicator-required.js",[b["parts/Globals.js"]],function(h){var k=h.error;return{isParentLoaded:function(h,
l,e,d,c){if(h)return d?d(h):!0;k(c||this.generateMessage(e,l));return!1},generateMessage:function(h,l){return'Error: "'+h+'" indicator type requires "'+l+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+h}}});u(b,"indicators/indicators.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(h,k,b){var l=k.extend,e=k.isArray,d=k.pick,c=k.splat,a=h.error,f=h.Series,p=h.addEvent;k=h.seriesType;var t=h.seriesTypes,
y=h.seriesTypes.ohlc.prototype,m=b.generateMessage;p(h.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&l(this,{pointValKey:y.pointValKey,keys:y.keys,pointArrayMap:y.pointArrayMap,toYData:y.toYData})});p(f,"afterSetOptions",function(a){a=a.options;var c=a.dataGrouping;c&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(c.approximation="ohlc")});k("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var a=this.options.compareToMain,c=this.linkedParent;f.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){t[c]?t[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=
c)});return a},init:function(d,e){function n(){var a=g.points||[],d=(g.xData||[]).length,f=g.getValues(g.linkedParent,g.options.params)||{values:[],xData:[],yData:[]},n=[],p=!0;if(d&&!g.hasGroupedData&&g.visible&&g.points)if(g.cropped){if(g.xAxis){var e=g.xAxis.min;var t=g.xAxis.max}d=g.cropData(f.xData,f.yData,e,t);for(e=0;e<d.xData.length;e++)n.push([d.xData[e]].concat(c(d.yData[e])));d=f.xData.indexOf(g.xData[0]);e=f.xData.indexOf(g.xData[g.xData.length-1]);-1===d&&e===f.xData.length-2&&n[0][0]===
a[0].x&&n.shift();g.updateData(n)}else f.xData.length!==d-1&&f.xData.length!==d+1&&(p=!1,g.updateData(f.values));p&&(g.xData=f.xData,g.yData=f.yData,g.options.data=f.values);!1===g.bindTo.series&&(delete g.processedXData,g.isDirty=!0,g.redraw());g.isDirtyData=!1}var g=this,t=g.requireIndicators();if(!t.allLoaded)return a(m(g.type,t.needed));f.prototype.init.call(g,d,e);d.linkSeries();g.dataEventsToUnbind=[];if(!g.linkedParent)return a("Series "+g.options.linkedTo+" not found! Check `linkedTo`.",!1,
d);g.dataEventsToUnbind.push(p(g.bindTo.series?g.linkedParent:g.linkedParent.xAxis,g.bindTo.eventName,n));if("init"===g.calculateOn)n();else var r=p(g.chart,g.calculateOn,function(){n();r()});return g},getName:function(){var a=this.name,c=[];a||((this.nameComponents||[]).forEach(function(a,f){c.push(this.options.params[a]+d(this.nameSuffixes[f],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return a},getValues:function(a,c){var d=c.period,f=
a.xData;a=a.yData;var g=a.length,p=0,t=0,m=[],r=[],y=[],l=-1;if(!(f.length<d)){for(e(a[0])&&(l=c.index?c.index:0);p<d-1;)t+=0>l?a[p]:a[p][l],p++;for(c=p;c<g;c++){t+=0>l?a[c]:a[c][l];var h=[f[c],t/d];m.push(h);r.push(h[0]);y.push(h[1]);t-=0>l?a[c-p]:a[c-p][l]}return{values:m,xData:r,yData:y}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});f.prototype.destroy.call(this)}});""});u(b,"indicators/accumulation-distribution.src.js",[b["parts/Globals.js"]],function(h){var k=h.seriesType;
k("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,nameBase:"Accumulation/Distribution",getValues:function(k,l){var e=l.period,d=k.xData,c=k.yData,a=l.volumeSeriesID,f=k.chart.get(a);l=f&&f.yData;var p=c?c.length:0,t=[],y=[],m=[];if(!(d.length<=e&&p&&4!==c[0].length)){if(f){for(;e<p;e++){k=t.length;a=c[e][1];f=c[e][2];var g=c[e][3],r=l[e];a=[d[e],g===a&&g===f||a===f?0:(2*g-f-a)/(a-f)*r];0<k&&(a[1]+=t[k-1][1]);t.push(a);y.push(a[0]);m.push(a[1])}return{values:t,xData:y,yData:m}}h.error("Series "+
a+" not found! Check `volumeSeriesID`.",!0,k.chart)}}});""});u(b,"indicators/ao.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,k){var b=k.correctFloat,l=k.isArray;h.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:h.noop,getColumnMetrics:h.seriesTypes.column.prototype.getColumnMetrics,crispCol:h.seriesTypes.column.prototype.crispCol,
translate:h.seriesTypes.column.prototype.translate,drawPoints:h.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var e=this.options,d=this.points,c=e.greaterBarColor;e=e.lowerBarColor;var a=d[0];if(!this.userOptions.color&&a)for(a.color=c,a=1;a<d.length;a++)d[a].color=d[a].y>d[a-1].y?c:d[a].y<d[a-1].y?e:d[a-1].color},getValues:function(e){var d=e.xData||[];e=e.yData||[];var c=e.length,a=[],f=[],p=[],t=0,y=0,m;if(!(34>=d.length)&&l(e[0])&&4===e[0].length){for(m=0;33>m;m++){var g=(e[m][1]+
e[m][2])/2;29<=m&&(t=b(t+g));y=b(y+g)}for(m=33;m<c;m++){g=(e[m][1]+e[m][2])/2;t=b(t+g);y=b(y+g);g=t/5;var r=y/34;g=b(g-r);a.push([d[m],g]);f.push(d[m]);p.push(g);g=m+1-5;r=m+1-34;t=b(t-(e[g][1]+e[g][2])/2);y=b(y-(e[r][1]+e[r][2])/2)}return{values:a,xData:f,yData:p}}}});""});u(b,"mixins/multipe-lines.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,k){var b=k.defined,l=h.each,e=h.merge,d=h.error,c=h.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],
getTranslatedLinesNames:function(a){var c=[];l(this.pointArrayMap,function(d){d!==a&&c.push("plot"+d.charAt(0).toUpperCase()+d.slice(1))});return c},toYData:function(a){var c=[];l(this.pointArrayMap,function(d){c.push(a[d])});return c},translate:function(){var a=this,d=a.pointArrayMap,p=[],e;p=a.getTranslatedLinesNames();c.prototype.translate.apply(a,arguments);l(a.points,function(c){l(d,function(d,f){e=c[d];null!==e&&(c[p[f]]=a.yAxis.toPixels(e,!0))})})},drawGraph:function(){var a=this,f=a.linesApiNames,
p=a.points,t=p.length,y=a.options,m=a.graph,g={options:{gapSize:y.gapSize}},r=[],n=a.getTranslatedLinesNames(a.pointValKey),A;l(n,function(a,c){for(r[c]=[];t--;)A=p[t],r[c].push({x:A.x,plotX:A.plotX,plotY:A[a],isNull:!b(A[a])});t=p.length});l(f,function(f,n){r[n]?(a.points=r[n],y[f]?a.options=e(y[f].styles,g):d('Error: "There is no '+f+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+f],c.prototype.drawGraph.call(a),
a["graph"+f]=a.graph):d('Error: "'+f+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=p;a.options=y;a.graph=m;c.prototype.drawGraph.call(a)}}});u(b,"indicators/aroon.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/multipe-lines.js"]],function(h,k,b){function l(d,c){var a=d[0],f=0,p;for(p=1;p<d.length;p++)if("max"===c&&d[p]>=a||"min"===c&&d[p]<=a)a=d[p],f=p;return f}var e=k.pick;h.seriesType("aroon","sma",{params:{period:25},
marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},h.merge(b,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(d,c){c=c.period;var a=d.xData,f=(d=d.yData)?d.length:0,p=[],t=[],y=[],m;for(m=c-1;m<f;m++){var g=d.slice(m-c+1,
m+2);var r=l(g.map(function(a){return e(a[2],a)}),"min");g=l(g.map(function(a){return e(a[1],a)}),"max");g=g/c*100;r=r/c*100;a[m+1]&&(p.push([a[m+1],g,r]),t.push(a[m+1]),y.push([g,r]))}return{values:p,xData:t,yData:y}}}));""});u(b,"indicators/aroon-oscillator.src.js",[b["parts/Globals.js"],b["mixins/multipe-lines.js"],b["mixins/indicator-required.js"]],function(h,b,q){var l=h.seriesTypes.aroon;h.seriesType("aroonoscillator","aroon",{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}},
h.merge(b,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var e=arguments,d=this;q.isParentLoaded(l,"aroon",d.type,function(c){c.prototype.init.apply(d,e)})},getValues:function(e,d){var c=[],a=[],f=[];e=l.prototype.getValues.call(this,e,d);for(d=0;d<e.yData.length;d++){var p=e.yData[d][0];var t=e.yData[d][1];p-=t;c.push([e.xData[d],p]);a.push(e.xData[d]);f.push(p)}return{values:c,xData:a,yData:f}}}));""});u(b,"indicators/atr.src.js",[b["parts/Globals.js"],
b["parts/Utilities.js"]],function(h,b){function k(d,c){return Math.max(d[1]-d[2],c===e?0:Math.abs(d[1]-c[3]),c===e?0:Math.abs(d[2]-c[3]))}var l=b.isArray;h=h.seriesType;var e;h("atr","sma",{params:{period:14}},{getValues:function(d,c){c=c.period;var a=d.xData,f=(d=d.yData)?d.length:0,p=1,e=0,y=0,m=[],g=[],r=[],n;var A=[[a[0],d[0]]];if(!(a.length<=c)&&l(d[0])&&4===d[0].length){for(n=1;n<=f;n++)if(A.push([a[n],d[n]]),c<p){var w=c;var h=a[n-1],b=k(d[n-1],d[n-2]);w=[h,(e*(w-1)+b)/w];e=w[1];m.push(w);
g.push(w[0]);r.push(w[1])}else c===p?(e=y/(n-1),m.push([a[n-1],e]),g.push(a[n-1]),r.push(e)):y+=k(d[n-1],d[n-2]),p++;return{values:m,xData:g,yData:r}}}});""});u(b,"indicators/bollinger-bands.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/multipe-lines.js"]],function(h,b,q){var l=b.isArray,e=h.merge,d=h.seriesTypes.sma;h.seriesType("bb","sma",{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},
tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}},h.merge(q,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){d.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},
bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(c,a){var f=a.period,p=a.standardDeviation,e=c.xData,y=(c=c.yData)?c.length:0,m=[],g=[],r=[],n;if(!(e.length<f)){var A=l(c[0]);for(n=f;n<=y;n++){var w=e.slice(n-f,n);var h=c.slice(n-f,n);var b=d.prototype.getValues.call(this,{xData:w,yData:h},a);w=b.xData[0];b=b.yData[0];for(var k=0,q=h.length,x=0;x<q;x++){var F=(A?h[x][a.index]:h[x])-b;k+=F*F}F=Math.sqrt(k/(q-1));h=b+p*F;F=b-p*F;m.push([w,h,b,F]);g.push(w);r.push([h,b,F])}return{values:m,
xData:g,yData:r}}}}));""});u(b,"indicators/cci.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,b){function k(e){return e.reduce(function(d,c){return d+c},0)}var l=b.isArray;h=h.seriesType;h("cci","sma",{params:{period:14}},{getValues:function(e,d){d=d.period;var c=e.xData,a=(e=e.yData)?e.length:0,f=[],p=1,t=[],y=[],m=[];if(!(c.length<=d)&&l(e[0])&&4===e[0].length){for(;p<d;){var g=e[p-1];f.push((g[1]+g[2]+g[3])/3);p++}for(p=d;p<=a;p++){g=e[p-1];g=(g[1]+g[2]+g[3])/3;var r=f.push(g);
var n=f.slice(r-d);r=k(n)/d;var A,h=n.length,b=0;for(A=0;A<h;A++)b+=Math.abs(r-n[A]);n=b/d;g=(g-r)/(.015*n);t.push([c[p-1],g]);y.push(c[p-1]);m.push(g)}return{values:t,xData:y,yData:m}}}});""});u(b,"indicators/cmf.src.js",[b["parts/Globals.js"]],function(h){h.seriesType("cmf","sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var h=this.chart,b=this.options,l=this.linkedParent;h=this.volumeSeries||(this.volumeSeries=h.get(b.params.volumeSeriesID));
var e=l&&l.yData&&4===l.yData[0].length;return!!(l&&h&&l.xData&&l.xData.length>=b.params.period&&h.xData&&h.xData.length>=b.params.period&&e)},getValues:function(h,b){if(this.isValid())return this.getMoneyFlow(h.xData,h.yData,this.volumeSeries.yData,b.period)},getMoneyFlow:function(h,b,l,e){function d(a,c){var d=a[1],f=a[2];a=a[3];return null!==c&&null!==d&&null!==f&&null!==a&&d!==f?(a-f-(d-a))/(d-f)*c:(r=g,null)}var c=b.length,a=[],f=0,p=0,t=[],y=[],m=[],g,r=-1;if(0<e&&e<=c){for(g=0;g<e;g++)a[g]=
d(b[g],l[g]),f+=l[g],p+=a[g];t.push(h[g-1]);y.push(g-r>=e&&0!==f?p/f:null);for(m.push([t[0],y[0]]);g<c;g++){a[g]=d(b[g],l[g]);f-=l[g-e];f+=l[g];p-=a[g-e];p+=a[g];var n=[h[g],g-r>=e?p/f:null];t.push(n[0]);y.push(n[1]);m.push([n[0],n[1]])}}return{values:m,xData:t,yData:y}}});""});u(b,"indicators/dpo.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,b){function k(d,c,a,f,p){c=e(c[a][f],c[a]);return p?l(d-c):l(d+c)}var l=b.correctFloat,e=b.pick;h.seriesType("dpo","sma",{params:{period:21}},
{nameBase:"DPO",getValues:function(d,c){var a=c.period;c=c.index;var f=a+Math.floor(a/2+1),p=d.xData||[];d=d.yData||[];var t=d.length,h=[],m=[],g=[],r=0,n,l;if(!(p.length<=f)){for(n=0;n<a-1;n++)r=k(r,d,n,c);for(l=0;l<=t-f;l++){var b=l+a-1;n=l+f-1;r=k(r,d,b,c);b=e(d[n][c],d[n]);b-=r/a;r=k(r,d,l,c,!0);h.push([p[n],b]);m.push(p[n]);g.push(b)}return{values:h,xData:m,yData:g}}}});""});u(b,"indicators/ema.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,b){var k=b.correctFloat,l=b.isArray;
h=h.seriesType;h("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(e,d,c){for(var a=0,f=0,p;f<e;)p=0>d?c[f]:c[f][d],a+=p,f++;return a},calculateEma:function(e,d,c,a,f,p,t){e=e[c-1];d=0>p?d[c-1]:d[c-1][p];a="undefined"===typeof f?t:k(d*a+f*(1-a));return[e,a]},getValues:function(e,d){var c=d.period,a=e.xData,f=(e=e.yData)?e.length:0,p=2/(c+1),t=[],h=[],m=[],g=-1;if(!(f<c)){l(e[0])&&(g=d.index?d.index:0);d=this.accumulatePeriodPoints(c,g,e);for(d/=c;c<f+1;c++){var r=this.calculateEma(a,
e,c,p,r,g,d);t.push(r);h.push(r[0]);m.push(r[1]);r=r[1]}return{values:t,xData:h,yData:m}}}});""});u(b,"indicators/chaikin.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(h,b,q){var l=b.correctFloat,e=h.seriesTypes.ema,d=h.seriesTypes.ad,c=h.error;h.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var a=arguments,c=this;q.isParentLoaded(e,"ema",c.type,function(d){d.prototype.init.apply(c,
a)})},getValues:function(a,f){var p=f.periods,t=f.period,h=[],m=[],g=[],r;if(2!==p.length||p[1]<=p[0])c('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(f=d.prototype.getValues.call(this,a,{volumeSeriesID:f.volumeSeriesID,period:t}))if(a=e.prototype.getValues.call(this,f,{period:p[0]}),f=e.prototype.getValues.call(this,f,{period:p[1]}),a&&f){p=p[1]-p[0];for(r=0;r<f.yData.length;r++)t=l(a.yData[r+p]-f.yData[r]),h.push([f.xData[r],t]),m.push(f.xData[r]),
g.push(t);return{values:h,xData:m,yData:g}}}});""});u(b,"indicators/dema.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(h,b,q){var l=b.correctFloat,e=b.isArray,d=h.seriesTypes.ema;h.seriesType("dema","ema",{},{init:function(){var c=arguments,a=this;q.isParentLoaded(d,"ema",a.type,function(d){d.prototype.init.apply(a,c)})},getEMA:function(c,a,f,e,t,h){return d.prototype.calculateEma(h||[],c,"undefined"===typeof t?1:t,this.chart.series[0].EMApercent,
a,"undefined"===typeof e?-1:e,f)},getValues:function(c,a){var f=a.period,p=2*f,t=c.xData,h=c.yData,m=h?h.length:0,g=-1,r=[],n=[],b=[],w=0,k=[],z;c.EMApercent=2/(f+1);if(!(m<2*f-1)){e(h[0])&&(g=a.index?a.index:0);c=d.prototype.accumulatePeriodPoints(f,g,h);a=c/f;c=0;for(z=f;z<m+2;z++){z<m+1&&(w=this.getEMA(h,v,a,g,z)[1],k.push(w));var v=w;if(z<p)c+=w;else{z===p&&(a=c/f);w=k[z-f-1];var q=this.getEMA([w],q,a)[1];var x=[t[z-2],l(2*w-q)];r.push(x);n.push(x[0]);b.push(x[1])}}return{values:r,xData:n,yData:b}}}});
""});u(b,"indicators/tema.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(h,b,q){var l=b.correctFloat,e=b.isArray,d=h.seriesTypes.ema;h.seriesType("tema","ema",{},{init:function(){var c=arguments,a=this;q.isParentLoaded(d,"ema",a.type,function(d){d.prototype.init.apply(a,c)})},getEMA:function(c,a,f,e,t,h){return d.prototype.calculateEma(h||[],c,"undefined"===typeof t?1:t,this.chart.series[0].EMApercent,a,"undefined"===typeof e?-1:e,f)},getTemaPoint:function(c,
a,d,e){return[c[e-3],l(3*d.level1-3*d.level2+d.level3)]},getValues:function(c,a){var f=a.period,p=2*f,t=3*f,h=c.xData,m=c.yData,g=m?m.length:0,b=-1,n=[],l=[],w=[],k=[],z=[],v,q,x={};c.EMApercent=2/(f+1);if(!(g<3*f-2)){e(m[0])&&(b=a.index?a.index:0);c=d.prototype.accumulatePeriodPoints(f,b,m);a=c/f;c=0;for(v=f;v<g+3;v++){v<g+1&&(x.level1=this.getEMA(m,F,a,b,v)[1],k.push(x.level1));var F=x.level1;if(v<p)c+=x.level1;else{v===p&&(a=c/f,c=0);x.level1=k[v-f-1];x.level2=this.getEMA([x.level1],C,a)[1];z.push(x.level2);
var C=x.level2;if(v<t)c+=x.level2;else{v===t&&(a=c/f);v===g+1&&(x.level1=k[v-f-1],x.level2=this.getEMA([x.level1],C,a)[1],z.push(x.level2));x.level1=k[v-f-2];x.level2=z[v-2*f-1];x.level3=this.getEMA([x.level2],x.prevLevel3,a)[1];if(q=this.getTemaPoint(h,t,x,v))n.push(q),l.push(q[0]),w.push(q[1]);x.prevLevel3=x.level3}}}return{values:n,xData:l,yData:w}}}});""});u(b,"indicators/trix.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(h,b,q){var l=b.correctFloat,
e=h.seriesTypes.tema;h.seriesType("trix","tema",{},{init:function(){var d=arguments,c=this;q.isParentLoaded(e,"tema",c.type,function(a){a.prototype.init.apply(c,d)})},getTemaPoint:function(d,c,a,f){if(f>c)var e=[d[f-3],0!==a.prevLevel3?l(a.level3-a.prevLevel3)/a.prevLevel3*100:null];return e}});""});u(b,"indicators/apo.src.js",[b["parts/Globals.js"],b["mixins/indicator-required.js"]],function(h,b){var k=h.seriesTypes.ema,l=h.error;h.seriesType("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",
nameComponents:["periods"],init:function(){var e=arguments,d=this;b.isParentLoaded(k,"ema",d.type,function(c){c.prototype.init.apply(d,e)})},getValues:function(e,d){var c=d.periods,a=d.index;d=[];var f=[],p=[],t;if(2!==c.length||c[1]<=c[0])l('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var h=k.prototype.getValues.call(this,e,{index:a,period:c[0]});e=k.prototype.getValues.call(this,e,{index:a,period:c[1]});if(h&&e){c=c[1]-c[0];for(t=0;t<e.yData.length;t++)a=
h.yData[t+c]-e.yData[t],d.push([e.xData[t],a]),f.push(e.xData[t]),p.push(a);return{values:d,xData:f,yData:p}}}}});""});u(b,"indicators/ichimoku-kinko-hyo.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(h,b){function k(a){return a.reduce(function(a,c){return Math.max(a,c[1])},-Infinity)}function l(a){return a.reduce(function(a,c){return Math.min(a,c[2])},Infinity)}function e(a){return{high:k(a),low:l(a)}}function d(a){var c,d,f,e,g;a.series.forEach(function(a){if(a.xData)for(e=a.xData,
g=d=a.xIncrement?1:e.length-1;0<g;g--)if(f=e[g]-e[g-1],c===y||f<c)c=f});return c}function c(a,c,d,f){if(a&&c&&d&&f){var e=c.plotX-a.plotX;c=c.plotY-a.plotY;var g=f.plotX-d.plotX;f=f.plotY-d.plotY;var n=a.plotX-d.plotX,p=a.plotY-d.plotY;d=(-c*n+e*p)/(-g*c+e*f);g=(g*p-f*n)/(-g*c+e*f);if(0<=d&&1>=d&&0<=g&&1>=g)return{plotX:a.plotX+g*e,plotY:a.plotY+g*c}}return!1}function a(a){var c=a.indicator;c.points=a.points;c.nextPoints=a.nextPoints;c.color=a.color;c.options=m(a.options.senkouSpan.styles,a.gap);
c.graph=a.graph;c.fillGraph=!0;r.prototype.drawGraph.call(c)}var f=b.defined,p=b.isArray,t=b.objectEach,y;b=h.seriesType;var m=h.merge,g=h.color,r=h.seriesTypes.sma;h.approximations["ichimoku-averages"]=function(){var a=[],c;[].forEach.call(arguments,function(d,f){a.push(h.approximations.average(d));c=!c&&"undefined"===typeof a[f]});return c?void 0:a};b("ikh","sma",{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period",
"periodTenkan"],init:function(){r.prototype.init.apply(this,arguments);this.options=m({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:g(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:g(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:g(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(a){return[a.tenkanSen,a.kijunSen,
a.chikouSpan,a.senkouSpanA,a.senkouSpanB]},translate:function(){var a=this;r.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(d){f(c[d])&&(c["plot"+d]=a.yAxis.toPixels(c[d],!0),c.plotY=c["plot"+d],c.tooltipPos=[c.plotX,c["plot"+d]],c.isNull=!1)})})},drawGraph:function(){var d=this,e=d.points,g=e.length,p=d.options,h=d.graph,b=d.color,l={options:{gapSize:p.gapSize}},y=d.pointArrayMap.length,k=[[],[],[],[],[],[]],q={tenkanLine:k[0],kijunLine:k[1],chikouLine:k[2],
senkouSpanA:k[3],senkouSpanB:k[4],senkouSpan:k[5]},u=[],B=d.options.senkouSpan,G=B.color||B.styles.fill,J=B.negativeColor,M=[[],[]],L=[[],[]],O=0,I,P,N;for(d.ikhMap=q;g--;){var D=e[g];for(I=0;I<y;I++)B=d.pointArrayMap[I],f(D[B])&&k[I].push({plotX:D.plotX,plotY:D["plot"+B],isNull:!1});J&&g!==e.length-1&&(B=q.senkouSpanB.length-1,D=c(q.senkouSpanA[B-1],q.senkouSpanA[B],q.senkouSpanB[B-1],q.senkouSpanB[B]),I={plotX:D.plotX,plotY:D.plotY,isNull:!1,intersectPoint:!0},D&&(q.senkouSpanA.splice(B,0,I),q.senkouSpanB.splice(B,
0,I),u.push(B)))}t(q,function(a,c){p[c]&&"senkouSpan"!==c&&(d.points=k[O],d.options=m(p[c].styles,l),d.graph=d["graph"+c],d.fillGraph=!1,d.color=b,r.prototype.drawGraph.call(d),d["graph"+c]=d.graph);O++});d.graphCollection&&d.graphCollection.forEach(function(a){d[a].destroy();delete d[a]});d.graphCollection=[];if(J&&q.senkouSpanA[0]&&q.senkouSpanB[0]){u.unshift(0);u.push(q.senkouSpanA.length-1);for(y=0;y<u.length-1;y++){B=u[y];D=u[y+1];g=q.senkouSpanB.slice(B,D+1);B=q.senkouSpanA.slice(B,D+1);if(1<=
Math.floor(g.length/2))if(D=Math.floor(g.length/2),g[D].plotY===B[D].plotY){for(N=I=D=0;N<g.length;N++)D+=g[N].plotY,I+=B[N].plotY;D=D>I?0:1}else D=g[D].plotY>B[D].plotY?0:1;else D=g[0].plotY>B[0].plotY?0:1;M[D]=M[D].concat(g);L[D]=L[D].concat(B)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(c,f){M[f].length&&L[f].length&&(P=0===f?G:J,a({indicator:d,points:M[f],nextPoints:L[f],color:P,options:p,gap:l,graph:d[c]}),d[c]=d.graph,d.graphCollection.push(c))})}else a({indicator:d,
points:q.senkouSpanB,nextPoints:q.senkouSpanA,color:G,options:p,gap:l,graph:d.graphsenkouSpan}),d.graphsenkouSpan=d.graph;delete d.nextPoints;delete d.fillGraph;d.points=e;d.options=p;d.graph=h},getGraphPath:function(a){var c=[];a=a||this.points;if(this.fillGraph&&this.nextPoints){var d=r.prototype.getGraphPath.call(this,this.nextPoints);d[0]="L";var f=r.prototype.getGraphPath.call(this,a);d=d.slice(0,f.length);for(var g=d.length-1;0<g;g-=3)c.push(d[g-2],d[g-1],d[g]);f=f.concat(c)}else f=r.prototype.getGraphPath.apply(this,
arguments);return f},getValues:function(a,c){var f=c.period,g=c.periodTenkan;c=c.periodSenkouSpanB;var t=a.xData,m=a.yData,h=m&&m.length||0;a=d(a.xAxis);var b=[],l=[],n;if(!(t.length<=f)&&p(m[0])&&4===m[0].length){var r=t[0]-f*a;for(n=0;n<f;n++)l.push(r+n*a);for(n=0;n<h;n++){if(n>=g){var k=m.slice(n-g,n);k=e(k);k=(k.high+k.low)/2}if(n>=f){var A=m.slice(n-f,n);A=e(A);A=(A.high+A.low)/2;var q=(k+A)/2}if(n>=c){var u=m.slice(n-c,n);u=e(u);u=(u.high+u.low)/2}r=m[n][3];var L=t[n];b[n]===y&&(b[n]=[]);b[n+
f]===y&&(b[n+f]=[]);b[n+f][0]=k;b[n+f][1]=A;b[n+f][2]=y;b[n][2]=r;n<=f&&(b[n+f][3]=y,b[n+f][4]=y);b[n+2*f]===y&&(b[n+2*f]=[]);b[n+2*f][3]=q;b[n+2*f][4]=u;l.push(L)}for(n=1;n<=f;n++)l.push(L+n*a);return{values:b,xData:l,yData:b}}}});""});u(b,"indicators/keltner-channels.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/multipe-lines.js"]],function(b,k,q){var h=k.correctFloat,e=b.seriesTypes.sma,d=b.seriesTypes.ema,c=b.seriesTypes.atr,a=b.merge;b.seriesType("keltnerchannels","sma",{params:{period:20,
periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},a(q,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",
nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],init:function(){e.prototype.init.apply(this,arguments);this.options=a({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,e){var f=e.period,p=e.periodATR,b=e.multiplierATR,g=a.yData;g=g?g.length:0;var l=[];e=d.prototype.getValues(a,{period:f,index:e.index});var n=c.prototype.getValues(a,{period:p}),k=[],w=
[],q;if(!(g<f)){for(q=f;q<=g;q++){var z=e.values[q-f];var v=n.values[q-p];var E=z[0];a=h(z[1]+b*v[1]);v=h(z[1]-b*v[1]);z=z[1];l.push([E,a,z,v]);k.push(E);w.push([a,z,v])}return{values:l,xData:k,yData:w}}}}));""});u(b,"indicators/macd.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.correctFloat,l=k.defined;k=b.seriesType;var e=b.merge,d=b.seriesTypes.sma,c=b.seriesTypes.ema;k("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],
styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y",
"signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:b.noop,getColumnMetrics:b.seriesTypes.column.prototype.getColumnMetrics,crispCol:b.seriesTypes.column.prototype.crispCol,init:function(){d.prototype.init.apply(this,arguments);this.options&&(this.options=e({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),
startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,c=["plotSignal","plotMACD"];b.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(d){[d.signal,d.MACD].forEach(function(f,e){null!==f&&(d[c[e]]=a.yAxis.toPixels(f,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();d.prototype.destroy.apply(this,
arguments)},drawPoints:b.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var a=this,c=a.points,p=c.length,b=a.options,h=a.zones,m={options:{gapSize:b.gapSize}},g=[[],[]],r;p--;)r=c[p],l(r.plotMACD)&&g[0].push({plotX:r.plotX,plotY:r.plotMACD,isNull:!l(r.plotMACD)}),l(r.plotSignal)&&g[1].push({plotX:r.plotX,plotY:r.plotSignal,isNull:!l(r.plotMACD)});["macd","signal"].forEach(function(c,f){a.points=g[f];a.options=e(b[c+"Line"].styles,m);a.graph=a["graph"+c];a.currentLineZone=c+"Zones";
a.zones=a[a.currentLineZone].zones;d.prototype.drawGraph.call(a);a["graph"+c]=a.graph});a.points=c;a.options=b;a.zones=h;a.currentLineZone=null},getZonesGraphs:function(a){var c=d.prototype.getZonesGraphs.call(this,a),e=c;this.currentLineZone&&(e=c.splice(this[this.currentLineZone].startIndex+1),e.length?e.splice(0,0,a[0]):e=[a[0]]);return e},applyZones:function(){var a=this.zones;this.zones=this.signalZones.zones;d.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&
this.graphmacd.hide();this.zones=a},getValues:function(a,d){var f=0,e=[],b=[],m=[];if(!(a.xData.length<d.longPeriod+d.signalPeriod)){var g=c.prototype.getValues(a,{period:d.shortPeriod});var r=c.prototype.getValues(a,{period:d.longPeriod});g=g.values;r=r.values;for(a=1;a<=g.length;a++)l(r[a-1])&&l(r[a-1][1])&&l(g[a+d.shortPeriod+1])&&l(g[a+d.shortPeriod+1][0])&&e.push([g[a+d.shortPeriod+1][0],0,null,g[a+d.shortPeriod+1][1]-r[a-1][1]]);for(a=0;a<e.length;a++)b.push(e[a][0]),m.push([0,null,e[a][3]]);
d=c.prototype.getValues({xData:b,yData:m},{period:d.signalPeriod,index:2});d=d.values;for(a=0;a<e.length;a++)e[a][0]>=d[0][0]&&(e[a][2]=d[f][1],m[a]=[0,d[f][1],e[a][3]],null===e[a][3]?(e[a][1]=0,m[a][0]=0):(e[a][1]=h(e[a][3]-d[f][1]),m[a][0]=h(e[a][3]-d[f][1])),f++);return{values:e,xData:b,yData:m}}}});""});u(b,"indicators/mfi.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function h(d){return d.reduce(function(c,a){return c+a})}function l(d){return(d[1]+d[2]+d[3])/3}var e=
k.isArray;b.seriesType("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(d,c){var a=c.period,f=d.xData,p=d.yData,t=p?p.length:0,y=c.decimals,m=1,g=d.chart.get(c.volumeSeriesID),r=g&&g.yData,n=[],k=[],w=[],q=[],z=[];if(!g)b.error("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,d.chart);else if(!(f.length<=a)&&e(p[0])&&4===p[0].length&&r){for(d=l(p[m]);m<a+1;)c=d,d=l(p[m]),c=d>=c,g=d*r[m],q.push(c?g:0),z.push(c?0:
g),m++;for(a=m-1;a<t;a++)a>m-1&&(q.shift(),z.shift(),c=d,d=l(p[a]),c=d>c,g=d*r[a],q.push(c?g:0),z.push(c?0:g)),c=h(z),g=h(q),c=g/c,c=parseFloat((100-100/(1+c)).toFixed(y)),n.push([f[a],c]),k.push(f[a]),w.push(c);return{values:n,xData:k,yData:w}}}});""});u(b,"indicators/momentum.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function h(e,d,c,a,f){c=c[a-1][3]-c[a-f-1][3];d=d[a-1];e.shift();return[d,c]}var l=k.isArray;b=b.seriesType;b("momentum","sma",{params:{period:14}},{nameBase:"Momentum",
getValues:function(e,d){d=d.period;var c=e.xData,a=(e=e.yData)?e.length:0,f=c[0],b=[],t=[],y=[];if(!(c.length<=d)&&l(e[0])){var m=e[0][3];m=[[f,m]];for(f=d+1;f<a;f++){var g=h(m,c,e,f,d,void 0);b.push(g);t.push(g[0]);y.push(g[1])}g=h(m,c,e,f,d,void 0);b.push(g);t.push(g[0]);y.push(g[1]);return{values:b,xData:t,yData:y}}}});""});u(b,"indicators/natr.src.js",[b["parts/Globals.js"]],function(b){var h=b.seriesTypes.atr;b.seriesType("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(b,
l){var e=h.prototype.getValues.apply(this,arguments),d=e.values.length,c=l.period-1,a=b.yData,f=0;if(e){for(;f<d;f++)e.yData[f]=e.values[f][1]/a[c][3]*100,e.values[f][1]=e.yData[f],c++;return e}}});""});u(b,"indicators/pivot-points.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function h(c,a){var f=c.series.pointArrayMap,e=f.length;for(d.prototype.pointClass.prototype[a].call(c);e--;)a="dataLabel"+f[e],c[a]&&c[a].element&&c[a].destroy(),c[a]=null}var l=k.defined,e=k.isArray,
d=b.seriesTypes.sma;b.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",toYData:function(c){return[c.P]},translate:function(){var c=this;d.prototype.translate.apply(c);c.points.forEach(function(a){c.pointArrayMap.forEach(function(d){l(a[d])&&(a["plot"+
d]=c.yAxis.toPixels(a[d],!0))})});c.plotEndPoint=c.xAxis.toPixels(c.endPoint,!0)},getGraphPath:function(c){for(var a=this,f=c.length,e=[[],[],[],[],[],[],[],[],[]],b=[],h=a.plotEndPoint,m=a.pointArrayMap.length,g,r,n;f--;){r=c[f];for(n=0;n<m;n++)g=a.pointArrayMap[n],l(r[g])&&e[n].push({plotX:r.plotX,plotY:r["plot"+g],isNull:!1},{plotX:h,plotY:r["plot"+g],isNull:!1},{plotX:h,plotY:null,isNull:!0});h=r.plotX}e.forEach(function(c){b=b.concat(d.prototype.getGraphPath.call(a,c))});return b},drawDataLabels:function(){var c=
this,a=c.pointArrayMap,f,e,b;if(c.options.dataLabels.enabled){var h=c.points.length;a.concat([!1]).forEach(function(m,g){for(b=h;b--;)e=c.points[b],m?(e.y=e[m],e.pivotLine=m,e.plotY=e["plot"+m],f=e["dataLabel"+m],g&&(e["dataLabel"+a[g-1]]=e.dataLabel),e.dataLabels||(e.dataLabels=[]),e.dataLabels[0]=e.dataLabel=f=f&&f.element?f:null):e["dataLabel"+a[g-1]]=e.dataLabel;d.prototype.drawDataLabels.apply(c,arguments)})}},getValues:function(c,a){var d=a.period,b=c.xData,h=(c=c.yData)?c.length:0;a=this[a.algorithm+
"Placement"];var l=[],m=[],g=[],r;if(!(b.length<d)&&e(c[0])&&4===c[0].length){for(r=d+1;r<=h+d;r+=d){var n=b.slice(r-d-1,r);var k=c.slice(r-d-1,r);var w=n.length;var q=n[w-1];k=this.getPivotAndHLC(k);k=a(k);k=l.push([q].concat(k));m.push(q);g.push(l[k-1].slice(1))}this.endPoint=n[0]+(q-n[0])/w*d;return{values:l,xData:m,yData:g}}},getPivotAndHLC:function(c){var a=-Infinity,d=Infinity,e=c[c.length-1][3];c.forEach(function(c){a=Math.max(a,c[1]);d=Math.min(d,c[2])});return[(a+d+e)/3,a,d,e]},standardPlacement:function(c){var a=
c[1]-c[2];return[null,null,c[0]+a,2*c[0]-c[2],c[0],2*c[0]-c[1],c[0]-a,null,null]},camarillaPlacement:function(c){var a=c[1]-c[2];return[c[3]+1.5*a,c[3]+1.25*a,c[3]+1.1666*a,c[3]+1.0833*a,c[0],c[3]-1.0833*a,c[3]-1.1666*a,c[3]-1.25*a,c[3]-1.5*a]},fibonacciPlacement:function(c){var a=c[1]-c[2];return[null,c[0]+a,c[0]+.618*a,c[0]+.382*a,c[0],c[0]-.382*a,c[0]-.618*a,c[0]-a,null]}},{destroyElements:function(){h(this,"destroyElements")},destroy:function(){h(this,"destroyElements")}});""});u(b,"indicators/ppo.src.js",
[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/indicator-required.js"]],function(b,k,q){var h=k.correctFloat,e=b.seriesTypes.ema,d=b.error;b.seriesType("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var c=arguments,a=this;q.isParentLoaded(e,"ema",a.type,function(d){d.prototype.init.apply(a,c)})},getValues:function(c,a){var f=a.periods,b=a.index;a=[];var l=[],k=[],m;if(2!==f.length||f[1]<=f[0])d('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');
else{var g=e.prototype.getValues.call(this,c,{index:b,period:f[0]});c=e.prototype.getValues.call(this,c,{index:b,period:f[1]});if(g&&c){f=f[1]-f[0];for(m=0;m<c.yData.length;m++)b=h((g.yData[m+f]-c.yData[m])/c.yData[m]*100),a.push([c.xData[m],b]),l.push(c.xData[m]),k.push(b);return{values:a,xData:l,yData:k}}}}});""});u(b,"mixins/reduce-array.js",[b["parts/Globals.js"]],function(b){var h=b.reduce;return{minInArray:function(b,l){return h(b,function(e,d){return Math.min(e,d[l])},Number.MAX_VALUE)},maxInArray:function(b,
l){return h(b,function(e,d){return Math.max(e,d[l])},-Number.MAX_VALUE)},getArrayExtremes:function(b,l,e){return h(b,function(d,c){return[Math.min(d[0],c[l]),Math.max(d[1],c[e])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});u(b,"indicators/price-channel.src.js",[b["parts/Globals.js"],b["mixins/reduce-array.js"],b["mixins/multipe-lines.js"]],function(b,k,q){var h=k.getArrayExtremes;k=b.merge;b.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",
lineWidth:1}},dataGrouping:{approximation:"averages"}},k(q,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(e,d){d=d.period;var c=e.xData,a=(e=e.yData)?e.length:0,f=[],b=[],l=[],k;if(!(a<d)){for(k=d;k<=a;k++){var m=c[k-1];var g=e.slice(k-d,k);var r=h(g,2,1);g=r[1];var n=r[0];r=(g+n)/2;f.push([m,g,r,n]);b.push(m);l.push([g,r,n])}return{values:f,xData:b,yData:l}}}}));""});u(b,"indicators/price-envelopes.src.js",
[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray,l=b.merge,e=b.seriesTypes.sma;b.seriesType("priceenvelopes","sma",{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},
{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle",init:function(){e.prototype.init.apply(this,arguments);this.options=l({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},toYData:function(d){return[d.top,d.middle,d.bottom]},translate:function(){var d=this,c=["plotTop","plotMiddle","plotBottom"];e.prototype.translate.apply(d);
d.points.forEach(function(a){[a.top,a.middle,a.bottom].forEach(function(e,b){null!==e&&(a[c[b]]=d.yAxis.toPixels(e,!0))})})},drawGraph:function(){for(var d=this,c=d.points,a=c.length,f=d.options,b=d.graph,h={options:{gapSize:f.gapSize}},k=[[],[]],m;a--;)m=c[a],k[0].push({plotX:m.plotX,plotY:m.plotTop,isNull:m.isNull}),k[1].push({plotX:m.plotX,plotY:m.plotBottom,isNull:m.isNull});["topLine","bottomLine"].forEach(function(a,c){d.points=k[c];d.options=l(f[a].styles,h);d.graph=d["graph"+a];e.prototype.drawGraph.call(d);
d["graph"+a]=d.graph});d.points=c;d.options=f;d.graph=b;e.prototype.drawGraph.call(d)},getValues:function(d,c){var a=c.period,f=c.topBand,b=c.bottomBand,l=d.xData,k=(d=d.yData)?d.length:0,m=[],g=[],r=[],n;if(!(l.length<a)&&h(d[0])&&4===d[0].length){for(n=a;n<=k;n++){var A=l.slice(n-a,n);var w=d.slice(n-a,n);w=e.prototype.getValues.call(this,{xData:A,yData:w},c);A=w.xData[0];w=w.yData[0];var q=w*(1+f);var z=w*(1-b);m.push([A,q,w,z]);g.push(A);r.push([q,w,z])}return{values:m,xData:g,yData:r}}}});""});
u(b,"indicators/psar.src.js",[b["parts/Globals.js"]],function(b){b.seriesType("psar","sma",{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(b,h){var l=b.xData;b=b.yData;var e=b[0][1],d=h.maxAccelerationFactor,c=h.increment,a=h.initialAccelerationFactor,f=b[0][2],p=h.decimals,t=h.index,k=[],m=[],g=[],r=1,n;if(!(t>=b.length)){for(n=0;n<t;n++)e=Math.max(b[n][1],
e),f=Math.min(b[n][2],parseFloat(f.toFixed(p)));var A=b[n][1]>f?1:-1;h=h.initialAccelerationFactor;var w=h*(e-f);k.push([l[t],f]);m.push(l[t]);g.push(parseFloat(f.toFixed(p)));for(n=t+1;n<b.length;n++){t=b[n-1][2];var q=b[n-2][2];var z=b[n-1][1];var v=b[n-2][1];var E=b[n][1];var x=b[n][2];null!==q&&null!==v&&null!==t&&null!==z&&null!==E&&null!==x&&(f=A===r?1===A?f+w<Math.min(q,t)?f+w:Math.min(q,t):f+w>Math.max(v,z)?f+w:Math.max(v,z):e,t=1===A?E>e?E:e:x<e?x:e,E=1===r&&x>f||-1===r&&E>f?1:-1,r=E,w=t,
x=c,q=d,z=a,h=r===A?1===r&&w>e?h===q?q:parseFloat((h+x).toFixed(2)):-1===r&&w<e?h===q?q:parseFloat((h+x).toFixed(2)):h:z,e=t-f,w=h*e,k.push([l[n],parseFloat(f.toFixed(p))]),m.push(l[n]),g.push(parseFloat(f.toFixed(p))),r=A,A=E,e=t)}return{values:k,xData:m,yData:g}}}});""});u(b,"indicators/roc.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray;b=b.seriesType;b("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",getValues:function(b,e){var d=e.period,
c=b.xData,a=(b=b.yData)?b.length:0,f=[],l=[],t=[],k=-1;if(!(c.length<=d)){h(b[0])&&(k=e.index);for(e=d;e<a;e++){var m=0>k?(m=b[e-d])?(b[e]-m)/m*100:null:(m=b[e-d][k])?(b[e][k]-m)/m*100:null;m=[c[e],m];f.push(m);l.push(m[0]);t.push(m[1])}return{values:f,xData:l,yData:t}}}});""});u(b,"indicators/rsi.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray;b.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(b,e){var d=e.period,c=b.xData,a=(b=b.yData)?
b.length:0;e=e.decimals;var f=1,l=[],t=[],k=[],m=0,g=0,r;if(!(c.length<d)&&h(b[0])&&4===b[0].length){for(;f<d;){var n=parseFloat((b[f][3]-b[f-1][3]).toFixed(e));0<n?m+=n:g+=Math.abs(n);f++}var A=parseFloat((m/(d-1)).toFixed(e));for(r=parseFloat((g/(d-1)).toFixed(e));f<a;f++)n=parseFloat((b[f][3]-b[f-1][3]).toFixed(e)),0<n?(m=n,g=0):(m=0,g=Math.abs(n)),A=parseFloat(((A*(d-1)+m)/d).toFixed(e)),r=parseFloat(((r*(d-1)+g)/d).toFixed(e)),m=0===r?100:0===A?0:parseFloat((100-100/(1+A/r)).toFixed(e)),l.push([c[f],
m]),t.push(c[f]),k.push(m);return{values:l,xData:t,yData:k}}}});""});u(b,"indicators/stochastic.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/reduce-array.js"],b["mixins/multipe-lines.js"]],function(b,k,q,l){var e=k.isArray,d=b.merge,c=b.seriesTypes.sma,a=q.getArrayExtremes;b.seriesType("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},
smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},b.merge(l,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){c.prototype.init.apply(this,arguments);this.options=d({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(d,b){var f=b.periods[0];b=b.periods[1];var h=d.xData,m=(d=d.yData)?d.length:0,g=[],
l=[],n=[],p=null,k;if(!(m<f)&&e(d[0])&&4===d[0].length){for(k=f-1;k<m;k++){var q=d.slice(k-f+1,k+1);var z=a(q,2,1);var v=z[0];q=d[k][3]-v;v=z[1]-v;q=q/v*100;l.push(h[k]);n.push([q,null]);k>=f-1+(b-1)&&(p=c.prototype.getValues.call(this,{xData:l.slice(-b),yData:n.slice(-b)},{period:b}),p=p.yData[0]);g.push([h[k],q,p]);n[n.length-1][1]=p}return{values:g,xData:l,yData:n}}}}));""});u(b,"indicators/supertrend.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function h(a,c,d){return{index:c,
close:a.yData[c][d],x:a.xData[c]}}var l=k.correctFloat,e=k.isArray,d=k.objectEach,c=b.seriesTypes.atr,a=b.seriesTypes.sma,f=b.merge;b.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){a.prototype.init.apply(this,arguments);var c=this.options;c.cropThreshold=
this.linkedParent.options.cropThreshold-(c.params.period-1)},drawGraph:function(){var c=this,b=c.options,e=c.linkedParent,m=e?e.points:[],g=c.points,l=c.graph,n=g.length,k=m.length-n;k=0<k?k:0;for(var w={options:{gapSize:b.gapSize}},q={top:[],bottom:[],intersect:[]},z={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},v,E,x,u,C,H,B,G;n--;)v=
g[n],E=g[n-1],x=m[n-1+k],u=m[n-2+k],C=m[n+k],H=m[n+k+1],B=v.options.color,G={x:v.x,plotX:v.plotX,plotY:v.plotY,isNull:!1},!u&&x&&e.yData[x.index-1]&&(u=h(e,x.index-1,3)),!H&&C&&e.yData[C.index+1]&&(H=h(e,C.index+1,3)),!x&&u&&e.yData[u.index+1]?x=h(e,u.index+1,3):!x&&C&&e.yData[C.index-1]&&(x=h(e,C.index-1,3)),v&&x&&C&&u&&v.x!==x.x&&(v.x===C.x?(u=x,x=C):v.x===u.x?(x=u,u={close:e.yData[x.index-1][3],x:e.xData[x.index-1]}):H&&v.x===H.x&&(x=H,u=C)),E&&u&&x?(C={x:E.x,plotX:E.plotX,plotY:E.plotY,isNull:!1},
v.y>=x.close&&E.y>=u.close?(v.color=B||b.fallingTrendColor,q.top.push(G)):v.y<x.close&&E.y<u.close?(v.color=B||b.risingTrendColor,q.bottom.push(G)):(q.intersect.push(G),q.intersect.push(C),q.intersect.push(f(C,{isNull:!0})),v.y>=x.close&&E.y<u.close?(v.color=B||b.fallingTrendColor,E.color=B||b.risingTrendColor,q.top.push(G),q.top.push(f(C,{isNull:!0}))):v.y<x.close&&E.y>=u.close&&(v.color=B||b.risingTrendColor,E.color=B||b.fallingTrendColor,q.bottom.push(G),q.bottom.push(f(C,{isNull:!0}))))):x&&(v.y>=
x.close?(v.color=B||b.fallingTrendColor,q.top.push(G)):(v.color=B||b.risingTrendColor,q.bottom.push(G)));d(q,function(d,b){c.points=d;c.options=f(z[b].styles,w);c.graph=c["graph"+b+"Line"];a.prototype.drawGraph.call(c);c["graph"+b+"Line"]=c.graph});c.points=g;c.options=b;c.graph=l},getValues:function(a,d){var b=d.period;d=d.multiplier;var f=a.xData,g=a.yData,h=[],n=[],k=[],p=0===b?0:b-1,t=[],q=[],v;if(!(f.length<=b||!e(g[0])||4!==g[0].length||0>b)){a=c.prototype.getValues.call(this,a,{period:b}).yData;
for(v=0;v<a.length;v++){var u=g[p+v];var x=g[p+v-1]||[];var F=t[v-1];var C=q[v-1];var H=k[v-1];0===v&&(F=C=H=0);b=l((u[1]+u[2])/2+d*a[v]);var B=l((u[1]+u[2])/2-d*a[v]);t[v]=b<F||x[3]>F?b:F;q[v]=B>C||x[3]<C?B:C;if(H===F&&u[3]<t[v]||H===C&&u[3]<q[v])var G=t[v];else if(H===F&&u[3]>t[v]||H===C&&u[3]>q[v])G=q[v];h.push([f[p+v],G]);n.push(f[p+v]);k.push(G)}return{values:h,xData:n,yData:k}}}});""});u(b,"indicators/volume-by-price.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=
k.animObject,l=k.arrayMax,e=k.arrayMin,d=k.correctFloat,c=k.extend,a=k.isArray,f=Math.abs;k=b.noop;var p=b.addEvent,t=b.seriesType,y=b.seriesTypes.column.prototype;t("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},
dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:k,drawGraph:k,getColumnMetrics:y.getColumnMetrics,crispCol:y.crispCol,init:function(a){b.seriesTypes.sma.prototype.init.apply(this,arguments);var c=this.options.params;var d=this.linkedParent;c=a.get(c.volumeSeriesID);this.addCustomEvents(d,
c);return this},addCustomEvents:function(a,c){function d(){b.chart.redraw();b.setData([]);b.zoneStarts=[];b.zoneLinesSVG&&(b.zoneLinesSVG.destroy(),delete b.zoneLinesSVG)}var b=this;b.dataEventsToUnbind.push(p(a,"remove",function(){d()}));c&&b.dataEventsToUnbind.push(p(c,"remove",function(){d()}));return b},animate:function(a){var d=this,e={};b.svg&&!a&&(e.translateX=d.yAxis.pos,d.group.animate(e,c(h(d.options.animation),{step:function(a,c){d.group.attr({scaleX:Math.max(.001,c.pos)})}})),d.animate=
null)},drawPoints:function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),y.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));y.drawPoints.apply(this,arguments)},posNegVolume:function(a,c){var d=c?["positive","negative"]:["negative","positive"],b=this.options.volumeDivision,e=this.points.length,f=[],g=[],h=0,m;a?(this.posWidths=f,this.negWidths=g):(f=this.posWidths,g=this.negWidths);for(;h<e;h++){var l=this.points[h];l[d[0]+"Graphic"]=l.graphic;l.graphic=l[d[1]+"Graphic"];
if(a){var k=l.shapeArgs.width;var p=this.priceZones[h];(m=p.wholeVolumeData)?(f.push(k/m*p.positiveVolumeData),g.push(k/m*p.negativeVolumeData)):(f.push(0),g.push(0))}l.color=c?b.styles.positiveColor:b.styles.negativeColor;l.shapeArgs.width=c?this.posWidths[h]:this.negWidths[h];l.shapeArgs.x=c?l.shapeArgs.x:this.posWidths[h]}},translate:function(){var a=this,c=a.options,b=a.chart,e=a.yAxis,h=e.min,k=a.options.zoneLines,p=a.priceZones,t=0,q,u,x;y.translate.apply(a);var F=a.points;if(F.length){var C=
.5>c.pointPadding?c.pointPadding:.1;c=a.volumeDataArray;var H=l(c);var B=b.plotWidth/2;var G=b.plotTop;var J=f(e.toPixels(h)-e.toPixels(h+a.rangeStep));var M=f(e.toPixels(h)-e.toPixels(h+a.rangeStep));C&&(h=f(J*(1-2*C)),t=f((J-h)/2),J=f(h));F.forEach(function(c,b){u=c.barX=c.plotX=0;x=c.plotY=e.toPixels(p[b].start)-G-(e.reversed?J-M:J)-t;q=d(B*p[b].wholeVolumeData/H);c.pointWidth=q;c.shapeArgs=a.crispCol.apply(a,[u,x,q,J]);c.volumeNeg=p[b].negativeVolumeData;c.volumePos=p[b].positiveVolumeData;c.volumeAll=
p[b].wholeVolumeData});k.enabled&&a.drawZones(b,e,a.zoneStarts,k.styles)}},getValues:function(c,d){var e=c.processedXData,f=c.processedYData,g=this.chart,h=d.ranges,l=[],m=[],k=[],p;if(c.chart)if(p=g.get(d.volumeSeriesID))if((d=a(f[0]))&&4!==f[0].length)b.error("Type of "+c.name+" series is different than line, OHLC or candlestick.",!0,g);else return(this.priceZones=this.specifyZones(d,e,f,h,p)).forEach(function(a,c){l.push([a.x,a.end]);m.push(l[c][0]);k.push(l[c][1])}),{values:l,xData:m,yData:k};
else b.error("Series "+d.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,g);else b.error("Base series not found! In case it has been removed, add a new one.",!0,g)},specifyZones:function(a,c,b,f,h){if(a){var g=b.length;for(var m=b[0][3],n=m,k=1,p;k<g;k++)p=b[k][3],p<m&&(m=p),p>n&&(n=p);g={min:m,max:n}}else g=!1;g=(m=g)?m.min:e(b);p=m?m.max:l(b);m=this.zoneStarts=[];n=[];var t=0;k=1;if(!g||!p)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];var r=
this.rangeStep=d(p-g)/f;for(m.push(g);t<f-1;t++)m.push(d(m[t]+r));m.push(p);for(f=m.length;k<f;k++)n.push({index:k-1,x:c[0],start:m[k-1],end:m[k]});return this.volumePerZone(a,n,h,c,b)},volumePerZone:function(a,c,d,b,e){var g=this,h=d.processedXData,l=d.processedYData,m=c.length-1,k=e.length;d=l.length;var n,p,t,r,q;f(k-d)&&(b[0]!==h[0]&&l.unshift(0),b[k-1]!==h[d-1]&&l.push(0));g.volumeDataArray=[];c.forEach(function(c){c.wholeVolumeData=0;c.positiveVolumeData=0;for(q=c.negativeVolumeData=0;q<k;q++)t=
p=!1,r=a?e[q][3]:e[q],n=q?a?e[q-1][3]:e[q-1]:r,r<=c.start&&0===c.index&&(p=!0),r>=c.end&&c.index===m&&(t=!0),(r>c.start||p)&&(r<c.end||t)&&(c.wholeVolumeData+=l[q],n>r?c.negativeVolumeData+=l[q]:c.positiveVolumeData+=l[q]);g.volumeDataArray.push(c.wholeVolumeData)});return c},drawZones:function(a,c,d,b){var e=a.renderer,f=this.zoneLinesSVG,g=[],h=a.plotWidth,l=a.plotTop,m;d.forEach(function(d){m=c.toPixels(d)-l;g=g.concat(a.renderer.crispLine(["M",0,m,"L",h,m],b.lineWidth))});f?f.animate({d:g}):f=
this.zoneLinesSVG=e.path(g).attr({"stroke-width":b.lineWidth,stroke:b.color,dashstyle:b.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&(this.negativeGraphic=this.negativeGraphic.destroy());return b.Point.prototype.destroy.apply(this,arguments)}});""});u(b,"indicators/vwap.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray;k=b.seriesType;k("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(l,
e){var d=l.chart,c=l.xData;l=l.yData;var a=e.period,f=!0,k;if(k=d.get(e.volumeSeriesID))return h(l[0])||(f=!1),this.calculateVWAPValues(f,c,l,k,a);b.error("Series "+e.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,d)},calculateVWAPValues:function(b,e,d,c,a){var f=c.yData,h=c.xData.length,l=e.length;c=[];var k=[],m=[],g=[],r=[],n;h=l<=h?l:h;for(n=l=0;l<h;l++){var q=b?(d[l][1]+d[l][2]+d[l][3])/3:d[l];q*=f[l];q=n?c[l-1]+q:q;var u=n?k[l-1]+f[l]:f[l];c.push(q);k.push(u);r.push([e[l],q/u]);m.push(r[l][0]);
g.push(r[l][1]);n++;n===a&&(n=0)}return{values:r,xData:m,yData:g}}});""});u(b,"indicators/williams-r.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/reduce-array.js"]],function(b,k,q){var h=k.isArray,e=q.getArrayExtremes;b.seriesType("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(d,c){c=c.period;var a=d.xData,b=(d=d.yData)?d.length:0,l=[],k=[],q=[],m;if(!(a.length<c)&&h(d[0])&&4===d[0].length){for(m=c-1;m<b;m++){var g=d.slice(m-c+1,m+1);var r=e(g,
2,1);g=r[0];r=r[1];var n=d[m][3];g=(r-n)/(r-g)*-100;a[m]&&(l.push([a[m],g]),k.push(a[m]),q.push(g))}return{values:l,xData:k,yData:q}}}});""});u(b,"indicators/wma.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function h(d,c){c*=(c+1)/2;return d.reduce(function(a,c,d){return[null,a[1]+c[1]*(d+1)]})[1]/c}function l(d,c,a,b){a=h(d,d.length);c=c[b-1];d.shift();return[c,a]}var e=k.isArray;b=b.seriesType;b("wma","sma",{params:{index:3,period:9}},{getValues:function(d,c){var a=c.period,
b=d.xData,h=(d=d.yData)?d.length:0,k=1,q=b[0],m=d[0],g=[],r=[],n=[],u=-1;if(!(b.length<a)){e(d[0])&&(u=c.index,m=d[0][u]);for(c=[[q,m]];k!==a;)c.push([b[k],0>u?d[k]:d[k][u]]),k++;for(a=k;a<h;a++)k=l(c,b,d,a),g.push(k),r.push(k[0]),n.push(k[1]),c.push([b[a],0>u?d[a]:d[a][u]]);k=l(c,b,d,a);g.push(k);r.push(k[0]);n.push(k[1]);return{values:g,xData:r,yData:n}}}});""});u(b,"indicators/zigzag.src.js",[b["parts/Globals.js"]],function(b){b=b.seriesType;b("zigzag","sma",{params:{lowIndex:2,highIndex:1,deviation:1}},
{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(b,h){var l=h.lowIndex,e=h.highIndex,d=h.deviation/100;h=1+d;var c=1-d;d=b.xData;var a=b.yData;b=a?a.length:0;var f=[],k=[],t=[],q,m,g=!1,r=!1;if(!(!d||1>=d.length||b&&(void 0===a[0][l]||void 0===a[0][e]))){var n=a[0][l];var u=a[0][e];for(q=1;q<b;q++){if(a[q][l]<=u*c){f.push([d[0],u]);var w=[d[q],a[q][l]];g=m=!0}else a[q][e]>=n*h&&(f.push([d[0],n]),w=[d[q],a[q][e]],m=!1,g=!0);if(g){k.push(f[0][0]);t.push(f[0][1]);
var K=q++;q=b}}for(q=K;q<b;q++)m?(a[q][l]<=w[1]&&(w=[d[q],a[q][l]]),a[q][e]>=w[1]*h&&(r=e)):(a[q][e]>=w[1]&&(w=[d[q],a[q][e]]),a[q][l]<=w[1]*c&&(r=l)),!1!==r&&(f.push(w),k.push(w[0]),t.push(w[1]),w=[d[q],a[q][r]],m=!m,r=!1);l=f.length;0!==l&&f[l-1][0]<d[b-1]&&(f.push(w),k.push(w[0]),t.push(w[1]));return{values:f,xData:k,yData:t}}}});""});u(b,"indicators/regressions.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray;b=b.seriesType;b("linearRegression","sma",{params:{xAxisUnit:void 0},
tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(b,e){var d=this.options.params.index,c=function(a,c){return h(a)?a[c]:a},a=b.reduce(function(a,c){return c+a},0),f=e.reduce(function(a,b){return c(b,d)+a},0);a/=b.length;f/=e.length;var l=0,k=0,q;for(q=0;q<b.length;q++){var m=b[q]-a;var g=c(e[q],d)-f;l+=m*g;k+=Math.pow(m,2)}b=k?l/k:0;return{slope:b,intercept:f-b*a}},getEndPointY:function(b,e){return b.slope*e+b.intercept},transformXData:function(b,
e){var d=b[0];return b.map(function(c){return(c-d)/e})},findClosestDistance:function(b){var e,d;for(d=1;d<b.length-1;d++){var c=b[d]-b[d-1];0<c&&("undefined"===typeof e||c<e)&&(e=c)}return e},getValues:function(b,e){var d=b.xData;b=b.yData;e=e.period;var c,a={xData:[],yData:[],values:[]},f=this.options.params.xAxisUnit||this.findClosestDistance(d);for(c=e-1;c<=d.length-1;c++){var h=c-e+1;var k=c+1;var l=d[c];var m=d.slice(h,k);h=b.slice(h,k);k=this.transformXData(m,f);m=this.getRegressionLineParameters(k,
h);h=this.getEndPointY(m,k[k.length-1]);a.values.push({regressionLineParameters:m,x:l,y:h});a.xData.push(l);a.yData.push(h)}return a}});b("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(b){return b.slope}});b("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(b){return b.intercept}});b("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},
{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(b){return 180/Math.PI*Math.atan(b)},getEndPointY:function(b){return this.slopeToAngle(b.slope)}});""});u(b,"indicators/acceleration-bands.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/multipe-lines.js"]],function(b,k,q){var h=k.correctFloat,e=b.seriesTypes.sma;k=b.merge;b.seriesType("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},
dataGrouping:{approximation:"averages"}},k(q,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(b,c){var a=c.period,d=c.factor;c=c.index;var k=b.xData,l=(b=b.yData)?b.length:0,q=[],m=[],g=[],r=[],n=[],u;if(!(l<a)){for(u=0;u<=l;u++){if(u<l){var w=b[u][2];var K=b[u][1];var z=d;w=h(K-w)/(h(K+w)/2)*1E3*z;q.push(b[u][1]*h(1+2*w));m.push(b[u][2]*h(1-2*w))}if(u>=a){w=k.slice(u-
a,u);var v=b.slice(u-a,u);z=e.prototype.getValues.call(this,{xData:w,yData:q.slice(u-a,u)},{period:a});K=e.prototype.getValues.call(this,{xData:w,yData:m.slice(u-a,u)},{period:a});v=e.prototype.getValues.call(this,{xData:w,yData:v},{period:a,index:c});w=v.xData[0];z=z.yData[0];K=K.yData[0];v=v.yData[0];g.push([w,z,v,K]);r.push(w);n.push([z,v,K])}}return{values:g,xData:r,yData:n}}}}));""});u(b,"indicators/trendline.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){var h=k.isArray;
b=b.seriesType;b("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,getValues:function(b,e){var d=b.xData,c=b.yData;b=[];var a=[],f=[],k=0,l=0,q=0,m=0,g=d.length,r=e.index;for(e=0;e<g;e++){var n=d[e];var u=h(c[e])?c[e][r]:c[e];k+=n;l+=u;q+=n*u;m+=n*n}c=(g*q-k*l)/(g*m-k*k);isNaN(c)&&(c=0);k=(l-c*k)/g;for(e=0;e<g;e++)n=d[e],u=c*n+k,b[e]=[n,u],a[e]=n,f[e]=u;return{xData:a,yData:f,values:b}}});""});u(b,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map